### ISSUE TITLE
Import statements from CSV

### ISSUE THREAD

**Issue by obuylov** [LearningLocker/learninglocker#1009]
Hello.
It would be cool to be able to import statistics from CSV file, how in Watershed LRS: https://watershedlrs.zendesk.com/hc/en-us/articles/203376670-How-do-I-import-data-from-a-CSV-file-.

**Comment by ht2** [comment]
Hi @obuylov - agreed! This would be a nice feature, but not something we currently have roadmapped. I will close this off as a feature request for others to find if they do go looking. As always, happy to accept pull requests from the community for new features like this.
