### ISSUE TITLE
CentOS Scripted Install - Pre-requisites

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#1012]
**Version**
2.0.5

**Steps to reproduce the bug**
1. Create a new CentOS 7.4 VM
2. Run 'yum update'
3. Run LL v2 installation script
4. Various errors about mongodb, nginx, and redis

**Expected behaviour**
Should install those requirements

**Actual behaviour**
You need to install epel-release, mongodb-org (via mongo RedHat instructions), and redis
Then install works (almost all the way - other issue submitted.)

**Additional information**
OS: CentOS 7.4

**Comment by ht2** [comment]
I'm going to close this one David and keep everything in #1011 as this may just be related specifically to this Distro
