### ISSUE TITLE
Multiple GET /data/xAPI/statement filters not working correctly

### ISSUE THREAD

**Issue by ht2** [LearningLocker/learninglocker#1017]
**Version**
xapi-statements
v1.0.15

**Steps to reproduce the bug**
1. Make GET to /data/xAPI/statements with activity AND verb AND/OR agent

**Expected behaviour**
Should return statements based on filters

**Actual behaviour**
Returns statements based on one of the query parameters only. 
Seems to prioritise them; activity will trump verb, verb will trump agent etc

**Comment by ryansmith94** [comment]
Released in [xapi-service v1.1.2](https://github.com/LearningLocker/xapi-service/releases/tag/v1.1.2)
