### ISSUE TITLE
Extremely slow performance in web admin tool.

### ISSUE THREAD

**Issue by moneyhan** [LearningLocker/learninglocker#1018]
You need to replace the parts of this template where you see {{some text}}.

**Version**
Current version that install instructions for vanilla install script on LL website

**Steps to reproduce the bug**
1. Log In
2. Any data entry but particularly when entering names for visualizations, dashboards, etc.

**Expected behavior**
Pages should not freeze, pause or be choppy as you are trying to add names to new queries, sources, visualizations, dashboards.

**Actual behaviour**
Pages freeze, pause or are choppy as you are trying to add names to new queries, sources, visualizations, dashboards.

**Additional information**
OS: Ubuntu 16.04
Browser: IE 11, FireFox 55.01, Chrome  61.0.3163.100
LL Running on Dell PowerEdge R610 with 2 Zeon Quad Core 2.04gHz Processors and 24gb Ram.  Nothing else running.  Development box so no users or loads but still extremely slow.

Saw a post on a Google group indicating LL was checking github repeatedly for new versions and was causing problems.  Not sure if this is related. https://groups.google.com/forum/#!searchin/learning-locker/slow%7Csort:date/learning-locker/O_l3yXmE6iM/tKJUIW-tBAAJ

**Comment by ht2** [comment]
To confirm, you see this same problem in Firefox and Chrome?

**Comment by ht2** [comment]
Closed as we believe its CPU limitation on client machine
