### ISSUE TITLE
Support bad requests from Captivate and Articulate Rise

### ISSUE THREAD

**Issue by ryansmith94** [LearningLocker/learninglocker#1022]
**Version**
[xapi-service v1.2.2](https://github.com/LearningLocker/xapi-service/releases/tag/v1.2.2)

**Steps to reproduce the bug**
Send a HTTP PUT request to `xAPI/activities/state` with `application/json` in the content type header, but a _**invalid**_ JSON string without quotes in the body. This is the _**invalid**_ behaviour observed in Captivate and  Articulate Rise

**Expected behaviour**
HTTP response status should be 204 because supporting Captivate and Storyline's users is more important than being 100% xAPI conformant (probably).

**Actual behaviour**
HTTP response status is 400 because Captivate and Storyline are sending _**invalid**_ JSON.

**Additional Notes**
Some other LRSs seem to be supporting these _**invalid xAPI requests**_ despite being listed as conformant LRSs, so it's probably acceptable for us to do the same.

I've [reported the issue to Captivate](https://forums.adobe.com/thread/2408007), I believe this issue has been reported to Storyline by someone else from the Gitter channel. I've also [reported the missing conformance test to the ADL](https://github.com/adlnet/lrs-conformance-test-suite/issues/223).

**Comment by garemoko** [comment]
@ryansmith94 is this happening with the latest version of Storyline, do you know?

**Comment by ryansmith94** [comment]
Pretty sure we've seen it happening on Gitter in the latest version yeah @garemoko

**Comment by ht2** [comment]
@garemoko Not sure - we've just been working off people's packages they've been sending us. How do you feel about this one @garemoko? It feels like everyone does the same thing here (Watershed, SCORM Cloud, us) - everyone will accept the following as valid JSON...

```
Content-type: application/json

hello world
```

Where (technically) what it should be is:

```
Content-type: application/json

"hello world"
```

It's petty - but validation is validation, and the JSON bodyparser we use (https://github.com/expressjs/body-parser) is throwing on it. Now, we'll probably just have to implement something to check and make it a string prior to that validation, but it's still a bit of an odd one. Basically we all (v1 included) just weren't that strict originally.

**Comment by garemoko** [comment]
Ugh. That's not good. 

I think @ryansmith94 is right to flag this up with the test suite and we can discuss there. 

Definitely interested to know about the version of Storyline though. They made some big improvements to statements in 2.5, though I guess I've got no reason to assume the state calls changed too.

**Comment by ryansmith94** [comment]
Aye not ideal. Thanks, I'm glad you agree.

Yeah would be good to get some Storyline 2.5 content and check out what requests that sends. I think the bigger problem here is that people have already created their content in those older versions, so even if a fix is pushed it'll take a while for it to be used in most content.

**Comment by ht2** [comment]
@garemoko Seems to be the current version of Articulate Rise it was failing on, although I'm guessing under the hood they will use the same libs for dealing with xAPI (_warning: assumption alert!_)

**Comment by markusd1984** [comment]
This issue, coming from an xAPI tin can export from Articulate Rise which results in not being able to connect to LLv2 as the LRS. I shared this with LL team on gitter as well as to Articulate who are currently looking into this issue to be fixed, here their response:

> Our  QA Team noted in my report that they were able to trace the problem back to the parser in the scormdriver - it is choking on a `#` in the URL. They also mentioned that in Learning Locker version 1 they ignored that error but no longer in version 2. That explains why it’s failing now.  Other people or LMSs don’t hit this because they ignore that error too.

> They have an idea of how to fix this however depending on priority and risk, some bugs can be fixed quickly, while others take longer to resolve.

**Comment by garemoko** [comment]
AFAIK, Storyline doesn't use SCORM Driver for it's xAPI implementation (only for It's SCORM implementation), so if Rise does, that suggests that Storyline's xAPI implementation is significantly different to that of Rise.

**Comment by ht2** [comment]
OK - will be something I'll need to check and see if Storyline has this action too then

**Comment by ht2** [comment]
OK, I've had a look at Storyline and from what I can tell it PUTs State as `application/octet-stream`, which whilst not ideal is at least valid.

**Comment by garemoko** [comment]
Great news. Thanks for sharing!

**Comment by ryansmith94** [comment]
We need to figure out what we want to do when we return the data, I bet if we correctly return the JSON string with quotes in response to a GET request they won't handle it correctly. So we may need to store a flag on the state/profile model that determines whether we use quotes or not.

**Comment by ryansmith94** [comment]
The other thing we could do, is rather than changing the content to be valid JSON where the text is wrapped in quotes, we could change the content type to be text/plain. However that is currently stored in files rather than the DB.

**Comment by ryansmith94** [comment]
To get around the issue of storing in files rather than the DB, we could change the code to store small content in the DB and larger content in files.

**Comment by ryansmith94** [comment]
Ok update time: we have a tested fix for this in xapi-state. Currently there are some complications in the xapi-service regarding what I can only describe quickly as "leaky" Express mixins. We have came up with a plan to resolve those complications and I will be pursuing that tomorrow 👍

**Comment by ryansmith94** [comment]
Fixed in [xapi-service v1.2.9](https://github.com/LearningLocker/xapi-service/releases/tag/v1.2.9).

**Comment by ryansmith94** [comment]
For the record the issue was fixed by switching the content type to "text/plain" when we receive requests with "application/json" containing "text/plain" content. This content is stored in the DB instead of files for better performance.

Note that the same behaviour is not currently accepted for activity profiles or agent profiles, only state.

This fix has gone someway towards storing all small files in DB. However, we can't necessarily know the content length ahead of time because of chunked requests.

**Comment by garemoko** [comment]
https://github.com/adlnet/xAPI-Spec/issues/1070#issuecomment-351501226
