### ISSUE TITLE
How can I delete a statement in my Learning Locker?

### ISSUE THREAD

**Issue by Nicosoft** [LearningLocker/learninglocker#1023]
**Version**
Learning Locker Entreprise Edition v2

**Steps to reproduce the bug**
The documentation v2 says:
"Statements can be deleted by the REST API (on a statement by statement basis, but again this is not recommended." (http://docs.learninglocker.net/http-statements/)

However there no "DELETE /statements" method.

So How can I delete a statement in my logstore?

Thanks

**Comment by ryansmith94** [comment]
Hey @Nicosoft, you should be able to use [`DELETE /statements/:id`](http://docs.learninglocker.net/http-models/#delete-id) where the id is the Mongo ID for statement model not the Statement's ID. The Mongo ID can be found using the [connection API](http://docs.learninglocker.net/http-connection/) for statements or via the source page in the UI in the `_id` property on the statements. You may wish to consider [voiding](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#voided) instead.

**Comment by ht2** [comment]
For bulk removal of statements, we recommend doing this action directly in the database; removing statements is such a destructive action to the state of an LRS that we really made it quite hard to do deliberately.

For info on deleting from Mongo, read more here: https://docs.mongodb.com/manual/reference/method/db.collection.remove/

**Comment by Nicosoft** [comment]
Hi @ryansmith94 ,

Thank you for your reply. I'm glad there is a way to delete statement.
As you mentioned, I tried `DELETE /statements/:id`.
Unfortunately it was unsuccessful. Please see the screenshot below:

<img width="921" alt="screen shot 2017-11-09 at 2 58 22 pm" src="https://user-images.githubusercontent.com/4625910/32587908-561e1342-c55f-11e7-8c11-857c73a6e7e5.png">

- My key is correct
- My URL is correct
- The ID is correct
- In my dashboard / client settings, the overall of the API Key is ALL.

Did I miss anything?
Thanks.

**Comment by ht2** [comment]
You have used the wrong URL. As @ryansmith94 explained, the xAPI does not have a delete method but rather our custom APIs do. 

Please refer to the Models API documentation http://docs.learninglocker.net/http-models/

**Comment by ryansmith94** [comment]
As an update to this, I believe the authorisation requirements have changed such that only GET requests can be made to the HTTP models endpoint for statements.

**Comment by dunghoang74** [comment]
@Nicosoft make sure that the xAPI has right to delete, you can check under the settings section in admin

**Comment by ryansmith94** [comment]
Thanks @dunghoang74, forgot to note on this issue that we added some new APIs for statement deletion, you can read more in [our documentation](http://docs.learninglocker.net/http-statement-deletion/).

**Comment by michzimny** [comment]
Could you please tell me how to delete statements in LL v2.x via API? Is it possible at all?

The [deletion API](http://docs.learninglocker.net/http-statement-deletion/) exists since 3.x. The [HTTP models API](http://docs.learninglocker.net/http-rest/) seems not to offer a way to delete statements.

I'd appreciate any tips.

**Comment by ryansmith94** [comment]
Prior to v3 you'd have to delete them directly from the Mongo database.
