### ISSUE TITLE
Question: Abstracting away DB Connection

### ISSUE THREAD

**Issue by getaclue** [LearningLocker/learninglocker#1025]
Hey guys,

First and foremost, thanks for your hard work on this project. 
Been following you guys along on the new rewrite! Exciting!

Quick question regarding your roadmap:

Do you guys see yourself adding a connection wrapper to the database such that I could use my own database? Not talking about maintaining that support... that could be up to the people using it. Just an additional abstraction level?

Any comment is appreciated!

Thanks,
Alex

**Comment by ht2** [comment]
Hey Alex, thanks for your kind words!

Just to clarify, are you talking about switching out MongoDB to another database?

**Comment by getaclue** [comment]
@ht2 yeap, exactly.

**Comment by getaclue** [comment]
@ht2 yeap, exactly. I'm just doing some research and looking at the compatibilities / ease of modification.

**Comment by getaclue** [comment]
@ht2 yeap, exactly. I'm just doing some research and looking at the compatibilities / ease of modification.

**Comment by ht2** [comment]
It would be quite a large change, as the entire query setup is based around sending in Mongo aggregations. Currently this is not something we are looking at doing/implementing but I wouldn't mark it as a "never".

**Comment by getaclue** [comment]
@ht2 okay thank you for an honest response 👌
Keep doing awesome work!
