### ISSUE TITLE
Additional User Authentication Mechanisms?

### ISSUE THREAD

**Issue by clcollins** [LearningLocker/learninglocker#1026]
Is there support for other user authentication mechanisms in addition to the local user accounts or Google OAuth?  Apologies if I've somehow overlooked some extremely obvious documentation.  That's a distinct possibility.

It would be particularly useful to have support for authentication information via REMOTE_USER header, support for SAML2, or a more plug-able way to integrate other OAuth solutions.

Thanks for your hard work on this!  It looks really promising for us!

**Comment by ht2** [comment]
Hi @clcollins - SAML or OpenID/OAuth equivalents are something we are interested in looking into, but will typically come on board as and when a client pays us to implement that as a requirement.

We're always happy to accept Pull Requests for features like this though. In the meantime I will close this off but mark down as a feature request for anyone searching for it.
