### ISSUE TITLE
LL-432 Received extra attachments with existing statement

### ISSUE THREAD

**Issue by ht2** [LearningLocker/learninglocker#1031]
**Version**
Observed on v2.0.7

**Steps to reproduce the bug**
1. Insert statement with attachment
2. Reinsert same statement with ID

**Expected behaviour**
SHould allow in statement (with no conflict)

**Actual behaviour**
`Received extra attachments` error

**Comment by ht2** [comment]
We suspect that `checkAttachments` should be receiving more than just the unstored models...

https://github.com/LearningLocker/xapi-statements/blob/master/src/service/storeStatements/index.ts#L49

**Comment by ryansmith94** [comment]
Fixed in [xapi-service v1.2.4](https://github.com/LearningLocker/xapi-service/releases/tag/v1.2.4)
