### ISSUE TITLE
Unclear error when not passing `method` in query params

### ISSUE THREAD

**Issue by ht2** [LearningLocker/learninglocker#1033]
Let the alternateRequest method handle the missing `method` param

https://github.com/LearningLocker/xapi-statements/blob/master/src/expressPresenter/postStatements/index.ts#L35

**Comment by ryansmith94** [comment]
Fixed in [xapi-statements v2.2.3](https://github.com/LearningLocker/xapi-statements/releases/tag/v2.2.3). I'll update the xapi-service soon to close this issue.

**Comment by ryansmith94** [comment]
Fixed in [xapi-service v1.2.5](https://github.com/LearningLocker/xapi-service/releases/tag/v1.2.5).
