### ISSUE TITLE
Learning Locker Integration not working with Moodle 3.2

### ISSUE THREAD

**Issue by tjr007ma** [LearningLocker/learninglocker#1035]
Did you guys change your credential API?
i cant get xAPI tin can to work with learning locker. 

Check link for more details

[https://github.com/garemoko/moodle-mod_tincanlaunch/issues/144](url)

**Comment by ht2** [comment]
The credential API is indeed different in version 2

**Comment by tjr007ma** [comment]
is there a way we can obtain the new one so we can update the plugin?

**Comment by ht2** [comment]
All the documentation for the APIs is available here: http://docs.learninglocker.net/http-models/
