### ISSUE TITLE
Learning Locker Integration not working with Moodle.

### ISSUE THREAD

**Issue by tjr007ma** [LearningLocker/learninglocker#1037]
Someone removed my issue request. Can someone help me please?

can you provide the new credential api ?

https://github.com/garemoko/moodle-mod_tincanlaunch/issues/144

**Comment by ht2** [comment]
Hi @tjr007ma - I did not remove the issue, I [closed it](https://github.com/LearningLocker/learninglocker/issues/1035) after I posted a link to the [API documentation](http://docs.learninglocker.net/http-models/) for [Clients](http://docs.learninglocker.net/http-clients/). 

This is a Moodle (plugin) issue, not a Learning Locker one. The way Moodle creates multiple clients in V1 using the API was, to be blunt, not a very secure or practical way of handling launching (but it got the job done at the time). Really the plugin should look into other launch methods such as [CMI5](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#launch_method) or [xAPI Launch](https://github.com/adlnet/xapi-launch) but that is on the authors of the plugin and not something we handle over here.

These issue pages are related to bugs with Learning Locker itself, not how other software implements it, as such, I will now close this issue too.

**Comment by tjr007ma** [comment]
sorry James. I didnt see the email

Thank you
TJ

**Comment by ht2** [comment]
No problem, I've added some resources to the moodle-mod_tincanlaunch issue which details how a client could be made, although I fear its not as simple as a drop in fix.
