### ISSUE TITLE
Support bad requests from Articulate Storyline

### ISSUE THREAD

**Issue by ryansmith94** [LearningLocker/learninglocker#1042]
**Version**
[xapi-service v1.2.10](https://github.com/LearningLocker/xapi-service/releases/tag/v1.2.10)

**Steps to reproduce the bug**
Send a `HTTP POST` request to `xAPI/activities/state` with the `method` query parameter set to `PUT`, but with `text/plain;charset=UTF-8` in the content type header. This is the invalid behaviour observed in Articulate Storyline.

**Expected behaviour**
HTTP response status should be 204 because supporting Storyline's users is more important than being 100% xAPI conformant (probably).

**Actual behaviour**
HTTP response status is 400 because Storyline are sending invalid `text/plain;charset=UTF-8` content type for an alternate request.

**Additional information**
Very similar circumstances to https://github.com/LearningLocker/learninglocker/issues/1022. This is made slightly tricky because we can't rely on the [url encoding middleware](https://github.com/HT2-Labs/jscommons/blob/master/src/expressPresenter/mixins/urlEncoding.ts) since it explicitly works on the alternate request content type.

For the record, despite being a simple string change for the folks at Storyline, this actually involves a few changes for us because we have to change our validation to be less conformant with the xAPI spec and re-implement the work that express middleware was previously doing for us.

**Comment by ht2** [comment]
🤡

**Comment by ryansmith94** [comment]
Fixed in [xapi-service v1.2.11](https://github.com/LearningLocker/xapi-service/releases/tag/v1.2.11).
