### ISSUE TITLE
LRS Configuration: AGGREGATION_REFRESH_AT_SECONDS

### ISSUE THREAD

**Issue by doender** [LearningLocker/learninglocker#1057]
Thank you for this wonderful project.

Could you please explain the effect of the config setting `AGGREGATION_REFRESH_AT_SECONDS`?
Does this mean that aggregation results will never expire, but always stay in the cache and refreshed at `AGGREGATION_REFRESH_AT_SECONDS`?

**Comment by ht2** [comment]
Hey there :) Details are all in http://docs.learninglocker.net/guides-configuring/ but broadly:


AGGREGATION_CACHE_SECONDS | How many seconds are aggregation results cached
AGGREGATION_REFRESH_AT_SECONDS | Refresh aggregations when this close to expiry

So for example if my `AGGREGATION_CACHE_SECONDS ` was set to 600 (10 minutes) and my `AGGREGATION_REFRESH_AT_SECONDS ` was set to 60 (1 minute), then if a request for a (cached) aggregation came in and there was less than 1 minute until it expired, we would instantly return you the cached result, but also run the aggregation behind the scenes, updating the cache when it finishes. When you next query that aggregation, the results would be a more up to date version.

Broadly it's a way of always ensuring we return snappy results for a dashboard, whilst still trying to keep the data updated in the background.
