### ISSUE TITLE
Statement in dashboard graph remains after LRS delete

### ISSUE THREAD

**Issue by Rinkuk1993** [LearningLocker/learninglocker#1059]
I have created LRS for testing and deleted it while giving to production. What I found is

1. LRS is deleted
2. Statements are also deleted
3. Dashboard still shows 24 statements (from previous LRS)
4. I can not view those statements as it was deleted along with LRS

The API for dashboard graph : 
https://fpedu-xapi.learnyst.com/site/graphdata?graphStartDate=2016-12-03&graphEndDate=2017-12-09+23%3A59

Here is the screenshot (Statements count shall be 0)
<img width="1261" alt="screen shot 2017-12-09 at 5 18 08 pm" src="https://user-images.githubusercontent.com/14367488/33795309-ff8dd694-dd04-11e7-8c3b-27d123c991b7.png">

I am using LearningLocker V1

**Comment by ht2** [comment]
Hi @Rinkuk1993, statements are not actually removed from the database when you remove an LRS (to prevent accidental data loss). You will need to manually remove this data from the databsae if you no longer wish to see it in the top level dashboard.
