### ISSUE TITLE
Redis connection to Learning Locker Failing

### ISSUE THREAD

**Issue by RS1603** [LearningLocker/learninglocker#1066]
You need to replace the parts of this template where you see {{some text}}.

Learning Locker : v2.0.1
Mongo DB : 3.4.9
Redis: 2.8.11

**Steps to reproduce the bug**
1. {{step 1}}
2. {{step 2}}

**Expected behaviour**
I should be logged in

**Actual behaviour**
Not able to log in, although login screen of learning locker comes

**Additional information**
OS Version
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

On backend : pm2 logs gives 
'Error: Redis connection to name:6379 failed - connect ECONNREFUSED ip:6379

**Comment by ht2** [comment]
Your Redis isn't running or is not configured correctly.
