### ISSUE TITLE
"http://www&46;learning&46;com/xAPI/extensions/ --- . dot gets replaced with &46

### ISSUE THREAD

**Issue by RS1603** [LearningLocker/learninglocker#1074]
You need to replace the parts of this template where you see {{some text}}.

Learning Locker : v2.0.1
Mongo DB : 3.4.9
Redis: 2.8.11

Steps to reproduce the bug

{{step 1}}
{{step 2}}
Expected behaviour
Enabling https

Actual behaviour
http://www.learning.com/xAPI/extensions/ 

Additional information
OS Version
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

Problem Statement: "http://www&46;learning&46;com/xAPI/extensions/ 
Instead of . dot I get &46, in LRS

Until Now: While I generate the statements in learning content , I form the xAPI statement with "extensions": {
"http://www.learning.com/xAPI/extensions/

**Comment by ht2** [comment]
Addressed in [v2.1.0](https://github.com/LearningLocker/learninglocker/releases/tag/v2.1.0)
