### ISSUE TITLE
Mongo DB just re - adjusts itself to 0.00GB, has anyone came across this issue. I am v2

### ISSUE THREAD

**Issue by RS1603** [LearningLocker/learninglocker#1075]
You need to replace the parts of this template where you see {{some text}}.

Learning Locker : v2.0.1
Mongo DB : 3.4.9
Redis: 2.8.11

Actual behaviour
Mongo DB should have the data of the LL

Additional information
OS Version
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

Problem Statement: Mongo DB just re - adjusts itself to 0.00GB, has anyone came across this issue. I am v2

**Comment by ht2** [comment]
Sorry, not really enough information to go on here, and sounds like a Mongo issue which we can't support
