### ISSUE TITLE
app/storage/cache taking a lot of inodes

### ISSUE THREAD

**Issue by davidscholberg** [LearningLocker/learninglocker#1076]
The `app/storage/cache` directory in our learning locker install is constantly growing with lots of tiny files. An example file path is `app/storage/cache/00/00/0000016feaa67d9c6c5cdc1b2057661e` with the contents:

```
1496174655a:3:{s:8:"waitedMS";i:0;s:6:"result";a:0:{}s:2:"ok";i:1;}
```

I'm not entirely sure what these files are. Some sort of profiler or request logging?

I've already turned off laravel debugging per https://github.com/LearningLocker/learninglocker/issues/808, and that stopped the files being added in `app/storage/clockwork`, but `app/storage/cache` is still filling up.

Is there a way to stop this? Can I delete these files without causing any harm?

I realize that we're using an old version, but we're not in a position to upgrade at this time.

**Version**
`v1.13.3` at `afad68f3694e0363f3e5c7272958a2ca5f26a1af` on `1.13.3` 

**Steps to reproduce the bug**
1. Set `debug` to `false` in `app/config/local/app.php`.
1. Run learning-locker.
1. Watch inode usage constantly grow in app/storage/cache.

**Expected behaviour**
Given that debug is set to false, I would expect to not have the filesystem filling up with debug-type information.

**Actual behaviour**
`app/storage/cache` is filling up with the files described above.

**Additional information**
OS: Debian Jessie 
Browser: N/A

**Comment by ht2** [comment]
I believe this is the aggregation results being cached (https://github.com/LearningLocker/learninglocker/blob/v1/app/locker/repository/Query/EloquentQueryRepository.php#L87) which is a feature of v1 that never got built out any further.

I would suggest you use the `php artisan cache:clear` function on a cron to periodically clear this folder. Or even better, upgrade your V1 instance to V2 which provides optional caching to the aggregation API via Redis :)
