### ISSUE TITLE
Feature Request: Quarterly Reports

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#1099]
This came in from a client. Please offer quarterly reporting dates.

**Comment by ht2** [comment]
Hey @davetosh - probably the easiest way to achieve this will be with shareable dashboards with a filter for the date you need. 

In an upcoming release (see #1096) we are introducing multiple shareable links per dashboard (each with it's own filter) so in this way you would be able to create a Q1 2017 link, Q2 link, Q3 etc each with a respective `timestamp` filter applied.
