### ISSUE TITLE
AMI Deployment fails

### ISSUE THREAD

**Issue by imclean** [LearningLocker/learninglocker#1100]
The following occurs, deployed twice same issue.

**Version**
Learning Locker 2.1.2-1 from HT2 Labs Public AMI

**Steps to reproduce the bug**
1. Start a new instance as per the video.
2. Open browser after waiting for deployment to complete (waited 15 minutes)

**Expected behaviour**
Should see login screen

**Actual behaviour**
404 Not Found

nginx/1.10.3 (Ubuntu)

**Additional information**
Free Tier box

**Comment by imclean** [comment]
3rd attempt, got login screen

**Comment by imclean** [comment]
And its down again, was only up long enough for me to get the credentials from ssh, trying to login it had already fallen over.

**Comment by imclean** [comment]
Ok, after numerous attempts with the AMI and with manual scripts, it is fair to say that this will not deploy on a free tier EC2 box.

**Comment by ht2** [comment]
Thanks @imclean - advice for the moment is spin this up on a larger instance size.
