### ISSUE TITLE
Ability to set SideNavFooter values via the .env

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#1111]
**Version**
2.0+

**Steps to reproduce the bug**
1. Log into LL
2. Look at lower left corner of the screen

**Expected behaviour**
* Should say "Powered by Learning Locker" as opposed to "Learning Locker Cloud"
* Maybe offer an option of "Powered by Learning Locker on XYZ Cloud"
* Localization of "Help Centre"
* Removal of "Help Centre"
* Ability to set URL of "Help Centre"
* All settings configurable via .env file

**Comment by ryansmith94** [comment]
I think this just needs to say "Powered by Learning Locker" at all times, not much use in customising that. @Ian247 want to get someone to tweak that real quick? I'll close this for now because I don't think it matters too much either way, but thanks for reporting this David.
