### ISSUE TITLE
Error requesting password reset

### ISSUE THREAD

**Issue by hamishdewe** [LearningLocker/learninglocker#1118]
You need to replace the parts of this template where you see {{some text}}.

**Version**
{{branch}} at {{commit}} on release 2.1.4 

**Steps to reproduce the bug**
1. Navigate to /forgot
2. Enter a valid user email address
3. Click 'Send reset instructions'
4. Error message displayed: Error communicating with the server. Actual error message return is 'Could not save resetToken onto user'

Some investigation showed that the source error was 'MongoError: Unknown modifier: $pushAll'.
Adding 'usePushEach: true' to the schema options in models/user.js and rebuilding resolved this issue. This may be required in other places as well, perhaps due to my version of MongoDB.

**Expected behaviour**
User should have resetToken set in record, email sent.

**Actual behaviour**
Error thrown.

**Additional information**
OS: CentOs 7
Browser: Chrome
Database: 
mongod --version
  db version v3.6.3
  git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
  OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
  allocator: tcmalloc
  modules: none
  build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

**Comment by ht2** [comment]
Certainly looks to me like an issue with using Mongo 3.6. We currently have no tests or support for that version so I would recommend dropping to 3.4.
