### ISSUE TITLE
LL missing deps when installing only production deps

### ISSUE THREAD

**Issue by mdeboer** [LearningLocker/learninglocker#1145]
**Version**
master at 4d9014f on v2.2.4 (quite possibly also v2.3.0)

**Steps to reproduce the bug**
1. Install learning locker manually (yarn build-all etc.)
2. Remove devDepencendies by running `yarn install --production --force` (to save space)
3. Start the app, it'll complain about missing cookie-parser

**Expected behaviour**
Stuff should work!

**Actual behaviour**
Stuff is broken. Cookie parser is missing.

**Additional information**
OS: Docker on OSX using node:6 image

**Proposed fix**
Move cookie-parser from devDependencies to dependencies just like body-parser.

**Comment by ryansmith94** [comment]
Hi @mdeboer, thanks for reporting this, apologies that we've taken so long to respond, I noticed that we've not responded to a few issues recently, I accidentally un-watched the repository at some point so I've not been receiving notifications of new issues.

**Comment by ryansmith94** [comment]
@Ian247 we need to ideally add a ticket to ensure that LL runs without dev deps.

**Comment by ryansmith94** [comment]
Sorry we're tracking this in #1302, forgot we'd had this discussion in here.
