### ISSUE TITLE
Learning Locker Version 2.2.2 Basic Configuration Issue

### ISSUE THREAD

**Issue by pexpert9** [LearningLocker/learninglocker#1147]
I have trying to install learning locker version 2 on centos by following command
So Got following error when step reached at last steps ..
1. Node js user not created 

I have create user externally from command prompt .
It works ..

But when i open first time LRS v2 from HOST:3000
then it show login page and i have successfully login.

Now problem is that i have not show statement in dashboard ..

i have trying lot of times ..
but not success..
1. i have add statement through migration tool from LRS v1
2. i have also added statements directly from mongo db shell
3. statement(tables) is collected all statements but not show in dashboard.

Please provide basic configuration details which are required in first time.

Please give me some sample ...

**Comment by ht2** [comment]
Please conform to our issue template.
