### ISSUE TITLE
No Credentials on AMI instance

### ISSUE THREAD

**Issue by bknill** [LearningLocker/learninglocker#1160]
I span up a server in Sydney using the lastest community AMI. 

It shows the login screen. 

I've ssh'd into server an can't find the credentials file, it's not in home/ubuntu/

![image](https://user-images.githubusercontent.com/7074483/39977933-5cd294f0-5791-11e8-828f-7a00b39b3677.png)

**Comment by ht2** [comment]
Hi @bknill - could you please provide the exact AMI ID you used to do this?

**Comment by bknill** [comment]
It was the 2.5-6 version on the Community store in Sydney I think. I'll find the ID.  

I used an older version and it was fine.
