### ISSUE TITLE
Unable to add/update data from Learning Locker UI with Mongodb sharded cluster as backend

### ISSUE THREAD

**Issue by Puneet-Singh01** [LearningLocker/learninglocker#1164]
**Version**
Learning Locker 2.1.3 - community version

**Steps to reproduce the bug**
1. Login to Learning Locker UI which has backend as Mongodb sharded cluster.
2. Try adding/updating a User or Organization.
3. Data doesn't get saved and an error message is displayed - 
    MongoError: "mode" had the wrong type. Expected string, found null
4. If we replace sharded cluster with a standalone mongo database or replica set, then we are able to edit/save data from the UI.

**Expected behaviour**
We should be able to add/edit data from the Learning Locker UI which has mongodb sharded cluster as the backend.

**Actual behaviour**
Data doesn't get saved and an error message is displayed - 
"MongoError: "mode" had the wrong type. Expected string, found null"

**Additional information**
OS: Red Hat Linux 7.2
Browser: Firefox 52.7.2 (32-bit)
Database - MongoDB 3.6.2 community version

**Comment by ht2** [comment]
Hi @Puneet-Singh01 - are there any further errors in the logs?

**Comment by Puneet-Singh01** [comment]
No. Here is the full log.

3|API      | 2018-05-15 04:23:47:752 - error:  MongoError: "mode" had the wrong type. Expected string, found null
3|API      |     at Function.MongoError.create (/opt/app/workload/lib/learningLockerV2/learninglocker-master/node_modules/mongodb-core/lib/error.js:31:11)
3|API      |     at queryCallback (/opt/app/workload/lib/learningLockerV2/learninglocker-master/node_modules/mongodb-core/lib/cursor.js:212:36)
3|API      |     at /opt/app/workload/lib/learningLockerV2/learninglocker-master/node_modules/mongodb-core/lib/connection/pool.js:469:18
3|API      |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
3|API      |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
3|API      | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
3|API      | MongoError: "mode" had the wrong type. Expected string, found null
3|API      |     at Function.MongoError.create (/opt/app/workload/lib/learningLockerV2/learninglocker-master/node_modules/mongodb-core/lib/error.js:31:11)
3|API      |     at queryCallback (/opt/app/workload/lib/learningLockerV2/learninglocker-master/node_modules/mongodb-core/lib/cursor.js:212:36)
3|API      |     at /opt/app/workload/lib/learningLockerV2/learninglocker-master/node_modules/mongodb-core/lib/connection/pool.js:469:18
3|API      |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
3|API      |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by Puneet-Singh01** [comment]
Hi @ht2 can you please let me know if I am missing something in the configuration? Functionality works fine for standalone mongo database and replicaset but doesn't fork for a sharded cluster. One thing to note is xapi statements are getting saved to the same sharded cluster but it is giving error when trying to save something from the LL UI.

**Comment by ht2** [comment]
Hi @Puneet-Singh01 - sorry but it's very hard for us to diagnose this issue for you. We know of Mongo shards working with version 2, however we have no knowledge of your mongos setup and cannot support that directly for you. I would question the Mongo connection URI string you are using and would suggest you check that.

Learning Locker uses Mongoose under the hood to connect to Mongo; there are many settings which you can find in their documentation and you are able to add and change connection options in the  mongoose connection module in LL. Please find some useful links below:

### Mongo connection URL formatting
https://docs.mongodb.com/manual/reference/connection-string/

### Mongoose documentation
#### v4 (for LL versions 2.3 and less)
http://mongoosejs.com/docs/4.x/

#### v5 (for upcoming LL version 2.4 and higher)
http://mongoosejs.com/docs/api.html#

### Mongoose connection module
https://github.com/LearningLocker/learninglocker/blob/master/lib/connections/mongoose.js

If you are really hitting issues still, I would suggest writing a simple and small Node script that uses the mongoose connection module to try and connect. We know Mongoose can connect to shards, so I do not believe this is a Learning Locker issue.
