### ISSUE TITLE
Upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by doender** [LearningLocker/learninglocker#1166]
Using the latest version of learning locker, I get the following nginx error when querying the `/api/statements/aggregate` endpoint.

`upstream prematurely closed connection while reading response header from upstream`

This only happens when the amount of data that is requested is large.

**Comment by doender** [comment]
Is there any extra information I can give that would help in finding out where the problem lies?

**Comment by ht2** [comment]
Hey @doender - this sounds like nginx timing out on the request. Likely problems:

- Your query is not optimised
- Your query does not use good indexes
- Your query times out (scans too much data)

If I was you I would monitor the database queries and see if anything is taking too long (and why).

**Comment by doender** [comment]
@ht2 It could be that the query can be optimized, but we have set the appropriate indexes and as far as I understand `MAX_TIME_MS` and `MAX_SCAN` are set to unlimited by default (http://docs.learninglocker.net/guides-configuring/). Or is there another timeout set?

**Comment by ht2** [comment]
What's the query, and looking at your query logs can you see things taking longer than expected (say 60s)? I would recommend using the following tools to understand exactly where you might be seeing issue:

https://gist.github.com/rantav/3433277

https://docs.mongodb.com/manual/reference/method/db.setProfilingLevel/

**Comment by doender** [comment]
FYI, we're seeing this again but for another reason. In Node 8.14, URL length is limited to 8192 bytes: https://github.com/nodejs/node/commit/186035243fad247e3955fa0c202987cae99e82db.

For this reason, calls to the aggregation API (where URLs can get quite long...) fail when long URLS are used (the UI service immediately closes the connection). Maybe it would make sense to encode the pipeline in the body?

See also: https://github.com/nodejs/node/issues/24692

**Comment by ht2** [comment]
Hey @doender - yea we've toyed with the idea of changing the aggregation to a POST endpoint (or at least adding one). Good spot on the 8.14 restriction. Up to now when we've hit this limitation it's been on the nginx side for us and we've simply upped the client buffers accordingly, but Node having the limitation makes this food for thought.

https://stackoverflow.com/questions/1067334/how-to-set-the-allowed-url-length-for-a-nginx-request-error-code-414-uri-too

**Comment by figureone** [comment]
FYI I was able to get this to work by passing the argument directly to the pm2 restart command:
```
pm2 restart all --node-args="--max-http-header-size=262144"
```
Note that you need to be running Node 6.16.0, 8.15.0, 10.15.0, or above.
Also note that this should persist to the next restart command, even if you don't pass the argument:
https://github.com/Unitech/pm2/issues/13#issuecomment-220302011

I can't seem to get it working by modifying the pm2 json files, but that may be because the command line argument overrides anything set in the json config. Also, `webapp/pm2/all.json` may need the change, instead of `xapi/pm2/xapi.json` as mentioned above.
