### ISSUE TITLE
Set HTTPS with Nginx in Ubuntu

### ISSUE THREAD

**Issue by neboduus** [LearningLocker/learninglocker#1208]
In order to set HTTPS over Learning Locker within Ubuntu Server 16.04 LTS You should:

If you have the certificate for Windows, first export SSL certificate from Windows to Linux

	https://major.io/2007/03/23/exporting-ssl-certificates-from-windows-to-linux
	
Once you have the certificates for Linux, you should have 2 files:
	
	cert.key  ->  The Key file
	cert.crt  ->  The certificate
	
	# Copy those file into Default Ubuntu SSL folder, from terminal, like this:
	
	>>> sudo cp /path/to/cert/learninglocker_cert.crt /etc/ssl/certs
	>>> sudo cp /path/to/key/learninglocker_cert.key /etc/ssl/private
	
	
	# In order to set the HTTPS certificate through NGINX we follow this guide:
		
	http://nginx.org/en/docs/http/configuring_https_servers.html

## Essential steps:

	# Go to learninglocker.conf file -> this is learninglocker's file configuration for NGINX
	
	>>> cd etc/nginx/sites-avalable
	
	# Edit learninglocker.conf file as an administrator
	
	>>> sudo nano learninglocker.conf
	
	# We can edit the .conf file now
	
	# Following the specified guide we tell to NGINX where to find the certificate with his key,
	and some others configurations like this:
	
	server {
		listen 80 default_server;
		listen [::]:80 default_server;
		
		######### NEW LINES OF CODE #########
		listen 443 ssl default_server;
		listen [::]:443 ssl default_server;
		#####################################
	
		server_name SITE_URL;
		
		######### NEW LINES OF CODE #########
		# We specify the location of the Key and the Certificate
		ssl_certificate /etc/ssl/certs/learninglocker_cert.crt
		ssl_certificate_key /etc/ssl/private/learninglocker_cert.key
		# Limit connections to include only the strong versions and ciphers of SSL/TLS
		ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers         HIGH:!aNULL:!MD5;
		#####################################
		
		...
	}
	
	# Reload NGINX configurations
	
	>>> sudo service nginx reload

**Comment by ryansmith94** [comment]
Thanks @neboduus 👍
