### ISSUE TITLE
xapi not working after upgrading to 2.4.1 - Mongo replicaset

### ISSUE THREAD

**Issue by MehdiAmin** [LearningLocker/learninglocker#1209]
**Version**
2.4.1

**Steps to reproduce the bug**
1. I have LRS 2.0.7 and here is my MONGO_URL for xapi
1. cat current/xapi/.env 

MONGO_URL=mongodb://mongo1.x.com:27017,mongo2.x.com:27017,mongo3.x.com:27017/learninglocker?replicaSet=rs0&readPreference=secondaryPreferred&slaveOk=true

2. Everything is working without any issue.
3. I'm upgrading LRS to 2.4.1 using ./deployll.sh
4. After upgrade, I'm getting "A server error occurred" in xapi_stderr-3.log

{ message: 'not master',
  name: 'MongoError',
  ok: 0,
  errmsg: 'not master',
  code: 10107,
  codeName: 'NotMaster',
  stack: 'MongoError: not master\n    at /opt/learninglocker/releases/ll-20180723-6b58feb3459853b3e7bd26febe7674e9551a65dc/xapi/node_modules/mongodb-core/lib/connection/pool.js:580:63\n
}

5. If I remove "readPreference=secondaryPreferred" from MONGO_URL, xapi works like a charm!
6. FYI, mongo1 and mongo2 are secondary and mongo3 is primary.

**Expected behaviour**
I have expected to forward the read queries to secondary monogs and not primary.

**Actual behaviour**
I'm getting error as I mentioned before.

**Additional information**
OS: Debian 8.10
Percona Mongo: 3.4.10

**Comment by MehdiAmin** [comment]
I gather some more info.

1- I have the same issue with fresh install of 2.4.1

2- webapp is working fine with: MONGO_URL=mongodb://mongo1.x.com:27017,mongo2.x.com:27017,mongo3.x.com:27017/learninglocker?replicaSet=rs0&readPreference=secondaryPreferred&slaveOk=true

3- Here are the entries in /var/log/learninglocker/xapi_stdout-4.log 

2018-07-31 13:33:53:896 - info: Listening on port 8081
2018-07-31 13:33:53:897 - info: Process ready
2018-07-31 13:33:53:921 - info: Created new Mongo connection
2018-07-31 13:33:53:922 - info: A secondary server joined the replica set mongo3.x.com:27017
2018-07-31 13:33:57:126 - info: A primary server (mongo1.x.com:27017) left the replica set
2018-07-31 13:33:57:148 - info: Created new Mongo connection
2018-07-31 13:33:57:150 - info: A secondary server joined the replica set mongo3.x.com:27017

FYI,  "mongo1.x.com" server is fully operational as primary node.


Please advise.

**Comment by ht2** [comment]
Hi @MehdiAmin. Aggregations are automatically sent to the secondaries already (https://github.com/LearningLocker/learninglocker/blob/master/lib/models/statement.js#L95). Reading from the primary is absolutely required in many cases as we need to ensure we have the most up to date version of documents to avoid concurrency concerns and issues that arise from oplog lag.
