### ISSUE TITLE
TypeError: Cannot read property '_id' of null

### ISSUE THREAD

**Issue by doender** [LearningLocker/learninglocker#1251]
**Version**
2.1.2

In our LearningLocker instance we're sometimes seeing:
```
TypeError: Cannot read property '_id' of null
    at /usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/worker/dist/server/webpack:/handlers/statement/listenForV1.js:39:49
    at Query.<anonymous> (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/mongoose/lib/model.js:3932:16)
    at /usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/kareem/index.js:273:21
    at /usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

in our logs. What could cause this error?

**Comment by ryansmith94** [comment]
Hi @doender, thanks for reporting this, could you please try to upgrade to the latest version of Learning Locker and let us know if this has been resolved now?

**Comment by ht2** [comment]
Hi @doender - have you set readPreference to secondary in your connection details or simply not pointed the worker at all your hosts? There's no reason it should be connecting and reading from the secondary for this operation. The worker would require read preference set to primary (the default) in order to deal with a whole host of race conditions.

**Comment by doender** [comment]
@ht2 We've set the readPreference in `/usr/local/learninglocker/current/webapp/.env` to 'nearest' in order to have faster read queries (for example using the aggregation API). Do you suggest we change that?

**Comment by ht2** [comment]
Yes - FYI aggregations already automatically are sent to the secondaries anyway. 

Plus unless your replicas are literally deployed half a world away from each other, then really you're not going to see much more than a couple of milliseconds of improvements

**Comment by doender** [comment]
Our replica set members are deployed quarter a world away from each other :) (Amsterdam and Singapore). We'll do some measurements to see whether latency is still acceptable when we use the default readPreference.

Are the statements for which we saw the error lost or just kept on the queue and processed again?

**Comment by ht2** [comment]
They are probably lost, there is no capture and retry for this as it simply pops off the subscribe.

An interesting setup re:replicas. Do you have application servers across both locations as well?

**Comment by doender** [comment]
Yes, we have application servers in both locations.

May I ask what the reason is why aggregations are sent to the secondaries? Is it to reduce load on the primaries?

**Comment by ht2** [comment]
Exactly - secondaries tend to run no more than a second behind the primary, and when you are aggregating (for visualisations), that information is simply not time critical. However, when inserting statements and running worker jobs, that does require consistency that you can only get from the primary.

If you want to modify behaviour for aggregations, you can make your own change on your deployments here: https://github.com/LearningLocker/learninglocker/blob/master/lib/models/statement.js#L96

**Comment by doender** [comment]
After removing `readPreference=nearest` in `MONGODB_PATH` in `/usr/local/learninglocker/current/webapp/.env`, we're still seeing this error in 2.6.1.

**Comment by ctm8788** [comment]
@doender  @ht2  Was a fix ever found for this? We are currently seeing this issue.

**Comment by samuelimbert** [comment]
Hello, I was working on the same problem and just find a solution.
the payload received is a now a stringified JSON :
`{"statementId":"------------------","organisationId":"--------------"}`

so we need to :

1. add depencies :
`var _mongoose = __webpack_require__(3);
var _mongoose2 = _interopRequireDefault(_mongoose);
`

2. decode JSON :
`newPayload = JSON.parse(payload)`

3. change the mongo request :
`_statement2.default.findOne({ 'statement.id': newPayload.statementId, "organisation": new _mongoose2.default.Types.ObjectId(newPayload.organisationId) }, function (err, statement) {`

It's just a quick fix and should be corrected in next version I guess.

**Comment by badri-neparidze** [comment]
We are currently seeing this issue too, Ubuntu 18.04 and the latest version of learning locker. Installed via the official installation script.
