### ISSUE TITLE
Learning Locker LRS for Red Hat

### ISSUE THREAD

**Issue by msulaksh** [LearningLocker/learninglocker#1252]
Hello All,

I have done some work with LL over Ubuntu and other open source OS, which works very well, and with that done i was thinking of moving on to Red Hat OS, but found no reference to **LRS being Tested on Red Hat**.
Regarding which i would like to explore possible ways to go with Red Hat or any Alternative.

Thanks.

**Additional information**
OS: Red Hat

**Comment by ryansmith94** [comment]
Hi @msulaksh, thanks for posting your question. Will need some input from @ht2 or @asahd

**Comment by ht2** [comment]
Hi @msulaksh, Learning Locker will work fine on Red Hat/RHEL

**Comment by ryansmith94** [comment]
Hi @msulaksh, the install script doesn't support RHEL but you should be able to manually install Learning Locker on RHEL using our [custom installation documentation](http://docs.learninglocker.net/guides-custom-installation/).
