### ISSUE TITLE
Cannot Login into LearningLocker 

### ISSUE THREAD

**Issue by msulaksh** [LearningLocker/learninglocker#1253]
I have Installed LearningLocker v2 over my Ubuntu Machine, which works well and good, and Statement are being recorded in LRS.
But sometimes I am unable to login into LearningLocker Web Interface.
Error: **404 Not Found nginx/1.10.3 (Ubuntu)**
Same issue Using Google Chrome and Mozilla Firefox.
Please Check Attached Image.

![ll_web_404_issue](https://user-images.githubusercontent.com/38561021/46398353-889b0680-c712-11e8-976e-88fb5a2aee60.png)

This isn't Usual Issue, most of the time it works fine.

Thanks.

**Comment by ryansmith94** [comment]
Hi @msulaksh, can you please check the PM2 logs on the server? Sounds like this is either a problem with the server or an issue with your setup (potentially including your Nginx setup).

**Comment by msulaksh** [comment]
Thanks @ryansmith94
It was Nginx issue, I did reloaded Nginx and its working fine, 
> sudo systemctl reload nginx 

And about PM2 logs, it seems good.
Thanks.

**Comment by ryansmith94** [comment]
That's great, glad it's working for you now. You're welcome @msulaksh 👍

**Comment by kosburn0408** [comment]
I am having this same issue, however I have verified that nginx is running. What are other possible issues?
![learninglocker](https://user-images.githubusercontent.com/32501442/48031568-a947e900-e122-11e8-9c09-435e6ce7add9.jpg)

**Comment by ht2** [comment]
@kosburn0408 Whilst nginx is running, your Node services probably aren't
