### ISSUE TITLE
Problem communicating with the Learning Record Store

### ISSUE THREAD

**Issue by barrysampson** [LearningLocker/learninglocker#126]
After successfully testing LL on my laptop, I've recently set it up on a Digital Ocean Droplet with less success...

Following what I understand to be Laravel best practice, I've installed LL outside the web root, and symlinked to the public folder (so far, so good). The site **is** now up and running, and I can create users and new LRS instances. However, I am unable to submit statements to it. 

I have a Wordpress/Learndash site set up with Grassblade and a couple of simple test courses created in Storyline. If I point the site at a Wax LRS instance, everything works ok. If I set it up to work with LL I get a 401 cannot connect to server error. 

I've tried sending a statement from the generator at [tincanapi.com/statement-generator](http://tincanapi.com/statement-generator) and it spits out a 404 error. 

The full error is below:

> There was a problem communicating with the Learning Record Store. (404 | {"error":true,"message":"","code":404,"trace":[{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":1021,"function":"match","class":"Illuminate\Routing\RouteCollection","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":989,"function":"findRoute","class":"Illuminate\Routing\Router","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":968,"function":"dispatchToRoute","class":"Illuminate\Routing\Router","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":738,"function":"dispatch","class":"Illuminate\Routing\Router","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":708,"function":"dispatch","class":"Illuminate\Foundation\Application","type":"->","args"...p","line":72,"function":"handle","class":"Illuminate\Http\FrameGuard","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php","line":47,"function":"handle","class":"Illuminate\Session\Middleware","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php","line":51,"function":"handle","class":"Illuminate\Cookie\Queue","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/var\/www\/learninglocker\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php","line":23,"function":"handle","class":"Illuminate\Cookie\Guard","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":606,"function":"handle","class":"Stack\StackedHttpKernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/learninglocker\/public\/index.php","line":49,"function":"run","class":"Illuminate\Foundation\Application","type":"->","args":[]}]})

I've reached the conclusion that I must have configured something wrong which means that the expected end point at [http://parcel-project.org/data/xAPI/](http://parcel-project.org/data/xAPI/) is not being found. I just can't work out what it is that I've done wrong! 

Any suggestions are greatly appreciated.

**Comment by HumeraShazia** [comment]
Hi @barrysampson ,
Have you tried GrassBlade LRS http://www.nextsoftwaresolutions.com/grassblade-lrs-experience-api/ ? Here is a link https://nextsoftwaresolutions.zendesk.com/hc/en-us/articles/203839019-Human-Readable-name-instead-of-IDs-for-Articulate-Content .It may be helpful.

**Comment by hallshouse** [comment]
@barrysampson I looked at Digital Ocean as well and was not able to get LL working properly. I would recommend trying Impact VPS http://impactvps.com/index.html using a free trial before trying another. Within the next few days, you will see a KB article I've written in their knowledgebase on installing a MEAN Stack.
I'm having great success with Storyline2 now that we've found the correct URL Query. I'm also currently building a Tin Can Launcher that works in WordPress. The launcher builds and Encodes the URL for you, it then creates a button for you to paste into your WordPress post or page.
Right now the launcher is working, however, I'm testing it against eLearning and non-eLearning projects before releasing it.

Don't give up on LL, it offers a great deal more flexibility the GrassBlade.

**Comment by barrysampson** [comment]
@HumeraShazia Since Articulate released Storyline 2 (with support for xAPI 1.0) we've had no problem and Learning Locker has been the perfect solution for us. 

@hallshouse The issue I had was related to Storyline's lack of support for xAPI 1.0. Once Storyline 2 came out we had no problems - we have had Learning Locker running on a Digital Ocean droplet for over a year now without any issues.

**Comment by ryansmith94** [comment]
Thanks for your input @barrysampson and @hallshouse :+1:
