### ISSUE TITLE
Binary attachments are getting corrupted

### ISSUE THREAD

**Issue by brian-learningpool** [LearningLocker/learninglocker#1261]
**Version**
`master` at e08b009 on 2.5.0

**Steps to reproduce the bug**
1. Generate an xAPI statement which includes a file attachment such as a PDF file or image.

**Expected behaviour**
The attachment should be stored successfully on local disk, S3 or whatever storage option is configured.

**Actual behaviour**
The attachment is stored but it is getting corrupted, i.e. the file size is different from expected, the contents are scrambled.

**Additional information**
OS: Ubuntu 16.04.5 LTS
Browser: Google Chrome version 69

This looks to be due to an assumption that `UTF8` encoding will be used in all the files uploaded.

**Comment by ryansmith94** [comment]
Thanks @brian-learningpool. Are you able to create a pull request for this in the xapi-statements repository and link to the PR here?

**Comment by brian-learningpool** [comment]
Hi @ryansmith94, yes, I will do.

**Comment by brian-learningpool** [comment]
PR here: https://github.com/LearningLocker/xapi-statements/pull/244

**Comment by ryansmith94** [comment]
Should be fixed as of [xapi-service v2.2.13](https://github.com/LearningLocker/xapi-service/releases/tag/v2.2.13). I'll close this an reopen if the issue persists beyond that release. Thanks for all of your help with this @brian-learningpool @wobrien really appreciated 👍
