### ISSUE TITLE
attachments=true causes GET on /xAPI/statements to timeout

### ISSUE THREAD

**Issue by brian-learningpool** [LearningLocker/learninglocker#1264]
**Version**
`master` at e08b009 on 2.5.0

**Steps to reproduce the bug**
1. Set the storage to AWS S3.
2. Send a statement to Learning Locker which contains an attachment.
3. Make a GET request to `/statements` with `attachments=true` set.

**Expected behaviour**
The endpoint should return with details of the attachments.

**Actual behaviour**
The request times out.

**Additional information**
OS: Ubuntu 16.04.5 LTS
Browser: Google Chrome version 69

**Note:** The API call to include attachments __works as expected when local__ is being used for storage.

Sample cURL request shown below:
```
curl -X GET \
  'http://ll-test.domain.com/data/xAPI/statements?statementId=76632bbb-6ded-4d78-bcfb-5d68bf171fa1&format=exact&attachments=true' \
  -H 'authorization: Basic ODVjMjFmZjY1M2Q2ZjMwMGM4ZDFmMmQ5ZDgyZGE4YmE0YWY1ODVmMzo3YmY1YTBiNmJkZDNlYzk1YjZmMzgwZWVkNWE0MDI2MDZhMzJkZmIx' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 6553b810-a091-24a4-62
```

It's possible that this might be something to do with a blank folder which was observed when attachments were uploaded to S3, e.g.
local: `/storage/statements/5bc5cddbc8051d0588ebe62e/attachments/`
s3: `//statements/5bc5cddbc8051d0588ebe62e/attachments/`

**Comment by wobrien** [comment]
I've created PR https://github.com/LearningLocker/xapi-statements/pull/247  to allow GET request to /statements with attachments=true  when storage is s3
