### ISSUE TITLE
Cannot log into learninglocker

### ISSUE THREAD

**Issue by kosburn0408** [LearningLocker/learninglocker#1274]
I have just completed (several times) a new installation of learninglocker on Ubuntu 18.04.  While there were no obvious issues during the installation I was unable to log into the server afterwards.  I noticed that someone had the same issue recently but resolved it by restarting nginx.  I have confirmed that nginx is running and even after restart it and/or the server the issue persists (nginx/1.14.0 (Ubuntu)).  See the attached screen shot:

![learninglocker](https://user-images.githubusercontent.com/32501442/48033385-24ac9900-e129-11e8-983e-5b90ce4fb5ed.jpg)

**Comment by msulaksh** [comment]
@kosburn0408 Simply Restart all the services, check status. It shall work then.

**Comment by kosburn0408** [comment]
@msulajsh. Tried "pm2 restart all" but that didn't help. Same error.

**Comment by asahd** [comment]
Hey @kosburn0408, are you using the Install Script?

If so, can you please try on Ubuntu 16.x and see if you have better results? There may be some issues in with 18.x

**Comment by kosburn0408** [comment]
Hi All,

I've figured out the issue is with 18.04 and specifically the issue is with
mongodb.  I'll try the 16.x version of Ubuntu later this afternoon and let
the group know.

Thanks!

Keith

On Nov 6, 2018 11:59 AM, "asahd" <notifications@github.com> wrote:

Hey @kosburn0408 <https://github.com/kosburn0408>, are you using the
Install Script?

If so, can you please try on Ubuntu 16.x and see if you have better
results? There may be some issues in with 18.x

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LearningLocker/learninglocker/issues/1274#issuecomment-436327927>,
or mute the thread

**Comment by kosburn0408** [comment]
Just confirming that the issue is clearly with Ubuntu 18.04 and specifically with mongo.  Seems that 18.04 has a lot of trouble installing mongodb.  I reinstalled 16.x on my server, reinstalled LL and had zero problems.

**Comment by asahd** [comment]
Thanks for confirming, @kosburn0408 - I'll close this issue for now.

Ubuntu 18.x support is likely something we will look into further down the line
