### ISSUE TITLE
Custom reports / dashboards

### ISSUE THREAD

**Issue by doender** [LearningLocker/learninglocker#1277]
Hi, we would like to retrieve and aggregate data on our learning locker instance to create custom reports. The reason for this is that requesting the 'raw' statements from our application server using LL's aggregation API and then aggregating it further on the application server is not possible / practical due to the amount of data (around 1 million statements) that needs to be processed.

We were thinking of creating our own API endpoint (next to the existing learning locker API) that would query mongo directly and cache the aggregated statistics. Is this the way to go or is there any existing API we can hook into?

**Comment by ryansmith94** [comment]
Hi @doender, the aggregation API does use Mongo directly, the only added latency is making the request via HTTP and receiving the response via HTTP. We'd recommend paginating through the statements either via the [aggregation API](http://docs.learninglocker.net/http-aggregation/) or the [connection API](http://docs.learninglocker.net/http-connection/). We have some users of Learning Locker inserting 1 million statements per day that are retrieving data via these APIs in chunks (usually paginated chunks).
