### ISSUE TITLE
update xapi service to have a version number

### ISSUE THREAD

**Issue by caperneoignis** [LearningLocker/learninglocker#1287]
**Version**
2.6.1

**Steps to reproduce the bug**
1. go to xapi/package.json
2. vi the package.json file look at version number

**Expected behaviour**
have the version of the xapi service

**Actual behaviour**
0.0.0-development

**Additional information**
OS: na
Browser: n/a
This is confusing to see 0.0.0-development when seeing the version numbers in pm2. It would be helpful for both debugging and issue tracking to have the actual version in the package.json file so you can also see it in pm2, due to the  fact some folks may be building the services separately for whatever reason.

**Comment by caperneoignis** [comment]
I would have put this in the xapi repository but there is no issue section there.

**Comment by ryansmith94** [comment]
Understand the need for this thanks @caperneoignis. Just a limitation of our current release process with Semantic Release.

**Comment by ryansmith94** [comment]
I think for now this can be obtained from the git tag so I'm going to close for now.
