### ISSUE TITLE
$sample as start in mongo pipeline not respected as start

### ISSUE THREAD

**Issue by davidavdav** [LearningLocker/learninglocker#1291]
**Version**
{{branch}} at f4fd50090b44b0b37fcd23c5f664619ee5c0e279 on 2.6.1

**Steps to reproduce the bug**
1. use database with large statements collection
2. use aggregate request starting with { $sample: size: 10 }
3. use mongo shell `db.currentOp()` to see what takes so long
4. observe that in the long lasting operation, the pipeline has been prepended with matches to `lrs_id` and `organisation`

**Expected behaviour**
The $sample pipeline statement, when used as a first, [should stay first](https://docs.mongodb.com/manual/reference/operator/aggregation/sample/#pipe._S_sample), otherwise mongo will do a full document scan---and it should sample instead. 

**Actual behaviour**
$sample is moved to 3rd place in the pipeline, making it do a full scan, which takes forever on large collections.  

**Additional information**
OS: linux
our collection has about 7 million statements at the moment.

**Comment by davidavdav** [comment]
I have a fix for this now, I'll try to make a PR soon

**Comment by ryansmith94** [comment]
PR #1292 was closed due to inactivity. We need to implement a `sampleSize` query parameter to allow this without modifying the query in a new PR.

**Comment by ryansmith94** [comment]
Resolved by [v3.7.0](https://github.com/LearningLocker/learninglocker/releases/tag/v3.7.0) 👍
