### ISSUE TITLE
send xapi statement to S3 bucket

### ISSUE THREAD

**Issue by gsaraceno92** [LearningLocker/learninglocker#1305]
**Version**
master on 2.5.5 

**Steps to reproduce the issue**
Build a POST request to LRS to save the statement in S3 as file storage system.
I set in the project .env of learninglocker (in webapp and xapi) the follow parameters:
-FS_AWS_S3_ACCESS_KEY_ID
-FS_AWS_S3_SECRET_ACCESS_KEY
-FS_AWS_S3_REGION
-FS_AWS_S3_BUCKET

Use as endpoint http://example.com/data/xAPI/statements, use basic auth and try to send a request with a json 

**Expected behaviour**
 I find a new file in my S3 bucket with statementId as name of the file.

**Actual behaviour**
I can't send a file or a json to S3

**Additional information**
Maybe I don't know how to set the content-type or any else parameter in the header.

**Comment by ryansmith94** [comment]
Hi @gsaraceno92, it sounds like you're expecting your statements to be stored in S3. The S3 storage is purely for statement attachments, not the statement's themselves. Storing the statements in S3 would make it more difficult to query them, right now we only support Mongo storage for statements.

**Comment by gsaraceno92** [comment]
I misunderstood the storage possibilities in Learning Locker.
I read the documentation and I thought that it could be possible send the statements to a file storage but it actually makes sense that it's not possible.
Sorry and thank you so much for your help.
