### ISSUE TITLE
Remove auth object from smtpConfig object when chosen

### ISSUE THREAD

**Issue by caperneoignis** [LearningLocker/learninglocker#1306]
Currently in the nodemailer.js file has this
````
auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS
  }
````
It should also have ntlm as an option since some smtp servers don't use plain or oauth2. 

See this [link](https://github.com/nodemailer/nodemailer-ntlm-auth) for a way to add ntlm as a custom auth, and add a condition if someone ask for ntlm to add the custom option to the auth. Otherwise email wont be sent for some instances, like mine, that don't allow for plain auth. 

this is the error I receive currently.

````
{ message: [32m'Invalid login: 504 5.7.4 Unrecognized authentication type'[39m, stack: [32m'Error: Invalid login: 504 5.7.4 Unrecognized authentication type\n at SMTPConnection._formatError (/usr/local/learninglocker/releases/ll-20181219-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/smtp-connection/lib/smtp-connection.js:528:15)\n at SMTPConnection._actionAUTHComplete (/usr/local/learninglocker/releases/ll-20181219-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/smtp-connection/lib/smtp-connection.js:1231:30)\n at SMTPConnection.<anonymous> (/usr/local/learninglocker/releases/ll-20181219-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/smtp-connection/lib/smtp-connection.js:319:22)\n at SMTPConnection._processResponse (/usr/local/learninglocker/releases/ll-20181219-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/smtp-connection/lib/smtp-connection.js:669:16)\n at SMTPConnection._onData (/usr/local/learninglocker/releases/ll-20181219-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/smtp-connection/lib/smtp-connection.js:493:10)\n at emitOne (events.js:116:13)\n at Socket.emit (events.js:211:7)\n at addChunk (_stream_readable.js:263:12)\n at readableAddChunk (_stream_readable.js:250:11)\n at Socket.Readable.push (_stream_readable.js:208:10)\n at TCP.onread (net.js:601:20)'[39m, code: [32m'EAUTH'[39m, response: [32m'504 5.7.4 Unrecognized authentication type'[39m, responseCode: [33m504[39m, command: [32m'AUTH PLAIN'[39m }
````

I see nodemailer considers the session already authenticated if there is no username or password specified. which is the correct way to handle it, but the auth method specified should probably be a configurable item, also if there is no username and password I believe auth should be blank, otherwise it will try to use auth plain with a blank username and password. Otherwise, I don't under stand why it is trying to use AUTH in the first place.

**Comment by caperneoignis** [comment]
Yep, the issue in my case, is no AUTH on the relay. So having the auth object is causing the LRS to try and AUTH PLAIN. If you remove the AUTH object if username and password is empty then it would work in my case. 

I purpose to add a condition and environment variable to allow a administrator to turn off auth. We can also add the ability to add additional auths like NTLM for those of us who are stuck using Microsoft exchange, which was also one of the smtp servers we were using but I was informed we had switched because who tells admins crap. 

I will try and add a condition to add the AUTH object, which will be the default, unless someone sets auth to false. Since a blank username and password may still require a auth request, just automatic approval instead of authentication.

**Comment by caperneoignis** [comment]
Will be pulling the code to our server today, and will see if the issue has been resolved.

**Comment by asahd** [comment]
> The email is _not_ functioning as expected when setting the new value to false.

Hoping that's a typo of _now_, @caperneoignis?

**Comment by caperneoignis** [comment]
yea lol

**Comment by caperneoignis** [comment]
Sorry about that @asahd for some reason I didn't even catch that. Must have had two sentences in my head I wanted to type and it came out in one.

**Comment by asahd** [comment]
Phew!
