### ISSUE TITLE
Mongo 3.4 end of life September '19

### ISSUE THREAD

**Issue by caperneoignis** [LearningLocker/learninglocker#1321]
Mongo 3.4 is approaching end of life in September. When is learning locker planning on supporting 3.6 or 4.0? As you well know once a piece of software hits EoL most networks will refuse to have that service on it. Any chance you guys have an idea when you will be doing the switch?

**Comment by caperneoignis** [comment]
Or what do you need to update to that version?

**Comment by ryansmith94** [comment]
![Excellent](https://media.giphy.com/media/8fen5LSZcHQ5O/giphy.gif)

This is a good point and a great time to use our new catchphrase... [We have plans](https://github.com/LearningLocker/docs/pull/72) lol

**Comment by ht2** [comment]
@caperneoignis You don't need to do anything. We support 3.6 and 4.0 already. Our next major release will actually require 3.6+ due to use of new features in 3.6
