### ISSUE TITLE
[Bug] Postman "Could not get any response"

### ISSUE THREAD

**Issue by TheoChapelot** [LearningLocker/learninglocker#1328]
#### What version were you using?
Mac : custom install v3.1.0 Open Source

VM Ubuntu : installer v3.1.0 Open Source

Windows 10 : v2.0.5 custom docker installs

#### What steps can we follow to reproduce the behaviour?
Do an xAPI call to store statements.

#### What is the actual behaviour?
The xAPI is exposed ( navigating to about will give results )
*test on Postman Mac ( LL version 3.1.0)*
![capture d ecran 2019-03-04 a 10 24 01](https://user-images.githubusercontent.com/33156809/53723338-df467100-3e67-11e9-9eae-37a7ff9efed3.png)

But trying to insert a statement will fail.
*test on Postman Mac ( LL version 3.1.0)*
![capture d ecran 2019-03-04 a 10 25 03](https://user-images.githubusercontent.com/33156809/53723360-ebcac980-3e67-11e9-9150-ab06b531359a.png)

I got the exact same error on Windows and Ubuntu ( with nginx proxy this time )

I don't get this error when using Insomnia, but i get a different one.
*LL version 3.1.0*
![capture d ecran 2019-03-04 a 10 30 07](https://user-images.githubusercontent.com/33156809/53723677-87f4d080-3e68-11e9-81d4-7882e7f8be35.png)

I only posted the Mac OS call, but i got the same result with the other OS ( while using nginx and calling http://localhost/data/xAPI )

#### What is the expected behavior?
With Postman, a response should be sent ( success or error )

With Insomnia, since the header is present, it should succeed.

#### Is there any additional information that will help us replicate/understand the problem?
I thought i might be coming from the custom installs, but after trying on three different OS, the problem seems to be elsewhere.

I might be missing a few things since it's my first time using LL. I scoured the docs but haven't found an answer to my problem.

**Comment by ht2** [comment]
Could you please run this in a shell:
```
curl -X -i POST \
  http://localhost:8081/data/xAPI/statements \
  -H 'Authorization: Basic REPLACE_WITH_YOUR_BASE64_AUTH' \
  -H 'Content-Type: application/json' \
  -H 'X-Experience-API-Version: 1.0.1' \
  -d '[{
    "actor": {"mbox": "mailto:ex@mple.org"},
    "verb": {"id": "https://example.org"},
    "object": {"id": "http://www.example.org"}
}
]'
```

Trying to take Postman out of equation. You need to change to include your basic auth details.

**Comment by TheoChapelot** [comment]
I got this : 

curl: (6) Couldn't resolve host 'POST'
curl: (52) Empty reply from server

**Comment by TheoChapelot** [comment]
With POST i got

curl: (6) Couldn't resolve host 'POST'
curl: (52) Empty reply from server

Without, i only got 
curl: (52) Empty reply from server

**Comment by ht2** [comment]
Apologies - the flags were wrong:
```
curl -i -X POST \
  http://localhost:8081/data/xAPI/statements \
  -H 'Authorization: Basic REPLACE_WITH_YOUR_BASE64_AUTH' \
  -H 'Content-Type: application/json' \
  -H 'X-Experience-API-Version: 1.0.1' \
  -d '[{
    "actor": {"mbox": "mailto:ex@mple.org"},
    "verb": {"id": "https://example.org"},
    "object": {"id": "http://www.example.org"}
}
]'
```

**Comment by TheoChapelot** [comment]
It worked with this one !

**Comment by ht2** [comment]
OK, great. That means that the problem lies with POSTman and there is no actual connectivity issues with Learning Locker. I'll close off this issue as I'm not sure we can offer anymore help specific to POSTman.
