### ISSUE TITLE
error in worker: querybuilderCaches

### ISSUE THREAD

**Issue by abhi9866** [LearningLocker/learninglocker#1332]
#### What version were you using?
Open Source
v3.2.3
#### What steps can we follow to reproduce the behaviour?
Insert statement using postman.
method:POST

#### What is the actual behaviour?

3|Worker  | 2019-03-05 18:08:55:101 - error: ERROR STATEMENT_QUERYBUILDERCACHE_QUEUE 
3|Worker  | { message: 'write operation failed',
3|Worker  |   stack: 'MongoError: write operation failed\n    at Function.create (/app/learninglocker/node_modules/mongodb-core/lib/error.js:43:12)\n    at toError (/app/learninglocker/node_modules/mongoose/node_modules/mongodb/lib/utils.js:149:22)\n    at UnorderedBulkOperation.handleWriteError (/app/learninglocker/node_modules/mongoose/node_modules/mongodb/lib/bulk/common.js:1065:11)\n    at /app/learninglocker/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:201:27\n    at handleCallback (/app/learninglocker/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)\n    at resultHandler (/app/learninglocker/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:161:5)\n    at handler (/app/learninglocker/node_modules/mongodb-core/lib/topologies/replset.js:1197:22)\n    at /app/learninglocker/node_modules/mongodb-core/lib/connection/pool.js:532:18\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)',
3|Worker  |   name: 'BulkWriteError',
3|Worker  |   driver: true,
3|Worker  |   code: 11000,
3|Worker  |   writeErrors: 
3|Worker  |    [ { err: 
3|Worker  |         { index: 2,
3|Worker  |           code: 11000,
3|Worker  |           errmsg: 'E11000 duplicate key error collection: learninglocker_v21.queryBuilderCaches Failed _id or unique key constraint',
3|Worker  |           op: 
3|Worker  |            { organisation: 
3|Worker  |               { _bsontype: 'ObjectID',
3|Worker  |                 id: 
3|Worker  |                  { '0': 92,
3|Worker  |                    '1': 126,
3|Worker  |                    '2': 175,
3|Worker  |                    '3': 113,
3|Worker  |                    '4': 46,
3|Worker  |                    '5': 58,
3|Worker  |                    '6': 242,
3|Worker  |                    '7': 106,
3|Worker  |                    '8': 191,
3|Worker  |                    '9': 98,
3|Worker  |                    '10': 152,
3|Worker  |                    '11': 110 } },
3|Worker  |              path: [ 'statement' ],
3|Worker  |              searchString: 'statement',
3|Worker  |              createdAt: 2019-03-05T18:08:54.954Z,
3|Worker  |              updatedAt: 2019-03-05T18:08:54.954Z,
3|Worker  |              _id: 
3|Worker  |               { _bsontype: 'ObjectID',
3|Worker  |                 id: 
3|Worker  |                  { '0': 92,
3|Worker  |                    '1': 126,
3|Worker  |                    '2': 187,
3|Worker  |                    '3': 54,
3|Worker  |                    '4': 10,
3|Worker  |                    '5': 188,
3|Worker  |                    '6': 148,
3|Worker  |                    '7': 124,
3|Worker  |                    '8': 117,
3|Worker  |                    '9': 138,
3|Worker  |                    '10': 171,
3|Worker  |                    '11': 16 } } } } },
3|Worker  |      { err: 
3|Worker  |         { index: 4,
3|Worker  |           code: 11000,
3|Worker  |           errmsg: 'E11000 duplicate key error collection: learninglocker_v21.queryBuilderCaches Failed _id or unique key constraint',
3|Worker  |           op: 
3|Worker  |            { organisation: { '$ref': '$["writeErrors"][0]["err"]["op"]["organisation"]' },
3|Worker  |              path: [ 'statement' ],
3|Worker  |              searchString: 'statement',
3|Worker  |              createdAt: 2019-03-05T18:08:54.954Z,
3|Worker  |              updatedAt: 2019-03-05T18:08:54.954Z,
3|Worker  |              _id: 
3|Worker  |               { _bsontype: 'ObjectID',
3|Worker  |                 id: 
3|Worker  |                  { '0': 92,
3|Worker  |                    '1': 126,
3|Worker  |                    '2': 187,
3|Worker  |                    '3': 54,
3|Worker  |                    '4': 10,

#### Is there any additional information that will help us replicate/understand the problem?
Im getting this error if I spin up the application using Azure cosmosdb mongo api. 
The native mongo did not throw any error.
In both cases the documents are inserted into collection: queryBuilderCaches.

**Comment by ht2** [comment]
Cosmos does not have full support for Mongo 3.6, so unfortunately we can't really help you here. Pretty sure we deliberately attempt to insert and catch the error to ensure you don't see this. The fact you do see this will be because Cosmos is doing it's own thing - sorry!
