### ISSUE TITLE
Statement forwarding not working as expected

### ISSUE THREAD

**Issue by abhi9866** [LearningLocker/learninglocker#1336]
Hello, Team

We are using Open Source
v3.2.3

When we set up a statement forwarding and sent few statements. They were not sent immediately. When we restarted the applications. The statements are sent.
 Is this expected behaviour? Does the worker goes offline if the system is idle?
Or does it run in specific intervals?

**Comment by ht2** [comment]
Hi @abhi9866,

It sounds to me like your workers unsubscribed from the queue job at a time prior to them not being sent. The workers are designed to persist, and using systems like PM2 they should autorestart if required. However its hard to say without knowing more.

I'd ask you check what queue provider you are using (Redis or SQS) and look if there was any service interuption at the time that the incident occured. Also checking error logs to see if there was anything reported by the workers that was cause them to stop "working" through queue jobs.

**Comment by abhi9866** [comment]
@ht2, I looked at the logs. prior to failing,  the worker had issue connecting to Redis(ECONNRESET errors). I suspect it might be a network issue which caused the worker to unsubscribe.
I was wondering, if there is anything like a failover mechanism/Health check to periodically check if worker is subscribed to Redis and restart it, if it is not.

Appreciate your help with this.

**Comment by ht2** [comment]
You're probably best looking into High Availability Redis setups such as Redis Sentinel (which we have direct support for), or HAProxy.

We pass off the client to a library called Bull which handles subscriptions and the connection (although you could probably abstract above that if absolutely necessary. 

For production environments I would recommend you use the SQS or Google PubSub configurations which provide better redundancy to your queues compared to the ephemeral nature of something like Redis. We are working on Azure additions and they will be available soon.

**Comment by abhi9866** [comment]
Thank you, I will look into them. 
We are largely using Azure stack. Glad to know you guys are working on Azure additions.

**Comment by ht2** [comment]
No problem - first up is Storage Blobs (#1335 and https://github.com/LearningLocker/xapi-service/pull/275) but plans are afoot to look at Azure Events as well
