### ISSUE TITLE
Cmi5 state doc

### ISSUE THREAD

**Issue by ap-prog** [LearningLocker/learninglocker#1342]
The cmi5 spec says that an AU must first fetch the auth-token and then "the AU MUST get the 'contextTemplate' value from the 'LMS.LaunchData' State document." but I can't find anything complete about how the AU is meant to fetch the state doc. This:

http://docs.learninglocker.net/http-xapi-states/#get-activitiesstate

seems like the way to go but their example returns a single key and not a doc with LMS.LaunchData and, at any rate, I haven't yet retrieved a registration or stateid yet.

**Comment by hallshouse** [comment]
What we have written in the cmi5 Spec. Section 10 (https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#100-xapi-state-data-model), is "Prior to launching an AU, the LMS MUST create or update a document in the State API record in the LRS. This MUST be a JSON document, as defined in this section."

I'll bring this question up in our meeting today to see if we can further clarify this area.

**Comment by hallshouse** [comment]
Per our response in the cmi5 project that Bill answered: https://github.com/AICC/CMI-5_Spec_Current/issues/592#issuecomment-475660409

**Comment by ap-prog** [comment]
I went to the xAPI spec and with help from Rustici I realised my misunderstanding:  "LMS.LaunchData is the state identifier, literally that string should be passed as the stateId query parameter in the GET state request."

**Comment by hallshouse** [comment]
You are correct, the LMS.LaunchData is the stateid, however, to help clarify this further; in the context of cmi5, the LMS is the originating source of the of the JSON we pointed you to.

So you would incorporate the JavaScripts we are developing (or develop your own), create an upload facility to upload a "cmi5.xml" file into the LMS (the source of the xAPI statements for the AU) and make use a launch URL similar to this example:
https://example.com/path/to/index.html?endpoint=https://example.com/path/to/lrsClientEndpoint/&fetch=https://example.com/path/to/LearningConnection/authToken/abc123ABC123&actor={"objecttype":"Agent","name":Firstname, Lastname","account":{homePage":"https://example.com/path/to/LearningConnection/","name":"123456-"1"}}&registration=1a2b3c4d-5e6f7g8h-9i0j1k2l-1m2n3o4p&activityId=https://example.com/path/to/LearningConnection/AU/123456

That is an example of what the LMS will send to the LRS.
I hope this helps you move forward and please continue to address your cmi5 questions in our repository.

**Comment by ssimo3lsuhsc** [comment]
It’s my understanding that by including the Fetch URL in the Launch URL, the Launch URL itself becomes one-time-only. This is an implementation headache for save-and-continue scenarios. I’d like to propose that cmi6 (I’m assuming that’s what the next generation of cmi5 will be called) implement a new parameter “disposeURL” in the launch URL. This will be a URL called upon exit (the equivalent of the Javascript `window.onbeforeunload` property, again a body-less POST request) to dispose of the token generated by the fetchUrl.

**Comment by hallshouse** [comment]
> It’s my understanding that by including the Fetch URL in the Launch URL, the Launch URL itself becomes one-time-only. This is an implementation headache for save-and-continue scenarios. I’d like to propose that cmi6 (I’m assuming that’s what the next generation of cmi5 will be called) implement a new parameter “disposeURL” in the launch URL. This will be a URL called upon exit (the equivalent of the Javascript `window.onbeforeunload` property, again a body-less POST request) to dispose of the token generated by the fetchUrl.

cmi5 will not become cmi6. The 5 is not a version number, it the spec name. Please refer to our Versions section on our cmi5 GitHub site: https://aicc.github.io/CMI-5_Spec_Current/

You would be best to post your statement into our cmi5 GitHub area since cmi5 is an LMS specification designed for xAPI and not an xAPI specification.
Please post your cmi5 statements, questions or concerns in the cmi5 specification on GitHub and we'll address it there.
https://github.com/AICC/CMI-5_Spec_Current
