### ISSUE TITLE
How to create persona from REST

### ISSUE THREAD

**Issue by ramazord** [LearningLocker/learninglocker#1351]
Hi, i will appreciate for anyone who answer to this newbie question, 

i want to create new persona in learning locker through REST Api, i have successfully created the persona but the name is not sent.

i have put the name in Body, Header, even Params but i could not make it sent.
here's my Postman code that i tried : 

ignore the example.org it's not the real endpoint

```
var form = new FormData();
form.append("name", "ramaaaa");

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://example.org/api/v2/persona/",
  "method": "POST",
  "headers": {
    "Content-Type": "application/x-www-form-urlencoded",
    "Authorization": "Basic Yzg3ZmNjZTgzNWI4MTZjZjFlNjdhYmVmOWJlN2NiMWJjMjk2YjhlODo0YmQ0OTNkZmJhZjhlZWQ3ZTQxMGVmZGVlNjY5YTY5MTk5ODExODhk",
    "cache-control": "no-cache",
    "Postman-Token": "57866335-1d12-40ca-be6a-09ecec586e33"
  },
  "processData": false,
  "contentType": false,
  "mimeType": "multipart/form-data",
  "data": form
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

Thank you, this is my first question issue so please be gentle with me 😃

**Comment by ryansmith94** [comment]
Hi @ramazord, sorry for the delayed reply. I don't believe the API accepts form data content, please use JSON instead as shown in the [persona API documentation](http://docs.learninglocker.net/http-personas/).

**Comment by ramazord** [comment]
ah i see so it need raw value instead form data, now it fixed, i'm trying from postman it the solution is just to select raw value instead form data.

Thank you very much sir.
