### ISSUE TITLE
Open Source - ReplyError: ERR wrong number of arguments for 'rpush' command

### ISSUE THREAD

**Issue by pawurb** [LearningLocker/learninglocker#1390]
#### What version were you using?

Learning Locker 2.6.3 from HT2 Labs - ami-0b978fec434602911

#### What steps can we follow to reproduce the behaviour?

Setup LL via AMI on EC2, create store and submit any xAPI statement via an authenticated cURL command. 

#### What is the actual behaviour?

When running `pm2 logs` I can see the following error when submitting an xAPI statement with cURL:

```
4|xAPI  | { ReplyError: ERR wrong number of arguments for 'rpush' command
4|xAPI  |     at JavascriptRedisParser.returnError (/usr/local/learninglocker/releases/ll-20190114-dcb84057e8d3aea11a00cbf8bb52d42a7d16fedd/xapi/node_modules/ioredis/lib/redis/parser.js:24:25)
4|xAPI  |     at JavascriptRedisParser.execute (/usr/local/learninglocker/releases/ll-20190114-dcb84057e8d3aea11a00cbf8bb52d42a7d16fedd/xapi/node_modules/redis-parser/lib/parser.js:572:12)
4|xAPI  |     at Socket.<anonymous> (/usr/local/learninglocker/releases/ll-20190114-dcb84057e8d3aea11a00cbf8bb52d42a7d16fedd/xapi/node_modules/ioredis/lib/redis/event_handler.js:107:22)
4|xAPI  |     at emitOne (events.js:116:13)
4|xAPI  |     at Socket.emit (events.js:211:7)
4|xAPI  |     at addChunk (_stream_readable.js:263:12)
4|xAPI  |     at readableAddChunk (_stream_readable.js:250:11)
4|xAPI  |     at Socket.Readable.push (_stream_readable.js:208:10)
4|xAPI  |     at TCP.onread (net.js:601:20)
4|xAPI  |   name: 'ReplyError',
4|xAPI  |   message: 'ERR wrong number of arguments for \'rpush\' command',
4|xAPI  |   command: { name: 'rpush', args: [ 'LEARNINGLOCKER:statement.new' ] } }
```

#### What is the expected behavior?

Error log should not be there.

#### Is there any additional information that will help us replicate/understand the problem?

I've tested it with default AMI redis 3.0.6 as well as 5.0.5 and error happens in both cases. It does not seem to break anything, statements and personas are getting created, but it looks worrisome.

**Comment by pawurb** [comment]
Just noticed that AWS AMI is using a very old version of LL. Closing because issue is probably outdated.

**Comment by pawurb** [comment]
I've decided to reopen because it also happens with the newest version of LL installed manually from the repo. Submitting the first statement does not cause this error in logs. Only replying the request with the same `statementId` value causes the following error to popup:

```
5|xAPI  | { ReplyError: ERR wrong number of arguments for 'rpush' command
5|xAPI  |     at JavascriptRedisParser.returnError (/home/ubuntu/xapi-service/node_modules/ioredis/lib/redis/parser.js:24:25)
5|xAPI  |     at JavascriptRedisParser.execute (/home/ubuntu/xapi-service/node_modules/redis-parser/lib/parser.js:572:12)
5|xAPI  |     at Socket.<anonymous> (/home/ubuntu/xapi-service/node_modules/ioredis/lib/redis/event_handler.js:107:22)
5|xAPI  |     at emitOne (events.js:116:13)
5|xAPI  |     at Socket.emit (events.js:211:7)
5|xAPI  |     at addChunk (_stream_readable.js:263:12)
5|xAPI  |     at readableAddChunk (_stream_readable.js:250:11)
5|xAPI  |     at Socket.Readable.push (_stream_readable.js:208:10)
5|xAPI  |     at TCP.onread (net.js:601:20)
5|xAPI  |   name: 'ReplyError',
5|xAPI  |   message: 'ERR wrong number of arguments for \'rpush\' command',
5|xAPI  |   command: { name: 'rpush', args: [ 'LEARNINGLOCKER:statement.new' ] } }
```

URL: ` {{HOST}}data/xAPI/statements?statementId=afb7218c-0fc9-4dfc-9524-d497097de022`
METHOD: `PUT`
LL version: `v3.15.1`
Redis version: `4.0.6' and `5.0.5` 
System: `Ubuntu 18.04`

**Comment by h-kanazawa** [comment]
I left a report of investigation about this issue.

> 5|xAPI  |   message: 'ERR wrong number of arguments for \'rpush\' command',
> 5|xAPI  |   command: { name: 'rpush', args: [ 'LEARNINGLOCKER:statement.new' ] } }

Redis `rpush` needs 2 or more arguments, but actual was 1.
Ref: https://redis.io/commands/rpush

I tried the command on redis-cli and got the same error message.

```
127.0.0.1:6379> RPUSH LEARNINGLOCKER:statement.new
(error) ERR wrong number of arguments for 'rpush' command
127.0.0.1:6379> RPUSH LEARNINGLOCKER:statement.new aa
(integer) 1
127.0.0.1:6379> RPUSH LEARNINGLOCKER:statement.new bb cc
(integer) 3
```

### Who calls `rpush`?

https://github.com/LearningLocker/xapi-statements/blob/6b0bff85961892d8573a22406821ec6665ed3c42/src/repo/eventsRepo/emitNewStatements/redis.ts#L12

If `ids` is empty list, the error is occurred.

### Who calls `emitNewStatements`?

https://github.com/LearningLocker/xapi-statements/blob/6b0bff85961892d8573a22406821ec6665ed3c42/src/service/storeStatements/index.ts#L75

[This if-condition](https://github.com/LearningLocker/xapi-statements/blob/6b0bff85961892d8573a22406821ec6665ed3c42/src/service/storeStatements/index.ts#L74
) should check unstoredStatementIds.length to prevent from passing empty list.

**Comment by freefri** [comment]
Just to update the links from @h-kanazawa to the new references

### Who calls `rpush`?

https://github.com/LearningLocker/xapi-service/blob/e050b0d7e578c4c0f79603dbb49cc2f8f457c24e/src/apps/statements/repo/eventsRepo/emitNewStatements/redis.ts#L18

If `ids` is empty list, the error is occurred.

### Who calls `emitNewStatements`?

https://github.com/LearningLocker/xapi-service/blob/e050b0d7e578c4c0f79603dbb49cc2f8f457c24e/src/apps/statements/service/storeStatements/index.ts#L86

[This if-condition](https://github.com/LearningLocker/xapi-service/blob/e050b0d7e578c4c0f79603dbb49cc2f8f457c24e/src/apps/statements/service/storeStatements/index.ts#L84) should check unstoredStatementIds.length to prevent from passing empty list.
