### ISSUE TITLE
The latest code cannot be compiled on node.js v10.x

### ISSUE THREAD

**Issue by htliu1111** [LearningLocker/learninglocker#1432]
Downloading the latest version and follow the guide to compile
it shows only node.js v6-8 supported.
as policy of company, only version node.js v10.x is allowed to install, any advise to compile and run on node.js v 10.x

**Comment by ryansmith94** [comment]
You should be able to run it with `yarn --ignore-engines`. Let me know if you find any specific issues with Node 10 besides the installation.
