### ISSUE TITLE
Vulnerability report review

### ISSUE THREAD

**Issue by chadabaker** [LearningLocker/learninglocker#1465]
Good afternoon ... 

We are hoping to use the latest version of Learning Locker with our application but our corporate security team used "synk" to review the codebase and found a number of high security issues.

https://snyk.io/test/github/LearningLocker/learninglocker

Just curious if you are tracking on any of these "high" issues?

**Comment by ryansmith94** [comment]
Yeah these are actually flagged to us by Github and reviewed on a regular basis. The reason for the majority of these remaining unaddressed is that the issues are in dev dependencies and therefore none of our users are actually exposed. When we identify an issue that does expose our users we aim to resolve the issue quickly and discreetly.
