### ISSUE TITLE
Nginx Error Sorry, the page you are looking for is currently unavailable. Please try again later.

### ISSUE THREAD

**Issue by zandercreations** [LearningLocker/learninglocker#1503]
I'm using the latest version of LL

Hi I get an Nginx error when sending statements to my local instance of LL.
when I navigate to my endpoint https://mydomain.com/data/xAPI

I get this Error:
**An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.**

This is the continuous error i'm getting from nginx error.log

2020/01/15 19:41:55 [error] 15501#15501: 695 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.100, server: site_url, request: "POST /data/xAPI/statements HTTP/1.1", upstream: "http://127.0.0.1:8081/data/xAPI/statements", host: "humalytics.works"
2020/01/15 19:41:55 [error] 15501#15501: 695 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.100, server: site_url, request: "POST /data/xAPI/statements HTTP/1.1", upstream: "http://127.0.0.1:8081/data/xAPI/statements", host: "humalytics.works"
2020/01/15 19:41:55 [error] 15501#15501: *695 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.100, server: site_url, request: "POST /data/xAPI/statements HTTP/1.1", upstream: "http://127.0.0.1:8081/data/xAPI/statements", host: "humalytics.works"

Couple of details:

This error began after I rebooted my Ubuntu machine
maybe I have I have to restart some services I am not sure.
Any advice will be helpful. Thanks

**Comment by ryansmith94** [comment]
Responded on Gitter.
> please make sure the processes have started by running `pm2 status` on the server

**Comment by zandercreations** [comment]
![learning locker_error](https://user-images.githubusercontent.com/17857024/72532438-695db500-3841-11ea-9d32-b85a3227ecc5.PNG)


this is what shows up when I run that command

**Comment by ryansmith94** [comment]
Ok looks like none of the processes are running. I'm reliably informed by our trusty sysadmin who maintains the install script that you can run `pm2 start webapp.json` and `pm2 start worker.json` in the webapp directory and `pm2 start xapi.json` in the xapi directory.

**Comment by zandercreations** [comment]
Ok thanks I will try

**Comment by zandercreations** [comment]
![learning locker_error2](https://user-images.githubusercontent.com/17857024/72539508-6668c180-384d-11ea-88b4-e172e979a6cd.PNG)


Here is the result 
If there is a way to uninstall please let me know

**Comment by ryansmith94** [comment]
Hi @zandercreations, seems strange that the status is `errored` for all of those processes. Check the application logs by running `pm2 logs`. Did you originally use the install script on a fresh instance to get this working?

**Comment by zandercreations** [comment]
this is what happens when I run that command
![learning locker_error3](https://user-images.githubusercontent.com/17857024/72540846-81d4cc00-384f-11ea-97e3-5dab5ecb29b2.PNG)

To give some context I originally received this issue when I rebooted my machine when I click the xapi endpoint link on the clients tab

![learning locker_error4](https://user-images.githubusercontent.com/17857024/72540996-bf395980-384f-11ea-8859-ef447d069064.PNG)

So I ran the install again to see if i needed to update the installation to fix those errors and no luck

**Comment by zandercreations** [comment]
Nginx and Mongo is running
![learning locker_error5](https://user-images.githubusercontent.com/17857024/72542782-b6965280-3852-11ea-92b3-789a50cc2f6b.PNG)

Also Hear the reinstall process I ran to try and fix things
![learning locker_error6](https://user-images.githubusercontent.com/17857024/72542833-c57d0500-3852-11ea-9171-38953d1fe55d.PNG)
![learning locker_error7](https://user-images.githubusercontent.com/17857024/72542844-c9108c00-3852-11ea-9e9e-15578165deab.PNG)

**Comment by zandercreations** [comment]
Hi @ryansmith94  I fixed the issue: apparently I didnt run your commands the right way. I had to give rights to user Learning Locker to run your root commands.
![learning locker_error8](https://user-images.githubusercontent.com/17857024/72550459-c5840180-3860-11ea-993a-d43a67fe88ee.PNG)

**Comment by ryansmith94** [comment]
Ah nice 👍
