### ISSUE TITLE
moodle use logstore xapi to scorm cloud but not work

### ISSUE THREAD

**Issue by cool3690** [LearningLocker/learninglocker#1504]
I have problem to need help.
I use moodle 3.7.2 and install logstore xapi, I hope I can do LRS on scorm cloud.
but It still not work after I install xapi and setting it,

I have build a course and quiz,student also finish quiz.
but my record still not show.
this is my setting picture. xapi setting
![image](https://user-images.githubusercontent.com/16379115/72486656-83e65d00-3846-11ea-8a85-e800374d684f.png)

this is my record my record
![image](https://user-images.githubusercontent.com/16379115/72486665-8e085b80-3846-11ea-8e57-9f730a8952ff.png)

please help me thanks.

**Comment by ryansmith94** [comment]
Hi @cool3690, apologies I wasn't clear in the Gitter chat, this needs to be reported to the Moodle plugin issue tracker not Learning Locker. https://github.com/xAPI-vle/moodle-logstore_xapi/issues

**Comment by cool3690** [comment]
ok,I have change,thanks
