### ISSUE TITLE
Login stopped working

### ISSUE THREAD

**Issue by TheoChapelot** [LearningLocker/learninglocker#1527]
Open Source v3.17.1

When trying to login onto the dashboard, cannot login anymore with the error
"There was an error communicating with the login server."

I restarted the pm2 service, but nothing changed.

LL has been running for 7 months on this server without problem.

This is what i got from running pm2 logs : 

`[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/usr/local/learninglocker/releases/.pm2/pm2.log last 15 lines:
PM2        | Error: EACCES: permission denied, open '/var/run/ui-2.pid'
PM2        |     at Object.fs.openSync (fs.js:646:18)
PM2        |     at Object.fs.writeFileSync (fs.js:1299:33)
PM2        |     at ProcessContainer (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:67:8)
PM2        |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:100:3)
PM2        |     at Module._compile (module.js:653:30)
PM2        |     at Object.Module._extensions..js (module.js:664:10)
PM2        |     at Module.load (module.js:566:32)
PM2        |     at tryModuleLoad (module.js:506:12)
PM2        |     at Function.Module._load (module.js:498:3)
PM2        |     at Function.Module.runMain (module.js:694:10)
PM2        | 2020-03-13T10:17:47: PM2 log: App [xAPI:5] online
PM2        | 2020-03-13T10:17:47: PM2 error: (node:10527) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | 2020-03-13T10:17:52: PM2 log: App [Worker:2] online
PM2        | 2020-03-13T10:17:52: PM2 error: (node:10527) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.

/var/log/learninglocker/ui_stderr-1.log last 15 lines:
1|UIServer |     at Pool.emit (events.js:211:7)
1|UIServer |     at Connection.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/pool.js:317:12)
1|UIServer |     at Object.onceWrapper (events.js:317:30)
1|UIServer |     at emitTwo (events.js:126:13)
1|UIServer |     at Connection.emit (events.js:214:7)
1|UIServer |     at Socket.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/connection.js:246:50)
1|UIServer |     at Object.onceWrapper (events.js:315:30)
1|UIServer |     at emitOne (events.js:116:13)
1|UIServer |     at Socket.emit (events.js:211:7)
1|UIServer |     at emitErrorNT (internal/streams/destroy.js:66:8)
1|UIServer |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
1|UIServer |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
1|UIServer |   name: 'MongoNetworkError',
1|UIServer |   errorLabels: [ 'TransientTransactionError' ],
1|UIServer |   [Symbol(mongoErrorContextSymbol)]: {} }

/var/log/learninglocker/ui_stdout-1.log last 15 lines:
1|UIServer |  ==> 💻  Open http://127.0.0.1 in a browser to view the app. 
1|UIServer |  --- 
1|UIServer | 
1|UIServer | 2020-03-13 10:16:47:959 - info: 
1|UIServer |  --- 
1|UIServer |  ==> ✅  Learning Locker is running, talking to API server on 8080. 
1|UIServer |  ==> 💻  Open http://127.0.0.1 in a browser to view the app. 
1|UIServer |  --- 
1|UIServer | 
1|UIServer | 2020-03-13 10:17:38:069 - info: 
1|UIServer |  --- 
1|UIServer |  ==> ✅  Learning Locker is running, talking to API server on 8080. 
1|UIServer |  ==> 💻  Open http://127.0.0.1 in a browser to view the app. 
1|UIServer |  --- 
1|UIServer | 

/var/log/learninglocker/scheduler_stdout-3.log last 15 lines:
3|Schedule | 2020-03-12 23:50:41:743 - info: processing expiration
3|Schedule | 2020-03-13 00:05:41:744 - info: processing expiration
3|Schedule | 2020-03-13 00:20:41:746 - info: processing expiration
3|Schedule | 2020-03-13 00:35:41:746 - info: processing expiration
3|Schedule | 2020-03-13 00:50:41:748 - info: processing expiration
3|Schedule | 2020-03-13 01:05:41:750 - info: processing expiration
3|Schedule | 2020-03-13 01:20:41:753 - info: processing expiration
3|Schedule | 2020-03-13 01:35:41:758 - info: processing expiration
3|Schedule | 2020-03-13 01:50:41:755 - info: processing expiration
3|Schedule | 2020-03-13 02:00:02:636 - info: processing org usage
3|Schedule | 2020-03-13 02:05:41:755 - info: processing expiration
3|Schedule | 2020-03-13 02:20:41:756 - info: processing expiration
3|Schedule | 2020-03-13 02:35:41:758 - info: processing expiration
3|Schedule | 2020-03-13 10:17:37:322 - info: The first org usage tracking is at Sat Mar 14 2020 03:00:00 GMT+0100 (CET)
3|Schedule | 2020-03-13 10:17:38:164 - info: processing expiration

/var/log/learninglocker/scheduler_stderr-3.log last 15 lines:
3|Schedule |     at Pool.emit (events.js:211:7)
3|Schedule |     at Connection.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/pool.js:317:12)
3|Schedule |     at Object.onceWrapper (events.js:317:30)
3|Schedule |     at emitTwo (events.js:126:13)
3|Schedule |     at Connection.emit (events.js:214:7)
3|Schedule |     at Socket.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/connection.js:246:50)
3|Schedule |     at Object.onceWrapper (events.js:315:30)
3|Schedule |     at emitOne (events.js:116:13)
3|Schedule |     at Socket.emit (events.js:211:7)
3|Schedule |     at emitErrorNT (internal/streams/destroy.js:66:8)
3|Schedule |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
3|Schedule |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
3|Schedule |   name: 'MongoNetworkError',
3|Schedule |   errorLabels: [ 'TransientTransactionError' ],
3|Schedule |   [Symbol(mongoErrorContextSymbol)]: {} }

/var/log/learninglocker/xapi_stdout-4.log last 15 lines:
4|xAPI     | 2020-03-13 09:58:29:609 - info: Starting retry 1 in 1000ms
4|xAPI     | 2020-03-13 09:58:30:620 - info: Starting retry 2 in 1000ms
4|xAPI     | 2020-03-13 09:58:31:631 - info: Starting retry 3 in 1000ms
4|xAPI     | 2020-03-13 10:02:01:109 - info: Starting retry 1 in 1000ms
4|xAPI     | 2020-03-13 10:02:02:117 - info: Starting retry 2 in 1000ms
4|xAPI     | 2020-03-13 10:02:03:132 - info: Starting retry 3 in 1000ms
4|xAPI     | 2020-03-13 10:02:41:756 - info: Starting retry 1 in 1000ms
4|xAPI     | 2020-03-13 10:02:42:767 - info: Starting retry 2 in 1000ms
4|xAPI     | 2020-03-13 10:02:43:788 - info: Starting retry 3 in 1000ms
4|xAPI     | 2020-03-13 10:16:25:989 - info: SIGINT
4|xAPI     | 2020-03-13 10:17:43:195 - info: Listening on port 8081
4|xAPI     | 2020-03-13 10:17:43:200 - info: Process ready
4|xAPI     | 2020-03-13 10:17:43:252 - info: Starting retry 1 in 1000ms
4|xAPI     | 2020-03-13 10:17:44:322 - info: Starting retry 2 in 1000ms
4|xAPI     | 2020-03-13 10:17:45:412 - info: Starting retry 3 in 1000ms

/var/log/learninglocker/api_stdout-0.log last 15 lines:
0|API      |  ==> 💻  Send requests to http://undefined:8080 
0|API      |  --- 
0|API      | 
0|API      | 2019-07-31 17:34:50:848 - info: 
0|API      |  --- 
0|API      |  ==> 🌎  API is running on port 8080 
0|API      |  ==> 💻  Send requests to http://undefined:8080 
0|API      |  --- 
0|API      | 
0|API      | 2020-03-13 10:17:45:621 - info: 
0|API      |  --- 
0|API      |  ==> 🌎  API is running on port 8080 
0|API      |  ==> 💻  Send requests to http://undefined:8080 
0|API      |  --- 
0|API      | 

/var/log/learninglocker/api_stderr-0.log last 15 lines:
0|API      |     at Pool.emit (events.js:211:7)
0|API      |     at Connection.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/pool.js:317:12)
0|API      |     at Object.onceWrapper (events.js:317:30)
0|API      |     at emitTwo (events.js:126:13)
0|API      |     at Connection.emit (events.js:214:7)
0|API      |     at Socket.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/connection.js:246:50)
0|API      |     at Object.onceWrapper (events.js:315:30)
0|API      |     at emitOne (events.js:116:13)
0|API      |     at Socket.emit (events.js:211:7)
0|API      |     at emitErrorNT (internal/streams/destroy.js:66:8)
0|API      |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
0|API      |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
0|API      |   name: 'MongoNetworkError',
0|API      |   errorLabels: [ 'TransientTransactionError' ],
0|API      |   [Symbol(mongoErrorContextSymbol)]: {} }

/var/log/learninglocker/xapi_stderr-4.log last 15 lines:
4|xAPI     | tryConnection.ts:8:11)\n    at step (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:32:23)\n    at Object.next (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:13:53)\n    at /usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:3:12)\n    at Object.exports.default (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/src/mongoRepo/utils/connectToDb/retryConnection.ts:6:54)\n    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/src/mongoRepo/utils/connectToDb/createConnection.ts:18:27)\n    at step (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/createConnection.js:32:23)\n    at Object.throw (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/createConnection.js:13:53)\n    at rejected (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/createConnection.js:5:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)' }
4|xAPI     | 2020-03-13 10:16:25:972 - error: 
4|xAPI     | (node:10618) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
4|xAPI     | 2020-03-13 10:17:43:249 - error: Failed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
4|xAPI     | 2020-03-13 10:17:44:321 - error: Failed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
4|xAPI     | 2020-03-13 10:17:45:411 - error: Failed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
4|xAPI     | 2020-03-13 10:17:46:464 - error: Failed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
4|xAPI     | 2020-03-13 10:17:46:466 - error: Failed initial mongo connection: Too many retries

/var/log/learninglocker/worker_stdout-2.log last 15 lines:
2|Worker   | 2020-03-09 02:01:05:928 - info: End orgUsageTracker
2|Worker   | 2020-03-10 02:00:02:950 - info: Start orgUsageTracker
2|Worker   | 2020-03-10 02:00:22:986 - info: Ran 5 samples
2|Worker   | 2020-03-10 02:00:23:102 - info: End orgUsageTracker
2|Worker   | 2020-03-11 02:00:02:643 - info: Start orgUsageTracker
2|Worker   | 2020-03-11 02:00:28:545 - info: Ran 5 samples
2|Worker   | 2020-03-11 02:00:28:643 - info: End orgUsageTracker
2|Worker   | 2020-03-12 02:00:02:638 - info: Start orgUsageTracker
2|Worker   | 2020-03-12 02:00:16:784 - info: Ran 5 samples
2|Worker   | 2020-03-12 02:00:16:921 - info: End orgUsageTracker
2|Worker   | 2020-03-13 02:00:02:739 - info: Start orgUsageTracker
2|Worker   | 2020-03-13 02:00:44:507 - info: Ran 5 samples
2|Worker   | 2020-03-13 02:00:45:172 - info: End orgUsageTracker
2|Worker   | 2020-03-13 10:17:52:279 - info: Subscribing to 'LEARNINGLOCKER:statement.notify' and will rpop on key 'LEARNINGLOCKER:statement.new'
2|Worker   | 2020-03-13 10:17:52:298 - info: STARTED WORKER

/var/log/learninglocker/worker_stderr-2.log last 15 lines:
2|Worker   |     at Pool.emit (events.js:211:7)
2|Worker   |     at Connection.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/pool.js:317:12)
2|Worker   |     at Object.onceWrapper (events.js:317:30)
2|Worker   |     at emitTwo (events.js:126:13)
2|Worker   |     at Connection.emit (events.js:214:7)
2|Worker   |     at Socket.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/webapp/node_modules/mongodb-core/lib/connection/connection.js:246:50)
2|Worker   |     at Object.onceWrapper (events.js:315:30)
2|Worker   |     at emitOne (events.js:116:13)
2|Worker   |     at Socket.emit (events.js:211:7)
2|Worker   |     at emitErrorNT (internal/streams/destroy.js:66:8)
2|Worker   |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
2|Worker   |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
2|Worker   |   name: 'MongoNetworkError',
2|Worker   |   errorLabels: [ 'TransientTransactionError' ],
2|Worker   |   [Symbol(mongoErrorContextSymbol)]: {} }

/var/log/learninglocker/xapi_stdout-5.log last 15 lines:
5|xAPI     | 2019-07-08 15:48:51:856 - info: Created new Mongo connection
5|xAPI     | 2019-07-31 17:35:06:325 - info: SIGINT
5|xAPI     | 2019-07-31 17:35:17:425 - info: Listening on port 8081
5|xAPI     | 2019-07-31 17:35:17:428 - info: Process ready
5|xAPI     | 2019-07-31 17:35:17:525 - info: Created new Mongo connection
5|xAPI     | 2019-08-29 17:21:03:887 - info: Creating redis connection
5|xAPI     | 2020-03-13 10:16:26:050 - info: SIGINT
5|xAPI     | 2020-03-13 10:17:47:640 - info: Listening on port 8081
5|xAPI     | 2020-03-13 10:17:47:655 - info: Process ready
5|xAPI     | 2020-03-13 10:17:47:733 - info: Starting retry 1 in 1000ms
5|xAPI     | 2020-03-13 10:17:48:746 - info: Starting retry 2 in 1000ms
5|xAPI     | 2020-03-13 10:17:49:756 - info: Starting retry 3 in 1000ms
5|xAPI     | 2020-03-13 10:31:01:161 - info: Starting retry 1 in 1000ms
5|xAPI     | 2020-03-13 10:31:02:181 - info: Starting retry 2 in 1000ms
5|xAPI     | 2020-03-13 10:31:03:196 - info: Starting retry 3 in 1000ms

/var/log/learninglocker/xapi_stderr-5.log last 15 lines:
5|xAPI     | ed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5|xAPI     | 2020-03-13 10:31:02:181 - error: Failed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5|xAPI     | 2020-03-13 10:31:03:196 - error: Failed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5|xAPI     | 2020-03-13 10:31:04:207 - error: Failed Mongo connection: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5|xAPI     | 2020-03-13 10:31:04:213 - error: 460cd724-b1e2-4f96-a78f-c3a96dd82b6f: jscommons handled - A server error occurred 
5|xAPI     | { message: 'Too many retries',
5|xAPI     |   stack: 'Error: Too many retries\n    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/src/mongoRepo/utils/connectToDb/retryConnection.ts:8:11)\n    at step (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:32:23)\n    at Object.next (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:13:53)\n    at /usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/retryConnection.js:3:12)\n    at Object.exports.default (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/src/mongoRepo/utils/connectToDb/retryConnection.ts:6:54)\n    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/src/mongoRepo/utils/connectToDb/createConnection.ts:18:27)\n    at step (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/createConnection.js:32:23)\n    at Object.throw (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/createConnection.js:13:53)\n    at rejected (/usr/local/learninglocker/releases/ll-20190708-99fbed7d1af6cac97fdec93bf31b6a53233d6b6b/xapi/node_modules/jscommons/dist/mongoRepo/utils/connectToDb/createConnection.js:5:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)' }

`

**Comment by djoudi** [comment]
i have the same issue

**Comment by TheoChapelot** [comment]
@djoudi Hey ! I managed to fix it.

The problem came from a change of permission in the mongo service.
This is what i did : 

If authentication to the LRS doesn't work, try restarting the learning locker service.

If the problem persists, check the logs with : 
`pm2 logs`

If there is a problem with the mongodb connection, run : 
```
sudo service mongod start 
sudo service mongod status
```

If there is an error with status 14, you must change the permission of two files from root : 
```
sudo chown mongodb:mongodb tmp/mongodb-27017.sock (replacing mongodb-27017 by your socket name )
sudo chown -R mongodb:mongodb /var/lib/mongodb
```

Then restart the mongod service and check the status : 
```
sudo service mongod start 
sudo service mongod status
```

If things are now working, restart the pm2 service of learning locker : 
`sudo su learninglocker service pm2-learninglocker restart`
