### ISSUE TITLE
Getting 401 Unauthorized for xAPI response

### ISSUE THREAD

**Issue by ksourabh45** [LearningLocker/learninglocker#1627]
Hi all,

I have setup learning locker on EC2 instance and trying to insert xAPI statements but getting 401 Unauthorized error.

I have setup store and client as required and also added Basic Authorization header but getting error while trying to insert statements through postman.

Added screenshot below:

![image](https://user-images.githubusercontent.com/120578312/227457869-994dd28e-c439-452a-970e-686e002a80d1.png)

Please help me in resolving the issue.

Thanks in advance.
Sourabh

**Comment by ToranSharma** [comment]
@ksourabh45 have you selected the store in the clients xAPI section?

On **Settings -> Clients** expand the client you are trying to use and check that your store is selected here (will say LRS (optional) in grey if not):
![Screenshot 2023-03-24 at 08 06 49](https://user-images.githubusercontent.com/4559968/227461590-cc8d0465-ef2f-405f-a1fb-bf431d71c0f5.png)

**Comment by ksourabh45** [comment]
Hi @ToranSharma , Thanks for your response.

Yes it has store selected.

![image](https://user-images.githubusercontent.com/120578312/227480483-263392c1-a591-4ff9-aba3-04501e146090.png)

**Comment by looperEit** [comment]
> 你好@ToranSharma， 感谢您的答复。
> 
> 是的，它选择了商店。
> 
> ![图像](https://user-images.githubusercontent.com/120578312/227480483-263392c1-a591-4ff9-aba3-04501e146090.png)

Hello, may I ask if your installation was successful? Does the Xapi service report no error? What is your system configuration like? After I installed it on my Ubuntu18, the Xapi service could not be started, and I have not been able to find a solution.
![image](https://user-images.githubusercontent.com/46367388/229726255-fb593395-c5b8-4cdd-8bda-38e36b799142.png)
![image](https://user-images.githubusercontent.com/46367388/229726299-44216235-4ff5-45d7-8574-a7b6108dc494.png)

**Comment by kichitan** [comment]
Do you have all in one server or Mongo is running on its own server ?

**Comment by ksourabh45** [comment]
Hi all, I was able to fix it. It was due to node libraries version mismatch in xAPI plugin and learning locker.

**Comment by ksourabh45** [comment]
Hi @looperEit ,

Have you tried with latest ubuntu?

I have had issues with the same and it works with latest version.

Thanks,
Sourabh

**Comment by looperEit** [comment]
> 您是在一台服务器上拥有所有功能还是在自己的服务器上运行 Mongo？

Yes, I installed all services on one server, including services such as mongoDB and Xapi.
but,  I just ran the official wget -qO deployll.sh https://raw.githubusercontent.com/LearningLocker/deploy/master/deployll.sh && bash deployll.sh   for automatic installation.

**Comment by looperEit** [comment]
> 你好@looperEit,
> 
> 您是否尝试过最新的 ubuntu？
> 
> 我遇到过同样的问题，它适用于最新版本。
> 
> 谢谢， 苏拉布

hello, thanks for your replying. Did you mean the ubuntu20? but the official recommendation is to use Ubuntu16 or 18. I have tried to use Ubuntu20, but the installation process prompts to use 18, so I use 18 to complete.

**Comment by looperEit** [comment]
> 大家好，我能够修复它。这是由于 xAPI 插件和学习储物柜中的节点库版本不匹配。

Could you please tell me which version I am using? I am using the officially recommended version 14.0 of nodejs.

**Comment by looperEit** [comment]
> 你好@looperEit,
> 
> 您是否尝试过最新的 ubuntu？
> 
> 我遇到过类似的问题，它适用于最新版本。
> 
> 谢谢， 苏拉布

I have been troubled by this problem for a long time, it is very painful. If you can please tell me your configuration and your known solution, thank you. I have tried to install it many times.

**Comment by looperEit** [comment]
> Do you have all in one server or Mongo is running on its own server ?

hello？

**Comment by kichitan** [comment]
> > Do you have all in one server or Mongo is running on its own server ?
> 
> hello？
> 

I used to, but I decided to go HA, so now the only thing running on my server is nginx and all the LRS roles. 

databases are separate, same as statements files and env files.

**Comment by looperEit** [comment]
> > > 您是在一台服务器上拥有所有功能还是在自己的服务器上运行 Mongo？
> > 
> > 
> > 你好？
> 
> 我曾经是，但我决定去 HA，所以现在我的服务器上唯一运行的是 nginx 和所有 LRS 角色。
> 
> 数据库是分开的，与语句文件和环境文件相同。
Have you ever had such a problem? After I opened http://192.168.103.133/data/xAPI, an error of Faithfully yours, nginx. appeared. But I installed it according to the official deployLL.sh. Do I need to adjust the configuration file during the installation process? May I ask if your mongodb is configured on another server, can it run LL normally? Can the statement be sent to LRS normally?
![image](https://user-images.githubusercontent.com/46367388/229998104-6d71a643-a8fe-42f3-a493-8d55b1fc2421.png)
![image](https://user-images.githubusercontent.com/46367388/229998169-9fb5acf1-b993-460a-bf6d-7e8ef65da5a7.png)
![image](https://user-images.githubusercontent.com/46367388/229998241-e250e341-8f78-4b67-bbf3-13c6756b3d41.png)

**Comment by ksourabh45** [comment]
Hi @looperEit ,

I had the same error. Please follow below:

First install learning locker using installation script and for xAPI use custom installation because it run on node version greater than >16 and learninglocker service uses node version 10. 

- For this we have to use 2 node versions simultaneously that can be done using node version manager ‘nvm’
- We have to switch node version every time depends upon which service we want to start 

Install both node versions 17.6.0 and 10.24.1 and use 17.6.0 while installing xAPI.

**Comment by looperEit** [comment]
> 

thanks for your replying. i will try it.

**Comment by looperEit** [comment]
> Hi @looperEit ,
> 
> I had the same error. Please follow below:
> 
> First install learning locker using installation script and for xAPI use custom installation because it run on node version greater than >16 and learninglocker service uses node version 10.
> 
> * For this we have to use 2 node versions simultaneously that can be done using node version manager ‘nvm’
> * We have to switch node version every time depends upon which service we want to start
> 
> Install both node versions 17.6.0 and 10.24.1 and use 17.6.0 while installing xAPI.

May I ask, should I start the manual installation directly, or use the script to install learninglocker first, and then use node17 to start the xapi service?

**Comment by looperEit** [comment]
> 你好@looperEit,
> 
> 我有同样的错误。请按照以下说明：
> 
> 首先使用安装脚本安装 Learning Locker，对于 xAPI 使用自定义安装，因为它在大于 16 的节点版本上运行，并且 LearningLocker 服务使用节点版本 10。
> 
> * 为此，我们必须同时使用 2 个节点版本，这可以使用节点版本管理器“nvm”来完成
> * 我们每次都必须切换节点版本取决于我们要启动哪个服务
> 
> 安装节点版本 17.6.0 和 10.24.1，并在安装 xAPI 时使用 17.6.0。

![image](https://user-images.githubusercontent.com/46367388/231366762-18e4dbb8-502e-4690-988f-d2fb326df7d5.png)
目前报了这个错误

**Comment by looperEit** [comment]
> 你好@looperEit,
> 
> 我有同样的错误。请按照以下说明：
> 
> 首先使用安装脚本安装 Learning Locker，对于 xAPI 使用自定义安装，因为它在大于 16 的节点版本上运行，并且 LearningLocker 服务使用节点版本 10。
> 
> * 为此，我们必须同时使用 2 个节点版本，这可以使用节点版本管理器“nvm”来完成
> * 我们每次都必须切换节点版本取决于我们要启动哪个服务
> 
> 安装节点版本 17.6.0 和 10.24.1，并在安装 xAPI 时使用 17.6.0。

If you use node10 to execute the LL installation script, then when you use node17 to install xapi, there will be a problem of inconsistent pm2 versions, and pm2 cannot start all services. How to solve this?

**Comment by looperEit** [comment]
> Hi @looperEit ,
> 
> I had the same error. Please follow below:
> 
> First install learning locker using installation script and for xAPI use custom installation because it run on node version greater than >16 and learninglocker service uses node version 10.
> 
> * For this we have to use 2 node versions simultaneously that can be done using node version manager ‘nvm’
> * We have to switch node version every time depends upon which service we want to start
> 
> Install both node versions 17.6.0 and 10.24.1 and use 17.6.0 while installing xAPI.

I have used nvm to switch node versions, but the problem now is that if I only have one server, should I switch node10 to install pm2, and then install node17 to install pm2?

**Comment by ToranSharma** [comment]
@looperEit,

I think part of the issue is that the `deployll.sh` script takes the latest version of the xAPI service, which since v7.0.0 does not support node <16. You can pass a flag to the `deployll.sh` to specify the the version of the xAPI service to use. I think it is the `-x` flag then pass the version number. So something like `-x v6.2.3` should tell the deploy script to use the last v6.x.x version of the xAPI service.

Hopefully this will let you just use a single node version for all processes in pm2. If node 10 worked for you previously try that again. I think this is the default in the `deployll.sh` script.

**Comment by looperEit** [comment]
> @looperEit,
> 
> 我认为部分问题是`deployll.sh`脚本采用了最新版本的 xAPI 服务，因为 v7.0.0 不支持节点 <16。您可以将标志传递给 以`deployll.sh`指定要使用的 xAPI 服务的版本。我认为这是`-x`标志然后传递版本号。所以类似的东西`-x v6.2.3`应该告诉部署脚本使用 xAPI 服务的最后一个 v6.xx 版本。
> 
> 希望这会让您只对 pm2 中的所有进程使用单节点版本。如果节点 10 之前为您工作，请再试一次。我认为这是脚本中的默认设置`deployll.sh`。
I have tried to use node10 to start, but the previous problem still occurs, that is, the error sent by postman to http://192.168.103.147/data/xAPI/statements, I have explored all the solutions, I am on 16, I have tried to install LL on both 18 and 20 but failed. When I tried the method mentioned by the partner above, I wanted to use NVM to switch node to 10 to start all services except xAPI, and then switch to node 17 to initialize xAPI, but it failed.
![image](https://user-images.githubusercontent.com/46367388/231709332-2ac0912f-8bc3-406e-9cf1-fc001beeb506.png)

**Comment by looperEit** [comment]
> -x v6.2.3

How to modify this version number?

**Comment by ToranSharma** [comment]
This is passed in a the point of running `deployll.sh` so something like:
```bash
./deployll.sh -x v6.2.3
```
The version number come from the releases pages for the xAPI-Service:
https://github.com/LearningLocker/xapi-service/releases

**Comment by looperEit** [comment]
> 这是在运行点传递的，`deployll.sh`例如：
> 
> ```shell
> ./deployll.sh -x v6.2.3
> ```
> 
> 版本号来自 xAPI 服务的发布页面： https://github.com/LearningLocker/xapi-service/releases
Hello, does this problem occur when using build-all?
![image](https://user-images.githubusercontent.com/46367388/231739584-7aadf926-0c81-4672-9ae2-cf8ffb6254fc.png)

**Comment by looperEit** [comment]
> 这是在运行点传送的，`deployll.sh`例如：
> 
> ```shell
> ./deployll.sh -x v6.2.3
> ```
> 
> 版本号来自 xAPI 服务的发布页面： https://github.com/LearningLocker/xapi-service/releases

Hi, I have installed it according to your method. The installation has been completed, and the xapi is running smoothly, but it still cannot be sent. I am thinking whether my use process is wrong?

![image](https://user-images.githubusercontent.com/46367388/231743973-86584211-3f00-4240-851b-06e14acbe5e9.png)
![image](https://user-images.githubusercontent.com/46367388/231744285-222c6c20-b8fc-4e6a-84a0-44d27ad46add.png)
![image](https://user-images.githubusercontent.com/46367388/231744345-e940a1ac-9e31-4fa6-837e-83dd9aa7c5a5.png)
It's really painful not being able to solve it.

**Comment by looperEit** [comment]
> 

as i running the `bash test.sh` , it shows that 
![image](https://user-images.githubusercontent.com/46367388/231745372-765467b1-9bb6-4447-a617-12d0716410c5.png)

**Comment by ToranSharma** [comment]
@looperEit

Is the `MONGO_URL` `/usr/local/learninglocker/current/xapi/.env` pointing to the correct place for your mongodb server?

EDIT: This now looks to be the state that it was in #1626. Maybe these updates should go in that issue.

**Comment by looperEit** [comment]
yes. I just modified the two key positions, 
![image](https://user-images.githubusercontent.com/46367388/231754762-275c7660-1d2b-4528-87c0-205ac703e518.png)
![image](https://user-images.githubusercontent.com/46367388/231754966-f9f98a5f-f614-46d3-a8c9-02e1d8d74b47.png)
and it can be sent, but after I run bash test.sh, it doesn't work again. I would like to ask whether bash test.sh reset xapi?
![cJ6WL4eYDJ](https://user-images.githubusercontent.com/46367388/231755015-90ea74f7-5ea4-46df-b1da-6a159382c136.jpg)
but now i tried again, it didn't work.
.env like 
![image](https://user-images.githubusercontent.com/46367388/231755241-bf62fa1d-c5e8-4898-bfeb-245ac92af9c7.png)

**Comment by looperEit** [comment]
> @looperEit
> 
> Is the `MONGO_URL` `/usr/local/learninglocker/current/xapi/.env` pointing to the correct place for your mongodb server?
> 
> EDIT: This now looks to be the state that it was in #1626. Maybe these updates should go in that issue.

Thank you very much, it is ready to use. I have found a complete solution.
