### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by ghendo** [LearningLocker/learninglocker#1629]
The software appears to no longer be maintained as last update was 2021. Can someone confirm this.

**Comment by SolutionsDEV** [comment]
We are not hearing anything from the developers. I hope to hear from them.

Are there plans for updates? The majority of code is many years old and it has too many issues on installation and in most cases it is not working.

Any replies on this?

Thanks,

**Comment by crazy-grizzly** [comment]
@ghendo , @SolutionsDEV , hey 👋 Unfortunately, the open-source version is no longer maintained. All the work focused on refactoring, improving, and adding new features to the enterprise version

**Comment by SolutionsDEV** [comment]
Thank you for your answer, but could we have a version that at least works? My question is that because I know that Learning Locker is much better than other choices.

**Comment by crazy-grizzly** [comment]
@SolutionsDEV , I will try to ask people who can give approval to spend some time on fixing issues. Meantime, please feel free to submit a PR that fixes issues. That would be appreciated, your contribution is important to us. Thank you

Also, please describe the problems you experienced while setting up
