### ISSUE TITLE
I created an administrator account with createSiteAdmin and tried to log in, but I couldn't log in.(message : Incorrect login details)

### ISSUE THREAD

**Issue by neoware01** [LearningLocker/learninglocker#1631]
ubuntu 22.04 and node.js 14. I installed with custom install and created an administrator account with createSiteAdmin..

Request URL:
http://~/api/auth/jwt/password
Request Method:
POST
Status Code:
401 Unauthorized
Remote Address:

Referrer Policy:
strict-origin-when-cross-origin

However, I was unable to log in and received the following message..
The key value was inserted into the APP_SECRET in the .env file.

APP_SECRET=f2aa61dbe5ec4f6c6a6a17bd82fdf0e840b31cab5ac8eb867b9695f59b3320ab

==============================================
{
    "success": false,
    "message": "Incorrect login details"
}

===============================
Request Header

POST /api/auth/jwt/password HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: ko,en;q=0.9,ko-KR;q=0.8,en-US;q=0.7
Authorization: Basic bGpzQG1pbmlzb2Z0LmNvLmtyOnF3ZXIxMjMk
Connection: keep-alive
Content-Length: 0
Host: 
Origin: 
Referer: 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

pleas help me.

**Comment by the-tarnished** [comment]
hello? Can you tell me how you fix this problem. I encounter the same error.Thanks.
