### ISSUE TITLE
Does Learning Locker support Multiple Databases?

### ISSUE THREAD

**Issue by SundarPPE** [LearningLocker/learninglocker#278]
Currently in Learning locker we can create multiple LRS in a single Mongo DB.
Do learning locker support multiple Database.(10LRS in one Db, another 10LRS in another DB).?

Thanks In Advance. :)
Sundar

**Comment by shahabuddin11** [comment]
is it possible there is only one mongo database instance but point multiple databases.like a have one test db and another one is learninglocker-v2 i want to point out both databases.
