### ISSUE TITLE
StatementRepository doesn't automatically replace `&46;` elements when retreiving statements

### ISSUE THREAD

**Issue by ht2** [LearningLocker/learninglocker#312]
We use a helper method (`replaceHtmlEntity`) to convert `&46;` back into the `.` character. 

Currently this is only being done when we know the statement will be passed back need for visual representation (e.g. within the [StatementController](https://github.com/LearningLocker/learninglocker/blob/master/app/controllers/xapi/StatementController.php#L229) and within the [statements/item](https://github.com/LearningLocker/learninglocker/blob/master/app/views/partials/statements/item.blade.php#L89) view).

A more consistent approach would be to ensure that whenever statements were queried from the [EloqeuentStatementRepository](https://github.com/LearningLocker/learninglocker/blob/master/app/locker/repository/Statement/EloquentStatementRepository.php), that conversion into `.` character took place. This would mean that views and controllers were agnostic to the conversion happening. 

This could well be achieved using an [Eloquent mutator](http://laravel.com/docs/eloquent#accessors-and-mutators).

**Comment by ryansmith94** [comment]
Closing because it's stagnated.
