### ISSUE TITLE
Articulate storyline 2 to LL failed...

### ISSUE THREAD

**Issue by amirfazamin** [LearningLocker/learninglocker#371]
Currently, Articulate storyline 2 (tin can v. 1.0) to cloud.scorm lrs was successful. But if i point to LL, it display error 
"Unable to connect to the server.
Please verify you can connect to the internet and relaunch the course.
Status Code: 401"...

So, how can i do to make it success?

my end point: http://ec2-54-169-37-71.ap-southeast-1.compute.amazonaws.com/data/xAPI/

**Comment by yashbantm** [comment]
Hi all,

I have developed an emodule using Articulate Story line 2 and published it for LRS report(Grassblade LRS) but its showing  "Configuration data is missing or incorrect. Please try again." error.

Please help me, please find my published URL below

http://mednl.com/tincantest/c1/story.html?endpoint=http://eptral.com/grassblade-lrs/xAPI/&auth=MTQtNDVlNjYwNmU2YjkwYjc2OmEyYmZkNTJhYWNmN2UwNjdhYTk3YTdkZjc=&actor={"mbox":"mailto:ex@mple.co.uk", "name":"Example User"}&activity_id=5pmXx3XAGvX_course_id&registration=2981c910-6445-11e4-9803-0800200c9a66

**Comment by ryansmith94** [comment]
You've been responded to in #878 @yashbantm

**Comment by hallshouse** [comment]
@yashbantm Based on the SL publish settings you displayed in your screenshot in your previous issue, you need to learn how to publish SL for xAPI.

Your issue is not at all a LL issue.
Watch this YouTube video: https://www.youtube.com/watch?v=RTQfWkq7yEI&list=FLyN_TVy2VZ_N5Yhf1Gswm5Q

Hope this helps.
