### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ryasmi** [LearningLocker/learninglocker#387]
**Motive**
Learning Locker needs strings translated into other languages so that it can be used by people that do not speak English.

**Expected behaviour**
The user should see text in their chosen language or even better the language that is determined by their current location.

**Discussed solutions**
1. Add a readme to the lang directory that explains how to add translations inside the lang directory.
2. Use [Transifex](https://www.transifex.com/projects/p/learning-locker) (we're leaning away from this solution).

**Additional information**
If you've been tagged here, it's because you've helped Learning Locker a lot in the past. We'd like to hear everyone's thoughts before we move forward. 

@fugu13 @gazzastone @garemoko @andytruong @RyanBrainerd @Klaasie @barrysampson

**Comment by votuduc** [comment]
Hello Ryan,

I'm Duc, I got your email via GitHub. Yesterday I raised a ticket regard to localize Learning Locker, then I got your reply via GitHut. That's why I now send this email to you.

As the topic #489 was closed by you and I know why it was. But After reading the topic #387 that you suggested, I can find out the solution. That's because I'm very new with Learning Locker / Lavarel...etc and I'm also not a technical expert.

So, Could you please give me a point for my starting (e.g which document I should read firtly....).

Thank you so much and have a nice day to you.

Best and Regards,

DUC

**Comment by votuduc** [comment]
Hello Ryan,

I now know a little bit about "Lang" folder and other activities regard to translate Learning Locker to another language.

But there is new question is that How I translate some text/words those appear on main chart/graph?

For instance, Please look at attached file. You will see some words as list below:

Statements 34
Your daily average is 1 statements with 3 learners in total.
Most active users
Popular Activities
Latest reports
Visit Reporting Tool.
For more detail, please take a look at attached images.

Thank you in advance.

DUC
![screen shot 2015-01-24 at 12 05 03 am](https://cloud.githubusercontent.com/assets/8246785/5878939/8a917942-a35d-11e4-8982-b2b7460ee803.png)
![screen shot 2015-01-24 at 12 08 28 am](https://cloud.githubusercontent.com/assets/8246785/5878941/8b51e34e-a35d-11e4-8a24-a7f295f4f158.png)

**Comment by ryansmith94** [comment]
Some of these things are in the code, they need to be moved to a
translation file. I'm in the process of tidying up LL so I will try to do
that too.

**Comment by votuduc** [comment]
@ Ryan, 

Could you please share the path/location where the mentioned code was put in?

**Comment by ryansmith94** [comment]
I don't know where that is right now, I'd search the repo.

**Comment by votuduc** [comment]
Did you find the mentioned location, Ryan? if yes, Please share it to me. Thank you so much for your support.

**Comment by ht2** [comment]
Hi @votuduc,

Translations are handled using Laravel's localization libraries. Please refer to [their documentation](http://laravel.com/docs/4.2/localization) if you wish to contribute to the localization effort with Learning Locker. 

We are currently not internally engaged in any updates to the translations, so any contributions you wish to make would be received by the community with open arms.
