### ISSUE TITLE
Articulate Storyline request not working with LL 1.1.2

### ISSUE THREAD

**Issue by manojmilani123** [LearningLocker/learninglocker#414]
Hi,

Articulate storyline courses not connecting with LL 1.1.2. Can you please help me figure out that?

Thanks,
Manoj

**Comment by priyankajuyal** [comment]
@ryansmith94  I have learninglockerv2 installed on my machine. And, Moodle LMS installed. Also installed xAPI plugin to send statements from LMS to LRS. But it is unable to do so. Can you suggest some quick measures?

**Comment by ryansmith94** [comment]
Hi @priyankajuyal so you're having trouble sending statements from Moodle to Learning Locker? If that's the case you need to change the Moodle plugin settings, it'll better for you to post this issue on the [Moodle plugin](https://github.com/xAPI-vle/moodle-logstore_xapi) or the [Gitter chat room](https://gitter.im/LearningLocker/learninglocker).
