### ISSUE TITLE
Installation - Register your first user returns not found

### ISSUE THREAD

**Issue by charyorde** [LearningLocker/learninglocker#477]
[host]/learninglocker/register returns not found.

Does LL takes care of trailing slash internally or it needs a custom rewrite rule?

ENV
- php 5.6
- centos 6.5
- LL v1.1.0

**Comment by ryansmith94** [comment]
Hi @charyorde, thanks for reporting the issue. What does `[host]/learninglocker/public/register` return?

**Comment by charyorde** [comment]
404 Not Found.

**Comment by ryansmith94** [comment]
I'm not sure how you've installed this, so could you also try:

1. [host]/public/register
2. [host]/learninglocker/public
3. [host]/public

**Comment by charyorde** [comment]
Okay, this worked: learninglocker/public/

But I'm getting this error: 
```
Error in exception handler: The stream or file "/var/www/learninglocker/app/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/learninglocker/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84
```
Is there any known convention for setting file/directory permissions for LL?

**Comment by ryansmith94** [comment]
Nice :smile: 

Go to your Learning Locker directory and try running this command first:

```
sudo find app/storage/ -type f -exec chmod 664 {} +
```

If that doesn't work run this:

```
sudo find app/storage/ -type d -exec chmod 775 {} +
```

**Comment by charyorde** [comment]
Thanks @ryansmith94 . This is what worked: `find app/storage/ -type d -exec chmod 777 {} +`

However, what can I do to make LL connect to mongo. I'm seeing `Failed to connect to: localhost:27017: Permission denied` from learninglocker/public/

I'm using the default mongodb config at app/config/database.php.

**Comment by ryansmith94** [comment]
No problem @charyorde :+1: 

Ok, there could be two issues:

1. Mongo is not running.
2. Your config is incorrect (this is more likely).

Regarding reason 2, it might be that the config being used is actually `app/config/local/database.php` rather than `app/config/database.php`. Try changing the config in there instead and see if that works. If not your config is probably incorrect so please paste in your config (without username/password).

**Comment by charyorde** [comment]
app/config/database.php:
```
mongodb' => array(
                    'driver'   => 'mongodb',
                    'host'     => 'localhost',
                    'port'     => 27017,
                    'username' => 'username',
                    'password' => 'password',
                    'database' => 'learninglocker' // Default name (removing this makes Travis fail).
                ),  
```
app/config/local/database.php config
```
return array(
  'connections' => array(
    'mongodb' => array(
      'driver'   => 'mongodb',
      'host'     => 'localhost',
      'port'     => 27017,
      'username' => 'username',
      'password' => 'password',
      'database' => 'learninglocker'
    )
  )
);
```
Connecting without specifying username and password also results `Failed to connect to: localhost:27017: Permission denied`

**Comment by charyorde** [comment]
@ryansmith94 

This fixed it: setsebool -P httpd_can_network_connect 1

**Comment by ryansmith94** [comment]
Ah nice! Well done! Thanks for letting me know.
