### ISSUE TITLE
During installation "php artisan migrate" error

### ISSUE THREAD

**Issue by jlowe64** [LearningLocker/learninglocker#478]
While installing learninglocker, when doing the command "php artisan migrate" from within the learninglocker directory the following error: "

status: 500 Error: localhost:27017: no such cmd: aggregate

[MongoResultException] localhost:27017: no such cmd: aggregate

LL version 1.1.0
PHP 5.6
Debian 7
Mongo 2.0.6

**Comment by ryansmith94** [comment]
Looks like you need to upgrade Mongo. Current version is 2.6.x.

**Comment by jlowe64** [comment]
That was exactly the problem. The documentation that I was going by didn't specify that 2.6.x was required. The standard version that ships with Debian 7 is 2.0.6. After upgrading I successfully finished installation.

**Comment by ryansmith94** [comment]
Nice :+1: ok, I'll create issue for this on our [docs](https://github.com/LearningLocker/docs) :-)
