### ISSUE TITLE
Redirect to learninglocker/public/register gives 404 Not Found

### ISSUE THREAD

**Issue by charyorde** [LearningLocker/learninglocker#480]
After submitting the form at learninglocker/public/, a redirect to learninglocker/public/register gives 404 Not Found

ENV
------
- php 5.6
- centos 6.5
- LL v1.1.0

**Comment by ryansmith94** [comment]
What's the difference between this and your earlier issue #477?

**Comment by ryansmith94** [comment]
Oh I see the difference, I didn't see the last part of your last comment sorry. I'm not sure why you're redirected after submitting the form. I would delete your db in Mongo and start again.

**Comment by ryansmith94** [comment]
If that doesn't work, please edit your initial comment on this issue to follow our guidelines, these can be found in the contributing.md file

**Comment by charyorde** [comment]
For an Alias based configuration, for example in Apache config site.conf:
```
Alias /learninglocker "/var/www/learninglocker/public/"

<Directory "/var/www/learninglocker/public/">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>
```
Corresponding Laravel public/.htaccess file, add this just after RewriteEngine On:
```
RewriteBase /learninglocker
```

This should belong in some docs somewhere. Is LL's docs managed by md so that I can contribute this into the docs?

**Comment by ryansmith94** [comment]
Hey sounds good, we do have a [docs repo](https://github.com/LearningLocker/docs), please edit the [installation.md](https://github.com/LearningLocker/docs/blob/master/installation.md) file and add this under "Configuration".
