### ISSUE TITLE
No create report button on report page

### ISSUE THREAD

**Issue by xcompass** [LearningLocker/learninglocker#485]
When I click on report on the left sidebar, only "Reporting" heading showed up, nothing else. This is fresh new instance and I'm logged in as super admin (first user).

Learning Locker version
develop branch at commit 1bc47eda198a6ff8eebd4e695ce2c12f141ec95d.

Steps to reproduce the problem
1. create a new instance of learninglocker
![screen shot 2015-01-19 at 11 30 00 am](https://cloud.githubusercontent.com/assets/465548/5806444/19820ee8-9fce-11e4-972f-7e4fc3c2f79d.png)
2. Click the "Reporting" button

Expected behavior
I expect to see "Create Report" button on the right of the screen as shown in the blog post: http://learninglocker.net/2014/10/02/reports-and-exports-part-1/

Actual behavior
No "Create Report" button showed up.

Server information
MongoDB with Basic Authentication

Client information
Google Chrome 39.0.2171.99 (64-bit) on OSX 10.9

**Comment by ryansmith94** [comment]
Hi please edit your comment to follow our [guidelines](http://docs.learninglocker.net/issues/). This would be a client side issue. You can find an [example of such an issue on our Github](https://github.com/LearningLocker/learninglocker/issues/317).

**Comment by xcompass** [comment]
@ryansmith94 updated. Hope it helps.

**Comment by ryansmith94** [comment]
Awesome thanks :-) I'll check it out tomorrow morning, assuming I've fixed the other issue I was working on this afternoon

**Comment by ryansmith94** [comment]
I can't seem to reproduce the issue unfortunately. Could you please check your console and network requests in your developer tools?

![image](https://cloud.githubusercontent.com/assets/3045513/5815439/87bad0f6-a08d-11e4-9991-0b0118086f58.png)

**Comment by xcompass** [comment]
Never mind. It seems working fine now. I did re-provision the server a few times with different configuration. Not sure what was causing the problem.

**Comment by ryansmith94** [comment]
Ok thanks for letting me know :-)

**Comment by bakkostas** [comment]
Hi I have the same problem.
the LL version is 1.3.10 
operation system ubuntu server 
the setup is new both.

Thx in advance.

**Comment by ee0pdt** [comment]
Same issue. Chrome on Mac OS X, LRS hosted version:

    Uncaught TypeError: this.$el.find(...).tooltip is not a function

![screen shot 2015-04-29 at 12 48 33](https://cloud.githubusercontent.com/assets/6094917/7390264/1c28adac-ee6e-11e4-8a57-a0d95db4e2a6.png)

**Comment by ryansmith94** [comment]
What happens when you refresh with cache turned on?

**Comment by ee0pdt** [comment]
Works as expected in that case

**Comment by ryansmith94** [comment]
Ok I'll try to take a look with cache disabled. Thanks Pete :-)

**Comment by bakkostas** [comment]
Hi ,

Could you please help me because i don't understant what cache do you mean.

thx.

**Comment by ryansmith94** [comment]
If you refresh your browser it should work fine @bakkostas unless you've not installed correctly.

[Web Cache](http://en.wikipedia.org/wiki/Web_cache)

**Comment by ryansmith94** [comment]
@xcompass, @ee0pdt, @bakkostas this issue has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.11.
