### ISSUE TITLE
mcrypt_encrypt(): key of size 14 not supported by this algorithm. Only keys of sizes 16, 24, or 32 supported.

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#488]
Getting the following error (domain/register) after successful installation: 
```
mcrypt_encrypt(): key of size 14 not supported by this algorithm. Only keys of sizes 16, 24, or 32 supported.
```
Looks like PHP5.6 mcrypt_encrypt needs to have keys of size 16, 24, or 32. I can easily pad with zeros, but where should I make the change?

**Comment by fugu13** [comment]
Instead of padding with zeroes, just add more random characters. Modify the line equivalent to this line in the default config (comments above recommend 32 characters): https://github.com/LearningLocker/learninglocker/blob/208f0f0bc5a293a63a8b2b561446caca2ef45fd0/app/config/app.php#L70

**Comment by davidpesce** [comment]
Ahh, beautiful! Thank you! 

I'll add it to my tutorial.

**Comment by NayefAlharbi** [comment]
Can the enckyption key be in a Base64 format?

**Comment by ht2** [comment]
It is a random set of characters of length 16, 24, or 32. It can be in whatever format you want it to be...
