### ISSUE TITLE
Localization GUI, strings and Logo...

### ISSUE THREAD

**Issue by votuduc** [LearningLocker/learninglocker#489]
Are there any guide/document for localization GUI of Learning Locker?
How if I want to change logo, some text/string?

**Comment by ryansmith94** [comment]
Please see #387. Logo and some strings must be changed in the code. When changing code please be aware of our [license](https://github.com/LearningLocker/learninglocker/blob/develop/LICENSE).

**Comment by votuduc** [comment]
Hello Ryan, 

I'm Duc, I got your email via GitHub. Yesterday I raised a ticket regard to localize Learning Locker, then I got your reply via GitHut. That's why I now send this email to you.

As the topic #489 was closed by you and I know why it was. But After reading the topic  #387 that you suggested, I can find out the solution. That's because I'm very new with Learning Locker / Lavarel...etc and I'm also not a technical expert.

So, Could you please give me a point for my starting (e.g which document I should read firtly....). 

Thank you so much and have a nice day to you.

Best and Regards, 

DUC

**Comment by votuduc** [comment]
Hello Ryan, 

I now know a little bit about "Lang" folder and other activities regard to translate Learning Locker to another language. 

But there is new question is that How I translate some text/words those appear on main chart/graph? 

For instance, Please look at attached file. You will see some words as list below:

1. Statements 34
2. Your daily average is 1 statements with 3 learners in total.
3. Most active users
4. Popular Activities
5. Latest reports 
6. Visit Reporting Tool.

For more detail, please take a look at attached images. 

Thank you in advance.

DUC
![screen shot 2015-01-24 at 12 05 03 am](https://cloud.githubusercontent.com/assets/8246785/5878920/5bf6dda2-a35d-11e4-9e08-134bcbb449e6.png)
![screen shot 2015-01-24 at 12 08 28 am](https://cloud.githubusercontent.com/assets/8246785/5878922/5e3b7730-a35d-11e4-8f31-7109d389ae48.png)
