### ISSUE TITLE
State API always(?) returns 412 pre-condition failed when PUTing updates to documents and when Etag headers are used. 

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/learninglocker#491]
**Version**
Latest from composer as 22nd Jan 2015

**Steps to reproduce the bug**
1. Store an application/json document in the State API. 
2. Get the document in order to get the latest eTag OR get the eTag directly from the database
2. Update the document (PUT) including the If-Match eTag header

**Expected behaviour**
Document should be accepted, returning 204 no content. 

**Actual behaviour**
412 pre-condition failed is returned. 

**Server information**
MongoDB with Basic auth. Running on MAMP. 

**Client information**
OS: OS X 10.10.1
Browser: Chrome

**Additional information**
I've tested the client code I'm using against Wax and Cloud and it works. This also affects the Agent Profile API.

**Comment by ryansmith94** [comment]
Thanks again Andrew, bit of an odd one, I'll take a look next week for 1.3.2.

**Comment by garemoko** [comment]
Couple of notes:

1. Commenting out [this line](https://github.com/LearningLocker/learninglocker/blob/ec7a6ec0245683fa4eb7cf6d57da4a9f760e4dc3/app/locker/repository/Document/EloquentDocumentRepository.php#L322) resolves the 412 issue as the problem seems to be comparing the value I'm sending with quotes with one without quotes, however when I do this I get 400 bad request instead. 

2. Looking at my database I have 2 objects in documentapi. They both have the same _id, the same sha and the same timestamp, which doesn't seem right. It's the state document I'm getting the error when updating. 

```
{
    _id: ObjectId("54c1773c44b444b8020041a7"),
    lrs: "54c1771844b444f0020041a7",
    documentType: "state",
    identId: "http://tincanapi.co.uk/stateapikeys/registrations",
    activityId: "http://id.tincanapi.com/activity/tincan-prototypes/golf-example",
    agent: {
        name: "Andrew Downes",
        mbox: "mailto:andrew.downes@tincanapi.com",
        objectType: "Agent"
    },
    registration: null,
    updated_at: ISODate("2015-01-22T22:18:36Z"),
    sha: "\"DA39A3EE5E6B4B0D3255BFEF95601890AFD80709\"",
    content: {
        "02acbe23-13ee-47ea-a68e-111309ec0d37": {
            created: "2015-01-22T23:18:36+01:00",
            lastlaunched: "2015-01-22T23:18:36+01:00"
        }
    },
    contentType: "application/json",
    created_at: ISODate("2015-01-22T22:18:36.544Z")
}
```

and

```
{
    _id: ObjectId("54c1773c44b444fe020041a7"),
    lrs: "54c1771844b444f0020041a7",
    documentType: "agentProfile",
    identId: "CMI5LearnerPreferences",
    agent: {
        name: "Andrew Downes",
        mbox: "mailto:andrew.downes@tincanapi.com",
        objectType: "Agent"
    },
    updated_at: ISODate("2015-01-22T22:18:36Z"),
    sha: "\"DA39A3EE5E6B4B0D3255BFEF95601890AFD80709\"",
    content: {
        languagePreference: "en"
    },
    contentType: "application/json",
    created_at: ISODate("2015-01-22T22:18:36.831Z")
}
```

**Comment by garemoko** [comment]
Edit: This also affects the Agent Profile API.

**Comment by ryansmith94** [comment]
Is the agent API effects before or after your alteration?

**Comment by ryansmith94** [comment]
Effected *

**Comment by ryansmith94** [comment]
Pausing this issue for now to see how #490 effects this.

**Comment by garemoko** [comment]
yeh, before this said "this does not affect the agent profile api" but that's a lie.

**Comment by ryansmith94** [comment]
Ok haha

**Comment by ryansmith94** [comment]
This should now be resolved on the develop branch.

**Comment by ryansmith94** [comment]
Had to make a few changes to pass the conformance tests that may effect this issue. If someone can test this issue with the issue/conformance branch that would be awesome.

**Comment by garemoko** [comment]
*looks at @davidpesce*

**Comment by davidpesce** [comment]
@ryansmith94 Confirmed! This issue is resolved.

**Comment by ryansmith94** [comment]
Good stuff thanks again @davidpesce! :+1:
