### ISSUE TITLE
400 Bad Request from Golf Prototype statement

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/learninglocker#492]
**Version**
Whatever version is on http://lrs.learninglocker.net/

**Steps to reproduce the bug**
1. Go to http://cdn.tincanapi.com/wp-content/assets/ClientPrototypes/GolfExample_TCAPI/index.html?endpoint=http%3A%2F%2Flrs.learninglocker.net%2Fdata%2FxAPI%2F&auth=Basic%20MTJmOTk0OGRlOGExNjZlYmMxMzY3MTVlNTYxNzQyMTM1ZDEzMTU1OTo5MTkwODY1OWVmYzMyYjYxNDE5NzY2MjE5MjEyNDdmNzQyOTAyYzQ3&actor=%7B%22name%22%3A%22Andrew%20Downes%22%2C%22mbox%22%3A%22mailto%3Aandrew.downes%40tincanapi.com%22%2C%22objectType%22%3A%22Agent%22%7D&registration=9816b43e-9be5-4f8b-9efd-1be260be9a59

(This uses my Learning Locker 14 day trial account!)

2. Open up the network panel in developer tools

3. Click next in the golf course.

**Expected behaviour**
The statement should be accepted. 

**Actual behaviour**
Error 400 is returned with the response:

``` {"error":true,"success":false,"message":["`{\"name\":\"\"}` must be `object` not `array` in `statement.authority`"]} ```

**Server information**
http://lrs.learninglocker.net/

**Client information**
OS: OS X
Browser: Chrome

**Additional information**
* The statements generated by the Golf example do not include an authority field. 
* The credentials used are "additional" credentials generated by API (the code I wrote), not the main credentials. This error does NOT occur when using the main credentials.

**Comment by ryansmith94** [comment]
Note to self: will be fixed in tidyup by using authorities.

**Comment by garemoko** [comment]
Note to Ryan: The vision I had with the multi credential feature was that you could specify a different authority for each credential set you create (whether by API or UI). I guess I messed something up in the implementation (or it got broken later) but this is still a worthwhile goal.

**Comment by ryansmith94** [comment]
Yeah this is something I'm addressing in the new branch. We've decided that actually the models at the foundation of Learning Locker should be Statement and Authority. An LRS then becomes a group of Authorities.

**Comment by ryansmith94** [comment]
(issue/490)[https://github.com/LearningLocker/learninglocker/tree/issue/490] should solve this issue. Update your clients to "migrate" them.

**Comment by ryansmith94** [comment]
Please test this with your plugin and let me know how it goes, if it works ok I'll merge into develop.

**Comment by davidpesce** [comment]
@garemoko Do you want me to test this? I've got the 490 branch still installed along with our latest changes to the plugin.

**Comment by garemoko** [comment]
Yes please! It's not related to the plugin at all, but very helpful for you to test.

**Comment by davidpesce** [comment]
I didn't want to step on any toes.

Happy to say, I can confirm this is working now. 

Only one more item for 1.3.4 release?

**Comment by ryansmith94** [comment]
Thanks @davidpesce! Really appreciate all of your help with LL recently!
:-D

I think so, I'll be trying to push 1.3.4 out before the week is over that's
for sure.

**Comment by davidpesce** [comment]
No problem, happy to help! I'll be sticking around for a while. Also interested to get involved with the CMI-5 spec. I've been in the industry for 10+ years and never had the time to devote to giving back. Now I'm making the time.

**Comment by garemoko** [comment]
Awesome! CMI-5 could definitely benefit from input, as could the spec itself. Also, feel very free to start hitting the list of issues at https://github.com/garemoko/moodle-mod_tincanlaunch/issues and ask me any questions you like. 

"The workers are few and the harvest is plentiful" - never worry about stepping on my toes!

**Comment by davidpesce** [comment]
Excellent! I'll get everything organized on my end tomorrow morning and should be able to work on issues Thursday.
