### ISSUE TITLE
More link includes double slash and no more-ness

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/learninglocker#495]
**Version**
http://lrs.learninglocker.net

**Steps to reproduce the bug**
Have a small number of Statements in your LRS.

GET Statements and look at the more link in the returned response. 

**Expected behaviour**
Either there is no 'more' property or it is an empty string. 

**Actual behaviour**
A more link similar to: ```http://lrs.learninglocker.net//data/xAPI/statements?limit=25&related_activities=false&related_agents=false``` (note the double slash). 

**Server information**
http://lrs.learninglocker.net

**Client information**
OS: Mac OS X
Browser: Chrome

**Additional information**
I didn't test the case where you have a large number of statements in the LRS.

**Comment by ryansmith94** [comment]
Fixed in `issue/tidyup` (however that branch is completely unusable right now), will be merged in the next couple of weeks hopefully.
