### ISSUE TITLE
"more" property returns absolute IRI instead of relative IRL

### ISSUE THREAD

**Issue by pondermatic** [LearningLocker/learninglocker#501]
**Version**
develop at 1684eb9b9e029fc9afe80e41b496e69c71487aa9

**Steps to reproduce the bug**
* Make sure that there is more than one statement in the LRS that matches a query.
* Perform a statement query with a limit parameter to ensure that there will be more statements to retrieve, e.g. `GET /data/xAPI/statements?verb=http%3A%2F%2Fadlnet.gov%2Fexpapi%2Fverbs%2Fterminated&limit=1`

**Expected behaviour**
The returned `StatementResult` object's `more` property should contain a relative IRL as defined in https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#retstmts.
`/data/xAPI/statements?verb=http%3A%2F%2Fadlnet.gov%2Fexpapi%2Fverbs%2Fterminated&amp;limit=1`

**Actual behaviour**
"more" contains an absolute IRI.
`http://exmaple.com/data/xAPI/statements?verb=http%3A%2F%2Fadlnet.gov%2Fexpapi%2Fverbs%2Fterminated&amp;limit=1`

**Server information**
Windows 8.1
Apache 2.4
MongoDB 2.6.0
PHP 5.4.31

**Client information**
OS: Windows 8.1
Browser: Chrome version 40

**Additional information**
I believe the change from relative to absolute happened in `app/controllers/xapi/StatementController.php` on 2014-11-21 with develop b7e0b9b9eb869ccfa4eb0dc3eaade25328372846.

**Comment by pondermatic** [comment]
On a related issue, the RusticiSoftware/TinCanPHP library sends an absolute full URI in the HTTP request for statements, which is a non-standard request format but some proxy servers require it. This causes `$_SERVER['REQUEST_URI']` to be absolute instead of relative.

Perhaps `Controllers/xAPI/StatementController->getMoreLink()` should check for the presence of `$_SERVER['HTTP_HOST']` or `$_SERVER['SERVER_NAME']` in `REQUEST_URI` and remove the scheme and host?

I'd like to be assigned to this issue.

**Comment by ryansmith94** [comment]
Thanks for reporting the issue. This is fixed on the `issue/tidyup` branch.
