### ISSUE TITLE
`more` property does not contain `offset` parameter

### ISSUE THREAD

**Issue by pondermatic** [LearningLocker/learninglocker#508]
**Version**
develop at 926285e23b40034bd3c3134a19b434fc58faf0e3

**Steps to reproduce the bug**
Perform a statement query where there are more results than the limit, e.g. `GET /data/xAPI/statements?verb=http%3A%2F%2Fadlnet.gov%2Fexpapi%2Fverbs%2Fcompleted&limit=1`

**Expected behaviour**
The returned `StatementResult` object's `more` property should contain an offset parameter.

**Actual behaviour**
There is no offset parameter.

**Server information**
Windows 8.1
Apache 2.4
MongoDB 2.6.0
PHP 5.4.31

**Client information**
OS: Windows 8.1
Browser: Chrome version 40

**Additional information**
The behavior changed in develop c4f9e964a946d7152a87e8121537976c7ded695a.

**Comment by ryansmith94** [comment]
Thanks for reporting the issue and following our guidelines. I'm now merging in a pull request to fix this issue in the `develop` branch.
