### ISSUE TITLE
404 at GET /xAPI/activities/state

### ISSUE THREAD

**Issue by agirton** [LearningLocker/learninglocker#512]
**Version**
master at 0989493f74da

**Steps to reproduce the bug**
Using TinCan.js it submitted the following data with the getState method
* ``stateId``
* ``activityId``
* ``agent``

**Expected behavior**
GET state should be returning the state of the course since I submitted the exact same data as I used on PUT state (xAPI/activities/state).

**Actual behaviour**
```
response: '{"error":true,"success":false,"message":null}',
responseText: '{"error":true,"success":false,"message":null}',
responseType: '',
status: 404,
statusText: 'Not Found',
```

**Server information**
* Apache/2.4.9 
* PHP/5.6.2

**Client information**
OS: Mac OSX 10.10.2
Browser: Safari version 8.0.3

**Additional information**
Before TinCan.js was using PUT and it seems the DocumentController requires POST. I updated to POST but it's still not finding the data. I put a log in after I made a POST request and it seems document is being set, but when it tries to find the data in the GET request it can't find anything which in return sends the 404. Documents are being created as I can see them being inserted in the uploads directory.

**Comment by ryansmith94** [comment]
Hi @agirton, thanks for reporting this issue and following our guidelines. Unfortunately I can't seem to reproduce this issue.

**Version**
develop at e9cd5d7

**Steps**
(1) Send the PUT request below:
```
PUT /ll/ll/public/data/xAPI/activities/state?activityId=http://www.example.com&agent={"name":"Example", "mbox":"mailto:ex@mple.com"}&stateId=hello HTTP/1.1
Host: localhost
Authorization: Basic ZWNiY2U2ZjE5ODlkOThlNDMwYTM1ZGY2OWZiMDdhNmUyNDg4MTE3MDplYTBiYTIxMjhkOGRkNDFjMDhhMjdkNDg4NzI5OWYzZjE5OTI4NmE1
X-Experience-API-Version: 1.0.1
Content-Type: application/javascript
Cache-Control: no-cache

{
    "x": 10
}
```

(2) Send the GET request below:
```
GET /ll/ll/public/data/xAPI/activities/state?activityId=http://www.example.com&stateId=hello&agent={"mbox":"mailto:ex@mple.com"} HTTP/1.1
Host: localhost
Authorization: Basic ZWNiY2U2ZjE5ODlkOThlNDMwYTM1ZGY2OWZiMDdhNmUyNDg4MTE3MDplYTBiYTIxMjhkOGRkNDFjMDhhMjdkNDg4NzI5OWYzZjE5OTI4NmE1
X-Experience-API-Version: 1.0.1
Cache-Control: no-cache
```

**Actual Result**
200 OK
```json
{
  "x": 10
}
```

**Comment by agirton** [comment]
Hi @ryansmith94,

Found the issue, user error. The activityId's didn't match up; the setState was using all lowercase /xapi/activities/state in the activityId and the getState was using /xAPI/activities/state. 

![](http://i.giphy.com/Kh296M49Zr1Sg.gif)

**Comment by ryansmith94** [comment]
Hey! No worries, it happens :+1: Thanks for letting me know! Someone else could potentially hit this issue, arrive here and see your comment so this is still of use :smile:

**Comment by ryansmith94** [comment]
Appreciated the Gif by the way ;)

**Comment by agirton** [comment]
:smile: all issues should have a GIF. I think you should include that in your requirements doc: "Include a GIF of how you are feeling".

**Comment by ryansmith94** [comment]
Haha that might be a fun idea. I try to use the emoticons wherever possible to the same effect :+1:
