### ISSUE TITLE
"Unknown properties (openID) from `Locker\\XApi\\Agent` in `statement.actor`"

### ISSUE THREAD

**Issue by kzkamiya** [LearningLocker/learninglocker#517]
LearningLocker can not use a property name with a capital letter.
When I used "openid", it could save a statement but when I used "openID", it could't save and showed below a message.

{"error":true,"success":false,"message":["A `Locker\\XApi\\Agent` must have exactly one identifier not `0` in `statement.actor`","Unknown properties (openID) from `Locker\\XApi\\Agent` in `statement.actor`"]}

On the other hand, ADL LRS could save both cases. Which is a correct behavior?

**Comment by garemoko** [comment]
See https://github.com/adlnet/ADL_LRS/issues/317#issuecomment-74478660

````openID```` is invalid

**Comment by ryansmith94** [comment]
Thanks for the question. It should be lower case as defined in the xAPI
spec. I expect the acceptance of upper case is a convenience in other LRSs.

**Comment by kzkamiya** [comment]
Thank you for your responses.
I am Sorry, My information was wrong. 
Once again, I tried testing ADL_LRS using "openid" and then that result was an error with below message.

```
Cannot resolve keyword 'openid' into field. Choices are: account_homePage, account_name, 
activitystate, actor_of_substatement, actor_statement, agentprofile, authority_statement,
 global_representation, id, mbox, mbox_sha1sum, member, name, oauth_identifier, objectType,
 object_of_statement, object_of_substatement, openID, statement_context_instructor,
 statement_context_team, substatement_context_instructor, substatement_context_team
```

And also, I checked the xAPI-Spec and then I confirmed "openid" is correct property name. 
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#actor

Property | Type | Description
------------ | ------------- | -------------
openid | URI | An openID that uniquely identifies the Agent.

I think Learning Locker's behavior is correct.

**Comment by ryansmith94** [comment]
You're very welcome. No problem. That's great, thanks for letting us know
:-)

**Comment by ty-** [comment]
@kzkamiya the bug referenced by @garemoko above addresses this behavior on the ADL LRS
