### ISSUE TITLE
Statement save trigger

### ISSUE THREAD

**Issue by nmuldashev** [LearningLocker/learninglocker#518]
I want to catch some statement save events. For example when actor attempted some tincan resource, i want to update my lms database record for student attempted that resource. how can I implement it?

**Comment by ryansmith94** [comment]
Hey, thanks for the question. Could you please clarify whether you're trying to update your LMS in real-time or whether you're just trying to make queries to the LRS?

**Comment by nmuldashev** [comment]
I'm trying to update LMS in real-time

**Comment by ryansmith94** [comment]
Ok nice. Unfortunately we don't have that functionality right now. However, you can of course add this functionality yourself. You would need to use [events in Laravel](http://culttt.com/2014/03/10/using-events-laravel-4/) to trigger an event after statements are "activated" and then your code would need to subscribe to that event.

**Comment by nmuldashev** [comment]
In which file could i find activating statements?

**Comment by ryansmith94** [comment]
https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/repository/Statement/EloquentStatementRepository.php#L715-L717
