### ISSUE TITLE
Question - Should the SHA change for documentType agentProfile on update?

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#524]
I'm curious if the SHA should change for documentType agentProfile when updating the agent profile via the API?

**Comment by fugu13** [comment]
If the contents change for any of the document APIs, the SHA must change to maintain the ETag contract

**Comment by garemoko** [comment]
@davidpesce in the case of the Moodle plugin you're working with, if the learner doesn't change their language preference, the etag won't change.

**Comment by ryansmith94** [comment]
Thanks for your question @davidpesce. Thanks for your responses on this issue @fugu13 and @garemoko :+1:
