### ISSUE TITLE
Timestamp query params not working

### ISSUE THREAD

**Issue by ryansmith94** [LearningLocker/learninglocker#533]
**Version**
tidy/all at 3313727

**Steps to reproduce the bug**
1. Insert a statement with `stored` set to `2015-03-02T16:02:57.094500+00:00`.
2. Attempt to get the statement with the `since` query param set to `2015-03-01`.

**Expected behaviour**
Response from step 2 should contain the statement from step 1 because the `stored` is after the `since` timestamp.

**Actual behaviour**
Response from step 2 does not contain the statement.

**Server information**
Mongo with Basic Auth.

**Comment by fugu13** [comment]
I may be missing something here, but spec-based xAPI statement retrieval *never* uses timestamp; it only relies on stored.

**Comment by ryansmith94** [comment]
You're right, I should have made that clearer in the issue.

**Comment by ryansmith94** [comment]
:confused: this works for me now... very odd. Maybe I voided the statement or something previously.
