### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by rohini12** [LearningLocker/learninglocker#540]
how to installation process in Learning Locker in windows7

**Comment by ryansmith94** [comment]
Hi @rohini12, thanks for your question. Our [installation guide](http://docs.learninglocker.net/installation/) can be found on our [docs](http://docs.learninglocker.net) please ensure that you have installed [LL's requirements](http://docs.learninglocker.net/requirements/) before installing.

**Comment by rohini12** [comment]
I will install Mongodb and Composer in my machine.but getting error "It looks like you are trying to access MongoDB over HTTP on the native driver port."

**Comment by ryansmith94** [comment]
That's not an issue with LL. I suggest you Google the error.
