### ISSUE TITLE
Report-editing is not saved successfully

### ISSUE THREAD

**Issue by Tschakki** [LearningLocker/learninglocker#547]
Hi,
I'm playing around a little with xAPI and Learning-Locker, and I think I found a bug.

LearningLocker-Version: 1.3.3
Steps to reproduce:
- create a report
- click on edit
- click on "with result"
- click on Success true and Complete true
- click on save

the notification "saved successfully" pops out, but in fact it is not saved.
If I close and open the edit of the report again, the fields are unchecked D:
If I change for example the "who"-setting, by adding a user, the saving works!

Please help!
Greetings, Tschakki

**Comment by ryansmith94** [comment]
Hi @Tschakki, thanks for reporting this issue and following our guidelines, this has now been reproduced and should be fixed soon.

**Comment by ryansmith94** [comment]
Hi @Tschakki, this issue has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.6.

**Comment by Tschakki** [comment]
Hey, thanks a lot for the quick fix! :-)

**Comment by ryansmith94** [comment]
No problem @Tschakki! Thanks for the bug report :smile:
