### ISSUE TITLE
When timeout occurs, after logging in, user is brought to dashboard rather than expired URL.

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#552]
**Motive**
User experience will be improved.

**Result**
After a timeout occurs, users logs back in and is brought back to the page they timed out on. Rather than the main dashboard

**Comment by ryansmith94** [comment]
Thanks for the suggested enhancement @davidpesce. I agree that it would improve UX. I'll take a look at this when I get some time. In the meantime, you or anyone else are welcome to create a PR to add the enhancement :smile:

**Comment by davidpesce** [comment]
It's on my todo list to help out! Working on getting the mod_tincanlaunch plugin wrapped up and then I'll be poking around over here.

**Comment by ryansmith94** [comment]
Awesome! Thanks a lot! :smile:

**Comment by ryansmith94** [comment]
I forgot to mention that I did have a go at this, but the issue is keeping the url part after the `#`.

**Comment by ryansmith94** [comment]
I'm going to archive this because I don't think it is something we'll do any time soon.
