### ISSUE TITLE
Question - Upgrade process for MySQL (MariaDB)

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#555]
After reading [this](http://t.co/yzYGpDXtJy)...

I got curious about setting up LL with MySQL (specifically MariaDB). Because the DB is abstracted with Laravel, is the general upgrade process identical to MongoDB? (php artisan migrate)

Is MongoDB what LL recommends?

**Comment by ryansmith94** [comment]
TLDR that link. Can you summarise it?

There are some parts of our API that rely on Mongo so those parts would need to be removed. We recommend MongoDB because it's quicker for querying statements. We have previously used MySQL and noticed that it doesn't scale for statements.

**Comment by davidpesce** [comment]
It's just talking about scalability of noSQL-db vs relational-db. It's actually an interesting read, but yes, it does take a while.

**Comment by ryansmith94** [comment]
Ok, I'll try to read it if I get time. I started to read it them looked at the scroll bar haha. 

The decision to use Mongo was based on experience and the structure of the data. I'm very certain that the correct decision was made.

**Comment by davidpesce** [comment]
Haha, yeah, I did the same thing. Saved it for a bit and then read it. I've
used Mongo on a few projects and absolutely love it. It's what made me zero
in on LL in the first place. The article gives an alternative perspective
on it's use and actually explains situations where it shouldn't be used.

Keep me posted if you read it!

**Comment by ryansmith94** [comment]
Haha I'll add it to my [pocket](getpocket.com) and try to read it on the train some time.

> I've used Mongo on a few projects and absolutely love it. It's what made me zero
in on LL in the first place.

That's awesome! 

> The article gives an alternative perspective on it's use and actually explains situations where it shouldn't be used. Keep me posted if you read it!

Cool, ok. I definitely think our situation qualifies as a good use of Mongo. Will definitely let you know my thoughts if I read it via this issue :+1:

**Comment by ryansmith94** [comment]
Just read the post. It is a good read, thanks the link :-) I think we could have made some optimisations in terms of storage with a relational database, but I'm not convinced that it would have been quicker over a large number of statements :-)

**Comment by ryansmith94** [comment]
Thanks for the link *
