### ISSUE TITLE
Preparing and installing LL on CentOS

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#556]
Here's a Gist I created to remember how to prepare and install LL on CentOS 7.0.

[Prepare CentOS 7.0](https://gist.github.com/davidpesce/7d6e1b81594ecbc72311#file-prepare-centos-7-0-for-learninglocker-installation-md)

[Install and Configure LL on CentOS 7.0](https://gist.github.com/davidpesce/7d6e1b81594ecbc72311#file-install-and-configure-learninglocker-md)

**Comment by scara** [comment]
Great!
It would be nice if you could have the chance to propose even a solution based on a [Software Collections](https://www.softwarecollections.org/en/) based path, alternative to _Remi_.

**Comment by davidpesce** [comment]
Ohhh, shiny. That looks awesome!

I can tie that in nicely with my [Ansible playbook](http://www.ansible.com/home)

**Comment by davidpesce** [comment]
Just noticed that Remi uses SoftwareCollection - https://www.softwarecollections.org/en/scls/user/remi/

**Comment by ryansmith94** [comment]
Nice guide @davidpesce! Thanks for posting it, I'll add that to our docs :+1:

**Comment by ryansmith94** [comment]
This has now been added to the docs.

**Comment by scara** [comment]
@davidpesce Yes but `remi-php56` is outside the scope of RHSCL, where you can find PHP `5.5`, https://www.softwarecollections.org/en/scls/rhscl/php55/ (and `5.4`). Remi extended `5.5` via https://www.softwarecollections.org/en/scls/remi/php55more/: SCLS are community driven but somewhat managed by RHEL and generally they are granted by the sysads.
BTW, TNX for your efforts and your sharing! As you have already noted I'm used to comment on the repos I'm watching even if not directly involved :grinning:.
