### ISSUE TITLE
MongoResultException: exception: $in needs an array (vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php line:58)

### ISSUE THREAD

**Issue by akermen** [LearningLocker/learninglocker#567]
**Version**
1.3.7

**Steps to reproduce the bug**
Exception is thrown when trying to create a sample report with the following steps:

- "Who" is empty
- "Did" is set to "http://adlnet.gov/expapi/verbs/completed"
- "What" is set to "http://tincanapi.com/GolfExample_TCAPI"
- "Where" is empty
- "With result" is set to "Success: True, Complete: True"
- "When" is empty

It seems to be the "With result" fields "Success" and "Completed" are somehow triggering the exception, when they both not set, the report is created without any issue.

**Server information**
PHP Version 5.5.9-1ubuntu4.6
Apache/2.4.7
mongodb version v2.4.13
3.13.0-46-generic #75-Ubuntu

**Comment by ryansmith94** [comment]
Hi @akermen, thanks for reporting this issue and following our guidelines. We will now try to reproduce your issue.

**Comment by ryansmith94** [comment]
Hi @akermen, thanks for providing the details to reproduce this issue, this has now been reproduced and should be fixed soon.

**Comment by ryansmith94** [comment]
Hi @akermen, this issue has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.9.
