### ISSUE TITLE
Exporting Not Working

### ISSUE THREAD

**Issue by stephenlane** [LearningLocker/learninglocker#568]
**Version**
{{master}} at {{unknown}}

**Steps to reproduce the bug**
{{Go to export data using the export functionality}}

**Expected behaviour**
{{Export}} should be {{expectedResult}} because {{it worked previously}}.

**Actual behaviour**
{{Export}} is {{giving this popup "Class 'Helpers\Exceptions\NotFound' not found"}}.

**Server information**
{{mongodb}} with {{yes}}.

**Client information**
OS: {{ubuntu}}
Browser: {{chrome}} version 1.0.1

**Comment by ht2** [comment]
Could you please confirm that you _are_ actually on master (as this sounds like a known bug in develop); and if so then please provide the version number provided in the VERSION file at the root of the repo.

Also FYI, the `{{ }}` characters are simply place-holders so you know where to put the relevant sections.

**Comment by stephenlane** [comment]
Hi there,


Here is my composer.json file

"{
  "authors": [
    {
      "name": "Dave Tosh",
      "email": "davidgtosh@gmail.com",
      "role": "Developer"
    },
    {
      "name": "HT2",
      "email": "hello@ht2.co.uk",
      "role": "sponsor"
    },
    {
      "name": "James Mullaney",
      "email": "james@ht2.co.uk",
      "role": "Developer"
    },
    {
      "name": "Ryan Smith",
      "email": "ryansmith@boun.cr",
      "role": "Developer"
    }
  ],
  "name": "learninglocker/learninglocker",
  "description": "The open source learning record store.",
  "license": "GPL v3",
  "keywords": ["lrs", "learninglocker"],
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:LearningLocker/oauth2-server-laravel"
    }
  ],
  "require": {
    "laravel/framework": "4.2.8",
    "jenssegers/mongodb": "1.4.x",
    "davejamesmiller/laravel-breadcrumbs": "2.2.x",
    "way/generators": "2.6.x",
    "rhumsaa/array_column": "~1.1",
    "barryvdh/laravel-cors": "0.2.x",
    "lucadegasperi/oauth2-server-laravel": "1.0.x",
    "andywer/js-localization": "dev-master",
    "philo/laravel-translate": "1.0.x",
    "learninglocker/statementfactory": "0.0.x"
  },
  "require-dev": {
    "phpunit/phpunit": "4.1.*"
  },
  "autoload": {
    "classmap": [
      "app/commands",
      "app/controllers",
      "app/models",
      "app/database/migrations",
      "app/database/seeds",
      "app/tests",
      "app/locker",
      "app/locker/helpers",
      "app/locker/data",
      "app/locker/graphing",
      "app/locker/explorer",
      "app/locker/statements",
      "app/locker/listeners"
    ]
  },
  "scripts": {
    "post-install-cmd": [
      "php artisan optimize",
      "php artisan js-localization:refresh",
      "cd public/assets/js && bower --allow-root update && cd ../../.."
    ],
    "post-update-cmd": [
      "php artisan clear-compiled",
      "php artisan optimize",
      "php artisan js-localization:refresh",
      "cd public/assets/js && bower --allow-root update && cd ../../.."
    ],
    "post-create-project-cmd": [
      "php artisan key:generate"
    ]
  },
  "minimum-stability": "stable"
}
"

It was previously working but then suddenly stopped.

**Comment by ryansmith94** [comment]
Uploaded on the Google Forum (should have been uploaded here)
![image](https://cloud.githubusercontent.com/assets/3045513/6893155/74faf098-d6c2-11e4-9094-6d34ddc5e5c5.png)

**Comment by ryansmith94** [comment]
> VERSION file
not the composer.json file is needed.

**Comment by ryansmith94** [comment]
From the screenshot I can see that you're not on Master branch as your original comment states. Additionally you're steps to reproduce this issue are vague and inaccurate, please provide more details.

**Comment by stephenlane** [comment]
1.3.5

**Comment by ryansmith94** [comment]
To improve our understanding of this issue. Please clear your "app/storage/logs/laravel.log", then reproduce this issue, then paste in the contents of your "app/storage/logs/laravel.log".

**Comment by stephenlane** [comment]
[2015-03-30 09:03:37] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Helpers\Exceptions\NotFound' not found' in /var/www/learninglocker/app/locker/repository/Base/EloquentRepository.php:43
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []

**Comment by ryansmith94** [comment]
Thank you for that. This issue should be resolved as of #563 and #564 in [v1.3.8](https://github.com/LearningLocker/learninglocker/pull/559) which will be released today. In the meantime you can use the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop).
