### ISSUE TITLE
Verifying a registration when logged in

### ISSUE THREAD

**Issue by stuartridout** [LearningLocker/learninglocker#57]
Problem Steps
- Registered user1 on Learning Locker and have created a LRS
- Registered user2 using learninglockeraddress/register and received a verification email
- User2 clicks the verification link when user1 is still logged in

Outcome
User2 is added to user1's Learning Locker as an observer role.    If user2 then logs in they cannot see any LRS's so doesn't seem like they are really an observer on user1's LRS.  User1 can see user2 as a member of their Learning Locker.

**Comment by Jufervela** [comment]
Hi the server doesn't send the verification email

**Comment by ryansmith94** [comment]
Set `pretend` to `false` in your `app/config/*/mail.php` file.

**Comment by Jufervela** [comment]
Thanks ryan you made my day friend :dancer:

**Comment by ryansmith94** [comment]
You're welcome @Jufervela! :dancers:
