### ISSUE TITLE
Learning Locker wouldn't install from composer

### ISSUE THREAD

**Issue by james-siteclick** [LearningLocker/learninglocker#571]
v1.3.7

**Steps to reproduce the bug**
- Create an empty directory
- Create a composer.json file as described here https://packagist.org/packages/learninglocker/learninglocker
require : {
  "learninglocker/learninglocker": "dev-master"
}
- Run composer update

**Expected behaviour**
Composer should download all necessary files and dependencies

**Actual behaviour**
Composer gets stuck on andywer/js-localization

**Server information**
OSX Yosemite
MAMP

**Additional information**
I then tried pulling the Github repository and running composer update.  This also failed, but I was able to run it by changing to the following dependency:

    "andywer/js-localization": "dev-laravel-4.2",

**Comment by ryansmith94** [comment]
Hi @james-siteclick, this issue has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.9.
