### ISSUE TITLE
Release Instruction Typo

### ISSUE THREAD

**Issue by gazzastone** [LearningLocker/learninglocker#575]
Hi Ryan you have a typo on your release instructions for artsian should be artisan :-)  caught me out on previous release as well !! that's what you get for cut and paste :-)

Run  php artsian migrate --env=YOUR_ENV  where  YOUR_ENV  should be replaced with your environment (likely to be local or production).

Cheers

Gary

**Comment by ryansmith94** [comment]
Ha cheers @gazzastone, good spot, sorry about that. I'll change it now :+1:
