### ISSUE TITLE
Problem with statements ?

### ISSUE THREAD

**Issue by ludm** [LearningLocker/learninglocker#577]
Hello,

I made a test with xAPI using Learning Locker, Storyline and this tuto :
http://learninglocker.net/2014/10/27/767/

It wokrs, the statement are recorded in the LRS :

Ludo M failed http://68pfIo1Ic1x_course_id | 49 minutes ago (Sat, Apr 4, 2015 9:41 AM)
Ludo M answered http://68pfIo1Ic1x_course_id/5um1CntGbHe/63mpEaD7XeB | 51 seconds ago (Sat, Apr 4, 2015 10:30 AM)
avatar Ludo M experienced http://68pfIo1Ic1x_course_id/5um1CntGbHe | 53 seconds ago (Sat, Apr 4, 2015 10:29 AM)

I have 2 questions:

1 Is it normal to have http://68pfIo1Ic1x_course_id or http://68pfIo1Ic1x_course_id/5um1CntGbHe/63mpEaD7XeB and not the name of the module or question ?

2 I thought that I could see which choices made the learner and if it was correct or not ?

Here si the amswer on Articulate forums : https://community.articulate.com/discussions/articulate-storyline/xapi-tin-can-problem-with-statements

**Comment by ryansmith94** [comment]
Yes it's normal. That has been taken from the `object.id` part of the statement which has to be an IRI. However, the `object.definition.name` should also be set to human readable text (like the question). This is Storyline's responsibility as they send the statement. 

You should be able to via the `result` part of the statement.

FYI the full statement can be viewed by clicking the cog icon to the left of the statement.
