### ISSUE TITLE
Error: 'Lang' is undefined

### ISSUE THREAD

**Issue by Edcomm** [LearningLocker/learninglocker#590]
What can be causing following error?

I installed LL, was able to register user and log in. Clicking on each link within the dashboard causes following error  - 

Line: 1
Error: 'Lang' is undefined

Lang.addMessages({"en":{"reporting.create":"Create report","reporting.view":"View report","reporting.deleted":"That report has been deleted","reporting.who":"Who","reporting.did":"Did","reporting.what":"What","reporting.where":"Where","reporting.when":"When","reporting.with_result":"With result","reporting.related":"Related statements","reporting.clear":"Clear","reporting.save":"Save","reporting.query":"Query","reporting.run_query":"Run query","reporting.name":"Name","reporting.created":"Created","reporting.desc":"Description","reporting.run":"Run","reporting.view_stats":"View statements","reporting.graph":"Graph","reporting.to":"to","reporting.headings.info":"Report information","reporting.headings.learners":"Select learners","reporting.headings.verbs":"Select verbs","reporting.headings.activities":"Select activities","reporting.headings.types":"Select activity types","reporting.headings.parents":"Select parent activities","reporting.headings.groups":"Select grouping activities","reporting.headings.platforms":"Select platforms","reporting.headings.instructors":"Select instructors","reporting.headings.languages":"Select languages","reporting.headings.scales":"Scaled","reporting.headings.completion":"Success \/ Complete","reporting.headings.dates":"Select dates","reporting.scales.scaled":"Scaled","reporting.scales.raw":"Raw","reporting.scales.min":"Min","reporting.scales.max":"Max","reporting.booleans.success":"Success","reporting.booleans.completion":"Complete","reporting.dates.intro":"You can select a since date, until date or both to filter results between two dates.","reporting.dates.since":"From (Since)","reporting.dates.until":"From (Until)","reporting.placeholders.name":"Name your report","reporting.placeholders.desc":"Describe your report","exporting.title":"Exports","exporting.info":"Export information","exporting.select.report":"Select a report","exporting.select.fields":"Select fields","exporting.fields.name":"Name","exporting.fields.description":"Description","exporting.fields.created":"Created","exporting.actions.saved":"The export has been saved.","exporting.actions.save":"Save","exporting.actions.download":"Download","exporting.actions.add.field":"Add field","exporting.actions.add.export":"Add export","exporting.actions.edit":"Edit","exporting.actions.delete":"Delete","exporting.new.name":"New export","exporting.new.description":"A new export.","exporting.errors.noReport":"Must have a report.","exporting.errors.noFields":"Must have at least one field.","exporting.errors.mustSave":"You must save this new export before you can download it's result.","exporting.errors.notFound":"Export with id `:exportId` not found.","exporting.errors.reportExistence":"Report does not exist","exporting.errors.delete":"Could not delete report.","exporting.errors.undefinedKey":"`:key` is not defined.","exporting.placeholders.statementField":"Statement field name","exporting.placeholders.userField":"Your field name","exporting.placeholders.name":"Name this export","exporting.placeholders.description":"Describe this export","exporting.unknown":"Unknown","site.edit":"Edit","site.add":"Add","site.cancel":"Cancel","site.save":"Save","site.delete":"Delete","site.value":"Value","site.username":"Username","site.password":"Password","site.title":"Title","site.name":"Name","site.description":"Description","site.logo":"Logo","site.language":"Language","site.submit":"Submit","site.remove":"Remove","site.settings":"Settings","site.dash":"Dashboard","site.admin_dash":"Admin dashboard","site.logout":"Logout","site.email":"Site email","site.account":"Account settings","site.yes":"Yes","site.no":"No","site.on":"On","site.off":"Off","site.super_admin":"Super admin","site.admin":"Admin","site.plus":"Observer plus","site.observers":"Observers","site.open":"Open","site.closed":"Closed","site.details":"Details","site.register":"Register","site.login":"Login","site.forgotten_pw":"Forgotten password","site.edit_settings":"Edit settings","site.total_learners":"Total learners","site.statement_total":"Statement total","site.learner_number":"Learner number","site.activity_sources":"Activity sources","site.xapi_calls":"xAPI calls (retrival)","site.create_lrs":"Who can create new LRSs?","site.api_status":"API Status","site.registration":"Registration","site.restrict":"Restrict registration","site.claim":"Learners claim?","site.help.email":"The main contact email for this instance of Learning Locker","site.help.create_lrs":"Select which user roles can create new LRSs","site.help.api_status":"Turn on the Learning Locker API. @todo","site.help.registration":"Is user registration for the site open or closed?","site.help.restrict":"Restrict registration to a particular email domain. Just enter the domain part e.g. ht2.co.uk","site.help.claim":"Can learners' login and claim all xAPI statements that belong to them?","site.help.language":"Default language to be used when generating statements using the statement generator","site.navbar.lrs_home":"LRS home","site.navbar.other":"Other","site.navbar.none":"No LRSs available","site.navbar.lrs_list":"LRS List","site.updated":"Learning Locker details have been updated","site.welcome":"Welcome to Learning Locker","site.sure":"Are you sure?","site.roleChange":"Role successfully changed","site.hello":"hello","site.saved":"Saved successfully","site.notSaved":"Could not save.","statements.statements":"Statements","statements.generator":"Generator","statements.filter":"filter","statements.explorer":"Explorer","statements.reporting":"Reporting","statements.exporting":"Exporting","statements.analytics":"Analytics","statements.added":"Your statement has been added."},"es_ES":{"reporting.password":"Las contrase\u00f1as deben tener al menos seis caracteres y coincidir con la confirmaci\u00f3n.","reporting.user":"No podemos encontrar un usuario con ese e-mail.","reporting.token":"Este token de restablecimiento de contrase\u00f1a no es v\u00e1lido.","reporting.sent":"Recordatorio de contrase\u00f1a enviado!","reporting.reset":"Su contrase\u00f1a se ha restablecido","reporting.password_reset":"Restablecer contrase\u00f1a","reporting.password_reset_form":"Para restablecer su contrase\u00f1a, rellene este formulario","reporting.password_reset_sent":"Ha sido enviado un correo electr\u00f3nico con el restablecimiento de la contrase\u00f1a ","exporting":"exporting","site.edit":"edici\u00f3n","site.delete":"eliminar","site.username":"Nombre de usuario","site.password":"Contrase\u00f1a","site.title":"T\u00edtulo","site.name":"Nombre","site.description":"Descripci\u00f3n","site.logo":"Logo","site.language":"Idioma","site.submit":"Enviar","site.remove":"Retire","site.settings":"Ajustes","site.dash":"Dashboard","site.admin_dash":"Tablero de instrumentos de administraci\u00f3n","site.logout":"Salir","site.email":"Email sitio","site.account":"Configuraciones de la cuenta","site.yes":"S\u00ed","site.no":"No","site.on":"En","site.off":"Off","site.super_admin":"Administrador de Super","site.admin":"Administraci\u00f3n","site.plus":"Observe m\u00e1s","site.observers":"Observadores","site.open":"Abierta","site.closed":"Cerrado","site.details":"Detalles","site.register":"Registro","site.login":"Iniciar sesi\u00f3n","site.forgotten_pw":"Contrase\u00f1a olvidada","site.edit_settings":"Editar configuraci\u00f3n","site.total_learners":"Alumnos totales","site.statement_total":"Total de Declaraci\u00f3n","site.learner_number":"N\u00famero de Estudiantes","site.activity_sources":"Las fuentes de actividad","site.xapi_calls":"Llamadas xAPI (recuperaci\u00f3n)","site.create_lrs":"\u00bfQui\u00e9n puede crear nuevos LRS?","site.api_status":"Estado de la API","site.registration":"Registro","site.restrict":"Restringir registro","site.claim":"Afirman Estudiantes?","site.help.email":"El correo electr\u00f3nico de contacto principal para esta instancia de Learning Locker","site.help.create_lrs":"Seleccione los roles de usuario se pueden crear nuevos LRSs","site.help.api_status":"Encender el API Learning Locker. @pendiente","site.help.registration":"\u00bfEl registro de usuarios para el sitio es abierto o cerrado?","site.help.restrict":"Restringir el registro a un dominio de correo electr\u00f3nico en particular. Solo tiene que introducir la parte de dominio, por ejemplo, ht2.co.uk","site.help.claim":"\u00bfLos estudiantes pueden hacer login y reclamar todas las sentencias xAPI que le pertenecen?","site.help.language":"Lenguaje por defecto a utilizar al generar sentencias utilizando el generador de sentencias","site.navbar.lrs_home":"Inicio LRS","site.navbar.other":"Otros","site.navbar.none":"Ning\u00fan LRS disponible","site.navbar.lrs_list":"Listado de LRSs","site.updated":"Detalles Learning Locker han sido actualizados","site.welcome":"Bienvenido a Learning Locker","statements.statements":"Sentencias","statements.generator":"Generador","statements.filter":"filtro","statements.explorer":"Explorador","statements.reporting":"Informes","statements.analytics":"Estad\u00edsticas","statements.added":"Su sentencia ha sido a\u00f1adida"}});Lang.setLocale("en");

**Comment by ryansmith94** [comment]
Hi @Edcomm, thanks for reporting this issue. Please edit your comment to follow our [bug template](http://docs.learninglocker.net/troubleshooting/). Once you've edited your comment we'll attempt to reproduce your issue.

[Example of the template in use](https://github.com/LearningLocker/learninglocker/issues/533).

**Comment by ryansmith94** [comment]
Note: Closed because of inactivity. Will be reopened if it becomes active again.

**Comment by optimizeHIT-daanish** [comment]
This issue seems to have surfaced again. Would it be better if I create a ticket according to your template or would you prefer reopening this issue?

On build 1.11, opening Reporting and Exporting pages gives an empty page. Console lists two errors:

ReferenceError: Lang is not defined messages:1:1 at messages:1:1
ReferenceError: trans is not defined at  underscore.js line 1454 > Function:4:1
