### ISSUE TITLE
composer install (unexpected ")" in Helpers.php on line 157

### ISSUE THREAD

**Issue by samthill** [LearningLocker/learninglocker#591]
**Version**
master at 1192

**Steps to reproduce the bug**
Run through the installation process as per the guide on http://docs.learninglocker.net/installation/#requirements

After running "composer install" the following error occurs at what looks to be the end of the process:

Parse error: syntax error, unexpected ')' in C:\learninglocker\app\locker\helpers\Helpers.php on line 157

Call Stack:
    0.0000     230072   1. {main}() C:\learninglocker\artisan:0
    0.0130     862104   2. require_once('C:\learninglocker\bootstrap\start.php') C:\learninglocker\artisan:30
    0.0310    2137032   3. Illuminate\Foundation\Application->detectEnvironment() C:\learninglocker\bootstrap\start.php:51
    0.0310    2154480   4. Illuminate\Foundation\EnvironmentDetector->detect() C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:262
    0.0310    2154560   5. Illuminate\Foundation\EnvironmentDetector->detectConsoleEnvironment() C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\EnvironmentDetector.php:18
    0.0330    2296752   6. Illuminate\Foundation\EnvironmentDetector->detectWebEnvironment() C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\EnvironmentDetector.php:74
    0.0330    2296800   7. call_user_func:{C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\EnvironmentDetector.php:39}() C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\EnvironmentDetector.php:39
    0.0330    2296880   8. {closure:C:\learninglocker\bootstrap\start.php:30-51}() C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\EnvironmentDetector.php:39
    0.0330    2297152   9. spl_autoload_call() C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\EnvironmentDetector.php:32
    0.0330    2297192  10. Composer\Autoload\ClassLoader->loadClass() C:\learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\EnvironmentDetector.php:0
    0.0340    2297192  11. Composer\Autoload\includeFile() C:\learninglocker\vendor\composer\ClassLoader.php:301

Script php artisan optimize handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

**Expected behaviour**
I was not expecting an error to occur.

**Actual behaviour**
Error occurred as per the details above.

**Server information**
Windows 7 Home Premium SP1 (64bit)
WAMP Server Version 2.5
MongoDB shell version: 3.0.2
Mongo PHP: php_mongo-1.6.6-5.5-ts-vc11-x64
Node: v0.12.2
Composer version 1.0-dev (a32c91914558a3ff293d83f7b99c49f4a7931798) 2015-04-18 18:11:12
Bower: 1.4.1

**Client information**
OS: Win 7 SP1 64bit
Browser: Chrome 42+

**Comment by ryansmith94** [comment]
Hi @samthill, thanks for reporting this issue using our template. Could you please provide the version number which can be found in your copy of the VERSION file. Thanks.

**Comment by sanduhrs** [comment]
This is version 1.3.9
The error has been introduced 7 days ago in 476ba20
See https://github.com/LearningLocker/learninglocker/blame/develop/app/locker/helpers/Helpers.php#L157

**Comment by ryansmith94** [comment]
I've already fixed this for 1.3.10, but it's part of a larger tidy up that hasn't been merged into develop. Whilst the version file will contain 1.3.9, this was not actually part of 1.3.9. 1.3.9 was released on 2015-04-08 whereas this commit is from 2014-04-14.

**Comment by ryansmith94** [comment]
Please use 1.3.9 until #592 is merged into develop.
