### ISSUE TITLE
Exception is thrown editing LRS details

### ISSUE THREAD

**Issue by sanduhrs** [LearningLocker/learninglocker#600]
**Version**
`develop` at `79cd707a31` on `1.3.9`

**Steps to reproduce the bug**
* Do a fresh install
* Create an LRS
* Edit created LRS
* Press submit

**Expected behaviour**
The LRS's Title and Description should be update when changed.

**Actual behaviour**
> ErrorException (E_UNKNOWN)
>
> Argument 3 passed to Locker\Repository\Base\EloquentRepository::update() must be of the type array, none given, called in /home/sauditor/workspace/public/learninglocker/app/controllers/LrsController.php on line 115 and defined

**Server information**
`mongodb` with `eloquent`.

**Client information**
OS: `Linux 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux`
Browser: `Firefox` version `37.0.1`

**Additional information**
PHP 5.6.8

**Comment by ryansmith94** [comment]
Hi @sanduhrs, thanks for reporting this issue and following our guidelines. This has now been reproduced and fixed. The fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.10.
