### ISSUE TITLE
Exception is thrown creating new client

### ISSUE THREAD

**Issue by sanduhrs** [LearningLocker/learninglocker#603]
**Version**
`develop` at `b033f5a9e3c4789a8ad8ee008990ca878a6ab9bf` on 1.3.9 

**Steps to reproduce the bug**
* Fresh install
* Create new LRS
* Press xAPI statements
* Press Manage additional clients
* Press Create new client

**Expected behaviour**
A new client should be created

**Actual behaviour**
>ErrorException (E_UNKNOWN)
>
>Undefined variable: lrs_id

**Server information**
`mongodb` with `eloquent`.

**Client information**
OS: `Linux 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux`
Browser: `Firefox` version `37.0.1`

**Additional information**
PHP 5.6.8

**Comment by ryansmith94** [comment]
Hi @sanduhrs, thanks for reporting this issue and following our guidelines. This has now been reproduced and fixed. The fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.10.
