### ISSUE TITLE
Alert displays translation key instead of translation

### ISSUE THREAD

**Issue by sanduhrs** [LearningLocker/learninglocker#605]
**Version**
`develop` at `670bf6bece` on 1.3.9 

**Steps to reproduce the bug**
Case 1: Create new client
Case 2: Delete Client

**Expected behaviour**
Case 1: Alert should show `The client was created sucecssfully. Hurrah!`
Case 2: Alert should show `Client deleted.`

**Actual behaviour**
Case 1: Alert shows `update_key`
Case 2: Alert shows `delete_client_success`

**Server information**
`mongodb` with `eloquent`.

**Client information**
OS: `Linux 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux`
Browser: `Firefox` version `37.0.1`

**Additional information**
PHP 5.6.8

**Comment by ryansmith94** [comment]
Hi @sanduhrs, thanks for reporting this issue and following our template. This has now been reproduced and fixed. The fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.10.

Just want to say a big thanks for all your help with this release, it's really appreciated! :+1:
