### ISSUE TITLE
Problem with Dashboard, exporting and reporting page 

### ISSUE THREAD

**Issue by bakkostas** [LearningLocker/learninglocker#614]
Hi,

I have installed LL version 1.3.10 and i create a new LRS.
When i select this LRS i cant see the above pages as in issue #485

I don't now what is wrong from this pages. The statement seems to worked fine.

the operation system is ubuntu server.

Thx in advance.

**Comment by ryansmith94** [comment]
Hi @bakkostas, thanks for reporting this issue. Please edit your comment to follow our [bug template](http://docs.learninglocker.net/troubleshooting/). Once you've edited your comment we'll attempt to reproduce your issue.

[Example of the template in use](https://github.com/LearningLocker/learninglocker/issues/533).

**Comment by bakkostas** [comment]
**Version**
v1.3.10 at 1626f14

**Steps to reproduce the bug**
i create LRS.
I open it and i can see the menu in the left.
the pages dashboard is empty, the export and reporting pages there are no button to create new (something like 'Create Report' or Add export button )

**Expected behaviour**

**Actual behaviour**

**Server information**
mongo with no security

**Client information**
OS: ubuntu server
Browser: chrome version 42.0.2311.90 m

**Additional information**
