### ISSUE TITLE
Reports are only editable once without refreshing the page.

### ISSUE THREAD

**Issue by ryansmith94** [LearningLocker/learninglocker#628]
**Version**
1.4.0

**Steps to reproduce the bug**
1. Create a new report.
2. Edit the report.
3. Add an actor.
4. Save the report.
5. Change the already added actor.
6. Save the report.
7. Refresh the page.

**Expected behaviour**
Step 7 should display the actor used in step 5 because I saved again in step 6.

**Actual behaviour**
Step 7 displays the actor from step 3.

**Comment by esasgon** [comment]
Hi, 

Is this solved? I am not sure if it is the same issue, but when I try to add more than one verb to a report, only the first one is saved. If I refresh the page I can add more verbs. 

By the way, I am using version 1.12.1 of Learning Locker.
