### ISSUE TITLE
[PROXY]Cannot create super-admin. Getting Status 500 error

### ISSUE THREAD

**Issue by blumonkey** [LearningLocker/learninglocker#635]
Hello,
After **struggling for a long time** with Composer and bower due to the proxy, I was finally able to install LL. But now after registering the super-admin I get a Status 500 error.

Full Error Description: 
`Status: 500 Error: file_get_contents(https://raw.githubusercontent.com/LearningLocker/learninglocker/master/VERSION): failed to open stream: Connection refused (View:/home/blumonkey/myPages/learninglocker/app/views/layouts/sidebars/sidebar_footer.blade.php) (View: /home/blumonkey/myPages/learninglocker/app/views/layouts/sidebars/sidebar_footer.blade.php) (View: /home/blumonkey/myPages/learninglocker/app/views/layouts/sidebars/sidebar_footer.blade.php)
Whoops, looks like something went wrong.`

Yeah, myPages is my `apache2` root directory
I presume this has something to do with the proxy. Although I bypass it for localhost, LL apparently cant connect to raw.github, leaving me stuck here.

I followed a mix of [this](http://cloudboffins.com/advanced-projects/learning-locker-lrs-free-server-part-1/) and [this](http://www.jpablo128.com/how_to_install_learning_locker/) to install LL and its dependencies. (I followed a majority of the first tut, except using `apache2` instead of `nginx` and also locally as opposed to on EC2).

Do ask if you need any info.
Thanks!

**Comment by ryansmith94** [comment]
Hi @blumonkey, I appreciate you taking so much time to try to get LL going. You current issues appears to be due to Internet connectivity. I'll try to make a fix for the next version so that LL is still usable without the connectivity.

**Comment by blumonkey** [comment]
@ryansmith94 Thanks for the support. I can however go through if I replace the file_get_content with the actual value `1.4.1` This is good, but are there any more features which might not be available to me right now due to this issue? Although I could add statements using the  xAPI Statement Generator.

**Comment by ryansmith94** [comment]
@blumonkey that solution is perfectly fine, a better solution from the Learning Locker's point of view would be to wrap it in a try catch and notify the user that it's disconnected from checking updates or something similar. No you're absolutely fine to replace that without any issues, we only connect to the Internet to grab the latest version number to check that you're up to date.

**Comment by blumonkey** [comment]
@ryansmith94 Will do that.

**Comment by ryansmith94** [comment]
Awesome. You're welcome to submit a pull request with your changes. I like to get people involved via pull requests so they get some extra credit for reporting their issues and helping us solve them.
