### ISSUE TITLE
ubuntu install issue

### ISSUE THREAD

**Issue by nphoenix** [LearningLocker/learninglocker#654]
After fresh install of 1.4.2 noticed Reporting and Exporting pages without option and browser tools reporting bower not present on site.  With assistance of staff I am told an original node executable came with ubuntu - but it was being invoked instead of node.js in installer script so we had to do:

	sudo mv /usr/sbin/node /usr/sbin/node1
	sudo ln -s /usr/bin/nodejs /usr/sbin/node
	
	cd /var/www/learninglocker/public/assets/js
	sudo bower --allow-root install
	 (select the latest version of underscore)

**Comment by ryansmith94** [comment]
Thanks for reporting this, but it was fixed today in #653 ready for the next release.
