### ISSUE TITLE
Does not return more than 200 statements

### ISSUE THREAD

**Issue by dailez** [LearningLocker/learninglocker#662]
I just recognized that when having more than 200 statements (after getting the first and the second 100 statements), the more attribute is empty. It only show the "more" url for the next 100 statements, but not for the remaining n statements. In contrast, the admin dashboard shows all statements and when I manually try to get more statements by using "/data/xAPI/statements?offset=200", it returns the statements as expected.

**Comment by ryansmith94** [comment]
Hi @dailez, thanks for reporting this issue. Please edit your comment to follow our [bug template](http://docs.learninglocker.net/troubleshooting/). Once you've edited your comment we'll attempt to reproduce your issue.

[Example of the template in use](https://github.com/LearningLocker/learninglocker/issues/533).

**Comment by dailez** [comment]
Hi @ryansmith94, I will do that on Monday. But in the meantime, you could check this behavior by querying an LRS with more than 200 statement results (e.g., ... ->queryStatements(null)). The first result contains 100 statements and an "more" url link this ("/data/xAPI/statements?offset=100"). When querying this url you get the next 100 statements, but the "more" field for the url for the remaining statements is empty.

**Comment by ryansmith94** [comment]
Recreated at #663
