### ISSUE TITLE
Problem fetching more than 200 result statements (more url is empty)

### ISSUE THREAD

**Issue by dailez** [LearningLocker/learninglocker#663]
**Version**
master at 3b817ec

**Steps to reproduce the bug**
1. Add more than 200 statements
2. Query the LRS (e.g. by using the PHP TinCan library) expecting more than 200 results

**Expected behaviour**
The first result set includes 100 statements and a (more) url to get the next 100 results
Querying the LRS with the "more url" return the next 100 statements and actually should give the "more url" to the next 100 statements

**Actual behaviour**
The "more url" is empty which seems that there is no more statements, but it is (LL admin interface shows all statements)

**Server information**
{{database}} with {{authentication}}.

**Client information**
OS: Windows 7
Browser: Chrome version 43.0.2357.124 m

**Additional information**
Use of https://github.com/RusticiSoftware/TinCanPHP to store/retrieve/etc. statements

**Comment by ryansmith94** [comment]
Hi @dailez, thanks for reporting this issue and using our template, this should be fixed by #665.
