### ISSUE TITLE
Uncaught TypeError: Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by esasgon** [LearningLocker/learninglocker#664]
**Version**
branch head at one week ago on 1.5.0 version

**Steps to reproduce the bug**
I have created an LRS and I am receiving statements from another site. Then, I go to Reporting and I create a new report. In the report information I only add the verb Viewed, that is the most common on my statements, and I save the changes.

**Expected behaviour**
The expected behaviour is that Graph option should show a graph based on the statements where I could see which day the LRS has received more information  because the verb viewed is present in different days on the statements.

**Actual behaviour**
The real behaviour of the Graph is that nothing shows up, and if I check the console on the developer tools, I see the  error "Uncaught TypeError: Cannot read property 'label' of undefined" at morris.min.js.

**Server information**
I have everything installed on my laptop.

**Client information**
OS: OS X Yosemite 10.10.3
Browser: Google Chrome version 43.0.2357.81

**Additional information**
{{additionalInfo}}

**Comment by ryansmith94** [comment]
Hi @esasgon, thanks for reporting this issue and using our template. We will now try to reproduce your issue.

Reference to the Google Forums where this discussion began. https://groups.google.com/forum/#!topic/learning-locker/cK7t5FUqoek

**Comment by esasgon** [comment]
Perfect, thank you. Let me know if I can help with something :)

**Comment by ryansmith94** [comment]
No problem. Will do, thanks a lot :+1:

**Comment by ryansmith94** [comment]
Actually could you please paste a screenshot of your report and a statement that should match the report?

**Comment by esasgon** [comment]
Hello Ryan, 

this are some screenshots from my Learning Locker

![image](https://cloud.githubusercontent.com/assets/7951340/8201293/cb21c0d2-14cf-11e5-985a-3ac0e624adf0.png)

![image](https://cloud.githubusercontent.com/assets/7951340/8201322/0f89ad7a-14d0-11e5-9fdf-9dc3a6af404c.png)

![image](https://cloud.githubusercontent.com/assets/7951340/8201343/46ca6bda-14d0-11e5-8227-f06577e92d41.png)

Let me know if you have any problema because I am not sure I did it right

**Comment by ryansmith94** [comment]
Hey @esasgon that's great, can you also send me a screenshot of the "Statements" page and the content of one of the statements you expect to match your report.

**Comment by esasgon** [comment]
Hello Ryan,

sorry for the delay answering. 
This is the screenshot of the Statements page

![image](https://cloud.githubusercontent.com/assets/7951340/8249974/c418ab56-166f-11e5-87df-aefa1a35f5d5.png)

and this is the content of one of the contents

![image](https://cloud.githubusercontent.com/assets/7951340/8249994/fc6c7d84-166f-11e5-9864-d46b592872e7.png)

Le me know if you need something else ;)

**Comment by ryansmith94** [comment]
Hi @esasgon, no problem.

This is perfect, exactly what I needed, thank you very much :+1: 

Will do thanks :smile:

**Comment by ryansmith94** [comment]
I can't seem to reproduce this issue unfortunately, can you please check the following:
1. There are no spaces before or after the verb's URL in the report (see your 2nd screenshot).
2. There are no empty filters in the other report tabs. For example in "Who?" you might have accidentally left a blank actor.
3. Check your date filter in "When?" to ensure that you're not excluding the statements you expect to return.

If none of that works, please try the following:
1. Create a new report.
2. Go to "Did what?".
3. Click "Add Verb".
4. Enter "http://adlnet.gov/expapi/verbs/viewed" in the text box that appears after step 3.
5. Click "Save".
6. Click "Statements".

**Comment by esasgon** [comment]
Hello Ryan, 

thank you for answering me so fast.
I ´ve tried what you suggest, and the second option worked, so I can see the graph now. 
I have compared the old report with the new one and they are exactly the same, the only different thing is the title :( I don´t understand why the old one does not work. 
Anyway, the problem is solved, so thank you so much :)

**Comment by ryansmith94** [comment]
Hi @esasgon, you're very welcome. I'm glad that worked. Oh right, that's odd. No neither do I, something strange must have happened there. Brilliant, no worries :+1:

**Comment by Fhyo** [comment]
???
