### ISSUE TITLE
Question - Storing/accessing Data in Agent Profile API

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#670]
I'm attempting to store and retrieve information within the Agent Profile API. Is this functionality built-in to LL? If so, how do I view statements where this is being used (since it's not linked to an activity)?

**Comment by davidpesce** [comment]
Still curious on if this is a current/planned capability within LL, but I found a way to access it using:

http://adlnet.github.io/xapi-lab/

**Comment by ryansmith94** [comment]
I'm not entirely sure what you're trying to do with the Agent Profile API. The Agent Profile API does exist in LL, so what exactly are you trying to do with it?

**Comment by davidpesce** [comment]
I'm trying to view data stored within it. I can retrieve it using xapi-lab, but can't seem to with LL.

**Comment by ryansmith94** [comment]
How have you inserted it and how are you trying to retrieve it via LL?

**Comment by davidpesce** [comment]
it's inserted via the tincanlaunch plugin. I can retrieve it from LL with TinCanJS's getAgentProfile('key') method. But curious if there's a way to retrieve it within LL.

**Comment by ryansmith94** [comment]
Ahhhh if I understand you correctly, you'd like to know if there is a UI for viewing them inside LL. The answer to that question is no. However, it would be awesome if we did have something in this area.

**Comment by ryansmith94** [comment]
If this is a feature you'd like please create an issue requesting the enhancement using our [enhancement template](https://github.com/LearningLocker/learninglocker/blob/develop/contributing.md#issue-templates). You may wish to reference this issue from there.
