### ISSUE TITLE
Problems in upgrading from 1.4.1 to the latest 1.5.3

### ISSUE THREAD

**Issue by blumonkey** [LearningLocker/learninglocker#678]
I have run into the probelm of not being able to fetch more than 200 statements in my older version of LL and saw that it was fixed in newer updates ( #663 ). So I decided to update LL by following [this](http://docs.learninglocker.net/upgrading/) (using `composer`). 

At first I got a 500 error about the Encryption key being too small. I have submitted it as issue #677. I have naively fixed it, but need more info on that. After that, my older issue #635 reappeared. This was strange as @ryansmith94 fixed this in the same thread and updated the source code as well. I updated that file from the online repo. But still have the bug of not being able to fetch more than 200 statements. 

**PS:** It says in the sidebar that my version is still `1.4.1`

Whats going wrong?

**Comment by ryansmith94** [comment]
Hi @blumonkey, thanks for reporting this issue. Can you please provide the contents of your VERSION file?

**Comment by blumonkey** [comment]
@ryansmith94 I have retried the update process and this time, I emptied my composer cache. Apparently  it was installing from the cache due to connectivity issues. Although now, I am getting a new error message, with no stacktrace, when I try to access `public/index.html`. 

`Whoops, looks like something went wrong.`

 I dont even know where to start.

**Comment by ryansmith94** [comment]
Hey @blumonkey, oh right that's good news then.

Ah ok, please can you go to your "app/storage/logs/laravel.log" file, empty it and save. Then go to "public/index.html" again and paste the contents of the "laravel.log" file here.

**Comment by blumonkey** [comment]
Strangely enough, the `logs` dir is empty. I tried to see if opening `public/index.html` would create one but it didn't. :/

**Comment by ryansmith94** [comment]
Oh right ok, can you please set `debug` to `true` in "app/config/local/app.php"? Also if you followed the Composer instructions for the upgrade, please check that all of your configuration settings are as you would expect.

**Comment by blumonkey** [comment]
Got it! 

    file_put_contents(/home/blumonkey/myPages/learninglocker/app/storage/meta/services.json): failed to open stream: Permission denied

**Comment by ryansmith94** [comment]
Do you have any further details of the exception from your "laravel.log" file because that's not been thrown from LL code.

**Comment by ryansmith94** [comment]
I think you're still on version 1.4.1 too.

**Comment by blumonkey** [comment]
**laravel.log:**

    [2015-06-29 12:24:06] local.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in     /home/blumonkey/myPages/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:424
    Stack trace:
    #0 /home/blumonkey/myPages/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(424): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/home/blumonkey...', 424, Array)
    #1 /home/blumonkey/myPages/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
    #2 /home/blumonkey/myPages/learninglocker/app/locker/data/dashboards/AdminDashboard.php(63): Illuminate\Database\Eloquent\Builder->get()
    #3 /home/blumonkey/myPages/learninglocker/app/locker/data/dashboards/AdminDashboard.php(24): app\locker\data\dashboards\AdminDashboard->actorCount()
    #4 /home/blumonkey/myPages/learninglocker/app/routes.php(33): app\locker\data\dashboards\AdminDashboard->getFullStats()
    #5 [internal function]: {closure}()
    #6 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(5362): call_user_func_array(Object(Closure), Array)
    #7 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(5028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
    #8 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(5016): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
    #9 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(717): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
    #10 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(698): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
    #11 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(7738): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
    #12 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(8341): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
    #13 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(8288): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
    #14 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(10953): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
    #15 /home/blumonkey/myPages/learninglocker/bootstrap/compiled.php(659): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
    #16 /home/blumonkey/myPages/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run()
    #17 {main} [] []

>I think you're still on version 1.4.1 too. 

Nah. I have checked the VERSION file, it says `1.5.3`.

**Comment by ryansmith94** [comment]
Hey @blumonkey, I think this was only a problem for new users. Nevertheless it should be fixed as of #683 and released with v1.5.4. Thanks for reporting the issue and providing the information required to reproduce the issue.
