### ISSUE TITLE
Number of Learners does not match number of actual learners

### ISSUE THREAD

**Issue by hallshouse** [LearningLocker/learninglocker#689]
<b>Version</b>
1.6.0

<b>Steps to reproduce the bug</b>
1. Perform a new installation of 1.5.4
2. Add Client LRS's and invite users as Observers (these users will view statements in the LRS)
3. Create Tin Can activities where the Users are "mbox" the Users First and Last Names as well as email addresses should not be registered in the LearningLocker LRS (these users will use the activities)
4. Upgrade to 1.6.0
5. View the Tin Can statements in the LRS (from the LRS Home Dashboard and from the Client LRS Dashboards) Note the incorrect number of Learners.

![2015-07-08_1237](https://cloud.githubusercontent.com/assets/11246769/8576848/c3a06e40-2572-11e5-8ec1-b2139eba03ee.jpg)
![2015-07-08_1238](https://cloud.githubusercontent.com/assets/11246769/8576847/c3a03ed4-2572-11e5-99df-01fcdb3ce03c.jpg)
![2015-07-08_1239](https://cloud.githubusercontent.com/assets/11246769/8576849/c3a081d2-2572-11e5-988e-f1da4c34991f.jpg)
![2015-07-08_1243](https://cloud.githubusercontent.com/assets/11246769/8576851/c3a3d81e-2572-11e5-91e9-27d08e9818cc.jpg)
![2015-07-08_1249](https://cloud.githubusercontent.com/assets/11246769/8576850/c3a0fc02-2572-11e5-8ba4-0904baa068b1.jpg)
5. Compare number learners recorded below graph(s) with number of learners printed above graph(s)

<b>Actual Behavior</b>
Number of users identified above graph(s) seems to actually identify number of statements, when it should identify Average number of Users per day.

<b>Server Information</b>
Ubuntu 14.04.1
apache 2.4.7
php 5.5.9 (with Zend Eng. 2.5.0 and OPcache 7.0.3)
mongod 2.6.10

<b>Client Information</b>
FF, IE, Chrome, Safari (all latest)

<b>Additional Information</b>
Hosted on a self managed VPS

**Comment by daniel-abbey** [comment]
Hi @hallshouse, thanks for providing the details to reproduce this issue, this has now been reproduced and should be fixed soon.

**Comment by daniel-abbey** [comment]
Hi @hallshouse, this should be fixed by #690 and will be merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop) soon.
