### ISSUE TITLE
Login returns to login page

### ISSUE THREAD

**Issue by nekcih** [LearningLocker/learninglocker#691]
Every time I try to login, LL returns to the login page. It was working fine and then out of nowhere it started doing this. I'm wondering if it's related to something else (PHP config or something). Any suggestions?

BTW - this is v1.6.1

**Comment by nekcih** [comment]
Just discovered that this is actually an issue with my employer's web filter. The issue occurs due to the 302 redirect on login.

**Comment by ryansmith94** [comment]
Hi @nekcih, thanks for reporting the issue and closing it when it was resolved :+1:
