### ISSUE TITLE
When viewing statements via the dashboard or reports, display verb according to site lang

### ISSUE THREAD

**Issue by dennis-learningpool** [LearningLocker/learninglocker#692]
**Motive**
When viewing statements for an LRS, it can be confusing to see verbs in a language that is different from the language in the site settings. For example, when a site language setting is en-US, the statements will show only the first translation of the verb's "display" attribute, which may not be en-US.

**Result**
This enhancement will show the appropriate translation from a verb's "display" attribute, if available, or fall back to the current behavior if unavailable

**Additional information**
When using ADL's scorm wrapper, verb definitions are fetched from http://adlnet.gov/expapi/verbs - on my local learninglocker sandbox, the site lang is "en-US", but the statements only show the german display attribute for verbs.

**Comment by daniel-abbey** [comment]
Learning Locker will either use your browser's language or the first language in the language map provided by the display property.

**Comment by dennis-learningpool** [comment]
Hi @daniel-abbey, thanks for responding so quickly.

I've popped up a PR here: https://github.com/LearningLocker/learninglocker/pull/693

When I'm logged in as an admin and I view my statements via http://mysite/lrs/id/statements or http://mysite/lrs/id/reporting/id/statements my browser's language seems to be ignored, but I might be missing something. Can you take a quick look at the above PR and let me know your thoughts?

Thanks!

**Comment by daniel-abbey** [comment]
Hi @dennis-learningpool, thanks for providing the details to reproduce this issue, this has now been reproduced and should be fixed soon.
