### ISSUE TITLE
Does LearningLocker supports MySQL

### ISSUE THREAD

**Issue by sahilpurav** [LearningLocker/learninglocker#702]
Hi, I see LearningLocker populates the data in MongoDB. Is it possible for this LRS to populate all its data under MySQL only?

**Comment by flipace** [comment]
You have to use MongoDB for Learning Locker. There's not an option to switch to mysql easily at this moment.

**Comment by sahilpurav** [comment]
"If you are comfortable with various technology including: MongoDB, PHP, Composer, MySQL and xAPI and wish to host your own Learning Record Store, then this will be the option for you."

This is what I've seen on LearningLocker home page. Where does "MySQL" comes while setting up this application?

**Comment by ryansmith94** [comment]
Hi @sahilpurav, thanks for your question. As @flipace said, there isn't currently an easy way to switch to MySQL without changing a significant amount of the code.

In regards to the quote from the home page, the "MySQL" part of that should be removed as it is incorrect (thanks for referencing that here). MySQL was previously the primary database used for Learning Locker, however it had performance issues as the volume of statements increased hence our switch to MongoDB and why that was on the home page in the first place.

**Comment by ywarnier** [comment]
Could you point me to the "previous" version of LL that used to use MySQL as a primary database?
We are considering including it in Chamilo LMS, and using MongoDB would add a (complex) new requirement for users with shared hosting.

Would you accept a proper PR offering support for both?

**Comment by ryansmith94** [comment]
Hi @ywarnier the previous version is no longer available. I think we'd certainly consider accepting a PR, however, V2 will become open source soon and uses JavaScript instead of PHP.
