### ISSUE TITLE
Emails are not being sent from the system after upgrade from 1.8 to 1.10

### ISSUE THREAD

**Issue by salexfo** [LearningLocker/learninglocker#733]
Hi,

In addition to issue #732 I have found out that after the upgrade emails are not being sent from the system (verification emails + invite emails).

I've verified that postfix is running and that I can send an email via mailutils (command line:mail)

**Comment by hallshouse** [comment]
Hi All:

This was something I had also found after a fresh install 2 weeks past to 1.8. I forgot to mention this issue.
After a fresh install, I found the mail related files were non-existent (app/config/mail.php and app/config/local/mail.php). I fixed it immediately by copying them from my backup.

**Comment by ryansmith94** [comment]
Any configs inside app/config/local should have been kept if the upgrade instructions were followed. No configuration changes should be made to the ".env.php" file or files in the "app/config" directory. You should only change the ".env.local.php" file and files in the "app/config/local" directory.

**Comment by ryansmith94** [comment]
In this particular case I suspect the global config in "app/config/mail.php" had been changed. You need to write you mail config in "app/config/local/mail.php" as [documented](http://docs.learninglocker.net/installation/#configuration)

**Comment by salexfo** [comment]
That's correct. The settings had been changed. I don't know how this has happened as I have explicitly backed-up and then moved back my local dir.

**Comment by ryansmith94** [comment]
Perhaps you changed something in the global config not the local one. Not to worry though, if you can configure to the way it was using local config files (inside "app/config/local") and the ".env.local.php" file you should good to carry on as normal.

**Comment by daniel-abbey** [comment]
I can verify that after upgrading via the steps in issue [#732](https://github.com/LearningLocker/learninglocker/issues/732#issuecomment-138590660) I am still able to invite users. The "mail.php" remains untouched.

**Comment by hallshouse** [comment]
All I had done was rebuild my Dev server from scratch (Linux and all), then install LL as usual. I then created my admin user and did not receive the Activation email. I immediately went to the folders and saw there was no mail.php files. I copied both files to their respective locations and it worked fine. I did nothing else.

**Comment by daniel-abbey** [comment]
@hallshouse this is normal for a new installation and [documented on the installation page](http://docs.learninglocker.net/installation/#configuration). This issue relates to the upgrade process.

**Comment by hallshouse** [comment]
Thanks @daniel-abbey : I always knew we needed to edit the files, however, I this case, both files did not exist. My upload created them.

**Comment by daniel-abbey** [comment]
Thanks @hallshouse. The need to create the files was [introduced in v1.8.0](https://github.com/LearningLocker/learninglocker/pull/707/files#diff-7) as part of improving the dev workflow. It only applies to new installations and upgrading does not affect the mail config.

**Comment by daniel-abbey** [comment]
@salexfo can you confirm if @ryansmith94's [suggestion](issuecomment-138594162) worked? If so I can close the issue. Thanks

**Comment by salexfo** [comment]
Issue closed. Thanks
