### ISSUE TITLE
Observer users can not view LRS List

### ISSUE THREAD

**Issue by pondermatic** [LearningLocker/learninglocker#736]
**Version**
develop at 40adae0260a5f9f1d9c09931927fc44e9977f6a2 on 1.10.0

**Steps to reproduce the bug**
1. Invite users to a LRS.

**Expected behaviour**
When the user goes to `/lrs`, they should see a list of LRSs that they have been invited to.

**Actual behaviour**
The LRS list says "No LRS's available."

**Server information**
MongoDB 2.6.11 and 3.0.6
PHP 5.6.5 and 5.6.12
Windows 10 and CentOS 7.1

**Client information**
OS: Windows 10
Browser: Chrome version 45

**Additional information**
The `lrs` collection contains users with string `_id` columns. `Jenssegers\Mongodb\Query\Builder->compileWheres()` 2.0.x will convert the values in columns named `_id` or **ending** with `._id` from a string to MongoId. When users are invited to a LRS, their string `_id` is used for `lrs.users._id`.
The version of `jenssegers/laravel-mongodb` was changed from 1.4.x to 2.0.x in commit f60753f3a127496ee4e809d7d3d060d1b9b4cb86. v1.4 did not convert columns if the named ended with `._id`.

**Comment by daniel-abbey** [comment]
Hi @pondermatic, thanks for reporting this bug and using our [template](https://github.com/LearningLocker/learninglocker/blob/develop/contributing.md#issue-templates). We will now try to reproduce your issue

**Comment by hallshouse** [comment]
I was also able to reproduce the issue by:
1. Selecting an LRS instance (already created)
2. Going to the Users page and inviting a user
3. Having the user authenticate

I then logged in as my admin user, traversed to the users page, and saw the user have no LRS assigned.
I think this is the cause of the symptom.

**Comment by pondermatic** [comment]
While working on a fix for this issue, I am finding several other places where a id from one Mongo collection is referenced in another collection using a string instead of a [MongoId](http://php.net/manual/en/class.mongoid.php)/[ObjectId](http://docs.mongodb.org/manual/reference/object-id/).

Show we tackle the MongoId issue as one issue, or an issue for each model?

**Comment by daniel-abbey** [comment]
Once this current issue has been resolved, we can look into fixing the rest.

**Comment by daniel-abbey** [comment]
This issue has been solved and will not be an issue in v1.11.0. Fix provided by @pondermatic in #741
