### ISSUE TITLE
Installation - http://localhost/learninglocker/public/ returns Class 'MongoClient' not found

### ISSUE THREAD

**Issue by coreyd303** [LearningLocker/learninglocker#746]
It should first be noted that I am brand new to anything in PHP / apache2 land, I work pretty strictly in RoR, and am still rather novice over all. I finally was able to get things up-ish and running, hitting the URL  http://localhost/learninglocker/public/ lands me at a page, but I get an error

Symfony\Component\Debug\Exception\FatalErrorException
…/­vendor/­jenssegers/­mongodb/­src/­Jenssegers/­Mongodb/­Connection.php133

Class 'MongoClient' not found. 

Any help with this would be greatly appreciated, googling is walking me in circles at this point.

Thanks so much

**Comment by daniel-abbey** [comment]
Hi @coreyd303,
You need to install MongoDB as this is the database Learning Locker uses.
Please [follow our installation steps](http://docs.learninglocker.net/installation/) to get up and running.
Let us know if you encounter any problems.

**Comment by coreyd303** [comment]
@daniel-abbey I have installed installed MongoDB, and have an instance running, I followed your installation steps on the Learning Locker site to get to this point.

Thus far I have installed mongodb, php55, mcrypt, and the mongo php driver, I have run the migration as well.

**Comment by daniel-abbey** [comment]
Hi @coreyd303,
Please can you confirm the Mongo Daemon (mongod) is running. It can be found in
the 'bin' directory of your MonoDB installation.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.3.5&pv=5.1.1&source=email_footer_2] On Tue, Sep 22, 2015 at 10:13 PM, coreyd303 < notifications@github.com [notifications@github.com] > wrote:
@daniel-abbey [https://github.com/daniel-abbey] I have installed installed MongoDB, and have an instance running, I followed
your installation steps on the Learning Locker site to get to this point.

Thus far I have installed mongodb, php55, mcrypt, and the mongo php driver, I
have run the migration as well.

—
Reply to this email directly or view it on GitHub
[https://github.com/LearningLocker/learninglocker/issues/746#issuecomment-142424493] .[https://github.com/notifications/beacon/AMhkH3xNA9IAsck_bsMJ5gUpem7Wmjp4ks5o0bvjgaJpZM4GB5UY.gif]

**Comment by pondermatic** [comment]
`Class 'MongoClient' not found` sounds like the autoloader files have not been updated. Try running `composer dump-autoload`.

**Comment by pondermatic** [comment]
Whoops! The `MongoClient` class is not part of a PHP library. It is part of the MongoDB extension for PHP. You said that you installed the Mongo PHP driver. It sounds like PHP is not loading it. Check the php.ini file. You may need to add it in the extensions section.

**Comment by coreyd303** [comment]
I believe it is, below is my cli stack trace:

CODE (production)⚡ mongod
2015-09-23T10:52:14.515-0600 I JOURNAL  [initandlisten] journal dir=/data/db/journal
2015-09-23T10:52:14.515-0600 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
2015-09-23T10:52:14.529-0600 I JOURNAL  [durability] Durability thread started
2015-09-23T10:52:14.529-0600 I CONTROL  [initandlisten] MongoDB starting : pid=74925 port=27017 dbpath=/data/db 64-bit host=Coreys-MacBook-Pro.local
2015-09-23T10:52:14.529-0600 I JOURNAL  [journal writer] Journal writer thread started
2015-09-23T10:52:14.529-0600 I CONTROL  [initandlisten]
2015-09-23T10:52:14.529-0600 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
2015-09-23T10:52:14.529-0600 I CONTROL  [initandlisten] db version v3.0.6
2015-09-23T10:52:14.530-0600 I CONTROL  [initandlisten] git version: nogitversion
2015-09-23T10:52:14.530-0600 I CONTROL  [initandlisten] build info: Darwin yosemitevm.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
2015-09-23T10:52:14.530-0600 I CONTROL  [initandlisten] allocator: system
2015-09-23T10:52:14.530-0600 I CONTROL  [initandlisten] options: {}
2015-09-23T10:52:14.747-0600 I NETWORK  [initandlisten] waiting for connections on port 27017

and

~⚡ ps -ax | grep mongo
74925 ttys002    0:00.92 mongod
75080 ttys004    0:00.00 grep mongo
~⚡

**Comment by coreyd303** [comment]
@pondermatic added extension=mongo.so to php.ini, restarted apache2, having the same issue. @daniel-abbey mongod is running: 
~⚡ mongod
2015-09-23T13:50:40.609-0600 I JOURNAL  [initandlisten] journal dir=/data/db/journal
2015-09-23T13:50:40.609-0600 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
2015-09-23T13:50:40.623-0600 I JOURNAL  [durability] Durability thread started
2015-09-23T13:50:40.623-0600 I CONTROL  [initandlisten] MongoDB starting : pid=16919 port=27017 dbpath=/data/db 64-bit host=Coreys-MacBook-Pro.local
2015-09-23T13:50:40.623-0600 I JOURNAL  [journal writer] Journal writer thread started
2015-09-23T13:50:40.623-0600 I CONTROL  [initandlisten] db version v3.0.6
2015-09-23T13:50:40.623-0600 I CONTROL  [initandlisten] git version: nogitversion
2015-09-23T13:50:40.623-0600 I CONTROL  [initandlisten] build info: Darwin yosemitevm.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
2015-09-23T13:50:40.623-0600 I CONTROL  [initandlisten] allocator: system
2015-09-23T13:50:40.623-0600 I CONTROL  [initandlisten] options: {}
2015-09-23T13:50:40.637-0600 I NETWORK  [initandlisten] waiting for connections on port 27017

**Comment by daniel-abbey** [comment]
Hi @coreyd303,
Please can you echo out `phpinfo()` to see if a) the Mongo driver is being loaded and b) the location of `php.ini`.
Also, there may be multiple `php.ini` files being used as there are different versions for web and CLI.
`php -i | grep 'Configuration File'` will help locate the CLI version.
Just to be safe, it might be a good idea to include `extension=mongo.so` in both `php.ini` files.

**Comment by coreyd303** [comment]
So I found some new info based on the above and some new Google-ling, I thought it might be worth nothing that I keep seeing this show up:
PHP Warning:  Module 'mongo' already loaded in Unknown on line 0

Warning: Module 'mongo' already loaded in Unknown on line 0

I don't know if that is a useful bit of info or not?

**Comment by coreyd303** [comment]
I cannot find evidence of mongo being loaded in phpinfo(), although running php -m returns:
etc (master)⚡ php -m
PHP Warning:  Module 'mongo' already loaded in Unknown on line 0

Warning: Module 'mongo' already loaded in Unknown on line 0  <--- unsure of this???
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mhash
mongo   <--- Would indicate mondo being loaded???
mysql
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]

tried reinstalling mongo, still getting the same error. Is there a specific line I should be looking for in phpinfo() to confirm or deny mongo is being loaded? Thanks for all the help, again I am in highly uncharted waters here :)

**Comment by pondermatic** [comment]
`php -m` shows that the mongo module is definitely loaded (either by an extension in `php.ini` or compiled into PHP itself). The `Warning: Module 'mongo' already loaded in Unknown on line 0` is indeed strange. I've seen similar warnings before, but do not remember the cause.

When I run `php -i`, the following is included in the output.
```
mongo

MongoDB Support => enabled
Version => 1.6.0
Streams Support => enabled
SSL Support => enabled
                   Supported Authentication Mechanisms                   
MONGODB-CR => enabled
SCRAM-SHA-1 => enabled
MONGODB-X509 => enabled
GSSAPI (Kerberos) => enabled
PLAIN => enabled

Directive => Local Value => Master Value
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 0 => 0
mongo.ping_interval => 5 => 5
```

You should see a Mongo section In the HTML output of phpinfo(). The module sections are listed alphabetically.

**Comment by coreyd303** [comment]
Okay, so php -i looks correct:

mongo

MongoDB Support => enabled
Version => 1.6.11
Streams Support => enabled
SSL Support => enabled
                   Supported Authentication Mechanisms
MONGODB-CR => enabled
SCRAM-SHA-1 => enabled
MONGODB-X509 => enabled
GSSAPI (Kerberos) => disabled
PLAIN => disabled

Directive => Local Value => Master Value
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 1 => 1
mongo.ping_interval => 5 => 5

I am wondering if it has something to do with my file structure?? Could that be? I was struggling initially to get anything in the browser, I kept getting 404s, so I moved the learning locker folder into the default dir for apache2 ~/Library/Webserver/Documents/learninglocker, I don't know if this could be an issue? This is not where the app lived initially when I ran migrations? Could that cause a misconnect? Just trying to think of other possible issues...

Also, in digging into the mongo already loaded error, I found that it commonly comes from a redundant line in .ini files, running

~⚡ php --ini
PHP Warning:  Module 'mongo' already loaded in Unknown on line 0

Warning: Module 'mongo' already loaded in Unknown on line 0
Configuration File (php.ini) Path: /usr/local/etc/php/5.5
Loaded Configuration File:         /usr/local/etc/php/5.5/php.ini
Scan for additional .ini files in: /usr/local/etc/php/5.5/conf.d
Additional .ini files parsed:      /usr/local/etc/php/5.5/conf.d/ext-mcrypt.ini,
/usr/local/etc/php/5.5/conf.d/ext-mongo.ini

seems to only show one php.ini being loaded, I looked into the additional .ini files, and couldn't find anything, but I did find that I seem to have multiple copies of mongo.so installed:

conf.d (master)⚡ mdfind -name mongo.so
/usr/local/Cellar/php55/5.5.29_2/lib/php/extensions/no-debug-non-zts-20121212/mongo.so
/Users/coreydavis1/mongo-php-driver/mongo-php-driver-master/modules/mongo.so
/usr/local/Cellar/php55-mongo/1.6.11/mongo.so

Lastly, tried a complete fresh install, pulled everything out, and started fresh and same issue . . .

**Comment by coreyd303** [comment]
tried to rerun artisan migrate, getting this error:

php artisan migrate
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php55/5.5.29_2/lib/php/extensions/no-debug-non-zts-20121212/mongo.so' - dlopen(/usr/local/Cellar/php55/5.5.29_2/lib/php/extensions/no-debug-non-zts-20121212/mongo.so, 9): image not found in Unknown on line 0

I have a strange feeling this may be part of the problem, where would I find this line and be able to update it?

**Comment by pondermatic** [comment]
@coreyd303,

Moving the Learning Locker files would not affect migrations. They only manipulate the database.

It looks like the php mongo extension is not correctly loaded. Possible causes:
* extension not compatible with that version of PHP
* extension not the correct thread safety version
* extension not found in the directory

**Comment by daniel-abbey** [comment]
@coreyd303 If you are installing LL for the first time, which it sounds like you are, I recommend starting afresh following our [installation instructions](http://docs.learninglocker.net/installation/) which may also involve reinstalling the prerequisites.

**Comment by coreyd303** [comment]
@daniel-abbey I am installing for the first time, I have tried restarting fresh 3 times on my local and cannot get it working, I am trying one more run on a Heroku instance . . . not sure how to link the DB, Heroku requires using MongoLab for mongodbs, I got these lines from MongoLab: 

To connect using the shell:
mongo ds051853.mongolab.com:51853/heroku_6hmzclcp -u <dbuser> -p <dbpassword>

To connect using a driver via the standard URI (what's this?):
  mongodb://<dbuser>:<dbpassword>@ds051853.mongolab.com:51853/heroku_6hmzclcp

I can deconstruct them for the database.php file, but artisan migrate throws an error:

Running php artisan migrate on <instance>... up, run.8419
PHP Fatal error:  Class 'MongoClient' not found in /app/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php on line 133
Status: 500 Error: Class 'MongoClient' not found{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'MongoClient' not found","file":"\/app\/vendor\/jenssegers\/mongodb\/src\/Jenssegers\/Mongodb\/Connection.php","line":133}}

Are you familiar with how to get this working on Heroku? I am not sure how to config the connection. The app itself seemed to deploy fine to heroku, its just getting the DB and the App talking now . . .

**Comment by pondermatic** [comment]
`Class 'MongoClient' not found` means that the PHP MongoDB driver is not loaded.
http://php.net/manual/en/mongo.installation.php
http://docs.mongodb.org/ecosystem/drivers/php/

**Comment by daniel-abbey** [comment]
@coreyd303 Whilst we cannot offer support for third party systems, it is evident that your mongo driver is not being loaded. This issue would be better directed to Heroku themselves. I would suggest moving to an IaaS platform instead of a PaaS as this would give you more control over things such as the mongo and php config.

**Comment by coreyd303** [comment]
Solved: 
- added "ext-mongo": "*",  to require section of composer.json in root of /learninglocker
- $composer update

...and to deploy to Heroku, parse the URI from MongoLab
mongodb://dbuser:dbpass@host:port/dbname, and edit datebase.ini in config local
Heroku builders take care of the rest, including running migrations on deploy
