### ISSUE TITLE
Problem with 1.11.0 upgrade from 1.10.0

### ISSUE THREAD

**Issue by hallshouse** [LearningLocker/learninglocker#750]
I've just run the upgrade procedure and am getting the following error while running php artisan migrate -env=local

PHP Fatal error:  Call to undefined method MongoId::isValid() in /var/www/learninglocker/app/locker/helpers/Helpers.php on line 250

I also tried a fresh install of LL while keeping Mongo intact and got the exact same error.

**Comment by daniel-abbey** [comment]
@hallshouse Thankyou for reporting this issue. We are currently looking into it.

**Comment by ht2** [comment]
Hi @hallshouse, can you check your version of the PHP Mongo extension? Looks like this method is available from 1.5.0 up... 

http://php.net/manual/en/mongoid.isvalid.php

**Comment by hallshouse** [comment]
@ht2 Sorry about the late reply, my PHP Mongo driver is 1.4.5...
MongoDB Support => enabled
Version => 1.4.5

It's no big deal for me, I have the option to rebuild from scratch, my concern was more to verify the upgrade procedure posted in Github.

**Comment by ht2** [comment]
Yes and it's a fair point, probably not something we had checked when we introduce the method. We'll look to update the LL docs with the relevant dependencies when we are all back in on Monday. Thanks for highlighting this!

**Comment by davidpesce** [comment]
Running 1.6.5 - can confirm upgrade works properly.

**Comment by daniel-abbey** [comment]
@hallshouse The installation documentation has been updated to include MongoDB PHP driver **v1.5.x+** as a requirement. Upgrading to this version should solve your problem. Thanks for highlighting this. Please let us know if this solves your issue.

**Comment by hallshouse** [comment]
Thanks @daniel-abbey I during the weekend, I had rebuilt my server from scratch anyhow and had no issues using the installation script I had developed, so finally I did not perform the upgrade process.
