### ISSUE TITLE
CORS OPTIONS request not working

### ISSUE THREAD

**Issue by chadabaker** [LearningLocker/learninglocker#754]
**Version**
1.9.0

**Steps to Reproduce**
1. Send OPTIONS request from HTTPS application domain to HTTPS learning locker domain.
2. See that request fails due to missing header (Access-Control-Allow-Origin) 

**Expected behaviour**
Response should include "Access-Control-Allow-Origin" header

**Actual behaviour**
Response does not include header

**Server information**
CentOS, MongoDB, Basic Auth

**Client information**
OS: Windows and Mac
Browser: All
Content: Adobe Captivate 8, published for Tin Can
Content (cont): Seems to be sending requests through scormdriver.js

**Additional information**
Route configuration includes the following:
Route::options($route->getUri(), 'Controllers\API\Base@CORSOptions');

I'm not sure where the CORSOptions function is declared. Seems that it was removed in commit e1ac0d5a76a3ec415f9d12abbccb3c0ee4fe525c and not included in commit 666a7c6f6baffb399f201e796b0c19f73374d2a3. 

**Full Error**
XMLHttpRequest cannot load https://learninglocker.mydomain.com/data/xAPI/activities/state?stateId=suspen…%3A%22Chad%20Baker%22%7D&registration=7c624b02-84d0-47dc-a4a3-0ea26c5a1651. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://otp.mydomain.com' is therefore not allowed access.

**Comment by ht2** [comment]
This header is set in the https://github.com/LearningLocker/learninglocker/blob/master/app/filters.php#L25 file. It would seem to me that perhaps there is no HTTP_ORIGIN being sent to allow it to create the `Access-Control-Allow-Origin` header perhaps? Can you see if it is present in the request headers? Any cross origin request should be sending this.

**Comment by chadabaker** [comment]
Here are the request headers:

OPTIONS /data/xAPI/activities/state?stateId=bookmark&activityId=http%3A%2F%2FCourse_ID1&agent=%7B%22objectType%22%3A%22Agent%22%2C%22account%22%3A%7B%22name%22%3A%22shdrlevel90en%22%2C%22homePage%22%3A%22https%3A%2F%2Fotp-shdr.mydomain.com%22%7D%2C%22name%22%3A%22First%20Last%22%7D&registration=3a538fc8-c06c-46f7-b2d7-3e3e129e8427 HTTP/1.1
Host: learninglocker.mydomain.com
Connection: keep-alive
Access-Control-Request-Method: PUT
Origin: https://otp-shdr.mydomain.com
X-FirePHP-Version: 0.0.6
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.27 Safari/537.36
Access-Control-Request-Headers: authorization, content-type, x-experience-api-version
Accept: */*
Referer: https://otp-shdr.mydomain.com/courses/tincan/20151022-1514_mycompany_ebrochure_express_tutorial_cp8_tincan/mycompany%20eBrochure%20Express%20Tutorial%20Cp8%20TinCan.htm?endpoint=https://learninglocker.mydomain.com/data/xAPI/&auth=Basic%20ZTM5MWE4OTU1NjM1ZWE4ODk1YjUzNjRiNTE5YjY1YzlmNjZkMWQ5MjplODZjYWI2MzM4NTRmNjRmYWNlNjMyN2YxOGEyMjUxN2FlZDMxOWFk&activity_id=http://Course_ID1&grouping=http://Course_ID1&actor={%22objectType%22:%22Agent%22,%22name%22:%22First%20Last%22,%22account%22:{%22homePage%22:%22https:\/\/otp-shdr.mydomain.com%22,%22name%22:%22shdrlevel90en%22}}&registration=3a538fc8-c06c-46f7-b2d7-3e3e129e8427
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,es;q=0.6,fr;q=0.4

And the response headers ...
HTTP/1.0 200 OK
Date: Tue, 27 Oct 2015 13:25:00 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000
Vary: Accept-Encoding
Content-Encoding: gzip
Cache-Control: max-age=0, no-cache
Content-Length: 20
Connection: close
Content-Type: text/html; charset=UTF-8

I'm wondering if the OPTIONS request is even getting to the application. Looking into that now.

**Comment by ht2** [comment]
That's a good call, that doesn't look to me like an LL (or even Laravel) constructed response. Trying to think why Apache would intercept an OPTION request, check your vhost or `httpd.conf` for limits on methods allowed perhaps?

**Comment by chadabaker** [comment]
Another day of review and still not able to determine why the response does not include the CORS header(s). I see that the barryvdh/laravel-cors plugin / ServiceProvider and that there are custom configurations under the app/config/packages directory. There's also the filters.php, which was mentioned above. I'm still not getting why the routes.php seems to reference the CORSOptions function of the "Base" controller in controllers/api/ (maybe there's some magic that happens to handle that missing function call, or it's not a function reference).

On a side note, we think we've confirmed that the application is getting the request as the following additions to the Learning Locker virtual host has resolved the issue. I think this is more of a "throwing a hammer" at the problem type of solution, but maybe not.

Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Headers "authorization, content-type, x-experience-api-version"
Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
Header set Access-Control-Expose-Headers "ETag"

Hopefully these settings don't affect normal Learning Locker behavior.

**Comment by ht2** [comment]
Hi Chad, 

The ommision of the CORSOptions method is a strange one and I'm just looking at that now. It seems that was removed to make way for the `barryvdh/laravel-cors` package (which should handle all of this automatically) but I can replicate your problem and can't get it working myself (I see the same Headers returned for OPTIONS requests). For the meantime your workaround is fine and shouldn't affect operation, but I will see if I can get to the bottom of why the `laravel-cors` package isn't handling it as it should.

James

**Comment by chadabaker** [comment]
Just curious if there's any update to this issue? Our workaround hasn't presented any issues. Not sure if we should look into the original issue more on our side or wait for an official update to LL. Thanks!

**Comment by ryansmith94** [comment]
@ht2 @andrewhickey

**Comment by ht2** [comment]
Sorry guys, nothing our end. There's defintely an issue with the reference to the `CORSOptions` which we'll look to amend, but as to the actual CORS headers not been sent I'm at a loss unfortunately.

**Comment by ht2** [comment]
Could be related to https://github.com/barryvdh/laravel-cors/issues/87

**Comment by ryansmith94** [comment]
We think this is fixed in the develop branch @chadabaker 👍 it'll be released in 1.13.4 😄

**Comment by EmmanVazz** [comment]
Anyone know how to set CORS settings on V2 of this project? All the information above seems to be related to V1 of this project?
