### ISSUE TITLE
 InvalidArgumentException - Cannot redirect to an empty URL. 

### ISSUE THREAD

**Issue by salexfo** [LearningLocker/learninglocker#757]
(version 1.11.0)

Hi,
I have a bit of a non standard installation of learninglocker where the path is https://server.name/learninglocker (subdirectory and not just the domain name as it's usually the case with Laravel).

I get the error:  InvalidArgumentException - Cannot redirect to an empty URL. When I try to save changes to LRS details and in other places in the admin as well (apparently when sending POST requests).

By the way, the changes are saved. It's just that the routing doesn't work correctly (see attached)

![selection_507](https://cloud.githubusercontent.com/assets/8767588/11456089/374e68c8-9685-11e5-8973-18161f46bdb6.png)

Thanks in advance.

**Comment by ryansmith94** [comment]
Hi @salexfo, apologies that no one responded, is this resolved?

**Comment by ryansmith94** [comment]
Hi @salexfo, this issue is being closed due to inactivity and will be reopened if it later becomes active.
