### ISSUE TITLE
Statement fields available for exporting

### ISSUE THREAD

**Issue by gazzastone** [LearningLocker/learninglocker#767]
Could you please advise whether the following field is supposed to be available to be exported ?

"statement.context.contextActivities.grouping.definition.name.en-US"

Cheers

Gary

**Comment by ryansmith94** [comment]
Yes it is, but you have to specify which of the grouping context activities you're looking for by index. For example.

```
statement.context.contextActivities.grouping.0.definition.name.en-US
```

**Comment by gazzastone** [comment]
Thanks Ryan helps if I had read the spec properly i.e. "The LRS MUST return every value in the contextActivities Object as an array, even if it arrived as a single Activity Object"

Anyway Happy New Year to you and everyone involved with LearningLocker

**Comment by ryansmith94** [comment]
You're welcome. No worries :smile: 

Thanks, a happy new year to you too :+1: :balloon:
