### ISSUE TITLE
Bug: Deleting Single Document via Document API deletes ALL for an agent id

### ISSUE THREAD

**Issue by svensteudter** [LearningLocker/learninglocker#768]
### Version

1.11.0
### Steps to reproduce the bug
1. Step
   POST http://{{learning-lokcer-base-url}}/data/xAPI/agents/profile?agent={"mbox":"{{agentId}}"}&profileId="id1"
   With some JSON in body
2. Step:
   POST http://{{learning-lokcer-base-url}}/data/xAPI/agents/profile?agent={"mbox":"{{agentId}}"}&profileId="id2"
   With some JSON in body
3. Step 
   Verify that both docuemnts are stored:
   GET http://{{learning-lokcer-base-url}}/data/xAPI/agents/profile?agent={"mbox":"{{agentId}}"}
   retrurns both profileIds, i.e. ["id1","id2"]

4 Step:
Delete ONE document by specifying agent Id and profile Id, e.g.
DELETE http://{{learning-lokcer-base-url}}/data/xAPI/agents/profile?agent={"mbox":"{{agentId}}"}&profileId="id2"
### Expected behaviour

GET http://{{learning-lokcer-base-url}}/data/xAPI/agents/profile?agent={"mbox":"{{agentId}}"}
Exactly ONE document should be deleted, the other one should be still present
### Actual behaviour

Both documents are deleted
### Server information

OS: Ubuntu 14.04.03 LTS
PHP:  5.5.9-1ubuntu4.14
MongoDB:  2.6.9
### Client information

Not relevant, sending REST messages to API endpoints via POSTMAN (Chrome Plugin for sending REST messages)
### Additional information

According xApi specification:
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#agentprofapi
"Single Agent or Profile PUT | POST | GET | DELETE
Example endpoint: http://example.com/xAPI/agents/profile
Saves/retrieves/deletes the specified profile document in the context of the specified Agent."

This seems to be a bug for me. Most likely this can be fixed in https://github.com/LearningLocker/learninglocker/blob/develop/app/controllers/xapi/DocumentController.php line 139 set the signature to:
protected function completeDelete($data = null, $singleDelete = true) {

Best regards,
Sven

**Comment by ryansmith94** [comment]
Hi @svensteudter, thanks for reporting this bug. Please edit your initial comment so that it’s similar to [issue 664](https://github.com/LearningLocker/learninglocker/issues/664). Once you've edited your comment we'll attempt to reproduce your bug. In future please use the [issue template links provided in our contributing.md file](/contributing.md#issue-templates).

**Comment by ryansmith94** [comment]
Thanks for updating this @svensteudter :+1:

**Comment by ryansmith94** [comment]
Hi @svensteudter, apologies that's it's taking so long to confirm this issue.

**Comment by ht2** [comment]
Addressed in v2.0.0
