### ISSUE TITLE
LL sometimes returns application/json to GET statements requests when attachments=true

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/learninglocker#775]
**Version**
http://demo.learninglocker.net/

**Steps to reproduce the bug**
This HTTP request:
```
GET /data/xAPI/statements?attachments=true&statementId=d132f53b-9fe4-4f17-8498-069cc4a797de HTTP/1.1
Host: demo.learninglocker.net
Authorization: Basic ZDQxNmU2MjIwODEyNzQwZDM5MjJlYjA5ODEzZWJiNDE2M2U4ZWIzZTpiYzdlMGEyZWRkNWQxOTY5YjZkNzc0ZTY3OWQ0ZWI0ZTdhMzViZTEz
X-Experience-API-Version: 1.0.0
```
**Expected behaviour**
multipart/mixed content should be returned **always** when attachments are requested, even if there are no attachments to return.

**Actual behaviour**
application/json is returned

**Server information**
http://demo.learninglocker.net/

**Client information**
Postman Chrome extension, but that shouldn't make a difference. 

**Additional information**
n/a

**Comment by ht2** [comment]
demo is out of date

**Comment by garemoko** [comment]
Same question here, do you know if this is fixed by upgrading?

**Comment by ht2** [comment]
I've just tested this in the new release and I see the following when passing in `attachments=true` with no attachments present:

`Content-Type → multipart/mixed; boundary="abcABC0123'()+_,-./:=?"`

**Comment by ryansmith94** [comment]
Did that effect the attachment demo @ht2?
