### ISSUE TITLE
boundry header is bad for multipart/mixed responses

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/learninglocker#776]
**Version**
http://demo.learninglocker.net/

**Steps to reproduce the bug**
This HTTP request:
```
GET /data/xAPI/statements?attachments=true HTTP/1.1
Host: demo.learninglocker.net
Authorization: Basic ZDQxNmU2MjIwODEyNzQwZDM5MjJlYjA5ODEzZWJiNDE2M2U4ZWIzZTpiYzdlMGEyZWRkNWQxOTY5YjZkNzc0ZTY3OWQ0ZWI0ZTdhMzViZTEz
X-Experience-API-Version: 1.0.0
```
**Expected behaviour**
If the boundry header value includes reserved HTTP characters, it should be enclosed in quotes e.g. 

* boundary="abcABC0123'()+_,-./:=?"
* boundary =someboundrythatdoesntincludereservedchars

**Actual behaviour**
boundary=abcABC0123'()+_,-./:=?

**Server information**
http://demo.learninglocker.net/

**Client information**
Postman Chrome extension, but that shouldn't make a difference. 

**Additional information**
See https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

Also: https://github.com/adlnet/xAPI-Spec/pull/863

**Comment by ht2** [comment]
Demo is very out of date (1.4).

**Comment by garemoko** [comment]
@ht2 thanks for that info; do you know if this is fixed in the latest version?

**Comment by ht2** [comment]
@garemoko Do you know if this is covered in the conformance tests? They (alogn with our own unit tests) are currently passing for the latest version and the planned [v1.12](https://github.com/LearningLocker/learninglocker/pull/788) release

**Comment by ryansmith94** [comment]
@ht2 pretty certain it isn't quoted correctly (see links below). If fixing this issue breaks my [xAPI Attachment](https://github.com/ryansmith94/xapi-attach) demo, the demo will also need a PR.

https://github.com/LearningLocker/learninglocker/blob/4638696ad1c3b6252a2b6421b13a76ea98301797/app/locker/helpers/Attachments.php#L79
https://github.com/LearningLocker/learninglocker/blob/4638696ad1c3b6252a2b6421b13a76ea98301797/app/controllers/xapi/StatementIndexController.php#L51
https://github.com/LearningLocker/learninglocker/blob/4638696ad1c3b6252a2b6421b13a76ea98301797/app/tests/routes/StatementAttachmentTest.php#L7

**Comment by ht2** [comment]
Alrighty, looks like it's still an issue then. Will throw it onto the 1.12.1 heap

**Comment by garemoko** [comment]
Note: my description above is a little misleading. It's not supposed to be an actual boundary header, but rather boundary=X is part of the content type header.

**Comment by ht2** [comment]
OK, makes sense. I think I've got something to handle most cases of this here: https://github.com/LearningLocker/learninglocker/commit/7a3042e6081fa094d28606d84755d9b1bfcc16f4

**Comment by ht2** [comment]
This has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.
