### ISSUE TITLE
ob_flush() in StatementIndexController.php without a buffer to flush

### ISSUE THREAD

**Issue by ralfwiederhold** [LearningLocker/learninglocker#777]
**Version**
1.11

**Steps to reproduce the bug**
We can't reproduce this in a different installation so far. In the affected installtion it is triggered with a GET request like the following:

http://{server}/data/xAPI/statements

> activity=http://domain.com/cor-prod_9501_4711/9
> agent={"objectType":"Agent","mbox":"mailto:example@example.com","name":"example"}
> limit=1
> registration=aa516be7-a7fa-4dc4-994a-eab691f6c900
> verb=http://adlnet.gov/expapi/verbs/suspended

**Expected behaviour**
Should return something like:

> {"more":"","statements":[]}

**Actual behaviour**

> {"more":"","statements":[]}{"error":true,"success":false,"message":"ob_flush(): failed to flush buffer
. No buffer to flush","code":500,"trace":"#0 [internal function]: Illuminate\\Exception\\Handler->handleError
(8, 'ob_flush(): fai...', '\/www\/learninglo...', 133, Array)\n#1 \/www\/learninglocker\/app\/controllers
\/xapi\/StatementIndexController.php(133): ob_flush()\n#2 \/www\/learninglocker\/app\/controllers\/xapi
\/StatementIndexController.php(90): Controllers\\xAPI\\StatementIndexController->emit('{\"more\":\"\"
,\"sta...')\n#3 \/www\/learninglocker\/app\/controllers\/xapi\/StatementIndexController.php(58): Controllers
\\xAPI\\StatementIndexController->makeStatementsResult(Array, 0, Array)\n#4 [internal function]: Controllers
\\xAPI\\StatementIndexController->Controllers\\xAPI\\{closure}()\n#5 \/www\/learninglocker\/vendor\/symfony
\/http-foundation\/Symfony\/Component\/HttpFoundation\/StreamedResponse.php(109): call_user_func(Object
(Closure))\n#6 \/www\/learninglocker\/vendor\/symfony\/http-foundation\/Symfony\/Component\/HttpFoundation
\/Response.php(376): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()\n#7 \/www\/learninglocker
\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(644): Symfony\\Component\
\HttpFoundation\\Response->send()\n#8 \/www\/learninglocker\/public\/index.php(49): Illuminate\\Foundation
\\Application->run()\n#9 {main}"}

**Server Information**
Red Hat Enterprise Linux Server release 6.7 (Santiago)
Server version: Apache/2.2.15 (Unix)
PHP 5.6.16 (cli) (built: Nov 26 2015 08:01:30)

Mongodb runs on a different server that i don't know how to access

**Client Information**
A Learning Object produced by Avallain.

**Additional Information**

local.ERROR: exception 'ErrorException' with message 'ob_flush(): failed to flush buffer. No buffer to flush' in /www/learninglocker/app/controllers/xapi/StatementIndexController.php:133

There is an ob_flush() in that file but no ob_start(). The request will succeed if the ob_flush() is commented out.

The weird thing is how this issue appeared: We had this LL instance (Version 1.11) running since installation on Dec 22, but only when the Apache was restarted on Jan 25 did this issue appear. The apache was restarted to add a server-alias to the vhost configuration of LL, to my knowledge nothing else was changed

**Comment by ryansmith94** [comment]
Hi @ralfwiederhold, thanks for reporting this bug. Please edit your initial comment so that it’s similar to [issue 664](https://github.com/LearningLocker/learninglocker/issues/664). Once you've edited your comment we'll attempt to reproduce your bug. In future please use the [issue template links provided in our contributing.md file](/contributing.md#issue-templates).

**Comment by ralfwiederhold** [comment]
Hi @ryansmith94, i edited the initial comment as best I could. Sorry for the hassle. Please tell me if you need additional info. Thank you.

**Comment by ryansmith94** [comment]
Thanks @ralfwiederhold :smile: Will do :+1:

**Comment by ht2** [comment]
Hi @ralfwiederhold, can you check the value of `output_buffering` in your php config?

`<?php phpinfo(); ?>` should output what you need. I think if this value is set to 0 or "off" then the output buffer will not already have started. I believe that a typicaly value for this in a new installation of PHP would probably be 4096.

**Comment by ht2** [comment]
I have a fix which will be part of any next release. If you just want a quick fix I would consider setting the value of `output_buffering` in your php.ini to something other than "Off" or 0

**Comment by ht2** [comment]
Hi @ralfwiederhold , this has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.

**Comment by ralfwiederhold** [comment]
Hi @ht2. I checked the systems php.ini and there is no setting for "output_buffering" in there, so i would assume it will be turned off by default. This may explain why this error only appeared after the apache was restarted. As this is a customer administrated system we don't have control over the configuration and i assume that the restart triggered something that may have reset any previous php/apache configuration to some default that we are seeing there right now.

**Comment by ht2** [comment]
OK, well if you can't upgrade (which is probably your best option), then you might be able to change it in the `public/.htaccess` file. It all depends on the setup though. If you can, then try:

`php_value output_buffering 4096`

Alternatively, check the changes in the [Pull Request](https://github.com/LearningLocker/learninglocker/pull/790/files) and make the same changes on your version.

**Comment by ralfwiederhold** [comment]
Sorry, I didn't make myself clear there. We installed LL on that server but the host-server itself is adminstrated by our client. We will update LL at some point, as we want to stay as close as possible to your releases.

I was trying to say that we don't control the configuration of the host server and are not able to tell what e.g. a restart of httpd will trigger and that our clients server-admin neither seems to know that. 

Your explanation is conclusive in that output_buffering must have been enabled by some means and then disabled by the restart of httpd mentioned in my original post. 

Just SNAFU with our client at this point. ;)
Thank you!

**Comment by ht2** [comment]
Gotcha, no prob - wasn't sure if you just didn't have access to the php.ini or the ability to restart the server. As a quick fix step, I would walk your client through adding the php_ini config to their `public/.htaccess` - that will temporarily fix the problem ahead of any upgrade you perform.
