### ISSUE TITLE
Is there a way to do a webhook per LRS?

### ISSUE THREAD

**Issue by adurolms** [LearningLocker/learninglocker#778]
Like this: https://github.com/LearningLocker/learninglocker/settings/hooks/new

our client have an internal progression tracking system, so just wonder if LRS can do a webhook to other services?

E.g.: listen on statement verb
```
On 'passed' verb
Make a request with custom payload to designated service

On 'completed' verb
Make a request with custom payload to designated service
```
Seems to be not at the moment, but would we have something similar to that in the roadmap?

Thank you

**Comment by WTurunen** [comment]
This could also be used to mark lessons complete in a WordPress/Learndash environment.

**Comment by adurolms** [comment]
i come up with this: https://github.com/LearningLocker/learninglocker/pull/779

work best with persistent queue backend - i tested manually with sqs

**Comment by nadavkav** [comment]
+1 from me too

**Comment by ryansmith94** [comment]
V2 is very likely to have webhooks. Stay tuned to the [LL chat](gitter.im/LearningLocker/learninglocker) for its release in the next few months.
