### ISSUE TITLE
Dependencies conflicts from league/flysystem-aws-s3-v3

### ISSUE THREAD

**Issue by adurolms** [LearningLocker/learninglocker#780]
Hi guys,

I got runtime errors when i do some implementation of Laravel SQS queue for LL
i did some tracebacks, it turns out that Laravel 4 SQS uses `aws/aws-sdk-php: ~2.8.x`
but our LL depends on `league/flysystem-aws-s3-v3 ` which asks for `aws/aws-sdk-php:  ^3.0.0`

Should we use `league/flysystem-aws-s3-v2` for LL instead of `league/flysystem-aws-s3-v3 ` (as our LL is based on Laravel 4) ?

**Comment by ht2** [comment]
Hi @adurolms, 

Its a tricky one - we certainly wouldn't be looking to downgrade the dependency to the `league/flysystem-aws-s3-v2` version, so I would suggest you just amend the composer.json and then run composer update to pull in the new dependency. 

The only issue you would have is if you are using the S3 client to store your documents, at which point you will have the wrong version for the `app\locker\repository\File\S3V3FlyRepository.php` to use. If ou aren't using that, then you will _probably_ be ok...
