### ISSUE TITLE
Composer secure-http

### ISSUE THREAD

**Issue by ht2** [LearningLocker/learninglocker#793]
**Version**
master at be336bfc19d57a60b4b838a899a8fe49edbc7633 on v1.12.0

**Steps to reproduce the bug**
1. Attempt to `composer install`

**Expected behaviour**
Successful installation

**Actual behaviour**
```
[Composer\Downloader\TransportException]
         Your configuration does not allow connection to http://pear.php.net. See https://getcomposer.org/doc/06-config.md#secure-http for details.
```

**Additional information**
OS: any
Browser: n/a

**Comment by ht2** [comment]
Fixed in #792

**Comment by ht2** [comment]
This has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.

**Comment by mohdsadiq1** [comment]
i recently install composer 4 days ago and still having same issue , how it can be resolved please suggest

**Comment by ht2** [comment]
What version of LL are you running @mohdsadiq1? `v1.12.1` addresses this issue

**Comment by mohdsadiq1** [comment]
@ht2 , i did not get what do mean by LL , i am using ubuntu 14.04 and composer version is:  "version 1.0-dev (3942cdf8df0867d7df5706b8a3ee05f601c2aa8c) 2016-03-13 16:30:39"

when i try to run " composer install " it give me following error 

[Composer\Downloader\TransportException]                                     
  Your configuration does not allow connection to http://pear.php.net. See ht  
  tps://getcomposer.org/doc/06-config.md#secure-http for details.

**Comment by ryansmith94** [comment]
LL means Learning Locker @mohdsadiq1. Please check the VERSION file in your LL installation.

**Comment by mohdsadiq1** [comment]
i do not have Learning Locker  i am using composer to set up an existing  zf2 project

**Comment by ht2** [comment]
Ahhh! OK.... Well the fix is actually that you need to add the following in your `composer.json`...

```
"config":{
  "secure-http": false
},
```

You will then need to run `composer update` as the install may still be looking to a `composer.lock` file. That fixed it for us, but I cannot comment on any other projects. 

Good luck!

**Comment by mohdsadiq1** [comment]
it works for me ! thank you ! you save my day :+1:
