### ISSUE TITLE
undefined method MongoCollection::createIndex() at php atrisam migrate

### ISSUE THREAD

**Issue by pklinka** [LearningLocker/learninglocker#796]
**Version**
Learninglocker 1.12.1  got by git clone at 7. Mar.  

**Steps to reproduce the bug**
1. Installed Ubuntu 14.04 by netboot 
2. Followed instructions from Installation on Ubuntu by jpablo128 (http://www.jpablo128.com/how-to-install-learning-locker/) but did not do it in a LXC-Contianer because I made an own virtual machine for LL
3. Got mongodb 2.6.11 with php-extension showing at php --ini
4. at composer install, I had an errror that curl is not present, guide installs only curl, not php5-curl, after install php5-curl, composer installed
5. made DB config files, jpablo128 describes a different file in his guide, I created/edited /var/www/learninglocker/app/ config/database.php and /var/www/learninglocker/app/config/local/database.php looking like this:

`<?php

return [
  'fetch' => PDO::FETCH_CLASS,
  'default' => 'mongodb',
  'connections' => [
                'mongodb' => [
        'driver'   => 'mongodb',
        'host'     => 'localhost',
        'port'     => 27017,
        'username' => 'learnlockuser',
        'password' => 'mypwd',
        'database' => 'learninglocker' // Default name (removing this makes Travis fail).
    ],
        ],
        'migrations' => 'migrations',
];`

**Actual behaviour**
Error at php artisam migrate
php artisan migrate 
Migration table created successfully.
All finished, hopefully!
All finished, hopefully!Migrated 0 attachments.
All finished, hopefully!
Foreign id values in client collection converted from string to MongoId.
PHP Fatal error:  Call to undefined method MongoCollection::createIndex() in /var/www/learninglocker/app/database/migrations/2015_12_23_093122_add_stored_to_statement_root.php on line 20
Status: 500 Error: Call to undefined method MongoCollection::createIndex(){"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method MongoCollection::createIndex()","file":"\/var\/www\/learninglocker\/app\/database\/migrations\/2015_12_23_093122_add_stored_to_statement_root.php","line":20}}

**Additional information**
OS: Ubuntu 14.04
MongoDB 2.6.11
php --ini
Configuration File (php.ini) Path: /etc/php5/cli
Loaded Configuration File:         /etc/php5/cli/php.ini
Scan for additional .ini files in: /etc/php5/cli/conf.d
Additional .ini files parsed:      /etc/php5/cli/conf.d/05-opcache.ini,
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-curl.ini,
/etc/php5/cli/conf.d/20-json.ini,
/etc/php5/cli/conf.d/20-mcrypt.ini,
/etc/php5/cli/conf.d/20-mongo.ini,
/etc/php5/cli/conf.d/20-readline.ini

Any ideas?

**Comment by ryansmith94** [comment]
Sounds like the PHP Mongo Driver might not be installed perhaps? Any thoughts @ht2 @andrewhickey?

**Comment by pklinka** [comment]
Thanks for the reply!

I tthink the driver is installed as can see in the output of php --ini at the end
root@xapi:/var/www/learninglocker# php --ini
Configuration File (php.ini) Path: /etc/php5/cli
Loaded Configuration File:         /etc/php5/cli/php.ini
Scan for additional .ini files in: /etc/php5/cli/conf.d
Additional .ini files parsed:      /etc/php5/cli/conf.d/05-opcache.ini,
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-curl.ini,
/etc/php5/cli/conf.d/20-json.ini,
/etc/php5/cli/conf.d/20-mcrypt.ini,
**/etc/php5/cli/conf.d/20-mongo.ini,**
/etc/php5/cli/conf.d/20-readline.ini

root@xapi:/var/www/learninglocker# **cat /etc/php5/cli/conf.d/20-mongo.in**i
**extension = mongo.so**

it was installed with apt-get install php5-mongo along with several other products 
jpablo128 guide install this with this command
apt-get install curl nano apache2 php5 php5-mongo php5-mcrypt git node npm mysql-server postfix
and so did I

**Comment by ht2** [comment]
Hi @pklinka, could you do a `phpinfo()` and check the version of that driver?

**Comment by pklinka** [comment]
mongo
MongoDB Support	enabled
Version 	1.4.5
SSL Support 	enabled
Streams Support 	enabled

Directive	Local Value	Master Value
mongo.allow_empty_keys	0	0
mongo.chunk_size	262144	262144
mongo.cmd	$	$
mongo.default_host	localhost	localhost
mongo.default_port	27017	27017
mongo.is_master_interval	15	15
mongo.long_as_object	0	0
mongo.native_long	0	0
mongo.ping_interval	5	5

**Comment by ht2** [comment]
Looks like the createIndex method wasn't added until [1.5.0](http://php.net/manual/en/mongocollection.createindex.php). 

I would strongly recommend using a newer version of that driver, the current release is [1.6.12](https://github.com/mongodb/mongo-php-driver-legacy/releases) and [1.4.5](https://github.com/mongodb/mongo-php-driver-legacy/releases/tag/1.4.5) was released in 2013.

**Comment by ht2** [comment]
Just to follow up, using PECL it should just be a matter of `pecl install mongo` and then add the extension to your php.ini.

Whilst you are in the process of setting up, I would also _strongly_ recommend using Mongo v3.x+ as 2.6 is now slightly outdated and you will not have access to a lot of the aggregation features.

**Comment by pklinka** [comment]
Thank you very much!!!

I had to do the following steps:
apt-get install php-pear
apt-get install php5-dev
pecl install mongo
service apache2 restart

php artisan migrate
0 statements total
Migrated: 2015_12_23_093122_add_stored_to_statement_root

This looks good!
I will continue with Apache setup

**Comment by nadavkav** [comment]
Thanks you @ht2 ! it help me too :smile:
