### ISSUE TITLE
error 500 when sending multipart/mixed with text after the closing boundary

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/learninglocker#800]
**Version**
1.12.1

**Steps to reproduce the bug**
POST /data/xAPI/statements HTTP/1.1
Host: locker.example.com
Authorization: Basic <Auth>
X-Experience-API-Version: 1.0.2
Content-Type: multipart/mixed; boundary=++++++
Cache-Control: no-cache
Postman-Token: 75686f5a-4170-a05b-5dd9-3c8084455759

--++++++

Content-Type:application/json
[
    {
        "id": "03969cc5-61e8-4b8c-bb56-a67db054e77d",
        "actor": {
            "mbox": "mailto:alid_email_address@example.com"
        },
        "verb": {
            "id": "http://example.com/verb-id"
        },
        "object": {
            "id": "http://example.com/activity-id"
        }
    }
]
--++++++--foobar

**Expected behaviour**
No error - statement is saved

**Actual behaviour**
Error 500

**Additional information**
The problem is here:
https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/helpers/Attachments.php#L27

This assumes that the text after the last boundary will be '--' but actually it could be any string starting with '--'. 

This fixes the issue:

```
if (substr($part,0,2) == "--") break;
```

**Comment by garemoko** [comment]
Watershed always uses multipart/mixed when forwarding statements regardless of if there are attachments.

**Comment by ryansmith94** [comment]
Do you have a stack trace from the error?

**Comment by garemoko** [comment]
{
  "error": true,
  "success": false,
  "message": "Undefined offset: 1",
  "code": 500,
  "trace": "#0 /var/www/learninglocker/app/locker/helpers/Attachments.php(35): Illuminate\\Exception\\Handler->handleError(8, 'Undefined offse...', '/var/www/learni...', 35, Array)\n#1 /var/www/learninglocker/app/controllers/xapi/StatementStoreController.php(32): Locker\\Helpers\\Attachments::setAttachments('multipart/mixed...', '--++++++?Conten...')\n#2 /var/www/learninglocker/app/controllers/xapi/StatementStoreController.php(101): Controllers\\xAPI\\StatementStoreController->getParts()\n#3 /var/www/learninglocker/app/controllers/xapi/StatementStoreController.php(66): Controllers\\xAPI\\StatementStoreController->createStatements(Array)\n#4 /var/www/learninglocker/app/controllers/xapi/StatementController.php(73): Controllers\\xAPI\\StatementStoreController->store(Array)\n#5 /var/www/learninglocker/app/controllers/xapi/BaseController.php(45): Controllers\\xAPI\\StatementController->store()\n#6 [internal function]: Controllers\\xAPI\\BaseController->selectMethod()\n#7 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)\n#8 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\\Routing\\Controller->callAction('selectMethod', Array)\n#9 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\\Routing\\ControllerDispatcher->call(Object(Controllers\\xAPI\\StatementController), Object(Illuminate\\Routing\\Route), 'selectMethod')\n#10 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'Controllers\\xAP...', 'selectMethod')\n#11 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()\n#12 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)\n#13 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))\n#14 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#15 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#16 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#17 /var/www/learninglocker/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#18 /var/www/learninglocker/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(51): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Asm89\\Stack\\Cors->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 /var/www/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#23 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#24 /var/www/learninglocker/public/index.php(49): Illuminate\\Foundation\\Application->run()\n#25 {main}"
}

**Comment by ryansmith94** [comment]
I think the actual problem here is that there aren't two new lines between the headers and body of the part.

**Comment by ryansmith94** [comment]
```
--++++++
Content-Type:application/json

[
{
"id": "03969cc5-61e8-4b8c-bb56-a67db054e77d",
"actor": {
"mbox": "mailto:alid_email_address@example.com"
},
"verb": {
"id": "http://example.com/verb-id"
},
"object": {
"id": "http://example.com/activity-id"
}
}
]
--++++++--
```

**Comment by ryansmith94** [comment]
Works fine for me if there are two new lines.

**Comment by garemoko** [comment]
@ryansmith94 thanks. Any thoughts on why not having the new line is a problem?

**Comment by garemoko** [comment]
NVM i see it.

**Comment by garemoko** [comment]
Ok, so i've got to the point where I've confirmed that Watershed is sending new lines, but I'm also definitely getting the error. I can't replicate in postman, but I do note that Watershed uses /r/n for new lines whereas postman just uses /n.

**Comment by garemoko** [comment]
I can also replicate the error message by removing -- from the last boundary; looking into that.

**Comment by ryansmith94** [comment]
"\r\n" shouldn't be a problem I don't think unless they're mixed with only "\n" in some cases.

**Comment by garemoko** [comment]
The error also occurs if you put a new line after the final boundary.

**Comment by garemoko** [comment]
From RFC 1341 "implementations should ignore anything that appears before the first boundary or after the last one."

**Comment by ryansmith94** [comment]
Is that the latest RFC?

**Comment by garemoko** [comment]
It's the one referenced in xapi at least

**Comment by garemoko** [comment]
The content after the final boundary seems to be what's breaking with the connection with Watershed. I've updated the initial issue with details of that actual problem and a code sample that fixes the issue. I've confirmed the issue is resolved in Postman and in Watershed (although now I'm hitting another issue with voiding statements - I'll investigate and raise this shortly.)

**Comment by ryansmith94** [comment]
Thanks for the fix.

**Comment by ryansmith94** [comment]
For anyone else viewing this issue. This has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.
