### ISSUE TITLE
BaseDashboard.php exception: invalid operator '$size'

### ISSUE THREAD

**Issue by woutertenbosch** [LearningLocker/learninglocker#801]
**Version**
master at 627be8f on 1.12.1

**Steps to reproduce the bug**
1. Register the first user on LearningLocker
2. Graph on the dashboard is not working

**Expected behaviour**
Expected an empty graph instead of an Mongo error.

**Actual behaviour**
```
error:
file: "/var/learninglocker/app/locker/data/dashboards/BaseDashboard.php"
line: 221
message: "mongodb:27017: exception: invalid operator '$size'"
type: "MongoResultException"
```

**Additional information**
OS: Ubuntu 14.04 x64
Browser: Google Chrome 49

**Comment by ryansmith94** [comment]
Hi @woutertenbosch, thanks for reporting this bug and using our [template](/contributing.md#issue-templates). We will now try to reproduce your issue.

**Comment by ht2** [comment]
Sounds like out of date Mongo. Are you running 2.4.x? The latest versions of LL actually require at least 2.6.x but we now recommend 3.x.

**Comment by ryansmith94** [comment]
Thanks @ht2, surprised I didn't suggest that when I replied.

**Comment by woutertenbosch** [comment]
Yep, I was running an old version of Mongo. Thanks @ht2
