### ISSUE TITLE
Can't implement elasticache as session driver

### ISSUE THREAD

**Issue by salexfo** [LearningLocker/learninglocker#807]
Hi,
I have used this package:
https://github.com/atyagi/elasticache-laravel

To implement elasticache as a session driver for our deployment on AWS (LL 1.12.1) to make it a HA deployment (tried to use it instead of NFS).

I have followed the instructions per the link above (changed the "connection" variable to our elasticache address including port on app/session.php as well as the "driver" to elasticache)
but for some reason now I can't login to the system. The error log does not provide any information, and once I send the post data of the login form I'm just taken again to the login page.

Any ideas?

**Comment by ryansmith94** [comment]
Hi @salexfo, thanks for reporting this issue. Please edit your initial comment so that it’s similar to [issue 664](https://github.com/LearningLocker/learninglocker/issues/664). Once you've edited your comment we'll attempt to reproduce your bug. In future please use the [issue template links provided in our contributing.md file](/contributing.md#issue-templates).

**Comment by salexfo** [comment]
Version:
11.12.1

Steps to reproduce the bug:
Install via composer per the installation instructions the laravel elastic cache driver:
 https://github.com/atyagi/elasticache-laravel

on app/config/session.php:
set  'driver' => 'elasticache',
and 
'connection'=> (your elasticache URL with port)

add 'Atyagi\Elasticache\ElasticacheServiceProvider' to the providers array on app/config/app.php

try to login. You'll see the page refresh but without any login.

Expected behaviour:
Use as usual in an HA environment.

Server information:
m3.xlarge machine on AWS

**Comment by ryansmith94** [comment]
What version of elasticache did you install @salexfo?

**Comment by salexfo** [comment]
@ryansmith94 memcached. The PHP extension I've installed for this is from the remi repo:
php56-php-pecl-memcached-2.2.0-4.el6.remi.x86_64

**Comment by ryansmith94** [comment]
Sorry @salexfo, I meant what version of [atyagi/elasticache-laravel](https://github.com/atyagi/elasticache-laravel) did you install via Composer?

**Comment by salexfo** [comment]
@ryansmith94  "atyagi/elasticache-laravel": "~1.1"

**Comment by ryansmith94** [comment]
@ht2 @andrewhickey anyway we can try to reproduce this? The [atyagi/elasticache-laravel](https://github.com/atyagi/elasticache-laravel) package is no longer maintained, so it might be an issue with that package rather than LL.

**Comment by ht2** [comment]
Not something we actively use unfortunately - I would suggest the [Laravel IRC channel](http://laravel.io/chat) to see if there are any known issues with 4.2 + Elasticache

**Comment by salexfo** [comment]
@ht2 thanks for the tip.
Switched to this package:
https://github.com/SpartzInc/elasticache-laravel/tree/1.x

and it works now.

**Comment by ryansmith94** [comment]
Awesome! Thanks for the update @salexfo 👍
