### ISSUE TITLE
Clockwork directory takes a few GB of space

### ISSUE THREAD

**Issue by salexfo** [LearningLocker/learninglocker#808]
Version:
1.12.1

Hi,
I was wondering whether the app/storage/clockwork should bloat this way or not? 
We have a lot of statements in our mongo db so I was wondering is it just used as a caching mechanism?

Running php artisan cache:clear does not clear this directory

**Comment by ryansmith94** [comment]
Clockwork isn't something I'm familiar with or associate with LL, so this may have been something you installed with [SpartzInc/elasticache-laravel](https://github.com/SpartzInc/elasticache-laravel), from your earlier resolution to #807 @salexfo.

**Comment by ht2** [comment]
@ryansmith94 I've added it with the last update, its a debugging tool that doesn't require HTML injected into the page.

It is used for debugging @salexfo and that folder simply fills up with caches and logs etc, pretty sure you can clear it out whenever you want but by the sound of it you have debugging turned on through app.php -> debug, hence lots of debugging information is being stored. I think if debug is false, then clockwork doesn't listen or log anything.

**Comment by ht2** [comment]
For reference: https://github.com/itsgoingd/clockwork

**Comment by ryansmith94** [comment]
Ah right thanks @ht2, was unaware of that change.

**Comment by ryansmith94** [comment]
I think the debug option is an issue our end @ht2, we need to set it to false in the default ["app.php" file](https://github.com/LearningLocker/learninglocker/blob/develop/app/config/app.php).

**Comment by ht2** [comment]
I think it's fine to suggest that it would be enabled for initial deployment, all configs should really be placed in their own `config/local/...` files anyway if following the docs.

**Comment by ryansmith94** [comment]
To fix this issue in the meantime @salexfo, please add a "app.php" file to the "app/config/local" directory in your Learning Locker installation with the following contents:

```php
<?php
return [
  'debug' => false
];
```

**Comment by ryansmith94** [comment]
After some discussion, we've decided to leave the default config as it is. However, I'll be updating the documentation tomorrow with a note about this issue and I'll leave it open until that update is complete. Thanks for reporting the issue @salexfo 👍

**Comment by salexfo** [comment]
@ryansmith94 @ht2 thanks for the info. Trying to add the code above to app/config/local/app.php

**Comment by ht2** [comment]
Feel free to flush that folder too (although you may want to keep the `.gitignore`) - how many files were in it to get to GBs?!
