### ISSUE TITLE
Problem with clients in the LRS

### ISSUE THREAD

**Issue by caperneoignis** [LearningLocker/learninglocker#809]
I'm having two separate issues, that may be linked. 
I'm getting the error Oops. "Something went wrong. The client has not been deleted." I also noticed a client account did not work, till I deleted it and recreated it. 
**Version**
1.12.1

**Steps to reproduce the bug**
1. Made a new account on a separate LRS in LL and received the same error
2. Also noticed, when I first added another LMS to the LRS the statements were not being stored. After I deleted the client and recreated it with a different name. The statements started to get loaded. 

**Expected behaviour**
When giving the xapi plugin a username and password from LL, should allow the statements to be stored. Also when deleting a client should get a message saying it was achieved. 

**Actual behaviour**
Error when deleting account. Statements did not get automatically entered when giving the xapi plugin the username and password supplied by LL, unless new client account is created. 

**Additional information**
OS: CentOS
Browser: Chrome version 49.0.2623.112
Running MongoDB version db version v2.6.11
PEAR Version: 1.10.1
PHP Version: 5.6.18
Zend Engine Version: 2.6.0
php driver MongoDB Version => 1.6.12

**Comment by ryansmith94** [comment]
Hi @caperneoignis, thanks for reporting this bug and using our [template](/contributing.md#issue-templates). We will now try to reproduce your issue.

Can you test this on the LL side @ht2? If the cloud LRS is on 1.12.1 I can try to reproduce it on there.

**Comment by caperneoignis** [comment]
I should also mention, three accounts existed before the update to 1.12.1. However, account A was already receiving statements and was working on both versions. Account B was created the same time as account A but did not start receiving statements till yesterday. Did the update for the database get rid of unused client accounts? Figured this part may be important.

**Comment by ryansmith94** [comment]
Hmmm that's very odd, there might have been a migration problem for clients between versions.

**Comment by caperneoignis** [comment]
That was what I was thinking also, when I started thinking back to when I created the clients. I just know, it took a while to trouble shoot, because this is an outside server so we kept thinking it was an SSL issue. Then I noticed the data coming in, but not being stored, so I created another LRS and had the LMS start reporting to that. That is when I saw the statements start coming in, and then went back and deleted the original client account and recreated it.  Then everything started working. So it may have been a migration issue. I was really hoping to get some form of error telling me the server was rejecting the statements for whatever reason.

**Comment by ryansmith94** [comment]
Definitely sounds like a migration issue.

**Comment by caperneoignis** [comment]
On which side? The server side, or the LMS side?

**Comment by ryansmith94** [comment]
Perhaps [this code comment](https://github.com/LearningLocker/learninglocker/blob/develop/app/database/migrations/2015_09_15_075532_client_foreign_ids.php#L18) isn't true @ht2

**Comment by ryansmith94** [comment]
The LRS would have sent an error message back saying there was a problem with the credentials @caperneoignis.

**Comment by caperneoignis** [comment]
@ryansmith94 any chance in the future, we can get that error message dumped locally as well? Maybe in the Apache web log? Because they didn't see anything in the web logs on the LMSs side. But that is a feature request. Thank you though for your help, I do appreciate it.

**Comment by ryansmith94** [comment]
If you have debugging turned on in LL (see #808), it probably was logged. I can't speak for the LMS, it would be their job to display errors sent back from LL in response to requests.

**Comment by caperneoignis** [comment]
@ryansmith94 gotcha, I'll look into that, but since everything is working right now, I'll probably leave it off. But It is nice to know where to go to turn it on. Thanks again.

**Comment by ryansmith94** [comment]
Ok, you're welcome @caperneoignis 😄

**Comment by ht2** [comment]
@ryansmith94 
Here's the mutator: https://github.com/LearningLocker/learninglocker/blob/develop/app/models/Client.php#L38

Hasn't been a problem for anyone else migrating, must be something else happening I think

**Comment by ryansmith94** [comment]
Ok the issue must be somewhere else then, but I definitely feel like this is a migration issue.

**Comment by ryansmith94** [comment]
Had a look around and I can't spot anything obviously wrong, I think we'd need more debugging info. Which version of LL did you upgrade from to get to v1.12.1 @caperneoignis?

**Comment by caperneoignis** [comment]
V1.11 not sure the exact value other then 1.11 I did the initial install late January early February from github.

**Comment by ryansmith94** [comment]
Ok thanks @caperneoignis

**Comment by caperneoignis** [comment]
Oh, also the initial setup was for development, and then I rolled over to production for the update to 1.12.1, when I was doing the migration.

**Comment by ryansmith94** [comment]
I think these two issues might have been fixed by #841 and #831 in the last two releases (v1.13.3 and v1.13.2). If that's not true @caperneoignis, please let me know and I'll reopen this issue.

**Comment by caperneoignis** [comment]
Nope you are correct, I have not seen any issues after updating. It worked flawlessly.

**Comment by ryansmith94** [comment]
Brilliant thanks for letting me know @caperneoignis 👍
