### ISSUE TITLE
Installed Learning Locker on AWS EC2

### ISSUE THREAD

**Issue by Virtualserve** [LearningLocker/learninglocker#810]
Hi,
Sorry if I have posted this in the wrong section, but I am completely new to Learninglocker and unbuntu
I have followed the installation guide produced by Cloudboffins for AWS install using ubuntu.

I do not believe that there were any issues when installing LearningLocker but I have the following 
initial issues
It seems to be running incredibly slow 2 mins to load admin page but this could be due to issues on start up.
version 1.12.1 installed using composer

However I do not believe that there were any issues when installing Learning locker but I have the following initial issues

Admin Dashboard 
this is not loading have spinning wheel /assets/img/ajax-loader.gif
When in developer mode I can see the following failed to load //xxxx/site/graphdata?graphStartDate=2016-04-22&graphEndDate=2016-04-29+23%3A59 responded with status 500 internal server error.

![image](https://cloud.githubusercontent.com/assets/15179795/14915178/bafa317a-0e08-11e6-8f1a-392c9daeb664.png)

Graphs not loading LRS reports re localization js file being in the incorrect place, copied the localization file to /var/www/learninglocker/public/js-localization/ this resolved the reporting issue.
Found the solution

Every link on the left side Dashboard , reporting etc takes 2Mins to load.

I am assuming that I have made a mistake in installing learninglocker but do not have enough experience to track down the issues if you can point me in the right direction to look at resources this would be very helpful

**Comment by ht2** [comment]
Re speed: I would double check the indexes you have on the collections. Please refer to my blog post here: https://learninglocker.net/blog/learning-locker-v1-12/

**Comment by ryansmith94** [comment]
Hi @Virtualserve, if you can't improve the speed using the blog post, it will help us to know what the Server Error was? This might be returned in the response from the request to "//xxxx/site/graphdata?graphStartDate=2016-04-22&graphEndDate=2016-04-29+23%3A59". If not, you can check the logs in the "app/storage/logs" and the "app/storage/clockwork" directories.

**Comment by Virtualserve** [comment]
The error reported from the developer mode of Chrome showed resource: the server responded with a status of 500 (Internal Server Error).  I will read the blog that you have just sent.

Regards

Steve

**Comment by ht2** [comment]
@Virtualserve your logs (app/storage/logs) will go into much better detail as to the actual 500 error, but my guess is MongoTimeout

**Comment by Virtualserve** [comment]
Hi,

Ran the scripts against the database as requested

The logs
In the clockwork folder there are hundreds of
141619xxxxx.xxxx.1494456xxxx.jason

In the storage/logs there are two days of logs in today's there is one error

Local.ERROR: exception 'MongoResultException' with message 'local
host:27017: exception invalid operator '$size" in/var/www/learning
locker/app/data/dashboards/BaseDashboard.php:221

So I presume that this is causing the issue is there a stand setting for
this.

Many thanks for your help.

Regards

Steve

On Friday, 29 April 2016, Ryan Smith <notifications@github.com> wrote:

> Hi @Virtualserve <https://github.com/Virtualserve>, if you can't improve
> the speed using the blog post, it will help us to know what the Server
> Error was? This might be returned in the response from the request to
> "//xxxx/site/graphdata?graphStartDate=2016-04-22&graphEndDate=2016-04-29+23%3A59".
> If not, you can check the logs in the "app/storage/logs" and the
> "app/storage/clockwork" directories.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LearningLocker/learninglocker/issues/810#issuecomment-215693520>
>


-- 

Steve Smith





(: 07462599556
(: 01273 387778

* *steve@virtualserve.biz* <steve@virtualserve.biz>

ü*    http://www.virtualserve.biz <http://www.virtualserve.biz/>*



*Confidentiality Notice*

*This email and any attachments are confidential and legally privileged and
intended solely for the use of the individual or entity to whom they are
addressed. If you are not the named addressee, please telephone +44(0) 1273
387778 Views expressed are those of the individual sender, except where
stated as those of Virtualserve. There will be no liability for damage
arising in any way from receipt or use thereof.*

**Comment by ryansmith94** [comment]
Looks like an issue with the Mongo version to me @ht2.

**Comment by ryansmith94** [comment]
What version of Mongo and what version of the Mongo driver did you install @Virtualserve? There's a chance that the tutorial you followed uses an older version that doesn't support $size.

**Comment by ht2** [comment]
I would concur; $size was introduced in Mongo 2.6, so you should be running that at least. I would strongly recommend v3.0+ anyway.

**Comment by ht2** [comment]
https://docs.mongodb.org/manual/reference/operator/aggregation/size/

**Comment by Virtualserve** [comment]
Hi,

MongoDb shell is 2.4.14 so l am completely out.

I will look to upgrade the mongodb.

Many thanks for your very speedy responses

Have a good weekend

Regards

Steve


On Friday, 29 April 2016, James Mullaney <notifications@github.com> wrote:

> I would concur; $size was introduced in Mongo 2.6, so you should be
> running that at least. I would strongly recommend v3.0+ anyway.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LearningLocker/learninglocker/issues/810#issuecomment-215726670>
>


-- 

Steve Smith





(: 07462599556
(: 01273 387778

* *steve@virtualserve.biz* <steve@virtualserve.biz>

ü*    http://www.virtualserve.biz <http://www.virtualserve.biz/>*



*Confidentiality Notice*

*This email and any attachments are confidential and legally privileged and
intended solely for the use of the individual or entity to whom they are
addressed. If you are not the named addressee, please telephone +44(0) 1273
387778 Views expressed are those of the individual sender, except where
stated as those of Virtualserve. There will be no liability for damage
arising in any way from receipt or use thereof.*

**Comment by Virtualserve** [comment]
Hi James,

Do you have a link to a document where l can start from fresh ensuring that
l am using the latest software as the link was back in 2014.

Regards

Steve


On Friday, 29 April 2016, James Mullaney <notifications@github.com> wrote:

> Closed #810 <https://github.com/LearningLocker/learninglocker/issues/810>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LearningLocker/learninglocker/issues/810#event-645627576>
>


-- 

Steve Smith





(: 07462599556
(: 01273 387778

* *steve@virtualserve.biz* <steve@virtualserve.biz>

ü*    http://www.virtualserve.biz <http://www.virtualserve.biz/>*



*Confidentiality Notice*

*This email and any attachments are confidential and legally privileged and
intended solely for the use of the individual or entity to whom they are
addressed. If you are not the named addressee, please telephone +44(0) 1273
387778 Views expressed are those of the individual sender, except where
stated as those of Virtualserve. There will be no liability for damage
arising in any way from receipt or use thereof.*

**Comment by ht2** [comment]
Not really unfortunately Steve, setting up a full system is quite an involved process (as the original doc probably showed!). You would want to be looking at instructions on how to install Mongo on Linux which there should be some decent documentation for.

If you are planning to use this in any production sense, then I would probably advise you look to proffesional help in setting up and maintaining it. Running an LRS at scale is not for the faint hearted! You can have a read at what our full stack looks like here: https://learninglocker.net/blog/lrs-enterprise-hosting/

**Comment by Virtualserve** [comment]
Many thanks for the advice,  have a good weekend.

Regards

Steve

On Friday, 29 April 2016, James Mullaney <notifications@github.com> wrote:

> Not really unfortunately Steve, setting up a full system is quite an
> involved process (as the original doc probably showed!). You would want to
> be looking at instructions on how to install Mongo on Linux which there
> should be some decent documentation for.
>
> If you are planning to use this in any production sense, then I would
> probably advise you look to proffesional help in setting up and maintaining
> it. Running an LRS at scale is not for the faint hearted! You can have a
> read at what our full stack looks like here:
> https://learninglocker.net/blog/lrs-enterprise-hosting/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LearningLocker/learninglocker/issues/810#issuecomment-215797383>
>


-- 

Steve Smith





(: 07462599556
(: 01273 387778

* *steve@virtualserve.biz* <steve@virtualserve.biz>

ü*    http://www.virtualserve.biz <http://www.virtualserve.biz/>*



*Confidentiality Notice*

*This email and any attachments are confidential and legally privileged and
intended solely for the use of the individual or entity to whom they are
addressed. If you are not the named addressee, please telephone +44(0) 1273
387778 Views expressed are those of the individual sender, except where
stated as those of Virtualserve. There will be no liability for damage
arising in any way from receipt or use thereof.*
