### ISSUE TITLE
MS Office document mimetypes refused

### ISSUE THREAD

**Issue by hamishdewe** [LearningLocker/learninglocker#819]
You need to replace the parts of this template where you see {{some text}}.

**Version**
 Commit 627be8f on 1.12.1

**Steps to reproduce the bug**
1. Submit statement with attachment where attachment uses contentType application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Expected behaviour**
Statement should be accepted because specified contentType is valid mimetype reported by file.

**Actual behaviour**
Post fails with error 
`application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` should be a valid `Locker\XApi\IMT` in `statement.attachments.0.contentType`.

**Additional information**
OS: Centos 7
Browser: Chrome latest

The issue seems to be the regex in \LearningLocker\XApi\MT that fails the mimetype for using `.`
Replacing 
^(application|audio|example|image|message|model|multipart|text|video)(\/[-\w\+]+)(;\s*[-\w]+[\=]+[-\w]+)*;?$
with 
^(application|audio|example|image|message|model|multipart|text|video)(\/[-\w\+\.]+)(;\s*[-\w]+[\=]+[-\w]+)*;?$
allows use of this contentType.

**Comment by ht2** [comment]
@ryansmith94 Something for [LearningLocker/StatementFactory](https://github.com/LearningLocker/StatementFactory) I presume?

**Comment by ryansmith94** [comment]
Yeah @ht2

**Comment by ryansmith94** [comment]
Note to self: fixed in V2 with `^(application|audio|example|image|message|model|multipart|text|video)(\/[-\w\+\.]+)(;\s[-\w]+[\=]+[-\w]+);?$`

**Comment by ryansmith94** [comment]
Wow sorry @hamishdewe, forgot all about this one. Looking into it now.

**Comment by ryansmith94** [comment]
Hi @hamishdewe, this has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.

**Comment by hamishdewe** [comment]
Thanks @ryansmith94. Looking forward to it.
