### ISSUE TITLE
Reports keep "reseting"

### ISSUE THREAD

**Issue by ngarafol** [LearningLocker/learninglocker#821]
**Version**
1.12.1
**Steps to reproduce the bug**
1. Make new report, edit, save changes
2. Click on report - edit - saved settings gone

**Expected behaviour**
Reports should keep saved settings.

**Actual behaviour**
Reports lose settings on every edit.

**Additional information**
OS: Debian 8 x64
Browser: Chrome Version 51.0.2704.63 (64-bit)

**Comment by ht2** [comment]
Hey @ngarafol, do you see a browser popup alert box after pressing "Save" saying "Saved successfully"?

**Comment by ht2** [comment]
Also it might be helpful to know which parts are not saving - is this across all fields or a handful? We can't replicate this on our 1.12.1 instances.

**Comment by ngarafol** [comment]
Actor is not saving now. Verb also did not save in other report. Here is the video https://www.youtube.com/watch?v=26XltWxUubU Will check if I get mongo timeout errors, that could be cause for not saving report values..

**Comment by ht2** [comment]
OK, I think I see the problem - the reports work using a "typeahead". You need to filter on existing agents/verbs/etc - by selecting something out of the dropdown it will format it ready for the query builder. Simply adding a name to the actor field won't create a catch all query to search all fields in that type. Try typing the name/email/account info of an actor that already exists in your LRS through statement insertion and you should see a drop down akin to this:
![capture](https://cloud.githubusercontent.com/assets/1352590/15707990/c0945ab6-27f3-11e6-8f5b-1e538a721791.JPG)

**Comment by ngarafol** [comment]
What do you mean? I dont see any dropdown menus, thats why I am entering data manually.

**Comment by ryansmith94** [comment]
From looking at the video @ngarafol it looks like you might not been seeing the drop down because of a slow connection to the LRS. It should come up eventually assuming you are searching for people that actually exist in the LRS.

**Comment by ngarafol** [comment]
Yes, even if I insert user from "statement.actor.name" that exists, I see typeahead requests you were mentioning but still no dropdown appears. I have debug enabled, and use clockwork inside developer tools...

**Comment by ryansmith94** [comment]
@ngarafol can you please try these steps and record what happens as you do?

1. Create a new report.
2. Click edit on the new report.
3. Change the title of the report to "Edit 1".
4. Add an actor called "Actor 1".
5. Save the report.
6. Go back to the list of reports.
7. Click edit on the report you created in step 1.
8. Change "Actor 1" to "Actor 2".
9. Add a verb called "Verb 2".
10. Save the report.

**Comment by ngarafol** [comment]
https://www.youtube.com/watch?v=duzjythpljU

**Comment by ryansmith94** [comment]
Hmmm that's strange that it didn't save the actor from step 4. If you do step step 9 before step 10, does it save the actor and not the verb @ngarafol?

**Comment by ngarafol** [comment]
Can you clarify? No way to save actor, or at least it is not showing :)

**Comment by ryansmith94** [comment]
Sorry I meant step 10 before step 9. Ok

**Comment by ngarafol** [comment]
Also when clicking on statements, since Actor is empty (right?) I get this error:

exception 'ErrorException' with message 'MongoCollection::find(): expects parameter 2 to be an array or object, null given' in /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php:59 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'MongoCollection...', '/var/www/learni...', 59, Array) #1 [internal function]: MongoCollection->find(Array, NULL) #2 /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php(59): call_user_func_array(Array, Array) #3 /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(343): Jenssegers\Mongodb\Collection->__call('find', Array) #4 /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(343): Jenssegers\Mongodb\Collection->find(Array, NULL) #5 /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(1089): Jenssegers\Mongodb\Query\Builder->count(NULL, NULL) #6 /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Builder.php(275): Jenssegers\Mongodb\Query\Builder->getPaginationCount(NULL, NULL) #7 /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Builder.php(260): Jenssegers\Mongodb\Eloquent\Builder->ungroupedPaginate(Object(Illuminate\Pagination\Factory), 20, Array, NULL, NULL) #8 /var/www/learninglocker/app/controllers/ReportingController.php(95): Jenssegers\Mongodb\Eloquent\Builder->paginate(20) #9 [internal function]: ReportingController->statements('572c4ecbdd4239f...', '574ee25ddd4239f...') #10 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #11 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('statements', Array) #12 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ReportingController), Object(Illuminate\Routing\Route), 'statements') #13 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ReportingContro...', 'statements') #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('572c4ecbdd4239f...', '574ee25ddd4239f...') #15 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array) #16 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #18 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/learninglocker/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkLegacyMiddleware.php(20): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #21 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Clockwork\Support\Laravel\ClockworkLegacyMiddleware->handle(Object(Illuminate\Http\Request), 1, true) #22 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #23 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #24 /var/www/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #25 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #26 /var/www/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run() #27 {main}

**Comment by ngarafol** [comment]
Seems to be mongo timeout issue. Now dropdown works, since typeahed queries manage to finish under 30 seconds of mongo timeout. Had to reduce statements collection to 500k statements. And settings remain saved. Even on editing saved report. So I think there is scalability issue with this version of learninglocker :)

**Comment by ngarafol** [comment]
So typeahead seems to work, entries seem to remain saved. But I still have problem with statements, error exactly as above: exception 'ErrorException' with message 'MongoCollection::find(): expects parameter 2 to be an array or object, null given' in 

Parameter 2 should be columns returned, right? If I see statements on graph, how come statements have null parameter for columns?

**Comment by ngarafol** [comment]
When I try to click "statements" button in reporting. I get error message ErrorException' with message 'MongoCollection::find(): expects parameter 2 to be an array or object, null given' in as shown above few comments earlier. Thats are "problems with statements" I am talking about. 
I should get statements that are included in report since report graph shows some bars and number of statements, but statements button throws error...

**Comment by ngarafol** [comment]
Using https://github.com/hongymagic/learninglocker instance on local machine and restoring test database, reports and report statements work. Could be due to docker instance using master branch I believe. So I am closing this ticket since it obviously is due to hardware/software issues on my side and not directly related to LearningLocker.

**Comment by ht2** [comment]
Thanks for digging @ngarafol - we'll keep an eye out for similar behaviours moving forward just in case
