### ISSUE TITLE
The default branch should be master, not develop?

### ISSUE THREAD

**Issue by jamarr81** [LearningLocker/learninglocker#822]
Most projects set their default branch to _master_ as this is more convenient for most users, as most users are intending on _using_ the project first and foremost. For devs who want to then contribute changes, it would be typical for them to create a _separate checkout_ of the _dev_ branch.

**Version**
n/a

**Steps to reproduce the bug**
1. Follow [install instructions](http://docs.learninglocker.net/installation/).

**Expected behaviour**
_git clone_ should checkout _master_ because it is the _stable branch_.

**Actual behaviour**
_git clone_ checks out _develop_ because it is set as the _default branch_.

**Comment by davidscholberg** [comment]
At the very least, the installation instructions should be updated to make it clear that you'll end up on the develop branch by default when you git clone, and that you should checkout a release tag if you want to use LL in production.

**Comment by ryansmith94** [comment]
Default branch is set to develop so that all PRs go to develop by default, so this will not be changed. However, the docs should certainly be changed.
