### ISSUE TITLE
Statement generated using tincan generator : Inserted but show error on statements page

### ISSUE THREAD

**Issue by diwakak** [LearningLocker/learninglocker#823]
You need to replace the parts of this template where you see {{some text}}.

**Version**
Master

**Steps to reproduce the bug**
1. Create a Group statement using Tincan Statement generator. Example.
{
    "timestamp": "2016-05-27T19:01:00+05:30",
    "version": "1.0.1",
    "actor": {
        "mbox": "mailto:learner@example.com",
        "name": "Example Learner",
        "objectType": "Agent"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/answered",
        "display": {
            "en-US": "answered"
        }
    },
    "object": {
        "mbox": "mailto:team@example.com",
        "member": [
            {
                "name": "Bob",
                "account": {
                    "homePage": "http://www.example.com",
                    "name": "13936749"
                },
                "objectType": "Agent"
            },
            {
                "name": "Tom",
                "mbox": "mailto:tom@example.com",
                "objectType": "Agent"
            },
            {
                "name": "Alice",
                "mbox_sha1sum": "ebd31e95054c018b10727de4db3ef2ec3a016ee9",
                "objectType": "Agent"
            }
        ],
        "objectType": "Group"
    },
    "result": {
        "score": {
            "scaled": 0.00023
        },
        "success": true,
        "completion": true
    }
}
2. Insert this statement into a LRS created using Learning locker admin
3. Now Login to Learning locker. You will be able to see the statements getting incremented on the dashboard. But when you click the statements link for that LRS. There would be a exception.
![screenshot-52 35 10 138 2016-06-03 20-35-17](https://cloud.githubusercontent.com/assets/395895/15783189/c75fb0f6-29ca-11e6-8476-519fd12c51e1.png)

**Expected behaviour**
Should load the statement screen showing all the statements inserted.

**Actual behaviour**
Shows exception

**Additional information**
OS: AWS linux
Browser: Any browser

**Comment by ht2** [comment]
Yea this is a problem with objects as groups - there needs to be a catch for when there is no statement ID

**Comment by ht2** [comment]
Fixed in `develop` via f153dbb2aa5082f042174f8df5b41cde1f4f7148
