### ISSUE TITLE
Learning Locker Result Report Issue

### ISSUE THREAD

**Issue by michaelpedro** [LearningLocker/learninglocker#830]
Version - 1.13.0

I am having trouble with the reporting tool for xAPI statements in learning locker. When I attempt to make a report and filter the query by result: score, no graph will show.  

The verb portion of my statement reads as this:

 "verb": {
        "id": "http://adlnet.gov/expapi/verbs/responded"
    },
    "result": {
        "success": true,
        "score": {
            "scaled": 0.9,
            "raw": 90
        },
        "completion": true
    },

When I change the filter in the reporting tool to return all statements with a raw score between 1-100, there is no graph that appears.

**Comment by ryansmith94** [comment]
Hi @michaelpedro, thanks for reporting this bug and using our [template](/contributing.md#issue-templates). We will now try to reproduce your issue.

**Comment by michaelpedro** [comment]
Thank you, @ryansmith94 its been a very frustrating issue.

**Comment by ryansmith94** [comment]
Hi @michaelpedro, thanks for providing the details to reproduce this issue, this has now been reproduced and should be fixed soon.

**Comment by ryansmith94** [comment]
Hi @michaelpedro, had some issues with my setup yesterday (AMPPS was being a thorn in my side), so I had to put this off until today. I'm looking into it now 👍

**Comment by ryansmith94** [comment]
Hi @michaelpedro, this has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.

**Comment by michaelpedro** [comment]
thank you very much @ryansmith94

**Comment by ryansmith94** [comment]
You're very welcome @michaelpedro.
