### ISSUE TITLE
Report / Export generation fails if on https

### ISSUE THREAD

**Issue by btopro** [LearningLocker/learninglocker#837]
**Version**
Latest

**Steps to reproduce the bug**
1. try and add a report while on https

**Expected behaviour**
Should add a report / export.

**Actual behaviour**
Doesn't. 401 thrown behind the scenes via JS attempting to load: `Failed to load resource: the server responded with a status of 401 (Unauthorized)`

**Additional information**
CentOS Linux 7.1.x
Apache/2.4.6

**Comment by ryansmith94** [comment]
Hi @btopro, thanks for reporting this bug and using our [template](/contributing.md#issue-templates). I'm unable reproduce this on one of our instances of Learning Locker. You might want to check out the ["Hosting Learning Locker on https:// site" thread](https://groups.google.com/forum/#!topic/learning-locker/3Y0VGYPV1d8) on our Google Forum, it's a little old now, but probably still relevant here.

**Comment by btopro** [comment]
Cool, as long as people are aware it's possible / have some place they can go :)
