### ISSUE TITLE
Upgrade to 1.13.2 breaks statements.

### ISSUE THREAD

**Issue by Unknown2k** [LearningLocker/learninglocker#838]
1.13.2

**Steps to reproduce the bug**
1. Upgraded to version 1.13.2 via http://docs.learninglocker.net/upgrading/ - Composer

**Expected behaviour**
Statements without error. 

**Actual behaviour**
Learning Locker responds, I can log in, but clicking on statements returns an error. 

I am able to log in, view graphs, but when I click on Statements the following occurs:
https://s32.postimg.org/60pt0369h/Clickonstatements.jpg

**Additional information**
OS: Ubuntu 14.04.3 LTS
Browser: Chrome

**Comment by manjunath-compassites** [comment]
Hi @Unknown2k, try running `php artisan migrate` .
I got the same issue(while installing)
https://github.com/LearningLocker/learninglocker/issues/820#issuecomment-229374408

**Comment by ryansmith94** [comment]
Hi @Unknown2k, thanks for reporting this bug and using our [template](/contributing.md#issue-templates). Please see @manjunath-compassites comment above, that should resolve your issue. As stated in our documentation, we no longer recommend using Composer to install/upgrade.

> we recommend that you download Learning Locker via Github with Git and upgrade via Github with Git for a better upgrade experience.

**Comment by Unknown2k** [comment]
Thanks. With this information I was able to repair it. 

We had originally deployed LearningLocker with Composer. Is it possible to use Git upgrade after a Composer install? Or would we need to reinstall using Git?

**Comment by ryansmith94** [comment]
Hi @Unknown2k, glad you were able to repair your installation.

Yes it is possible to use the Git upgrade after installing via Composer. You should be able to follow the steps below when upgrading.

1. Copy your “bootstrap/start.php” file.
1. Copy your “app/config/local” directory.
1. Remove your Learning Locker directory.
1. Run `git clone -b master git@github.com:LearningLocker/learninglocker.git learninglocker; cd learninglocker;`
1. Replace “bootstrap/start.php” with your previously copied version.
1. Replace your “app/config/local” directory with your previously copied version.
1. Then follow the [Upgrading via Github with Git instructions](http://docs.learninglocker.net/upgrading/#upgrading-via-github-with-git).
