### ISSUE TITLE
Deleting client displays error

### ISSUE THREAD

**Issue by ryansmith94** [LearningLocker/learninglocker#840]
**Version**
1.13.1

**Steps to reproduce the bug**
1. Create a client.
2. Delete the client created in step 1.

**Expected behaviour**
The completion message should be "Client deleted" because it gets deleted.

**Actual behaviour**
The completion message is "Oops. Something went wrong. The client has not been deleted".

**Comment by manjunath-muniraju-4444** [comment]
Hi @ryansmith94 

but now, when https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/repository/Base/EloquentRepository.php#L27 ( `protected function fire($allow, $event, array $opts, array $extra)` ) is called then if condition will fail in fire function. and it will not trigger https://github.com/LearningLocker/learninglocker/blob/develop/app/listeners.php#L27 (`Event::listen('Lrs.destroy', function ($opts)`)

i would suggest something  like this:

```
protected function fire($allow, $event, array $opts, array $extra) {
    if ($allow) {
      \Event::fire(ltrim($this->model, '\\').'.'.$event, [array_merge($opts, $extra)]);
    }

    if (is_null($allow) && $event == "destroy") {
      \Event::fire(ltrim($this->model, '\\').'.'.$event, [array_merge($opts, $extra)]);
      $allow=true;
    }
    return $allow;
  }
```

**Comment by ryansmith94** [comment]
That's okay @manjunath-muniraju-4444, I've fixed that now, I had to pop out for an hour before I had checked the fix properly, sorry for causing some confusion.
