### ISSUE TITLE
Question : Postman Collection for Document API 

### ISSUE THREAD

**Issue by manjunath-muniraju-4444** [LearningLocker/learninglocker#842]
Hi,
Do You Have Postman Collection for Document API (like http://docs.learninglocker.net/postman/#collections).
If you have, please share it. it would be great help for me and other if anyone require.

**Comment by ryansmith94** [comment]
Hi @manjunath-muniraju-4444, those collections are already included on that page. Please see the links for the following collections:

- [data/xAPI/activities](https://www.getpostman.com/collections/680c14a7e5fcd028ae7f)
- [data/xAPI/activities/state](https://www.getpostman.com/collections/c6307884d177fbc684e6)
- [data/xAPI/agents](https://www.getpostman.com/collections/8f1ed1a786c2c61bf087)

**Comment by manjunath-muniraju-4444** [comment]
Thanks @ryansmith94.

**Comment by ryansmith94** [comment]
You're welcome @manjunath-muniraju-4444 😄
