### ISSUE TITLE
extension ext-mongo * is missing

### ISSUE THREAD

**Issue by bgdssusu** [LearningLocker/learninglocker#845]
My question is so simple. I have a WAMP server on my win10 machine. (PC is in the office so I HAVE TO use windows...)

Everything is correct. MongoDB is working (run as a service, and I tested it from the cmd line). The php extension is loaded. (I can see it in the phpinfo page... And it is in the wamp-php-extension list, too)

But when I try to install learning locker, I see this: 

"Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-mongo * is missing from your system. Install or enable PHP's mongo extension."

So... Why? And what is the solution?
![phpinfo](https://cloud.githubusercontent.com/assets/13118492/17131016/f293e1d2-534d-11e6-85d0-af9522c21d0f.png)

**Comment by ht2** [comment]
You're PHP running in the CLI uses a different php.ini to the one running in apache. Go look at the php.ini in the `wamp/bin/php` folder and add the required extension there.

**Comment by ht2** [comment]
A bit more info on the subject, but the tl;dr is that there is a version in the `bin/apache` dir too:

http://stackoverflow.com/questions/22771050/wampserver-two-php-ini-files

**Comment by bgdssusu** [comment]
Thanks.

That's why I hate WAMP, and all "packages"... It is TOO easy to set-up, but after that I have a lot of problems with it.
Eg. first I used msi file to install bmongoDB and it was wrong. Second time I used the native src, and made my own cmd files, and it was good...

Thanks again, and I will check why we have different php.ini files... :XD
