### ISSUE TITLE
Articulate Storyline 2 course doesn't resume

### ISSUE THREAD

**Issue by chaiwei** [LearningLocker/learninglocker#847]
**Version**
1.13.3

**Steps to reproduce the bug**
1. Create working launch link to course
2. Launch course and play through a bit
3. Close course
4. Re-launch course with same launch link
5. The course does not prompt for resume

**Expected behaviour**
Course should prompt for resume when we refresh/reload with same activity and same actor

**Actual behaviour**
Course start over again

**Additional information**
OS: Window 10 x64 with WAMP + Mongodb
Browser: Version 51.0.2704.106 m (64-bit)

Tested the same course with ScormCloud and it is working fine. But couldn't get it work with LearningLocker.

---
The difference I notice is it return {} instead of { data:"xxxx" } in the http://localhost:8081/learninglocker/public/data/xAPI/activities/state?method=GET

I am not sure if the parameter I pass to the server is correct or not. 

> story.html?endpoint=http://localhost:8081/learninglocker/public/data/xAPI/&auth=Basic%20M2FjNDAwNWZhNDY4YWQ4M2Y2ZjUxMTZjN2UwMDdmMDIyMjJhZjdkNzozOTE1MzI5ODcxN2QxYjFmZTI3MzY5OGI2NWJjNzBjNzdlODUwNTFj&actor={"mbox":"mailto:xxx@xxx.com",%20"name":"Jason"}&registration=2981c910-6445-11e4-9803-0800200c9a66&activity_id=www.example.com/my-activity

Also I am not sure where to get/generate for the registration and activity_id paramenter for, I just copy from the tutorial website and use it. Is that the reason it doesn't work?

---
I suspect the `http://localhost:8081/learninglocker/public/data/xAPI/activities/state?method=GET` data return {} is due to the data in content & registration field in `documentapi ` table is empty. 
So that's why it couldn't resume. 

```
{
    "_id" : ObjectId("57991e7d7f7759ac2600002c"),
    "lrs" : ObjectId("57991beb7f7759b02100002d"),
    "lrs_id" : ObjectId("57991beb7f7759b02100002d"),
    "documentType" : "state",
    "identId" : "resume",
    "activityId" : "http://5a8SiBHMf0l_course_id",
    "agent" : {
        "mbox" : "mailto:xxx@xxx.com",
        "name" : "Jason"
    },
    "registration" : null,
    "updated_at" : ISODate("2016-07-27T21:31:27.000Z"),
    "sha" : "AA7B6DA600F7E471DEEE83DCB06F923C6353FF65",
    "content" : null,
    "contentType" : "application/json",
    "created_at" : ISODate("2016-07-27T20:50:05.000Z")
}

```

**Comment by ryansmith94** [comment]
> Also I am not sure where to get/generate for the registration and activity_id paramenter for, I just copy from the tutorial website and use it

Hi @chaiwei, what tutorial website is that?

**Comment by hallshouse** [comment]
@ryansmith94 @chaiwei LearningLocker A while back I created a little tools to help people form proper Launch URLs for LearningLocker. This tool also provides links to proper respources to obtain the information you need to enter into your Storyline Publish to Tin-Can settings and such.

If you have questions about what information to enter into Storyline and what eth final URL should look like (using Basic OAuth2) visit this URL and play around with the settings and visit the related links in the ? panels.

http://www.products-and-services.ca/tincan-launcher/tincan-launch-form.html

Hope this helps close this issue.

**Comment by chaiwei** [comment]
@ryansmith94 it is on https://learninglocker.net/blog/storyline-2-learning-locker/

The course is able to play without any problem, just that everytime I visit the same link (loaded with same actor and activity id) or refresh the page during middle progress of the course, it doesn't prompt for resume. 

I then check the network in chrome properties during the first load of the api however it returns {} which I think it should return some data such as {data:xxxxxx}

Below is the screenshot for testing

Tested with Learning Locker v1.13.3
![image](https://cloud.githubusercontent.com/assets/423006/17257427/ade83674-55f4-11e6-8511-b431d672bafd.png)

Below is the url that I am using for learning locker
`http://localhost:8081/learninglocker/public/assets/tincan/story.html?endpoint=http://localhost:8081/learninglocker/public/data/xAPI/&auth=Basic%20Zjc4NDFhMjdhZDRjMzIwZjAxNWE1ZTU3ZjA0ZDdjOGNkYzhmMDA3YjozOGNhOWEwZTU3MmU4MjZmMDg0YjE5ZTE2MjY5ZWNjMDMxM2I3MjQy&actor={%22mbox%22:%22mailto:xx@xxx.com%22,%20%22name%22:%22Jason%22}&registration=2981c910-6445-11e4-9803-0800200c9a66&activity_id=5a8SiBHMf0l_course_id`

---

Below is tested through SCORM Cloud. It returns data
![image](https://cloud.githubusercontent.com/assets/423006/17257705/f70ff69c-55f5-11e6-98d8-844097c70507.png)


Below is the url that I am using for Scorm Cloud
`http://localhost:8081/learninglocker/public/assets/tincan/story.html?endpoint=https://cloud.scorm.com/tc/EM6T0JXD70/&auth=Basic%20cHR0VnBjek9rdzBYRFczdzRSTTo2MU1RdDlXNWhzcENLX3JJM0s0&actor={%22mbox%22:%22mailto:xxx@xxx.com%22,%20%22name%22:%22Jason%22}&registration=2981c910-6445-11e4-9803-0800200c9a66&activity_id=www.example.com/my-activity`

**Comment by chaiwei** [comment]
Hi @hallshouse 

Thank you. Appreciate for the tool and video explanation.

I tried to fill in the form and generate the link and unfortunately It returns Unauthorized access 401 error.  Not sure if it the error is due to I am using localhost:8081
![image](https://cloud.githubusercontent.com/assets/423006/17258615/504aaf00-55fa-11e6-9f25-5b65fde09bd3.png)

Below is the URL that was generated (I hv replaced my email in below url) 
`http://localhost:8081/learninglocker/public/assets/tincan/story.html?endpoint=http://lrs.learning-templates.com/data/xAPI/%26auth%3DBasic%20MTljMGUzNWNkZWMxN2U4ZDM0MjdlZjZmYzdkMDE3ODUwNzIyNDU5YjphNGZmMmZiNWNhMDQ3NTg1YTI2Zjg3OGU2YTZlYWYyNWZlNmY0NjNh%26actor%3D%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%5B%22chaiwei%22%5D%2C%22mbox%22%3A%5B%22mailto%3Axxx@xxx.com%22%5D%7D%26registration%3D0072356f-3de8-4792-ab8a-e2d8a3295db5%26activity_id%3Dhttp%3A%2F%2F5a8SiBHMf0l_course_id/6Q4sOXgwR3i`

**Comment by hallshouse** [comment]
@chaiwei That is fine. you go the error only because I have changed the server. I did not expect you to get try to run the course, just to see your URL output and share it here (as you did).

So here is you query decoded:
http://localhost:8081/learninglocker/public/assets/tincan/story.html?endpoint=http://lrs.learning-templates.com/data/xAPI/&auth=Basic 19c0e35cdec17e8d3427ef6fc7d017850722459b:a4ff2fb5ca047585a26f878e6a6eaf25fe6f463a&actor={"objectType":"Agent","name":["chaiwei"],"mbox":["mailto:xxx@xxx.com"]}&registration=0072356f-3de8-4792-ab8a-e2d8a3295db5&activity_id=**http://5a8SiBHMf0l_course_id/6Q4sOXgwR3i**

So your Launch query looks fine (although I would try to use a real activity ID that is also **"identical" to the one you have configured in SL**). This is very important.

On your LL server, is caching enabled? If yes, turn it off and clear everything you can, this may be your issue.

**Comment by chaiwei** [comment]
@hallshouse Sorry to ask, how to disable cache on LL?

**Comment by hallshouse** [comment]
@chaiwei Server cache. LL does not have (and should not have) caching abilities built in.
You should also clear your browser cache when you revisit your SL course.
I have seen SL do this when cache was not cleared on the server.

You need to contact your host to find out if your server cache is turned on and how to turn it off.

**Comment by chaiwei** [comment]
I check in mongodb database, under "documentapi" table, the field "content" is null so that's why 
it returns {} empty content.

I hv manually update the field to "2Q16609080on1001311f010110121101311..." as show in screenshot below

![image](https://cloud.githubusercontent.com/assets/423006/17261473/7c89d272-5608-11e6-8e62-cacf94d73947.png)

Now the get is returning the value of what I manually update in mongodb earlier. 

![image](https://cloud.githubusercontent.com/assets/423006/17261252/5ab724c0-5607-11e6-8b38-06f3d263e507.png)

It is almost similar to the SCORM Cloud Lrs now, but just with extra " double quote. 

If you have another storyline2 course that is able to resume with LL, can you check for me the http://localhost:8081/learninglocker/public/data/xAPI/activities/state?method=GET is return what content?

**Comment by hallshouse** [comment]
@chaiwei I don't have time today to debug this, but ALL my Storyline2 TIN CAN published courses are launching correctly and asking to resume. They talk to LL 1.13.3 on 2 separate servers.

**Comment by chaiwei** [comment]
no worries, when u have time, can u please let me know what is the first xhr (/learninglocker/public/data/xAPI/activities/state?method=GET) return? 
Just want to make compare with mine. 

Also where can we get this registration id? through storyline or LL?
&registration=0072356f-3de8-4792-ab8a-e2d8a3295db5

Thank you for your precious time for helping me.

**Comment by chaiwei** [comment]
I have manage to fixed the issue,  I need to change 2 places on the LL code.

https://github.com/LearningLocker/learninglocker/blob/develop/app/models/DocumentAPI.php#L32

I need to remove the json_decode as the $content submitted by Articulate Storyline 2 can't be decoded. 

the $content contain below string `2H1ca090b01080609810015110~2015000001^1^1^1^1^1^1^1^1^10171^1^1^1^n6OHzsyXsiB3.6pOtZSyQxQE1^1^0a00000000002000`
```
      case 'application/json':
        $encoded_content = gettype($content) === 'string' ? $content : json_encode($content);
        $this->setSha($encoded_content);
 -       $this->overwriteContent(json_decode($encoded_content, true));
 +       $this->overwriteContent($encoded_content);
        break;
```
Next is  https://github.com/LearningLocker/learninglocker/blob/develop/app/controllers/xapi/DocumentController.php#L237

As the $document->content is not in JSON format, so I can't return json.

```
      if( $this->method === 'HEAD' ){ //Only return headers
        return \Response::make(null, 200, $headers);
      } else {
        switch ($document->contentType) {
          case "application/json":
-            return \Response::json($document->content, 200, $headers);
+            return \Response::make($document->content, 200, $headers);
```
I think the problem is due to storyline 2. It should request text/plain instead of JSON since the content supply is pure text. 

I am not sure if what I changed is correct, it is currently working for 1 publish course. Will get client to upload more courses to test out whether it works.

**Comment by ryansmith94** [comment]
That definitely sounds like a Storyline 2 issue, I don't think they should be sending application/json as the content type. Obviously we can't really make any changes to LL here to resolve this issue for you unfortunately.

**Comment by hallshouse** [comment]
@chaiwei 

> Also where can we get this registration id? through storyline or LL?
>  &registration=0072356f-3de8-4792-ab8a-e2d8a3295db5
This is not a LL requirement. The registration code is a "placeholder dummy code" to appease SL. Articulate uses this for their LMS and when you remove it you should get a 401 (or 2) error launching a SL course in any (except Rustici) based LRS systems.

**Comment by chaiwei** [comment]
@ryansmith94 I agree with you. I will create a discussion post on articulate community website to clarify with them about this. 

@hallshouse Thanks for the information.

Thanks and appreciate for your help on this.

**Comment by ryansmith94** [comment]
Ok @chaiwei. You're very welcome. I'm going to close this issue for now, if new information surfaces we can reopen it.
