### ISSUE TITLE
PHP artisan migrate fails on PHP5.5.9

### ISSUE THREAD

**Issue by Richard87** [LearningLocker/learninglocker#850]
I just set up a new Droplet on Digital Ocean 14.4 with PHP 5.5.9, no luck...

**Steps to reproduce the bug**
1. `git clone *repo*`
2. `git checout 1.13.3`
3. `composer install`
4. `php artisan migrate`

also checked out master, same error...

**Expected behaviour**
Should work?!

**Actual behaviour**

	php artisan migrate
	PHP Fatal error:  Call to undefined method MongoCollection::createIndex() in /var/learninglocker/app/database/migrations/2015_12_23_093122_add_stored_to_statement_root.php on line 20
	Status: 500 Error: Call to undefined method MongoCollection::createIndex()
	{
		"error": {
			"type": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
			"message": "Call to undefined method MongoCollection::createIndex()",
			"file": "\/var\/learninglocker\/app\/database\/migrations\/2015_12_23_093122_add_stored_to_statement_root.php",
			"line": 20
		}
	}

**Additional information**
OS:  Ubuntu 14.04
PHP 5.5.9

**Comment by ht2** [comment]
Please see #796
