### ISSUE TITLE
./assets/js/libs/require/require.js not loading on local installation

### ISSUE THREAD

**Issue by KillerSquid** [LearningLocker/learninglocker#857]
I have a local installation of Learning Locker set up on my MacBook Pro as an evaluation copy for my organization.  After some trial and error to get it installed I have everything working except the ./assets/js/libs/require/require.js file is not loading.  I can log in successfully as the admin user I set up but when I open my console I see that http://localhost/learninglocker/public/index.php/assets/js/libs/require/require.js is not loading on site:43

I'm running Apache 2.4.18 (Linux), PHP 5.5.38, Mongo 1.6.14, and Composer 1.2.0 and using Chrome 52.0.2743.116 on a MacBook Pro with full Admin rights.

Any help is greatly appreciated.

**Comment by ryansmith94** [comment]
Hey @KillerSquid, thanks for reporting your issue. Can you please confirm that the ["public/assets/js/libs/require/require.js" file](https://github.com/LearningLocker/learninglocker/blob/develop/public/assets/js/libs/require/require.js) exists?

**Comment by ryansmith94** [comment]
Can you also tell me what URL you are visiting when you receive that error? If you're running Apache, you should be using `http://localhost/learninglocker/public` not `http://localhost/learninglocker/public/index.php`.

**Comment by KillerSquid** [comment]
That did it.  We had the site redirecting to ~/public/index.php instead of just ~/public
Oy.  Always something simple.  Thanks!

**Comment by ryansmith94** [comment]
Awesome, you're very welcome @KillerSquid 👍
