### ISSUE TITLE
How to query property that is a url via API?

### ISSUE THREAD

**Issue by btopro** [LearningLocker/learninglocker#858]
Hoping someone can help me out here. I'm trying to query an extension property. The extension is formed the way xAPI statements should (to my knowledge) with it being url:value. The question I have is how do you query this via the api as valid JSON and still get results?

I've made a custom property that has the role of the user and so I'm trying to query the learning locker api to get something like this:
```
{
	"$match": {
		"statement.verb.id": "http://adlnet.gov/expapi/verbs/completed",
		"statement.object.definition.extensions['https://www.elmsln.org/x-api/elmsln-role']": "student"
	}
}
```
for an API query like
```
http://USER:PASS@LRSLOCATION/api/v1/statements/aggregate?pipeline=[{"$match":{"statement.verb.id":"http://adlnet.gov/expapi/verbs/completed","statement.object.definition.extensions['https://www.elmsln.org/x-api/elmsln-role']":"student"}}]
```

When I do this (and there's a ton of data off this) it comes up with nothing. However if I don't filter on student role, and then parse the JSON return for the same properties they are there. Is it not possible to query on extensions or what am I missing here?

**Comment by ryansmith94** [comment]
Hi @btopro, thanks for your question. You can use dot notation between the keys and replace the dots inside the key with "&46;", I've put an example of this below :smile:

```json
{
    "$match": {
        "statement.verb.id": "http://adlnet.gov/expapi/verbs/completed",
        "statement.object.definition.extensions.https://www&46;elmsln&46;org/x-api/elmsln-role": "student"
    }
}
```

**Comment by btopro** [comment]
no dice, even went and encoded the rest of the characters but now claiming that's now valid Json hmm...

```
/api/v1/statements/aggregate?pipeline=[{"$match":{"statement.object.definition.extensions.https&#x3A;&#x2F;&#x2F;www&46;elmsln&46;org&#x2F;x-api&#x2F;elmsln-role":"student","statement.verb.id":"http://adlnet.gov/expapi/verbs/completed"}}]
```

**Comment by ryansmith94** [comment]
Hey @btopro, you only need to encode the dots in the key. How are you sending the request? I'm 99% sure that should be working unless something else is going on.

**Comment by btopro** [comment]
yeah this is driving me nuts :)

```
$url = 'http://U:P@ADDRESS/api/v1/statements/aggregate?pipeline=[{"$match":{"statement.object.definition.extensions.https://www&46;elmsln&46;org/x-api/elmsln-role":"student","statement.verb.id":"http://adlnet.gov/expapi/verbs/completed"}}]';
```

is copied directly w/ U/P/ADDRESS all replaced obviously. If I take out just the `"statement.object.definition.extensions.https://www&46;elmsln&46;org/x-api/elmsln-role":"student"` part this works so I'm getting data, just can't get the encapsulation correct to claim it's valid JSON

Response:
```
{"error":true,"success":false,"message":"Expected the value of `pipeline` to be valid JSON in the URL parameter.","code":400,"trace":"#0 \/var\/www\/learninglocker\/app\/controllers\/api\/Statements.php(113): Controllers\\API\\Statements->getParam('pipeline')\n#1 \/var\/www\/learninglocker\/app\/controllers\/api\/Statements.php(33): Controllers\\API\\Statements->getPipeline()\n#2 [internal function]: Controllers\\API\\Statements->aggregate()\n#3 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(231): call_user_func_array(Array, Array)\n#4 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(93): Illuminate\\Routing\\Controller->callAction('aggregate', Array)\n#5 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(62): Illuminate\\Routing\\ControllerDispatcher->call(Object(Controllers\\API\\Statements), Object(Illuminate\\Routing\\Route), 'aggregate')\n#6 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(967): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'Controllers\\\\API...', 'aggregate')\n#7 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()\n#8 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(109): call_user_func_array(Object(Closure), Array)\n#9 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1033): Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))\n#10 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#11 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(775): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#12 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#13 \/var\/www\/learninglocker\/vendor\/itsgoingd\/clockwork\/Clockwork\/Support\/Laravel\/ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#14 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#15 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#16 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#17 \/var\/www\/learninglocker\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#18 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#19 \/var\/www\/learninglocker\/public\/index.php(49): Illuminate\\Foundation\\Application->run()\n#20 {main}"}
```

**Comment by ryansmith94** [comment]
Hey @btopro, why is there a single quote and semicolon at the end?

**Comment by ryansmith94** [comment]
Do you have the code that uses that url to send the request?

**Comment by btopro** [comment]
that url string is sent into https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_http_request/7.x and out the door. If the extension isn't included this all goes through fine and returns a ton of data.

**Comment by ht2** [comment]
Have you tried querying the endpoint using Postman (or similar) with (we would suggest) is the correct version of the string/url? It would allow you to isolate if Drupal or the LRS is the actual problem. 

My guess is that Drupal method is doing further encoding on that URL

**Comment by ryansmith94** [comment]
Hi @btopro, this issue is being closed due to inactivity and will be reopened if it later becomes active.

**Comment by btopro** [comment]
np. I need to explore further but I'm pretty sure your right. Talked it over with a few others who agree that's probably what's at play. Thank you for your help in tracking down the encapsulation format!

**Comment by ryansmith94** [comment]
No worries @btopro. It certainly sounds like that's what's happening. You're very welcome.

**Comment by btopro** [comment]
Got back to this; even in postman this doesn't work.
```
[{
	"$match": {
		"$or": [{
			"statement.object.id": "http://courses.elmsln.local/sing100/node/3"
		}, {
			"statement.context.extensions.https://www&46;elmsln&46;org/x-api/elmsln-url": "http://courses.elmsln.local/sing100/node/3"
		}]
	}
}]
```

which jsonlint is saying is valid json. My request

http://USER:PASS@HOST/api/v1/statements/aggregate?pipeline=[{"$match":{"$or":[{"statement.object.id":"http://courses.elmsln.local/sing100/node/3"},{"statement.context.extensions.https://www&46;elmsln&46;org/x-api/elmsln-url":"http://courses.elmsln.local/sing100/node/3"}]}}]

And it's claiming this isn't valid json. If I instead have it be www.elmsln.org in the request it goes through but returns nothing. There's a lot of stuff I've been reading about dot notation and $ being reserved characters in names. Is it possible that LL needs to translate this after the request has come through some how? http://stackoverflow.com/questions/8429318/how-to-use-dot-in-field-name

**Comment by ryansmith94** [comment]
Hey @btopro. I just tried sending the exact same pipeline via Postman and it works.

I used the following pipeline:
```json
[{"$match":{"$or":[{"statement.object.id":"http://courses.elmsln.local/sing100/node/3"},{"statement.context.extensions.https://www&46;elmsln&46;org/x-api/elmsln-url":"http://courses.elmsln.local/sing100/node/3"}]}}]
```

Here is what it looks like in Postman:
![screen shot 2016-10-18 at 13 51 07](https://cloud.githubusercontent.com/assets/3045513/19478360/339a9abc-953a-11e6-86fc-bf84edc70086.png)

Here is what the cURL request looks like from Postman:
```sh
curl -X GET -H "Authorization: Basic MY_BASIC_AUTH" -H "X-Experience-API-Version: 1.0.0" -H "Cache-Control: no-cache" -H "Postman-Token: 5bfb8e54-d5da-35b5-1442-6a71fa88b31f" "http://localhost:/ll/ll/public/api/v1/statements/aggregate?pipeline=%5B%7B%20%20%20%20%20%22$match%22:%20%7B%20%20%20%20%20%20%20%20%20%22$or%22:%20%5B%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%22statement.object.id%22:%20%22http://courses.elmsln.local/sing100/node/3%22%20%20%20%20%20%20%20%20%20%7D,%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%22statement.context.extensions.https://www%252646;elmsln%252646;org/x-api/elmsln-url%22:%20%22http://courses.elmsln.local/sing100/node/3%22%20%20%20%20%20%20%20%20%20%7D%5D%20%20%20%20%20%7D%20%7D%5D"
```

I'm using the following versions:
- Postman 4.7.2 on OS X Chrome 53.0.2785.116
- Learning Locker v1.13.4

**Comment by btopro** [comment]
so looks like postman is doing a double-encoding for the . so that it's `%252646;`. tried that and it goes through as valid json but returns nothing that matches. It's as if LL is evaluating
`statement.context.extensions.https://www%252646;elmsln%252646;org/x-api/elmsln-url'`
as
`statement -> context -> extensions -> https://www -> elmsln -> org/x-api/elmsln-url`

So it goes through but doesn't return any matching data (of which there's tons). Anyone been able to do a pipeline aggregation query that returns matching data against these extension properties?

**Comment by ht2** [comment]
Hi @btopro, we extensively use queries to extensions with URI values, never see problems with it.

**Comment by btopro** [comment]
@ht2 via the API endpoint or like mongodb php / other language library? Coworker suggested maybe i'm having issues because it's via webcall since `.` is a reserved character for $match engine

**Comment by ryansmith94** [comment]
Is there a chance you have something else going on between Postman and LL that is causing issues here @btopro? Apache/NGINX configs, etc?

**Comment by ht2** [comment]
@btopro Yes via the API. We're aware that `.` is reserved, that's why its encoded before you send. If you are sending it in the URL params then you'll need to encode it _a second time_ so that it arrives on the PHP side (once decoded) as `&46;` and not `.`

Here are the helper methods used to deal with this part: 
https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/helpers/Helpers.php#L25
https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/helpers/Helpers.php#L36

[I believe this is the exact place it is being utilised with aggregation](https://github.com/LearningLocker/learninglocker/blob/716188b3b3444666b9871b4cb4ea4238ad938f23/app/locker/repository/Query/EloquentQueryRepository.php#L89), maybe try logging out the value of $pipeline at this stage and see what is being passed in?

**Comment by ryansmith94** [comment]
Just tried this again in Postman, note that we pasted the following into the params.
```
[{"$match":{"statement.object.extensions.http://www&46;google&46;com":{"$exists":true}}}]
```

![screen shot 2016-10-18 at 15 11 12](https://cloud.githubusercontent.com/assets/3045513/19481218/207d2ec6-9545-11e6-85a5-6ceebe7c01c4.png)

And Postman converted the `&46;` to `%2646;` in the URL.
```
localhost:/ll/ll/public/api/v1/statements/aggregate?pipeline=[{"$match":{"statement.object.definition.extensions.http://www%2646;google%2646;com":{"$exists":true}}}]&46;google&46;com":{"$exists":true}}}]
```

![screen shot 2016-10-18 at 15 09 09](https://cloud.githubusercontent.com/assets/3045513/19481131/d6ec70fa-9544-11e6-9338-fb72491aacdd.png)

**Comment by btopro** [comment]
ok, well, thank you for confirming it works for you w/ what I'm going for. I've got it formatted correctly now as per the encoding your showing for `%252646;` and upgraded ll to 1.14.0 but still no success in postman :\.

Not really sure how to proceed other then mashing my face into the keyboard so I'll stop bugging you all about something clearly broken in what i'm doing. thanks for the quick response / feedback.

**Comment by ht2** [comment]
@btopro Know the feeling well!!! Try this quickly, place `dd($pipeline);` onto line 85 of `app/locker/repository/Query/EloquentQueryRepository.php` and post the results here. Even better, join us on https://gitter.im/LearningLocker/learninglocker and then we chat in realtime! If we find a problem/solution we can update this ticket.

**Comment by btopro** [comment]
```
array(1) {
  [0]=>
  array(1) {
    ["$match"]=>
    array(1) {
      ["$and"]=>
      array(2) {
        [0]=>
        object(stdClass)#687 (1) {
          ["statement.context.extensions.https://www%2646;elmsln%2646;org/x-api/elmsln-url"]=>
          string(42) "http://courses.elmsln.local/sing100/node/3"
        }
        [1]=>
        array(2) {
          ["lrs_id"]=>
          object(MongoId)#686 (1) {
            ["$id"]=>
            string(24) "5734c3d565f1495b508b485f"
          }
          ["active"]=>
          bool(true)
        }
      }
    }
  }
}
```

**Comment by ht2** [comment]
Looks like it was a triple encoding issue; Postman was _reencoding_ the `%2646` values as they were pasted in.
