### ISSUE TITLE
Hitting MongoDB Aggregation Pipeline Limit with Aggregate API

### ISSUE THREAD

**Issue by vjukarainen** [LearningLocker/learninglocker#859]
Hello,

We are using [aggregate API](http://docs.learninglocker.net/statements_api/) to fetch large amount of aggregated statements from the Learning Locker and have found ourselves hitting MongoDBs [100Mb Aggregation Pipeline Limit](https://docs.mongodb.com/manual/core/aggregation-pipeline-limits/). When interacting with MongoDB directly, the aggregate pipeline allows the queries to specify [allowDiskUse](https://docs.mongodb.com/manual/reference/command/aggregate/#aggregate-data-using-external-sort) option which lets users to overcome this limitation.

Is there a way to use this option with Learning Locker's aggregate API  and/or are there any plans to support this option ie. via query parameter?

Right now our only options seem to be either coming up with a custom paging which would allow us to handle smaller sets of data or by doing the aggregate pipeline query directly through MongoDB instead of LL's aggregate API.

Thanks!

Marko

**Comment by ht2** [comment]
Typically the first step is to use the $project stage of the pipeline to minimise what you are passing through. Do you have the ability to limit what you are returning or are you already doing that?

There are currently no plans to extend the aggregation API, but community pull requests are always welcome for such functionality.

**Comment by vjukarainen** [comment]
Thank you for your response! We already try to minimize the amount of data during the $project stage however even after that there are still cases when the sort limit is exceeded, additionally we can only limit the amount of statements based on a date range, however the volume of statement that still fits between the date range can't easily be limited more, however we will continue to look if it can be improved.

We are also considering creating a pull request in case we end up having to use the allowDiskUse option. Lets say we decide to follow that route, in that case I assume that an optional request parameter that can be passed along the pipeline request would be more favorable over a global setting that would apply the option to all the aggregate calls?

**Comment by ryansmith94** [comment]
Hey @vjukarainen, would it be possible to show us the query you're making?

**Comment by vjukarainen** [comment]
Hi @ryansmith94 sorry for the silence, I'll try to see if I can provide a sample query although I can't go too much in detail about the context. In general its pretty straightforward query with 4 stages, $match, $project, $sort and finally $group.

**Comment by ryansmith94** [comment]
No problem @vjukarainen. Thank you. No problem.

**Comment by ht2** [comment]
Just an FYI, if you wanted to build in this functionality, you would need to amend the Mongo ORM library to pass in this parameter:

https://github.com/LearningLocker/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Query/Builder.php#L248

That is our forked version (that the depenedencies already called) of that library. That call to `$results = $this->collection->aggregate($pipeline);` can take in a `allowDiskUse` option via the second param: http://php.net/manual/en/mongocollection.aggregate.php

e.g.
```
$this->collection->aggregate($pipeline, ['allowDiskUse'=>true]);
```

If you just want to fix your instance, find that file in the `vendors/` dir and amend accordingly.

**Comment by vjukarainen** [comment]
@ryansmith94 here you go, to summarize we are trying to find only the most recent answers for each unique (questionId) question recorded in the LRS within the given domains and associated history identifiers
```json
[{
    "$match": {
        "statement.actor.mbox": "mailto:user@example.com",
        "statement.verb.id": "http://adlnet.gov/expapi/verbs/answered",
        "statement.context.extensions.domain-identifier": {
            "$in": ["http://xapi.example.com/domains/SAMPLE_DOMAIN_1", "http://xapi.example.com/domains/SAMPLE_DOMAIN_2"]
        },
        "statement.context.extensions.http://xapi.sample.com/context/extensions/history-identifier": {
            "$in": [123,124,125]
        },
        "voided": false
    }
},
{
    "$project": {
        "_id": 0,
        "questionId": "$statement.object.id",
        "timeAnswered": "$statement.timestamp",
        "correct": "$statement.result.success",
        "historyIdentifier": "$statement.context.extensions.http://xapi.sample.com/context/extensions/history-identifier"
    }
},
{
    "$sort": {
        "questionId": 1,
        "timeAnswered": -1
    }
},
{
    "$group": {
        "_id": "$questionId",
        "timeAnswered": {"$first": "$timeAnswered"},
        "correct": {"$first": "$correct"},
        "historyIdentifier": {"$first": "$historyIdentifier"}
    }
}]
```

**Comment by ht2** [comment]
My immediate recommendation would be to add a compound index for the fields you are querying, specifically "statement.context.extensions.domain-identifier" and "statement.context.extensions.http://xapi.sample.com/context/extensions/history-identifier"

**Comment by ht2** [comment]
You could make a super compound of actor + verb + the extensions + voided, it might take up quite a bit of space though and indexes should really be able to sit inside RAM

**Comment by ht2** [comment]
A colleague of mine has made a good point, it could be the sort causing the allowDiskUse to be flagged (sorts are _very_ expensive). Can you try it..

a) without the sort
b) with the indexes and with the sort
c) with the indexes and without the sort
d) with a `questionId:1` and `timeAnswered:-1` compound index and the sort

**Comment by vjukarainen** [comment]
Thank you very much, we will start by moving the sort and creating compound indexes to see if it solves the issue.

I realized that I didn't mention in the initial description that the aggregation pipeline limit error happens because of sort operation as @ht2 mentioned.

**Comment by ht2** [comment]
Yes, $sort is extremely expensive as noted, especially after project as the database has to actually perform the sort of all the documents in memory until that limit has been reached. To start, moving the sort and then a simple `db.statements.createIndex({questionId:1, timeAnswered:-1}, {background:true})` should really help.

**Comment by ryansmith94** [comment]
Hi @vjukarainen, this issue is being closed due to inactivity and will be reopened if it later becomes active.

**Comment by vjukarainen** [comment]
Thank you @ryansmith94 I'll follow up with you in case the if the issue is still ongoing once we get back to it.

**Comment by ryansmith94** [comment]
No worries @vjukarainen. That's great, thank you 😄
