### ISSUE TITLE
Invalid JSON error due to ampersand?

### ISSUE THREAD

**Issue by chadabaker** [LearningLocker/learninglocker#861]
**Version**
master 1.13.4

**Steps to reproduce the bug**
1. Launch TinCan course
2. Course sends the following payload to Statement API (removed the "Authorization" parameter)

POST URL: https://lrs.dev.com/data/xAPI/statements?method=PUT

URL Encoded Payload:
X%2DExperience%2DAPI%2DVersion=1%2E0%2E1&statementId=cc4e3e2d%2Dbdb6%2D439d%2D8dec%2D818db7773b11&content=%7B%22actor%22%3A%7B%22name%22%3A%22Old%20Yeller%22%2C%22objectType%22%3A%22Agent%22%2C%22account%22%3A%7B%22name%22%3A%22aaatester%22%2C%22homePage%22%3A%22https%3A%2F%2Fotp%2Edev%2Ecom%22%7D%7D%2C%22context%22%3A%7B%22registration%22%3A%2250a37f2c%2D7984%2D46d1%2Dbbaa%2D0f7da96b0ce8%22%2C%22contextActivities%22%3A%7B%22parent%22%3A%7B%22id%22%3A%22http%3A%2F%2F6AftpAFkrXy%5Fcourse%5Fid%22%7D%2C%22grouping%22%3A%7B%22id%22%3A%22http%3A%2F%2F6AftpAFkrXy%5Fcourse%5Fid%22%7D%7D%7D%2C%22version%22%3A%221%2E0%2E0%22%2C%22verb%22%3A%7B%22id%22%3A%22http%3A%2F%2Fadlnet%2Egov%2Fexpapi%2Fverbs%2Fexperienced%22%7D%2C%22object%22%3A%7B%22id%22%3A%22http%3A%2F%2F6AftpAFkrXy%5Fcourse%5Fid%2F6WMoGiPhfsv%22%2C%22objectType%22%3A%22Activity%22%2C%22definition%22%3A%7B%22type%22%3A%22http%3A%2F%2Fadlnet%2Egov%2Fexpapi%2Factivities%2Fmodule%22%2C%22name%22%3A%7B%22und%22%3A%22FastPass%20%26%20MagicBands%22%7D%2C%22description%22%3A%7B%22und%22%3A%22FastPass%20%26%20MagicBands%22%7D%7D%7D%7D&Content%2DType=application%2Fjson

URL Decoded "content" parameter:
{"actor":{"name":"Old Yeller","objectType":"Agent","account":{"name":"aaatester","homePage":"https://otp.dev.com"}},"context":{"registration":"50a37f2c-7984-46d1-bbaa-0f7da96b0ce8","contextActivities":{"parent":{"id":"http://6AftpAFkrXy_course_id"},"grouping":{"id":"http://6AftpAFkrXy_course_id"}}},"version":"1.0.0","verb":{"id":"http://adlnet.gov/expapi/verbs/experienced"},"object":{"id":"http://6AftpAFkrXy_course_id/6WMoGiPhfsv","objectType":"Activity","definition":{"type":"http://adlnet.gov/expapi/activities/module","name":{"und":"FastPass & MagicBands"},"description":{"und":"FastPass & MagicBands"}}}}

4. Learning Locker response includes the following (with additional "message" details from exception after modifying line 120 of /app/controllers/xapi/StatementStoreController.php.

{"error":true,"success":false,"message":"Invalid JSON: JSON could not be parsed: Parse error on line 1:\n...dule\",\"name\":{\"und\":\"FastPass \n----------------------^\nInvalid string, it appears you forgot to terminated the string, or attempted to write a multiline string which is invalid","code":400,"trace":"`debug` must be `true` in the App's config to get a trace."}

**Expected behaviour**
Statement should not fail parsing and should be persisted to LRS

**Actual behaviour**
Statement fails parsing and course reports error back to user

**Additional information**
OS: any (LL is running on CentOS)
Browser: any

**Comment by chadabaker** [comment]
After some review, the error stems from the following function in (\locker\Request):

  public function getPayloadParams() {
    $payload = $this->getPayload();
    $decodedPayload = urldecode($payload);
    $payloadParams = [];
    parse_str($decodedPayload, $payloadParams); // Parse the payload into an AssocArray.
    $payloadParams = json_decode(json_encode($payloadParams), true);
    return $payloadParams;
  }


From the PHP docs: "parse_str" parses a string as if it were the query string passed via a URL and sets variables in the current scope.

This results in the ampersand being treated as the end of the parameter and the remainder of the JSON string being stripped (thereby terminating a string without a closing double-quote, among other issues).

Also noted in the comments of this function is that "parse_str" will automatically urldecode strings passed as arguments to the function.

Question is ... can we safely remove the explicit call to "urldecode" in the function above without affecting other uses of this function.

**Comment by ryansmith94** [comment]
Hi @chadabaker, thanks for reporting the issue. We're aware that the urldecode was added recently to fix another issue. We'll look into some alternatives and get back to you.

**Comment by ryansmith94** [comment]
Note to self:
```
  private function getAuth() {
    $result = [];

    // If the basic auth details are set, decode and return them.
    if ($this->hasParam(self::authParam)) {
      $auth = explode(' ', $this->getParam(self::authParam));
      if (count($auth) != 2) {
        // hack to retrieve Authorization header from Storyline, where it encodes the + value as part of the body "Content"
        $auth = explode('+', $this->getParam(self::authParam));
        if ($auth != 2) {
          // we couldn't find a valid user/pass set
          $result[self::authUser] = null;
          $result[self::authPass] = null;
          return $result;
        }
      }
      $decoded = base64_decode($auth[1]);
      $auth_parts = explode(':', $decoded);

      $result[self::authUser] = $auth_parts[0];
      $result[self::authPass] = $auth_parts[1];
    }

    // If the basic auth details are not set return a null user and password.
    else {
      $result[self::authUser] = null;
      $result[self::authPass] = null;
    }

    return $result;
  }
}
```

**Comment by ryansmith94** [comment]
Hi @chadabaker, we have reproduced the issue and have a fix for it. My previous comment demonstrates the changes that need to be made to two functions inside the ["app/locker/request/Request.php" file](https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/request/Request.php). I should get some time create a pull request for this tomorrow and release it for v1.13.5 👍

**Comment by chadabaker** [comment]
Excellent ... Thanks!

**Comment by ryansmith94** [comment]
Hi @chadabaker, this has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.

**Comment by chadabaker** [comment]
Got it ... thanks, again!

**Comment by ryansmith94** [comment]
You're very welcome 👍
