### ISSUE TITLE
Can't save statements 

### ISSUE THREAD

**Issue by salexfo** [LearningLocker/learninglocker#866]
Version: 1.13.5

When we try to send data from our app to learning locker here is the error we get:

error":true,"success":false,"message":"Argument 1 passed to Illuminate\\Auth\\Guard::setUser() must implement interface Illuminate\\Auth\\UserInterface, null given, 
called in \/var\/www\/vhosts\/learninglocker\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php on line 482 and defined","code":500,"trace":
"#0 \/var\/www\/vhosts\/learninglocker\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(682): Illuminate\\Exception\\Handler->handleError(4096, 'Argument 1 pass...', '\/var\/www\/vhosts...', 682, Array)
n#1 \/var\/www\/vhosts\/learninglocker\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(482): Illuminate\\Auth\\Guard->setUser(NULL)\
n#2 [internal function]: Illuminate\\Auth\\Guard->onceUsingId(Object(MongoId))\
n#3 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(8300): call_user_func_array(Array, Array)\
n#4 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(3267): Illuminate\\Support\\Manager->__call('onceUsingId', Array)\
n#5 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(3267): Illuminate\\Auth\\AuthManager->onceUsingId(Object(MongoId))\
n#6 \/var\/www\/vhosts\/learninglocker\/lrs\/app\/filters.php(72): Illuminate\\Support\\Facades\\Facade::__callStatic('onceUsingId', Array)\
n#7 \/var\/www\/vhosts\/learninglocker\/lrs\/app\/filters.php(72): Illuminate\\Support\\Facades\\Auth::onceUsingId(Object(MongoId))\
n#8 [internal function]: {closure}(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\
n#9 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(6259): call_user_func_array(Object(Closure), Array)\
n#10 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(6241): Illuminate\\Events\\Dispatcher->fire('router.filter: ...', Array, true)\n#11 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(5247): Illuminate\\Events\\Dispatcher->until('router.filter: ...', Array)\n#12 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(5229): Illuminate\\Routing\\Router->callRouteFilter('auth.statement', Array, Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#13 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(5181): Illuminate\\Routing\\Router->callAttachedBefores(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#14 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(5063): Illuminate\\Routing\\Router->callRouteBefore(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#15 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(5053): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#16 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(715): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#17 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(696): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#18 \/var\/www\/vhosts\/learninglocker\/lrs\/vendor\/itsgoingd\/clockwork\/Clockwork\/Support\/Laravel\/ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 \/var\/www\/vhosts\/learninglocker\/lrs\/vendor\/asm89\/stack-cors\/src\/Asm89\/Stack\/Cors.php(51): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(7825): Asm89\\Stack\\Cors->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(8432): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(8379): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#23 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(11138): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#24 \/var\/www\/vhosts\/learninglocker\/lrs\/bootstrap\/compiled.php(657): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#25 \/var\/www\/vhosts\/learninglocker\/lrs\/public\/index.php(49): Illuminate\\Foundation\\Application->run()\n#26 {main}

The expected behaviour is of course for the data to be stored. Instead we get a 500 error code and the exception above. Nothing changed but the version of learning locker

**Comment by ryansmith94** [comment]
Hi @salexfo, thanks for reporting this bug. This is one we've seen before and thought we'd fixed but clearly not. Issue #820 and #854 may be of use here.

If you not what you're doing in Mongo, I believe you can follow the steps below to resolve this issue.

1. Run `db.users.find({}, {_id: 1}).limit(1)`
1. That will return some JSON with a `_id` field like `{ "_id" : ObjectId("XXX") }`
1. Copy the ObjectId and paste it into the next command where you see `ObjectId("XXX")`
1. Run `db.lrs.update({}, {$set: {owner_id: ObjectId("XXX")}}, {multi: true})`

This will make the first user in your LRS (the super user), the owner of all of the LRSs.

**Comment by ryansmith94** [comment]
Hi @salexfo, this issue is being closed due to inactivity and will be reopened if it later becomes active.
