### ISSUE TITLE
Question: Why does client have authority settings?

### ISSUE THREAD

**Issue by s512** [LearningLocker/learninglocker#872]
Hi, a bit confused about the authority settings when editing a client record - you can set email, encrypted_email, open ID or account.  But what function does this provide? 

I have an LMS that will be reporting to an LRS.  I set up a client and use the username/password of this client to authorise the request.  As far as I can't tell, changing the client authority settings has no effect on the statements sent.  They are still saved.

As I understand it, authority is used in a statement to define who is asserting the statement is true.  So why is it also included in the client record?

I'm probably mis-understanding the spec, so any information would be much appreciated.

Thanks,
Sam

**Comment by ryansmith94** [comment]
Hi Sam (@s512), thanks for your question. The authority settings determine the authority object that is set on each statement that is sent using the client's credentials.

You're correct that the "authority is used in a statement to define who is asserting the statement is true", however the specification also states that "the asserting authority represents the authenticating user or some system or application", hence why these settings are specified with the client.

Beyond providing a trace of who/what sent the statement, it doesn't really have much use unless you make some use of it when you retrieve statements from the LRS.

I hope that helps.

**Comment by s512** [comment]
Thanks for your speedy response! 

I think I'm clear. Just to double check: if no authority is set in the statement, the learning locker will automatically set it to the authority settings on the client record? 

Thanks again.

**Comment by ht2** [comment]
Hi @s512, that is correct

**Comment by s512** [comment]
Makes sense, thank you!
