### ISSUE TITLE
ERROR while open the statements listing page in learning locker

### ISSUE THREAD

**Issue by dhanabalanc** [LearningLocker/learninglocker#877]
Hi,

The below issue arises while open the statements listing page in learning locker

 **error processing query: ns=learninglocker.statementsTree: lrs_id == ObjectId('5811aa3b58aace4025000029') Sort: {} Proj: {} planner returned error: bad hint**

How to fix it ... 

Regards,
Dhanabalan.cs

**Comment by ryansmith94** [comment]
Hi @dhanabalanc, thanks for reporting your issue. This is an issue we've seen before in #854. Please see that issue for the solution and confirm that it resolves your issue so that we may close this one.

**Comment by dhanabalanc** [comment]
Thank Ryan Issue Fixed

**Comment by ryansmith94** [comment]
Brilliant, you're welcome @dhanabalanc 👍
