### ISSUE TITLE
Unable to send xAPI statements to Grassblade LRS

### ISSUE THREAD

**Issue by yashbantm** [LearningLocker/learninglocker#879]
Hi all,

We are trying to republish our articulate based modules for TIN CAN grassblade LRS.

We found some solution from the below link(https://www.articulate.com/tincanapi/) but still there is 

no reporting happening on Grassblade.

We need your support team help to short it out please find the 

publish URL details also.

or just guide us how could we published our Articulate Storyline 2 modules for Grassblade LRS.

http://mednl.com/tincantest/c1/story.html?endpoint=http://eptral.com/grassblade-

lrs/xAPI/&auth=MTQtNDVlNjYwNmU2YjkwYjc2OmEyYmZkNTJhYWNmN2UwNjdhYTk3YTdkZjc=&actor=

{"mbox":"mailto:ex@mple.co.uk", "name":"Example User"}

&activity_id=5pmXx3XAGvX_course_id&registration=2981c910-6445-11e4-9803-0800200c9a66

API USER: 14-45e6606e6b90b76 PW:a2bfd52aacf7e067aa97a7df7

**Comment by ht2** [comment]
@yashbantm Sorry, as per my comment in #878, I'm unclear how this relates to Learning Locker?

Also unsure why you have made a duplicate issue? I will close the other one in the meantime........................

**Comment by yashbantm** [comment]
Hi can i use learning locker for the above problem to i mean does learning locker could help us to published our articulate based emodules and send the report to LL LRS?

**Comment by ht2** [comment]
You need to change your auth signature to `auth=Basic MTQtNDVlNjYwNmU2YjkwYjc2OmEyYmZkNTJhYWNmN2UwNjdhYTk3YTdkZjc`


Just FYI, you are not using Learning Locker in any part of this solution. In future please contact your LRSs support (Grassblade) for this kind of enquiry.

**Comment by yashbantm** [comment]
Thank you. How to use Learning Locker for my modules how to get register or download could you please help?

**Comment by ryansmith94** [comment]
Hi @yashbantm, [our documentation](http://docs.learninglocker.net/installation/) has installation instructions and guides. If you're not a technical person, you can go for [our enterprise solution](https://www.ht2labs.com/learning-locker/lrs-pricing/).

**Comment by yashbantm** [comment]
Can you please share some video tutorial about LL how its works and all please before we decide?

**Comment by ryansmith94** [comment]
@yashbantm a [list of Learning Locker's features](https://www.ht2labs.com/learning-locker/enterprise-lrs-features/) can be found on [our website](https://www.ht2labs.com/learning-locker/). You can also request a demo via our website.

In addition, there are also lots of videos and other resources in our [Learn xAPI MOOC](http://beta.curatr3.com/courses/xapi-2016) that help you learn more about the xAPI and Learning Locker.

**Comment by yashbantm** [comment]
Dear ryansmith94, 

I am very new to this field so i may sound different to you please support,
what i need to know is actually that till now we are developing a module using authoring tool(iSpring) where we are publishing as TIN CAN format and inserting the end point(Grassblade LRS) and auth directly on the iSpring tool and user learning report were recording on Grassblade LRS(WHICH WE COULD SEE after login).

So my question is how could we do this using Learnin Locker LRS, also as we have so may modules which has been developed using Articulate Storyline 2 SCORM based we need to covert those into TIN CAN for reporting on LRS, but grassblade LRS is not supporting but LL can so we need your guidance kindly help.

**Comment by ryansmith94** [comment]
Your link works just fine for me @yashbantm 

http://mednl.com/tincantest/c1/story.html?endpoint=http://eptral.com/grassblade-lrs/xAPI/&auth=Basic%20MTQtNDVlNjYwNmU2YjkwYjc2OmEyYmZkNTJhYWNmN2UwNjdhYTk3YTdkZjc=&actor={"mbox":"mailto:ex@mple.co.uk","name":"Example%20User"}&activity_id=5pmXx3XAGvX_course_id&registration=2981c910-6445-11e4-9803-0800200c9a66

Learning Locker would require the same URL to be used.

**Comment by ht2** [comment]
Hi @yashbantm, just FYI, Learning Locker is an open source LRS which you can install and run on your own hardware _if you have the technical know how to operate and configure a LAMP server and a Mongo database_.

If you do not wish to do that yourself then you may be interested in contacting us via contact details on  https://learninglocker.net/ for different hosting/support options.

**Comment by yashbantm** [comment]
Dear ryansmith94,

Could you please explain how it working for you as I can see the report in my LRS!!

What I need to do where I am wrong please.


I am using the same link for publishing but not working for me please guide.
Please check the screenshot

![screenshot_4](https://cloud.githubusercontent.com/assets/23094305/19765392/c4dc9f7a-9c65-11e6-8bb6-1cc5634ecacc.jpg)

**Comment by ht2** [comment]
@yashbantm Did you add the `Basic ` to the auth like I said?

**Comment by yashbantm** [comment]
Yes i did. Shall i copy your link(URL)... do i need to keep those %20 sign also for spacing or shall i remove? Do i need to upload anywhere after published?

because after publishing when i play the Story.html no reporting happening.

**Comment by ht2** [comment]
Sorry @yashbantm, we can't offer support on Storyline content. it's not really our thing. The link @ryansmith94 posted works so I would work off that. If you have further problems, please contact Articulate Storyline or Grassblade for assistance.

**Comment by yashbantm** [comment]
Dear @ryansmith94,

That is ok but please let us know where we are wrong before we shifting to LL. No need to tell about Storyline but just let us know after publishing do we need to upload on LL or what are the steps please.

**Comment by yashbantm** [comment]
Kindly reply

**Comment by ht2** [comment]
An LRS (like Grassblade or Learning Locker) is simply a place to hold the user's progress. Content is not uploaded, stored or served by an LRS.

**Comment by yashbantm** [comment]
Hi,

Than where is the issue is this publishing issue or something else? how come its working for your link we have the following doubt:

1. Your link is working without you having the source file means you dont require to publish
2. What procedure you are using
3. If you go for LL LRS how we need to do 

We request you please explain so that we could 100% before using LL and also tell to our client

**Comment by yashbantm** [comment]
Please reply and clear query for better undersating

**Comment by andrewhickey** [comment]
Hi @yashbantm, to receive support on the use of Learning Locker and consultation on bespoke solutions you will need to be an enterprise customer. Please see https://learninglocker.net/support/ for more information.
