### ISSUE TITLE
500 error thrown during API requests

### ISSUE THREAD

**Issue by dmurphy331** [LearningLocker/learninglocker#880]
**Version**
1.14.0

**Steps to reproduce the bug**
1. Using Guzzle HTTP client to call GET api/v1/reports with correct auth username and password located under LRS Manage Clients.

**Expected behaviour**
Should return all reports in the LRS.

**Actual behaviour**
Get the following 500 error
`Argument 1 passed to Illuminate\\Auth\\Guard::setUser() must implement interface Illuminate\\Auth\\UserInterface, null given, called in \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php on line 482 and defined`

**Additional information**
OS: Ubuntu 14.04.5 LTS
The same error is thrown when trying to view/create reports and view/create exports within the user interface.

**Comment by ht2** [comment]
Hi @dmurphy331, please refer to these issues:

https://github.com/LearningLocker/learninglocker/issues/820
https://github.com/LearningLocker/learninglocker/issues/854
https://github.com/LearningLocker/learninglocker/issues/866#issuecomment-249573663

**Comment by ht2** [comment]
Closing as duplicate - if you follow @ryansmith94's steps and still come up with issues we can look into it further.
