### ISSUE TITLE
Add SAML authentication support

### ISSUE THREAD

**Issue by kurtclifford** [LearningLocker/learninglocker#881]
It would be great to see SAML authentication support added into Learning Locker. This can greatly improve security concerns in enterprises requiring a single source of truth for authentication sources.

**Comment by kurtclifford** [comment]
Also allowing account creation and attribute updating via SAML would be amazing.

**Comment by WillSkates** [comment]
@kurtclifford What attributes would you require?

**Comment by ht2** [comment]
Just to note, this is a great (almost defacto standard) library for accomplishing this. We've used it on other projects to great success
https://simplesamlphp.org/

**Comment by ryansmith94** [comment]
Archiving due to inactivity.
