### ISSUE TITLE
Manage Multiple different database connections in Learning Locker?

### ISSUE THREAD

**Issue by dhanabalanc** [LearningLocker/learninglocker#882]
Hi ,
I need clarifications for below scenarios. I need  to use multiple different DB for my projects like mongo and Mysql.

**scenario:**
1. For API purpose , I need MYSQL connection
2. For Learning Locker Config need MONGO connection

Is it possible to achieve. How?? . Please guide me.

Regards,
Dhanabalan.c

**Comment by ryansmith94** [comment]
Hi @dhanabalanc. I'm not sure I'm following this issue 100% either. Can you please provide more details here too.

**Comment by ht2** [comment]
Hi @dhanabalanc, you need to look at this: http://fideloper.com/laravel-multiple-database-connections
