### ISSUE TITLE
How  to achive API server [Oauth] and Learning Locker in Same Project?

### ISSUE THREAD

**Issue by dhanabalanc** [LearningLocker/learninglocker#883]
Hi,,

How can i Run API server  [Oauth] and Learning Locker in Same Project.

Is it possible below scenarios, Please help me find solutions.

**Learning Locker Base:**

**Scenario 1:**
http://localhost:8000/api/user/validate [Api server run in 8000 port]

**Scenario 2:**
http://localhost:8000/public//lluserlist [Api server run in 8080 port - List users using learning locker]

Is it possible to achieve, both in same project. if not please provide a solution.

Regards,
Dhanabalan.c

**Comment by ryansmith94** [comment]
Hi @dhanabalanc, thanks for your question. I'm not 100% sure that I'm following this. Can you please provide more details? It sounds to me like you've wrote some code that you want to run on port 8000 and you want to run Learning Locker on the same server over port 8080.

**Comment by dhanabalanc** [comment]
@ryansmith94 

I have given my api code below:

Step1: My Route

$api->version('v1', function($api) {
	$api->get('hello', function() {
		return 'HELLO';
	});
});

step2: Run php artisan serve command.. My api server directly runs on 8000 port
Sample URL: http://localhost:8000/api/hello

------------------
step 3: I have another routing in the same route.php

	 Route::get('/userlist', 'UserController@index');
The above routing runs on 80 port
sample URL: http://localhost:80/userlist

My Question: 1. I want to run both api (step1) & step3 in 80 port.
is it possible.. if need clarifcation please let me know.


Dhanabalan.c

**Comment by dhanabalanc** [comment]
I have given my api code below:

Step1: My Route

$api->version('v1', function($api) {
$api->get('hello', function() {
return 'HELLO';
});
});

step2: Run php artisan serve command.. My api server directly runs on 8000 port
Sample URL: http://localhost:8000/api/hello

step 3: I have another routing in the same route.php

 Route::get('/userlist', 'UserController@index');
The above routing runs on 80 port
sample URL: http://localhost:80/userlist

My Question: 1. I want to run both api (step1) & step3 in 80 port.
is it possible.. if need clarifcation please let me know.

Dhanabalan.c****

**Comment by ryansmith94** [comment]
Hey @dhanabalanc, this is more of a Laravel issue than a Learning Locker issue. You should be able to discuss it in the [Laravel Chat](http://laravel.io/chat). Sorry for the slow reply, been mega busy the past week and this issue just got backlogged, thanks for the bump.
