### ISSUE TITLE
Remove _id from Mongodb?

### ISSUE THREAD

**Issue by dhanabalanc** [LearningLocker/learninglocker#884]
{
    "_id": {
      "$id": "58216cdfa66b900398066918"
    },
    "name": "Jack Matt",
    "mBox": "jack.m@lrs.com",
    "orgId": "test",
    "divId": "",
    "email": "jack.m@lrs.com",
    "crsId": "test-DM01",
    "sesId": "111222",
    "progress": 100,
    "verb": "completed",
    "status": "completed"
  },

**I need to remove 
"_id": {
      "$id": "58216cdfa66b900398066918"
    },
from json. how to remove?**  using php

Regards,
Dhanabalan.c

**Comment by ht2** [comment]
Please resubmit this issue inline with the contributing and troubleshooting guidelines:

https://github.com/LearningLocker/learninglocker/blob/develop/contributing.md
http://docs.learninglocker.net/troubleshooting/
