### ISSUE TITLE
Occassional mongodb connection timeouts

### ISSUE THREAD

**Issue by davidscholberg** [LearningLocker/learninglocker#887]
We are experiencing occassional mongodb connection timeouts in LRS. This only happens after LRS is idle for a period of time.

**Version 1.13.3**

**Steps to reproduce the bug**
1. Setup an LRS instance with a firewall (iptables) in between the LRS and mongodb instance.
2. Send some requests to LRS, then let it idle for an hour or two, then send another request to the LRS.

**Expected behaviour**
The request returns successfully.

**Actual behaviour**
The request fails with the following error:

```
MongoConnectionException (71)

HELP
Callstack information; navigate with mouse or keyboard using Ctrl+↑ or Ctrl+↓
Copy-to-clipboard button
Exception message and its type
Code snippet where the error was thrown
Server state information
Application provided context information
 MongoConnectionException thrown with message "Failed to connect to: mongo.teamgleim.com:27017: Remote server has closed the connection"Stacktrace:#23 MongoConnectionException in /var/www/learning-locker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:133#22 MongoClient:__construct in /var/www/learning-locker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:133#21 Jenssegers\\Mongodb\\Connection:createConnection in /var/www/learning-locker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:40#20 Jenssegers\\Mongodb\\Connection:__construct in /var/www/learning-locker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/MongodbServiceProvider.php:32#19 Jenssegers\\Mongodb\\MongodbServiceProvider:Jenssegers\\Mongodb\\{closure} in <#unknown>:0#18 call_user_func in /var/www/learning-locker/bootstrap/compiled.php:7615#17 Illuminate\\Database\\DatabaseManager:makeConnection in /var/www/learning-locker/bootstrap/compiled.php:7576#16 Illuminate\\Database\\DatabaseManager:connection in /var/www/learning-locker/vendor/jenssegers/mongodb-session/src/Jenssegers/Mongodb/Session/SessionManager.php:56#15 Jenssegers\\Mongodb\\Session\\SessionManager:getMongoDBConnection in /var/www/learning-locker/vendor/jenssegers/mongodb-session/src/Jenssegers/Mongodb/Session/SessionManager.php:14#14 Jenssegers\\Mongodb\\Session\\SessionManager:createMongoDBDriver in /var/www/learning-locker/bootstrap/compiled.php:8281#13 Illuminate\\Support\\Manager:createDriver in /var/www/learning-locker/bootstrap/compiled.php:8271#12 Illuminate\\Support\\Manager:driver in /var/www/learning-locker/vendor/jenssegers/mongodb-session/src/Jenssegers/Mongodb/Session/SessionServiceProvider.php:20#11 Jenssegers\\Mongodb\\Session\\SessionServiceProvider:Jenssegers\\Mongodb\\Session\\{closure} in /var/www/learning-locker/bootstrap/compiled.php:8287#10 Illuminate\\Support\\Manager:callCustomCreator in /var/www/learning-locker/bootstrap/compiled.php:8179#9 Illuminate\\Session\\SessionManager:callCustomCreator in /var/www/learning-locker/bootstrap/compiled.php:8279#8 Illuminate\\Support\\Manager:createDriver in /var/www/learning-locker/bootstrap/compiled.php:8271#7 Illuminate\\Support\\Manager:driver in /var/www/learning-locker/bootstrap/compiled.php:7896#6 Illuminate\\Session\\Middleware:getSession in /var/www/learning-locker/bootstrap/compiled.php:7843#5 Illuminate\\Session\\Middleware:startSession in /var/www/learning-locker/bootstrap/compiled.php:7822#4 Illuminate\\Session\\Middleware:handle in /var/www/learning-locker/bootstrap/compiled.php:8432#3 Illuminate\\Cookie\\Queue:handle in /var/www/learning-locker/bootstrap/compiled.php:8379#2 Illuminate\\Cookie\\Guard:handle in /var/www/learning-locker/bootstrap/compiled.php:11123#1 Stack\\StackedHttpKernel:handle in /var/www/learning-locker/bootstrap/compiled.php:657#0 Illuminate\\Foundation\\Application:run in /var/www/learning-locker/public/index.php:49
Failed to connect to: mongo.teamgleim.com:27017: Remote server has closed the connection
```
Any requests following the failed one work fine.

**Additional information**
We have a firewall on our mongodb server, and the firewall logs show the mongodb traffic being blocked because the firewall isn't tracking the connection anymore. Subsequent requests work fine since (presumably), a new mongodb connection is being created, which the firewall is able to track and allow through.

My guess as to what's happening on the LRS end is that the mongodb connection is being cached for use in multiple requests, and when LRS is idle for a while and then attempts to reuse the existing mongodb connection, the firewall rejects the traffic as untracked, and LRS returns an error back to the client.

What we'd like to see is a config option for us to specify a certain number of connection retry attempts before LRS considers the connection failed. I'm not aware of any such option, but I did find a similar issue submitted by @ryansmith94 to the [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb/issues/508) project. It looks like @ryansmith94 submitted a patch for it, but I don't know if it got merged or if laravel exposes it as a config option. Any help is appreciated.

**Comment by davidscholberg** [comment]
Just to add to this, Symfony already has the functionality I'm looking for, documented here: http://symfony.com/doc/master/bundles/DoctrineMongoDBBundle/config.html#retrying-connections-and-queries. I was just wondering if LRS and/or Laravel had the same functionality.

**Comment by ryansmith94** [comment]
Hi @davidscholberg, thank you very much for posting your issue and I really appreciate you taking the time to provide the additional information. Well done for finding my issue in that repository! 😄 

Since they didn't merge my pull request, I'd recommend [changing the code in the same way I did](https://github.com/jenssegers/laravel-mongodb/pull/510/files) for your installation of Learning Locker. You should be able to find that file inside the `vendor/jenssegers/laravel-mongodb` directory of your Learning Locker installation. 

I hope that helps.

**Comment by ryansmith94** [comment]
I'm going to close this issue for now, I hope that's ok. I'll reopen this if more is required 😄
