### ISSUE TITLE
users.registration.click showing up in registration email

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#894]
**Version**
v1.15.0

**Steps to reproduce the bug**

1. Create new LL instance (not an upgrade)
2. Browse to registration page
3. Fill in registration details
4. Open registration confirmation email
5. Look next to the verification link for "users.registration.click"

**Expected behaviour**
Guessing users.registration.click isn't supposed to appear and should only contain the link

**Actual behaviour**
users.registration.click appears as plaintext next to the verification link

**Additional information**
OS: CentOS 7.3
Browser: Chrome 56.0.2924.87
LL instance is secured with HTTPS

**Comment by ryansmith94** [comment]
Thanks @davidpesce, this looks like a missing language string in our language files 👍

**Comment by davidpesce** [comment]
It looks like the correct var should be users.registration.instructions. Do you want the lang var changed in the app/lang/users.php file? 

users.registration.click seems like a more descriptive var (for what it is) than users.registration.instructions. I can make the change and submit a PR, just let me know what you'd like.

**Comment by ryansmith94** [comment]
Hi @davidpesce, I think you're right. Yep please do make the PR. I'll try to get it into the next release, we have a bug to fix so we might make a release very soon.

**Comment by davidpesce** [comment]
I can do it today. I also noticed a typo in app/lang/lrs.php

`    	'created_fail' => 'The client was not created sucecssfully. Sorry.',
    	'created_sucecss' => 'The client was created sucecssfully. Hurrah!',
`

I can submit those in the same PR if you are cool with that.

**Comment by ryansmith94** [comment]
Awesome. Yeah I'm cool with that cheers @davidpesce 👍
