### ISSUE TITLE
"Password has been reset" title appears when clicking verification email link

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#895]
**Version**
v1.15.0

**Steps to reproduce the bug**

1. Create new LL instance (not an upgrade)
2. Browse to registration page
3. Fill in registration details
4. Open registration confirmation email
5. Look next to the verification link for "users.registration.click"
6. Click verification link
7. "Your password has been reset" appears above the login

**Expected behaviour**
The message above the login should say "Your email/account has been confirmed/verified"

**Actual behaviour**
The message says, "Your password has been reset". The password doesn't appear to have been reset, because I can log in with my existing un/pw.

**Additional information**
OS: CentOS 7.3
Browser: Chrome 56.0.2924.87
LL instance is secured with HTTPS

**Comment by ryansmith94** [comment]
Wow that's interesting. Thanks @davidpesce and extra thanks for following the guidelines!

**Comment by davidpesce** [comment]
This is resolved.

**Comment by ryansmith94** [comment]
Thanks @davidpesce, forgot to close this 👍
