### ISSUE TITLE
Broken dependancies : barracuda/copy through league/flysystem

### ISSUE THREAD

**Issue by mat250** [LearningLocker/learninglocker#896]
**Version**
master on 1.15.0

**Steps to reproduce the bug**
Install a fresh instance of Learning Locker

**Actual behaviour**
The following package is now abandoned : https://packagist.org/packages/barracuda/copy
The original github page seems to be down too : https://github.com/copy-app/php-client-library/
So it's now a broken dependancy with `league/flysystem`.

**Client information**
OS: Ubuntu 14.04

**Additional information**
I try to get through this removing the `league/flysystem` in composer.json file, but I expect some trouble when running the code...

**Comment by rigao-alexandre** [comment]
Same issue here.

So far, I have had no problems since I did not perform any integration with the Copy services.

**Comment by ryansmith94** [comment]
Thanks @mat250 @rigao-alexandre. I think we need to see if we can upgrade FlySystem @ht2, looks like they removed the dependency in thephpleague/flysystem/pull/623

**Comment by ryansmith94** [comment]
Hi @mat250 @rigao-alexandre. Can you please try using the issue/896 branch instead of the master branch in the installation process?

So you'd use this in the [download and install steps](http://docs.learninglocker.net/installation/#download-and-install):

```sh
git clone -b issue/896 git@github.com:LearningLocker/learninglocker.git learninglocker
```

instead of this:
```sh
git clone -b master git@github.com:LearningLocker/learninglocker.git learninglocker
```

**Comment by mat250** [comment]
Hi @ryansmith94 
Composer was fine this time. I've finished the installation of Learning Locker and I succeed to reach the login page.
Looks fine for me.
Thanks !

**Comment by ryansmith94** [comment]
Awesome thanks for testing that out @mat250 👍

**Comment by rigao-alexandre** [comment]
Sorry for the delay

Everything worked perfectly now!

Thanks!

**Comment by ryansmith94** [comment]
No worries. Good to hear, thanks for letting us know @rigao-alexandre
