### ISSUE TITLE
Failed to connect to: localhost:27017

### ISSUE THREAD

**Issue by duschata** [LearningLocker/learninglocker#901]
{{question}}?
This works
`tom@owly:~/src/webapps/php/learninglocker$ mongo --port 27017 -u "tom" -p "blafasel" --authenticationDatabase "lrs"
MongoDB shell version: 2.6.10
connecting to: 127.0.0.1:27017/test
> use lrs
switched to db lrs
> db.lrs.insert({"bla" : "fasel"})
WriteResult({ "nInserted" : 1 })
`
this is my app/config/local/database.php:

`<?php

return [
  'connections' => [
                'mongodb' => [
        'driver'   => 'mongodb',
        'host'     => 'localhost',
        'port'     => 27017,
        'username' => 'tom',
        'password' => 'REDACTED',
        'database' => 'lrs' // Default name (removing this makes Travis fail).
    ],
        ],
];
`
when I try to use the command:
/usr/bin/php5.6 artisan migrate

I got:
Status: 500 Error: Failed to connect to: localhost:27017: Connection refusedSegmentation fault (core dumped)

Any hints for me, how to debug this? Installation process with composer worked without an error. 
I'm on an Ubuntu 16.04 with default mongo 3.4 installation. PHP is 5.6 from PPA.  Code is a current clone from here.

Regards
Tom

**Comment by ht2** [comment]
Hi Tom,

Your Mongo looks like it is configured incorrectly - either it is not setup on port 27017 or it is not turned on etc.. Hard for us to debug and a bit out of our remit. However I would advise you have a look at these resources:

https://docs.mongodb.com/manual/security/
http://stackoverflow.com/questions/4961177/how-to-listen-only-to-localhost-on-mongodb

But in truth it could be a lot of other different things that we won't be able to diagnose.

I did notice you say you are using a Mongo 3.4 installation, but the shell version is 2.6... I would suggest a fresh clean install as you may have previous configurations that are causing problems?

**Comment by ht2** [comment]
I have also removed your password credentials from the original post - I would recommend not posting those online, even if only in a dev environment.

**Comment by duschata** [comment]
Thanks a lot. The host was set to localhost in database.php but 127.0.0.1 is the correct value according to my /etc/mongodb.conf.
Thank you for deleting the pw. The german word blafasel is like foobar in english. So this is not the real pw.

**Comment by ht2** [comment]
> The german word blafasel is like foobar in english. So this is not the real pw.

Good to know! 

Regarding the localhost/127.0.0.1, I would check your `/etc/hosts` file, either should work if setup correctly.

**Comment by duschata** [comment]
realy, your are right. My localhost is mapped to 127.0.1.1. I've no clue why. Thanks a lot

**Comment by sathsara1** [comment]
check whether you have turned off your firewall.
