### ISSUE TITLE
Learning Locker support with new mongodb driver (mongodb 1.2) of PHP

### ISSUE THREAD

**Issue by KulkarniRashmi** [LearningLocker/learninglocker#903]
Hi All,
Currently I am running
PHP: 5.6
Mongo DB Version: 2.6
Learning locker (1.13. Uses Laravel 4.2) https://github.com/LearningLocker/learninglocker
Mongo driver(1.6) for PHP (This is legacy driver. Not using mongodb driver)

Now I want to upgrade to latest mongodb Driver (1.2) for PHP
However, current laravel-mongodb package (version 3.2) supports new mongodb driver. Laravel-mongodb package is compatible with Laravel 5.4.

Please help me with
1) Will Learning Locker 1.13 support Laravel 5.4? 
2) Right approach for using new mongodb driver for PHP with current learning locker

Your help will be highly appreciated.

**Comment by ht2** [comment]
There are currently no plans to upgrade Learning Locker to either the new Mongo driver or Laravel 5 unless done through the community.

**Comment by KulkarniRashmi** [comment]
Thanks ht2 for your response.

Does it mean new mongodb PHP driver cannot work with learning locker? Is there any work around to make it work? 
The reason we are looking for this is - we need to upgrade Mongo database which in turn needs new mongodb driver but at the same time, we need this for learning locker.

**Comment by ht2** [comment]
The legacy Mongo driver works perfectly with Mongo 3.2 and we've seen OK results (albeit not in production) for 3.4. The driver support page does not explicitly mention it, but I spoke to the PHP driver maintainer at Mongo World 2016 and he said that whilst not "officially" supported, it is fine to work with 3.2. The reason for no official support was in case they added additional features down the line that broke compatibility.
