### ISSUE TITLE
Converting this app to PHP7, having issues with Session not being remembered.

### ISSUE THREAD

**Issue by barneydmedia** [LearningLocker/learninglocker#907]
I was in contact with your CEO a couple of months back about the work I'm doing to convert LL to PHP7 and the newer MongoDB php driver. I'm approaching the end, but I'm having some issues with sessions not being remembered. I don't expect you guys to solve my problem since it's a personal fork, but I would greatly appreciate any guidance you can provide as to troubleshooting why sessions aren't being remembered.

Essentially, each and every request is generating a new session even if I just refresh the login screen. This is a major issue since it prevents using CSRF, but it also causes issues getting logged in since the user isn't remembered after authenticating successfully.

I'm using Mongo for sessions and after each request I can see that a new session has been created. This is running locally so there is no chance these sessions are being created for other users, and I have similarly tested using the file driver to rule out any mongo related issues.

FWIW, I'm hoping to finish this out for my employer's internal use but I have permission from them to offer a PR with my finished updates and I plan to release a more user friendly version of the custom docker container I've built as well.

**Version**
Personal Fork at 3b2bf9d on 1.15.0

**Steps to reproduce the bug**
1.Register User (completes successfully)
2. Login (successful but forgets session)

**Expected behaviour**
Redirect after login should lead to site.index because auth for super was completed successfully.

**Actual behaviour**
Auth completes successfully but is then redirected back to login form without error, due to forgotten session.

**Additional information**
OS: Ubuntu 16.04 (Docker container) running under OSX Sierra
Browser: Chrome version 57.0.2987.98

**Comment by barneydmedia** [comment]
I seem to have fixed this issue, but I have no idea how :|

**Comment by davidpesce** [comment]
Happy to test things out when you get closer to release.
