### ISSUE TITLE
Bug: buttons left menu not working

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#908]
**Version**
1.15.1

After installation:
Buttons on left menu not working. For example, if i press the "users" button I just get "/site#users" on the url.

The button list "LRS list" just work if I jump to the settings page.

After add a new LRS I didn't get the admin dashboards.

Any help???

I followed this tutorial guide for installation: https://www.youtube.com/watch?v=51Dci7B49xA

**Comment by ht2** [comment]
If you open your developer tools and check the network panel you will see that clicking these links should trigger an XHR request to fetch the users/lrs etc. A page navigation is _not_ called by pressing these buttons.

Please confirm 
a) That the network requests are happening
b) That they return 200
c) If not, check your error logs

If everything is working as it should, check that you have javascript enabled in your browser.

**Comment by rena7o8** [comment]
Actually I am getting js errors: localization.js and require.js. And also message(lang is not defined ...).
About the XHR requests, nothing shows up!

![error](https://cloud.githubusercontent.com/assets/26470305/24193052/d4fe1d16-0ee8-11e7-9fa6-cbe4a89c9c6a.jpg)

**Comment by ht2** [comment]
Please see issue #451. You may also find this Google Group post of interest: https://groups.google.com/d/msg/learning-locker/PvaP4wgbQNY/J-GDpo0iRu8J

**Comment by rena7o8** [comment]
I did the following commands like suggested "apt-get install nodejs-legacy" and then relan" composer.phar install".

But i still get the "require.js" error...

**Comment by ht2** [comment]
Sorry @rena7o8, I'm not sure what else we an do to help. There are instructions about making copies of the required files into your `/public` dir to solve this, but basically the issue is you have a misconfiguration somewhere. Note that in the URL of one of the errors there is reference to `index.php` - this shouldn't be the case. Unfortunately there's not much more we can offer here

**Comment by rena7o8** [comment]
Solved!
I just changed a line in apache2.conf ->  "Allowoverride None" to "Allowoverride All" for "/var/www" directory.

Thanks!

**Comment by RyanFramePRA** [comment]
I'm having this same issue. I've followed every solution I have found. moving the localization file corrected the first part but still have the require.js issue. I installed bower and and reran the composer install. set allowoverride all in the apache2 config. Hit a wall wiped the server and started from scratch still having the exact same issue.

**Comment by RyanFramePRA** [comment]
it was an issue with mod_rewrite not loading in apache

**Comment by jpparamor** [comment]
I'm experiencing the same issue using 1.17 on a Mac.  Getting 404 on http://localhost:8080/index.php/assets/js/libs/require/require.js when trying to render the Dashboard, Reports or Export screens which appear blank except for the title. 

The require.js file is on the filesystem and will render if I go directly to http://localhost:8080/assets/js/libs/require/require.js in a browser.

I've set the allow override all in the httpd.conf and mod_rewrite is uncommented so should be getting loaded.
