### ISSUE TITLE
Combine platform with learninglocker

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#909]
I added a new folder with html pages in "/var/www/html/myplatform". My learninglocker index.php is located in "/var/www/html". 

I am trying to add a new platform on this directory "/var/www/html" but I get this error:

"Trying to get property of non-object (View: /var/www/html/learninglocker/app/views/system/navbar.blade.php)".

It seems that learninglocker is taking control.

Any suggestion?

**Comment by ht2** [comment]
I'm sorry, but this is an Apache configuration problem and we can't support you on this.
