### ISSUE TITLE
What is the maximum domain extension length for actor.mbox?

### ISSUE THREAD

**Issue by adrian-sarmas** [LearningLocker/learninglocker#913]
I am using v1.11.0 of Learning Locker.
I get this error in the Javascript console:

`"emailaddress@demo.today should be a valid Locker\\XApi\\Mailto in statement.actor.mbox"`

I've noticed that Learning Locker accepts only domain extensions that have max 4 characters.
emailaddress@demo.today -> does NOT work (today = 5 characters)
emailaddress@demo.toda -> works (toda = 4 characters)
emailaddress@demo.tod -> works (tod = 3 characters)

### Request
**Request URL:** http://LRSURL/public/data/xAPI/statements?method=PUT
**Method:** PUT
**Request Payload:**
Content-Type=application/json&statementId=XXXXXXXXX&Authorization=Basic XXXXXXXXX&content={"result":{"completion":false},"version":"1.0.0","actor":{"name":"Admin User","mbox":"mailto:emailaddress@demo.today","objectType":"Agent"},"context":{"contextActivities":{"grouping":{"id":"XXXXXXXXX"},"parent":{"id":"XXXXXXXXXX}},"registration":"XXXXXX"},"object":{"definition":{"name":{"und":"XXXXXXXXXXXX"},"description":{"und":""},"type":"http://adlnet.gov/expapi/activities/course"},"objectType":"Activity","id":"XXXXXXXXXXXXXX"},"verb":{"id":"http://adlnet.gov/expapi/verbs/attempted"}}&X-Experience-API-Version=1.0.1

### Response:
`{
	"error": true,
	"success": false,
	"message": [
		"`mailto:emailaddress@demo.today` should be a valid `Locker\\XApi\\Mailto` in `statement.actor.mbox`"
	],
	"code": 400,
	"trace": "#0 C:\\xampp\\htdocs\\lrs\\app\\locker\\repository\\Statement\\EloquentStorer.php(74): Locker\\Helpers\\Helpers::validateAtom(Object(Locker\\XApi\\Statement), 'statement')\n#1 C:\\xampp\\htdocs\\lrs\\app\\locker\\repository\\Statement\\EloquentStorer.php(35): Locker\\Repository\\Statement\\EloquentStorer->constructValidStatements(Array, Object(Locker\\Repository\\Statement\\StoreOptions))\n#2 C:\\xampp\\htdocs\\lrs\\app\\locker\\repository\\Statement\\EloquentRepository.php(31): Locker\\Repository\\Statement\\EloquentStorer->store(Array, Array, Object(Locker\\Repository\\Statement\\StoreOptions))\n#3 C:\\xampp\\htdocs\\lrs\\app\\controllers\\xapi\\StatementStoreController.php(129): Locker\\Repository\\Statement\\EloquentRepository->store(Array, Array, Array)\n#4 C:\\xampp\\htdocs\\lrs\\app\\controllers\\xapi\\StatementStoreController.php(86): Controllers\\xAPI\\StatementStoreController->createStatements(Array, Object(Closure))\n#5 C:\\xampp\\htdocs\\lrs\\app\\controllers\\xapi\\StatementController.php(63): Controllers\\xAPI\\StatementStoreController->update(Array)\n#6 C:\\xampp\\htdocs\\lrs\\app\\controllers\\xapi\\BaseController.php(44): Controllers\\xAPI\\StatementController->update()\n#7 [internal function]: Controllers\\xAPI\\BaseController->selectMethod()\n#8 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(231): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(93): Illuminate\\Routing\\Controller->callAction('selectMethod', Array)\n#10 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(62): Illuminate\\Routing\\ControllerDispatcher->call(Object(Controllers\\xAPI\\StatementController), Object(Illuminate\\Routing\\Route), 'selectMethod')\n#11 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(962): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'Controllers\\\\xAP...', 'selectMethod')\n#12 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()\n#13 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(109): call_user_func_array(Object(Closure), Array)\n#14 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1028): Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))\n#15 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(996): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#16 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(776): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#17 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(746): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#18 C:\\xampp\\htdocs\\lrs\\vendor\\asm89\\stack-cors\\src\\Asm89\\Stack\\Cors.php(51): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware.php(72): Asm89\\Stack\\Cors->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 C:\\xampp\\htdocs\\lrs\\vendor\\stack\\builder\\src\\Stack\\StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#23 C:\\xampp\\htdocs\\lrs\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(642): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#24 C:\\xampp\\htdocs\\lrs\\public\\index.php(49): Illuminate\\Foundation\\Application->run()\n#25 {main}"
}`

**Does Learning Locker allow .today domain extensions in mbox element?**

**Comment by ht2** [comment]
Hi @adrian-sarmas,

This was fixed in version 0.0.5 of the LearningLocker/StatementFactory (please see this issue for the full discourse: https://github.com/LearningLocker/StatementFactory/issues/8). That fix has been included into all versions of Learning Locker since 1.12.0.

As such you will need to upgrade. If you follow the instructions, and upgrade **each minor version invidually** (1.11.0 -> 1.12.0 -> 1.13.0 etc) by [following the release notes](https://github.com/LearningLocker/learninglocker/releases) for each release this can be done painfully and without incident. http://docs.learninglocker.net/upgrading/ However I implore you to take a backup before you begin!

If you simply want to upgrade the StatementFactory, you could try updating that single library, but we do not recommend that as we cannot say for sure how it would interact with your version of the LL code.

Looking back, 1.11.0 was released in Q3 2015. There have been 12 releases since then, all of which bring security patches, fixes and major performance enhancements. As a result I would _strongly_ recommend upgrading your Learning Locker.

The next release after yours in 1.12.0 - this is a major jump that includes some database migrations that need to modify the xAPI documents in the database. It brings massive speed enhancements due to changing to query on native Mongo dates and looking closer it also is the first version to include the fix you are looking for: https://github.com/LearningLocker/learninglocker/releases/tag/v1.12.0

**Comment by adrian-sarmas** [comment]
Thanks for your feedback, @ht2 ! 
I'll upgrade to latest version.

**Comment by ht2** [comment]
Hi @adrian-sarmas - just seen your ticket in the Help Centre. Sounds like you are still having issues?

**Comment by adrian-sarmas** [comment]
We've been upgrading to version 1.17.0 and now we have a different error. I cannot start a new attempt using mod_tincanlaunch plugin in Moodle. The same plugin works with the old version of Learning Locker we had.
The var_dump of the response Moodle gets from Learning Locker is:

object(TinCan\LRSResponse)#1902 (3) {
  ["success"]=>
  bool(false)
  ["content"]=>
  string(4237) "{"error":true,"success":false,"message":"Argument 1 passed to Illuminate\\Auth\\Guard::setUser() must implement interface Illuminate\\Auth\\UserInterface, null given, called in \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php on line 482 and defined","code":500,"trace":"#0 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(682): Illuminate\\Exception\\Handler->handleError(4096, 'Argument 1 pass...', '\/var\/www\/html\/l...', 682, Array)\n#1 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(482): Illuminate\\Auth\\Guard->setUser(NULL)\n#2 [internal function]: Illuminate\\Auth\\Guard->onceUsingId(Object(MongoId))\n#3 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Manager.php(138): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php(208): Illuminate\\Support\\Manager->__call('onceUsingId', Array)\n#5 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php(208): Illuminate\\Auth\\AuthManager->onceUsingId(Object(MongoId))\n#6 \/var\/www\/html\/lrs\/app\/filters.php(72): Illuminate\\Support\\Facades\\Facade::__callStatic('onceUsingId', Array)\n#7 \/var\/www\/html\/lrs\/app\/filters.php(72): Illuminate\\Support\\Facades\\Auth::onceUsingId(Object(MongoId))\n#8 [internal function]: {closure}(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#9 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Events\/Dispatcher.php(199): call_user_func_array(Object(Closure), Array)\n#10 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Events\/Dispatcher.php(154): Illuminate\\Events\\Dispatcher->fire('router.filter: ...', Array, true)\n#11 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1473): Illuminate\\Events\\Dispatcher->until('router.filter: ...', Array)\n#12 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1435): Illuminate\\Routing\\Router->callRouteFilter('auth.statement', Array, Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#13 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1322): Illuminate\\Routing\\Router->callAttachedBefores(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#14 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1029): Illuminate\\Routing\\Router->callRouteBefore(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#15 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#16 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(781): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#17 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#18 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 \/var\/www\/html\/lrs\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#23 \/var\/www\/html\/lrs\/public\/index.php(49): Illuminate\\Foundation\\Application->run()\n#24 {main}"}"
  ["httpResponse"]=>
  array(4) {
    ["status"]=>
    int(500)
    ["headers"]=>
    array(2) {
      ["contentType"]=>
      string(16) "application/json"
      ["date"]=>
      string(29) "Thu, 20 Apr 2017 06:42:10 GMT"
    }
    ["_content"]=>
    string(4237) "{"error":true,"success":false,"message":"Argument 1 passed to Illuminate\\Auth\\Guard::setUser() must implement interface Illuminate\\Auth\\UserInterface, null given, called in \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php on line 482 and defined","code":500,"trace":"#0 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(682): Illuminate\\Exception\\Handler->handleError(4096, 'Argument 1 pass...', '\/var\/www\/html\/l...', 682, Array)\n#1 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(482): Illuminate\\Auth\\Guard->setUser(NULL)\n#2 [internal function]: Illuminate\\Auth\\Guard->onceUsingId(Object(MongoId))\n#3 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Manager.php(138): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php(208): Illuminate\\Support\\Manager->__call('onceUsingId', Array)\n#5 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php(208): Illuminate\\Auth\\AuthManager->onceUsingId(Object(MongoId))\n#6 \/var\/www\/html\/lrs\/app\/filters.php(72): Illuminate\\Support\\Facades\\Facade::__callStatic('onceUsingId', Array)\n#7 \/var\/www\/html\/lrs\/app\/filters.php(72): Illuminate\\Support\\Facades\\Auth::onceUsingId(Object(MongoId))\n#8 [internal function]: {closure}(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#9 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Events\/Dispatcher.php(199): call_user_func_array(Object(Closure), Array)\n#10 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Events\/Dispatcher.php(154): Illuminate\\Events\\Dispatcher->fire('router.filter: ...', Array, true)\n#11 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1473): Illuminate\\Events\\Dispatcher->until('router.filter: ...', Array)\n#12 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1435): Illuminate\\Routing\\Router->callRouteFilter('auth.statement', Array, Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#13 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1322): Illuminate\\Routing\\Router->callAttachedBefores(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#14 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1029): Illuminate\\Routing\\Router->callRouteBefore(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#15 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#16 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(781): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#17 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#18 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 \/var\/www\/html\/lrs\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 \/var\/www\/html\/lrs\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#23 \/var\/www\/html\/lrs\/public\/index.php(49): Illuminate\\Foundation\\Application->run()\n#24 {main}"}"
    ["_metadata"]=>
    array(10) {
      ["wrapper_data"]=>
      array(11) {
        [0]=>
        string(34) "HTTP/1.0 500 Internal Server Error"
        [1]=>
        string(35) "Date: Thu, 20 Apr 2017 06:42:10 GMT"
        [2]=>
        string(30) "Server: Apache/2.4.10 (Debian)"
        [3]=>
        string(19) "Vary: Authorization"
        [4]=>
        string(39) "Cache-Control: private, must-revalidate"
        [5]=>
        string(16) "pragma: no-cache"
        [6]=>
        string(11) "expires: -1"
        [7]=>
        string(407) "Set-Cookie: laravel_session=eyJpdiI6IjNlYmU5WUpGUGpUNzlqbUE2d0tuR3hDVkJuQ0tPWVNKRTRPQnlHR29pMlk9IiwidmFsdWUiOiJqVmxscndGd2ZKMmhmZlZPZVUwWFRDeFRSNGo5WnZsdTNyNU9HWUNBS0dHN2ZQcjZvMUFaWnRKaW1MNlRuZzkyNmMzYXZOU29BcjlGMnl5eUlHXC96blE9PSIsIm1hYyI6ImM0MTY1Mjg5NzU0MjA4ZjhkNzNjNWVkZDk2ZjRmMzdiODVhZGY3ZTBlNmQ4YmRkMGQxMjIxODFjMWVhN2VlYjEifQ%3D%3D; expires=Thu, 20-Apr-2017 08:42:10 GMT; Max-Age=7200; path=/; httponly"
        [8]=>
        string(20) "Content-Length: 4237"
        [9]=>
        string(17) "Connection: close"
        [10]=>
        string(30) "Content-Type: application/json"
      }
      ["wrapper_type"]=>
      string(4) "http"
      ["stream_type"]=>
      string(14) "tcp_socket/ssl"
      ["mode"]=>
      string(2) "rb"
      ["unread_bytes"]=>
      int(4237)
      ["seekable"]=>
      bool(false)
      ["uri"]=>
      string(322) "http://demo.com/lrs/public/data/xAPI/activities/state?activityId=http%3A%2F%2FZUtELAqs3ms_general_grammar&agent=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Admin%20User%22%2C%22mbox%22%3A%22mailto%3Aemailaddress%40domain.com%22%7D&stateId=http%3A%2F%2Ftincanapi.co.uk%2Fstateapikeys%2Fregistrations"
      ["timed_out"]=>
      bool(false)
      ["blocked"]=>
      bool(true)
      ["eof"]=>
      bool(false)
    }
  }
}

**Comment by ht2** [comment]
OK, this is a common issue when migrating - you can find the process for resolving in this issue: https://github.com/LearningLocker/learninglocker/issues/820
