### ISSUE TITLE
Create client by php

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#914]
I am developing a platform to be connected with learning locker. I am trying to create a new client through php, and the xAPI specification it's not  helping that much.

Any help?

**Comment by ryansmith94** [comment]
Hey @rena7o8, there is a undocumented Learning Locker endpoint for doing exactly this. I've documented it for you below, I hope that helps.

#### Request Endpoint
```
POST http://www.example.com/data/xAPI/Basic/request
```

#### Request Headers
```
Authorization: Basic YOUR_EXISTING_BASIC_AUTH
Content-Type: application/json
```

#### Request Body
```json
{
  "name": "YOUR_NEW_CLIENT_NAME",
  "mbox": "mailto:test@example.com",
  "scopes": ["all"]
}
```

#### Response Status
200

#### Response Body
```json
{
  "key": "YOUR_NEW_CLIENT_BASIC_AUTH_KEY",
  "secret": "YOUR_NEW_CLIENT_BASIC_AUTH_SECRET"
}
```

**Comment by ryansmith94** [comment]
Closing this for now, I'll reopen if needed 👍

**Comment by hallshouse** [comment]
FYI: I've developed a WordPress > WooCommerce plugin that creates a new LRS and Client in LL if you are interested. The only thing is that is needs to be installed on the same server as LL. I'm also nearing the end of developing a multi-tenant Performance Support System that uses the new LL instances and clients while tying the content into the WooCommerce purchases.

Unfortunately, these are not open-source developments.
If you are interested in learning more, contact me.

**Comment by rena7o8** [comment]
Hey @ryansmith94, what you mean with Basic "YOUR_EXISTING_BASIC_AUTH"?

My admin credencials?

**Comment by rena7o8** [comment]
I read something -> "http://docs.learninglocker.net/exports_api/".
"Your Basic Auth details can be found under “Manage clients” in your LRS’s settings."

There is nothig there! Just the endpoint and the clients list.

**Comment by hallshouse** [comment]
@rena7o8 That clients list contains 2 keys:
The left key is your Basic Auth Username and the right key is your Basic Auth password.

**Comment by rena7o8** [comment]
Ok @hallshouse . I use those keys to post a statement for example. I am trying to create clients, it's supposed to use the keys of lrs owner or the Basic Auth of lrs owner.

**Comment by hallshouse** [comment]
I know what you are trying to do. I just answered the question you asked.
I know what it is supposed to do, writing a statement to an existing LL client is a far distance from creating an LL instance and client.

As I had previously mentioned, I've already built all of this as a both a WooCommerce plugin and as a stand-alone form.

**Comment by rena7o8** [comment]
Ok. So, I should use my admin key to post new clients?

**Comment by hallshouse** [comment]
No, you are way off.

This is GitHub area if used for LearningLocker issue tracking and feature requests, not for very basic questions on how to develop your 3rd. party product.

I'm sorry if this response is very blunt, but you may want to open discussions like this in another medium like Google xAPI Groups as you are not reporting a bug or opening a feature request.

You will also find a great deal of information here: https://www.learningsolutionsmag.com/articles/1526/five-things-a-web-developer-needs-to-know-about-the-xapi to help you understand the basics.

**Comment by ryansmith94** [comment]
Just to clarify @rena7o8, in Learning Locker "Clients" are used to access the API and "Users" are used to access the GUI. Since you are accessing the API, you need to use a Client's username and password, *not* a User's username and password. I hope that makes sense.

**Comment by ryansmith94** [comment]
To clarify further, in the response body for the API endpoint I documented above, the key is the new Client's username and the secret is the new Client's password.

**Comment by rena7o8** [comment]
@ryansmith94 I am building a LMS platform. This platform has a register page that should be used to register new clients in a specific LRS.

 I am getting a little bit confused. I just want to create new clients in a specific LRS via php post request.

**Comment by ryansmith94** [comment]
Hey @rena7o8, sorry for the slow reply, I do my best to avoid my computer at the weekends haha.

If you're confused about adding to a "specific LRS", your new client will be created inside the same LRS as the client used to create it.

**Comment by rena7o8** [comment]
Hi again @ryansmith94, that's normal... but I am a student, and students work hard at the weekend !

Ok, so I should use a LRS client to create another in the same LRS, got it. 

That's exacly what I am trying to do for now. But I still do not get results.

You think you can help me if a show you my php code?

**Comment by ryansmith94** [comment]
Haha no worries, I've been there! 😄 

Yeah go for it 👍

**Comment by rena7o8** [comment]
![capture](https://cloud.githubusercontent.com/assets/26470305/24832559/37f58a7a-1caa-11e7-881b-42813fa073fa.JPG)

**Comment by ryansmith94** [comment]
Ok that all looks good @rena7o8 except for the scopes which will probably need to be `'["all"]'` (because it's JSON). Can you tell me what is dumped too?

**Comment by rena7o8** [comment]
Ok, now it dumped something : bool(false)

**Comment by ryansmith94** [comment]
Ok I need to know exactly what came back from the HTTP request, I need the response code and body.

**Comment by rena7o8** [comment]
Forget it. I put back my endpoint and this is the response: 
![image](https://cloud.githubusercontent.com/assets/26470305/24832719/d592c182-1cad-11e7-9440-e05bc7148c01.png)

**Comment by ryansmith94** [comment]
You're also missing "/Basic/request" at the end of your URL.

**Comment by ryansmith94** [comment]
Give this a try (obviously change "www.example.com" to your own hostname)

```php
<?php

$client = json_encode([
	'name' => 'rn_client',
	'mbox' => 'rn_client@learninglocker.com',
	'scopes' => ['all'],
]);

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "http://www.example.com/data/xAPI/Basic/request",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => $client,
  CURLOPT_HTTPHEADER => [
    "authorization: Basic {{auth}}",
    "cache-control: no-cache",
    "content-type: application/json",
  ],
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

**Comment by ryansmith94** [comment]
Replace {{auth}} with your basic auth too

**Comment by rena7o8** [comment]
Just an error in the mbox parameter. I take a look on mongo database and it should be : 

'mbox' => 'mailto:rn_client@learninglocker.com'

Thank you @ryansmith94, it's solved! 

Have a nice weekend!

**Comment by ryansmith94** [comment]
Haha yeah good spot @rena7o8!

You're very welcome. Thanks @rena7o8, you too 😄

**Comment by JesterAntik** [comment]
If I have clear new instance of LL and add admin with a command line can I then create new client with API? I don't have any basic/secret keys

**Comment by ryansmith94** [comment]
If you log that user in via the API, you can use the JWT token returned from the login request to create an organisation and subsequently create a client within that organisation, this is discussed in #1246, please discuss this further there instead since the API discussed in this issue no longer exists from V2 onwards.
