### ISSUE TITLE
Not compatible with cmi5 auth fetch param

### ISSUE THREAD

**Issue by s512** [LearningLocker/learninglocker#916]
**Version**
develop at 8f504a8 on v1.17.0 

**Steps to reproduce the bug**
1. Import the following collection: [LL Auth.postman_collection.zip](https://github.com/LearningLocker/learninglocker/files/896038/LL.Auth.postman_collection.zip)
2. Configure baseUrl in your environment to be your learning locker URL
3. Run the request "Oauth Token - broken"

**Expected behaviour**
Auth token should be returned. 

**Actual behaviour**
Error is returned: "The grant type was not specified in the request".

**Additional information**
The "Oauth Token - broken" request contains client_credentials, client_id and client_secret in the query string. 

In the cmi5 spec, a fetch URL is passed to the course, which the course can use to get a token from the LRS.  This token is used in subsequent communications with the LRS: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#fetch_url

However, with learning locker, the fetch URL requires that client credentials are in the body of the request, rather than the query string. Therefore we're unable to pass a URL to the course on launch that the course can use to get a token, as it requires additional parameters in the body of the request. 

Any chance we can add support for credentials in the query string?  Or is there another way?

Thanks in advance! 
Sam

**Comment by ht2** [comment]
Hi Sam,

My understanding of the fetch URL was that this should be managed and maintained by the _LMS_ not the LRS.

From the quartz spec:
> The fetch URL is used by the AU to obtain an authorization token created and managed by the LMS. The authorization token is used by the AU being launched.

Notice in the example, the fetch URL is to the LMS
```
http://www.example.com/LA1/Start.html
?endpoint=http://lrs.example.com/lrslistener/
&fetch=http://lms.example.com/tokenGen.htm?k=2390289x0
&actor={"objectType": "Agent","account": 
{"homePage": "http://www.example.com","name": "1625378"}
&registration=760e3480-ba55-4991-94b0-01820dbd23a2
&activityId=http://www.example.com/LA1/001/intro
```

I believe that the LMS should be making a separate request on the server side using its client credentials to generate an oauth token, which is then returned to the activity provider.

**Comment by s512** [comment]
You are absolutely right! Thanks for clarifying, this makes a lot more sense.

I'll close the issue and slowly walk away...

**Comment by hallshouse** [comment]
Hi Sam:
as one of the cmi5 authors, I confirm James response. fetchURL is a cmi5 spec. requirement.

**Comment by ht2** [comment]
No problem! Broadly the idea is to never expose the LRS basic credentials on the client side. If the launch URL were to be something provided by the LRS, then you would need to expose the basic creds via an AJAX/XHR call which someone could easily look at in their developer tools. At that point you've handed the keys over and they can create as many oauth tokens as they want.

By the LRS handling the fetching, they can create "one time use" URLs that:
a) Can only be used by a particular user via a logged in session
b) Can be invalidated/remove whenever that session is closed

The LMS also then has the power to (in theory) to invalidate the LRSs OAuth token when a session is ended too. Of course the biggest benefit is that the LRS client credentials are only known to the LMS, and all requests to the LRS (for token generation) are handled server side. 

Its a neat system, and it overcomes a lot of problems. The only downside is finding an LMS that does some or all of the above!
