### ISSUE TITLE
Error updating 1.16.0 to 1.17.0 - php-bcmath

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#919]
**Version**
1.17.0

**Steps to reproduce the bug**
1. Follow upgrade procedure here: http://docs.learninglocker.net/upgrading/
2. On step 3, at the last command "php composer.phar install" I receive an error (see below)

**Expected behavior**
Composer will install dependencies/packages

**Actual behavior**
The following error:
```
Problem 1
    - Installation request for php-amqplib/php-amqplib v2.6.3 -> satisfiable by php-amqplib/php-amqplib[v2.6.3].
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
```

**Additional information**
OS: CentOS 7.3

**Resolution**
php-bcmath is a required extension for this upgrade. Be sure to install it prior to upgrading.

**Comment by davidpesce** [comment]
I'm going to close this but wanted it here in case other users run into the same problem.

**Comment by ryansmith94** [comment]
Awesome, thanks @davidpesce 😄
