### ISSUE TITLE
Can't find LRS's credencials.

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#920]
I need my  LRS crecencials to post new clients related to that LRS but i can't find it.

Here "http://docs.learninglocker.net/postman/" they say "You can find your LRS’s credentials via the “Manage clients” link (in the left sidebar)."

There is nothing there, just the endpoint and the clients list.

Should I use my admin credencials? Because in this case I am the admin and the LRS owner.

**Comment by hallshouse** [comment]
The document is describing the left sidebar of the LearningLocker GUI, not of Postman.

**Comment by rena7o8** [comment]
I am talking about the Learning Locker left sidebar!!!

**Comment by hallshouse** [comment]
Have you created your first LRS Client instance yet?

**Comment by rena7o8** [comment]
Yes, I created my first LRS and I add to it clients but manually. Now I want to add clients via PHP post request.

@ryansmith94 gave me  a undocumented Learning Locker endpoint to do it. 
But I need to know how to get his parameter: "Authorization: Basic YOUR_EXISTING_BASIC_AUTH".

**Comment by ht2** [comment]
@rena7o8 - I'm guessing you are looking for this?

https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side

If you have the username and password, you have everything you need to make a basic auth request; it is a standard HTTP procedure to base64 the username and password and pass it via that header.

**Comment by ryansmith94** [comment]
Hey, thanks for your message @rena7o8 and thanks for helping out here @hallshouse.

The "Authorization" header in your HTTP requests to the Learning Locker API should be "Basic " followed by a base 64 encoding of your client's username and password separated by a colon.

So if my client's username was "123" and my client's password was "456", then I would base 64 encode "123:456" using base64encode.org to get "MTIzOjQ1Ng==", so the "Authorization" header would be "Basic MTIzOjQ1Ng==".

You can get your client's username and password, by selecting your LRS from the "LRS List" dropdown in the top menu, then selecting "Manage clients" from the left menu. You should get a screen looking something like this:

![image](https://cloud.githubusercontent.com/assets/3045513/24830013/296eff70-1c75-11e7-8db5-6c30e7ac8b1b.png)

I hope that helps @rena7o8

**Comment by rena7o8** [comment]
Yes, but in this case the username and password of who? LRS owner? admin?

**Comment by ryansmith94** [comment]
@rena7o8 I think you missed [my comment above](https://github.com/LearningLocker/learninglocker/issues/920#issuecomment-292723826)

**Comment by hallshouse** [comment]
To help HT2, try to explain this...
Here is an example of the Authorization string taken from your **LRS Client**:
If your Username is: AbC123DeF456
and your password is: 123aBc456dEf
the separator you will need to go between the Username and Password is a ":"
Your Basic OAuth string will be: Basic AbC123DeF456:123aBc456dEf
you would then go to https://www.base64encode.org/ yo Base64Encode this string and you would get the resulting string: QWJDMTIzRGVGNDU2OjEyM2FCYzQ1NmRFZg==

**Comment by rena7o8** [comment]
Ok guys, I got it! 

I was considering the "Authorization: Basic YOUR_EXISTING_BASIC_AUTH" like a password of the lrs owner or something.

**Comment by ryansmith94** [comment]
Yeah no worries @rena7o8, glad you've got it now 👍  have a great weekend
