### ISSUE TITLE
Learning Locker with gmail

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#921]
I am trying to configure L.Locker with a gmail account. I add the email.php file configured in /app/config/local. 

I am testing it just inviting a user (microsoft mail account) and nothing, not even in the spam box.

Looking for help. Thanks!

**Comment by ryansmith94** [comment]
Hey again @rena7o8 😄 can you show us your app/config/local/mail.php file? It should look a bit like this:

```php
<?php
return [
    'pretend' => false,
    'username' => 'YOUR_USERNAME',
    'password' => 'YOUR_PASSWORD',
    'host' => 'YOUR_SMTP_HOST',
    'port' => 'YOUR_SMTP_PORT',
    'from' => [
        'address' => 'YOUR_EMAIL_ADDRESS',
        'name' => 'YOUR_NAME'
    ]
];
```

**Comment by rena7o8** [comment]
It's configured like this: 

![image](https://cloud.githubusercontent.com/assets/26470305/24870806/65bcdb0a-1e0f-11e7-9d59-762a1d95cb71.png)

**Comment by ryansmith94** [comment]
Can you confirm that this is in your "app/config/local/mail.php" file (not a "email.php" file)?

**Comment by ryansmith94** [comment]
You also need to set `pretend` to `false` in there as we do in the example file.

**Comment by rena7o8** [comment]
I confirm that my file name it's mail.php, my mistake up there.

After set pretend to false I got this error when inviting a new user:

![image](https://cloud.githubusercontent.com/assets/26470305/24872210/8aae86ca-1e14-11e7-8298-be2851ebaccf.png)

**Comment by rena7o8** [comment]
Ok. I was using the smtp in a implicit way : port 465 and I changed to explicit way : port 587.
It's all about SSL. Thanks @ryansmith94.

**Comment by ryansmith94** [comment]
Ah I see, glad to hear it's working now. You're very welcome :smile:
