### ISSUE TITLE
Client credencials - hash

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#922]
Hi, 

What's the hash algorithm used in learninglocker to create client credencials?

**Comment by ryansmith94** [comment]
Hey @rena7o8, the function that generates them is here https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/repository/Client/EloquentRepository.php#L46

**Comment by rena7o8** [comment]
It's the sha1. Thanks @ryansmith94
