### ISSUE TITLE
Learning Locker Shut Downs

### ISSUE THREAD

**Issue by RS1603** [LearningLocker/learninglocker#929]
You need to replace the parts of this template where you see {{some text}}.

**Version : 1.6**
{{branch}} at {{commit}} on {{version - found in your copy of the VERSION file}} 

**Steps to reproduce the bug**
1. {{step 1}}
2. {{step 2}}

**Expected behaviour**
Learning Locker should not shut down on its own

**Actual behaviour**
Learning Locker shut downs, looks like Linus - operating system is killing the process

**Additional information**
OS:Redhat OS 6.7
Mongo - 2.4.14-3.el6
Php - 5.6.30 
Browser: Internet Explorer 11.0
{{additionalInfo}}
Issue persists with version 1.14 also

**Comment by ht2** [comment]
Hi @rs1603, it sounds like your server is rebooting everyday and the Apache server isn't setup to restart. Either that, or something is stopping Apache daily.

Learning Locker doesn't actually run as a process, the server runs the PHP code as requested, so this is definitely a issue with the server.
