### ISSUE TITLE
Ansile Failed to Configure LearningLocker database's configuration details

### ISSUE THREAD

**Issue by NayefAlharbi** [LearningLocker/learninglocker#931]
Greetings, 

I followed the instructions given here which are well written, I would appreciate if anyone can help me with this issue. when I run `Vagrant up` and it reaches the task: 

> Configure LearningLocker database's configuration details 

it throws an exception saying 

> "msg": "Path /var/www/learninglocker/app/config/local/database.php does not exist !"
I SSH the server and found that there is no database.php in that directory. I removed everything and redid the installation and it shows the same error. Could anyone help? 

![ll installing db error](https://cloud.githubusercontent.com/assets/5903732/26284139/e2214ee0-3e3c-11e7-9bb0-981459c5fb2d.png)

Regards, 

~Nayef

**Comment by ht2** [comment]
We don't directly support any custom Vagrant installation within this repo, so it might be worth checking on Gitter (https://gitter.im/LearningLocker/learninglocker)

Saying that, it looks like your trying to amend files that don't actually exist. The repo does not ship with those files in by default.

https://github.com/LearningLocker/learninglocker/tree/develop/app/config/local
