### ISSUE TITLE
Learning Locker fails to install on Oracle Solaris 11.3 due to missing "php-mcrypt" support

### ISSUE THREAD

**Issue by steffen-moser** [LearningLocker/learninglocker#932]
**Version**
develop on 1.17.0

**Steps to reproduce the bug**
1. Try to install Learning Locker on a fully-patched Solaris 11.3 host according to the installation manual given in http://docs.learninglocker.net/installation

**Additional information**
OS: Oracle Solaris 11.3 SRU 19.5
PHP: PHP-5.6.22

We are currently evaluation LRS software and came across Learning Locker.

The PHP distribution of Oracle Solaris 11.3 does not come with php-mcrypt which is an extension required by Learning Locker. 

The reason for the lack of php-mcrypt in Solaris is that "libmcrypt" (which php-mcrypt relies on) is scheduled as EOL in Solaris (up to today, libmcrypt-2.5.8 is available), so the PHP maintainers seems to have already commented out the inclusion of the php-mcrypt extension in the build scripts. In avoiding a compilation of PHP by myself, I tried to install php-mcrypt using PECL, but PECL doesn't show any php-mcrypt extension for PHP 5.6. 

I've read some arcticles about libmcrypt in general and php-mcrypt in concrete, there are [sources which call libmcrypt as "abandonware"](https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong). Due to the fact that libmcrypt hasn't been updated for more than 10 years (version 2.5.8 appeared in February of 2007), I can understand the criticism at least a bit... 
As far as I found out, Learning Locker's requirement on php-mcrypt stems from the underlying Laravel framework. Is this correct? As Laravel 5.1 doesn't seem to [rely on php-mcrypt anymore](https://github.com/laravel/framework/pull/9041), my question or feature request is whether there are any plans on upgrading Learning Locker to a more recent version of Laravel.

**Comment by ht2** [comment]
Hi there,

There are no plans to move Learning Locker v1 to Laravel 5.1.

If Oracle Solaris does not php-mcrypt, then I would suggest that you will not be able to run Learning Locker on Oracle Solaris.

Thanks
