### ISSUE TITLE
How to Configure LL to use MongoDB over SSL\TLS

### ISSUE THREAD

**Issue by NayefAlharbi** [LearningLocker/learninglocker#935]
Greetings, 

How can I configure LL to use **MongoDB** over SSL/TLS?

**Comment by ht2** [comment]
You simply need to pass the relevant config to the database configuration options. An example of this for your database.php config might look like:

```
<?php

return [
  'default' => 'mongodb',
  'connections' => [
    'mongodb' => [
      'driver'   => 'mongodb',
      'database' => 'XXXX',
      'host' => 'XXXX',
      'port' => '27017',
      'username' => 'XXXX',
      'password' => 'XXXX',
      'options' => [
        'ssl' => true
      ]
    ]
  ],
  'migrations' => 'migrations',
];
```

Note the `options` and `ssl` vars in the `connections.mongodb` section

**Comment by ht2** [comment]
You can read about the available options passed to the MongoClient here: http://php.net/manual/en/mongoclient.construct.php

**Comment by NayefAlharbi** [comment]
What about the mongdb pem file and CA certificate? When I open mang shell I
provide them otherwise it would refuse the connection.

**Comment by ht2** [comment]
Please refer to the MongoClient link I provided. Look at the SSL context options.

**Comment by NayefAlharbi** [comment]
@ht2 thanks for your prompt response. 

I followed the link and changes database.php to: 

```php
'options' => 
			[
				'ssl' => 
				[
					'allow_self_signed' => true,
					'verify_peer' => true,
					'cafile' => '/etc/ssl/mongodb-cert.crt',
					'local_cert' => '/etc/ssl/mongodb.pem', 
					'peer_name' => 'lrs'	
				]
			],
```

but it throws an exception: 

> [MongoConnectionException]                                                
> **Failed to connect to: lrs:27017: Remote server has closed the connection**
> [ErrorException]            
> **Array to string conversion**

**Comment by ht2** [comment]
If you search that page for "SSL context" the second entry you will find will show you that information needs to go in the `context`. `ssl` is always a boolean looking at the docs

Try:
```
'options' => [
  'ssl' => true,
  'context' => [
    'allow_self_signed' => true,
    'verify_peer' => true,
    'cafile' => '/etc/ssl/mongodb-cert.crt',
    'local_cert' => '/etc/ssl/mongodb.pem', 
    'peer_name' => 'lrs'  
  ]
]
```

In all honesty this isn't something we have ever had to do as we don't have self signed certificates so I'm really not 100%. If you experience further issues I would make an issue on the [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) library that we use to talk to Mongo, explaining you are using Laravel 4.2.

**Comment by NayefAlharbi** [comment]
Would you open this case as I am still not able to continue the installation?

**Comment by ht2** [comment]
Sorry @NayefAlharbi but I can't support the jenssegers/laravel-mongodb package - you should request help in that library as that handles all of this. It's highly likely that the driver doesn't support that `context` option being passed through its own custom version of the extension, in which case you would need to fork the package we use for the Mongo library.

Unfortunately this version of Learning Locker is not under active development (apart from critical security patches etc0 and and that is not something we would be looking to do ourselves.

**Comment by ht2** [comment]
OK on further inspection of [this page](http://php.net/manual/en/mongoclient.construct.php), it seems like the context should be passed in as `driver_options`. You can try passing these in as...

```
'options' => [
  'ssl' => true
],
'driver_options` => [
  'context' => [
    'allow_self_signed' => true,
    'verify_peer' => true,
    'cafile' => '/etc/ssl/mongodb-cert.crt',
    'local_cert' => '/etc/ssl/mongodb.pem', 
    'peer_name' => 'lrs'  
  ]
]
```

But again, I have no idea if the jenseggers package allows this to be passed in the config.
