### ISSUE TITLE
'Unable to Save' error for editing a new report

### ISSUE THREAD

**Issue by davidsws** [LearningLocker/learninglocker#936]
We've installed LL v1.17.0 on our own server and have connected up an LMS successfully. That is, all our xAPI statements are coming in and being stored.

I then tried created a new report and tried to edit the settings. After setting the Actor, Verb and Object i tried to save the report. It won't let me and displays an error dialogue box of 'Could to save.'

I'm a Super Admin role so anything should be possible

I can't see any other message or error detail. Can someone please help me with a possible solution or place to start looking. The screens are fairly minimal so I'm guessing some backend work may be needed?

Thanks.
David

**Version**
{{branch}} at {{commit}} on {{1.17.0}} 

**Steps to reproduce the bug**
1. Create a New Report.
2. Edit the Report and set an Actor, Verb and Activity URL.
(All three were set using items from the drop down list. So statements for them do actually exist.
3. Click Save.

**Expected behaviour**
It should save.

**Actual behaviour**
Shows dialogue box: "Could not save." No  other details are found anywhere.

**Additional information**
OS: Windows 10 Enterprise
Browser: Firefox 54.0.1 64 bit.

** Logs** 
No entry in any recent log file can be found that relates to this error. Latest log file attached.
[laravel-2017-07-20.zip](https://github.com/LearningLocker/learninglocker/files/1161016/laravel-2017-07-20.zip)

** Browser Console** 
I looked into the browser console and debugger.....

PUT request:
http://www.sharewealthsystems.com/learninglocker/public/api/v1/reports/596f08e56cdb8fcb078b4567

>>> I note that the folder \api doesn't exist.

PUT Header:
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language:en-GB,en;q=0.5
Authorization: Basic xxxxxx
Connection: keep-alive
Content-Length: 530
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: __lc.visitor_id.5401741=S1461024039.602910e156; _ga=GA1.2.1472656985.1476764358; __utma=1.1472656985.1476764358.1476916986.1476916986.1; __utmv=1.internal; sharefinder_admin=sharefin; SMFCookie987=a%3A4%3A%7Bi%3A0%3Bs%3A4%3A%222073%22%3Bi%3A1%3Bs%3A40%3A%22c31b8ef9912a25ca27f6b74cdbdf2210a7a93764%22%3Bi%3A2%3Bi%3A1668294123%3Bi%3A3%3Bi%3A0%3B%7D; lc_window_state=minimized; laravel_session=eyJpdiI6IlhqUnBPa3FWM0Z5RDFWbis1ZXZ1emQxbm90NldJcTg1VEVzRUw4Ym5Rck09IiwidmFsdWUiOiJIMGVKa3VaXC91VzdSVll2K2NZeWRjbUJ2NG9zMUlMUWhPSmhMakQ0VnFyOGNWd0lzN05DNEorS241N3ZuMkRObnprcExcL2hQOTVJYm5Vbzd1Y29JdVpnPT0iLCJtYWMiOiIwMGVjODQ0ODE2MDljOTQ3YjQ0NmVkYWE0MWU4YmUwY2Y1YTg2Mzc3OTVmMGY0OWZhOTJlM2FlODM0OGY5NjgwIn0%3D
Host: www.sharewealthsystems.com
Referer: http://www.sharewealthsystems.com/learninglocker/public/lrs/59080ff66cdb8f72308b4567/reporting
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
X-Requested-With:XMLHttpRequest

>>> I note that the Referer URL doesn't exist in our folder structure from \lrs and down.

PUT Response:
<html><head><title>Error 403 - Forbidden</title><head><body><h1>Error 403 - Forbidden</h1><p>You don't have permission to access the requested resource. Please contact the web site owner for further assistance.</p></body></html>

>>> I note that it said forbidden. Is that because it doesn't exist or a permssion issue?

**Comment by hallshouse** [comment]
I looks like permissions.
If you are on a Ubuntu server, while in the learninglocker folder, try these and see if it works afterward.

sudo chown -R www-data:www-data *

sudo gpasswd -a www-data `id -g -n $USER`

sudo find app/storage/ -type d -exec chmod 775 {} + && sudo find app/storage/ -type f -exec chmod 664 {} +

sudo find uploads/ -type d -exec chmod 775 {} + && sudo find uploads/ -type f -exec chmod 664 {} +

**Comment by davidsws** [comment]
The site is hosted by InMotion but we have root/shell acess via WinSCP. 
uname returns:
Linux xxxx.inmotionhosting.com 2.6.32-042stab123.1 #1 SMP Fri Jun 23 18:45:27 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux

There is no www-data user but I tried the commands with another base user(not root) to see if that would work. No luck.

What user/s or group/s should exist and what permissions should they have.

I must admit that just getting LL and Mongo onto the server was a nightmare, so I can't recall what exact users were set up. I need a 'Lesson 101' approach to this please.

**Comment by ht2** [comment]
Hey @davidsws,

I think the key here is to ensure that whatever the Linux user that is executing the PHP has the file permissions set correctly. In @hallshouse's example he used `www-data` as that is a pretty common user for php-fpm to run under, but it really depends on what you are using (Apache, Nginx, Mod PHP, php-fpm). 

However I'm just wondering if that is the issue in this case. Can you elaborate a bit on what basic auth credentials you are using to access the report API? Are you using your LL login details, or the Basic Auth credentials created for a store?

**Comment by ht2** [comment]
Apologies, I just realised this is coming through the API, you aren't setting those values.

**Comment by ht2** [comment]
OK, I'm about 99.9% certain that error is not actually being generated by Learning Locker, rather the server is generating it. When I search for the exact error message:

`You don't have permission to access the requested resource. Please contact the web site owner for further assistance.`

The first google hit is this page:
http://www.inmotionhosting.com/support/community-support/website/error-403-forbidden-2

Given you said that you are hosting with InMotion, I am pertty certain this is a custom error message installed onto their servers. I would strongly suspect that your Apache config for the LL directory is not configured correctly to allow Mod Rewrite, htaccess overrides or something similar.

**Comment by davidsws** [comment]
Hi James,
You were spot on. There was a Limit in the public_html .htaccess file....
<Limit PUT DELETE>
order deny,allow
deny from all
</Limit>

So we changed the LL folder .htaccess to work around this. And we then had to get a Mod Security change made. Once these were done, it all worked.

**Comment by ryansmith94** [comment]
That's awesome @davidsws, thanks for letting us know. James is on holiday at the moment, but I'll close this now in his absence 👍
