### ISSUE TITLE
Graph view is not working - Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by hxtpoe** [LearningLocker/learninglocker#938]
**Version**
1.17.0 application is running in dev mode

**Steps to reproduce the bug**
1. Login
2. Go to reporting
3. Click Graph button

**Expected behaviour**
I should see a graph.

**Actual behaviour**
I see javascript error in console:

_Uncaught TypeError: Cannot read property 'label' of undefined at d.b.Bar.d.hoverContentForRow (morris.min.js:6)_

**Server information**
MongoDB  3.0.14

**Client information**
OS: OSX 10.12.5
Browser: Chrome 59.0.3071.115, Safari 10.1.1

**Additional information**
It occurs on empty statements collection. 

or

When I have some statements in the database I can see them when I click statements button instead of graph button. But clicking graph throws "Cannot read property 'label' of undefined".
When I open single LRS view by using LRS list and click update graph, I can see a graph.
The Graph contain total number of statements and total number of  learners total per day.
I can see "most active users", "popular activities" and "latest reports" on dashboard.

On report view api/v1/reports/59888fb375524cd507d51424/graph returns empty array, 
When I click statements I see list of statements.

I have the same error as described here #664

**Comment by ht2** [comment]
I am going to archive this issue due to v2.0.0
