### ISSUE TITLE
ERR_EMPTY_REPONSE on fresh install

### ISSUE THREAD

**Issue by matt360-biz** [LearningLocker/learninglocker#939]
You need to replace the parts of this template where you see {{some text}}.

**Version**
Master Branch 1.17

I followed steps on

http://docs.learninglocker.net/installation/

but when i accessed website.com/learninglocker/public/ 

it just said  ERR_EMPTY_RESPONSE Internal Server Error. It didnt have any detailed error
and https/error-logs didnt have anything relating to learninglocker.

Is there a way to debug this? debug is set to true in app.php

Any help is appreciated. Thank you

**Comment by matt360-biz** [comment]
Additional Info that might help:

I found this in  in app/storage/logs/laravel.log

[2017-08-12 00:48:15] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in directory/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
Stack trace:
#0 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 directory/learninglocker/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkLegacyMiddleware.php(20): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Clockwork\Support\Laravel\ClockworkLegacyMiddleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 directory/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 directory/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 directory/learninglocker/public/index.php(53): Illuminate\Foundation\Application->run()
#12 {main} [] []

**Comment by ht2** [comment]
Hi there, I don't think your mod_rewrite is configured correctly. Please see these issues for more info.

https://github.com/LearningLocker/learninglocker/issues?utf8=%E2%9C%93&q=is%3Aissue%20mod_rewrite%20
