### ISSUE TITLE
STATEMENTS_SERVICE_AWAIT_UODATES typo

### ISSUE THREAD

**Issue by ht2** [LearningLocker/learninglocker#973]
Change to accept STATEMENTS_SERVICE_AWAIT_UPDATES 

Will need to make this backwards compatible for any existing installations.

Unsure if this is also an issue seen in the xAPI-statements repo.

**Comment by ryansmith94** [comment]
https://github.com/LearningLocker/xapi-statements/releases/tag/v1.0.9
https://github.com/LearningLocker/xapi-service/releases/tag/v1.0.5
