### ISSUE TITLE
Unable to post statements over proxy connection

### ISSUE THREAD

**Issue by nadavkav** [LearningLocker/learninglocker#974]
**Version**
2.0.1
(Installed on a vanilla Debian 9, using the following instructions: http://docs.learninglocker.net/guides-installing/ with out any errors during install)

**Steps to reproduce the bug**
1. Setup Moodle + logstore_xapi over proxy 
2. send statements

**Expected behaviour**
Should show up on LL

**Actual behaviour**
Turning on DEBUGging, I am getting the following errors:
```json
{"response":{"success":false,"content":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error<\/title>\n<\/head>\n<body>\n<pre>Cannot POST \/data\/xAPIstatements<\/pre>\n<\/body>\n<\/html>\n","httpResponse":{"status":404,"headers":{"contentType":"text\/html","date":"Thu, 05 Oct 2017 16:39:27 GMT","contentTypeCharset":"utf-8"},"_content":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error<\/title>\n<\/head>\n<body>\n<pre>Cannot POST \/data\/xAPIstatements<\/pre>\n<\/body>\n<\/html>\n","_metadata":{"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-RSA-AES256-GCM-SHA384","cipher_bits":256,"cipher_version":"TLSv1\/SSLv3"},"timed_out":false,"blocked":true,"eof":false,"wrapper_data":["HTTP\/1.1 404 Not Found","Server: nginx\/1.10.3","Date: Thu, 05 Oct 2017 16:39:27 GMT","Content-Type: text\/html; charset=utf-8","Content-Length: 159","Connection: close","Vary: Origin","Access-Control-Allow-Credentials: true","X-DNS-Prefetch-Control: off","Strict-Transport-Security: max-age=15552000; includeSubDomains","X-Download-Options: noopen","X-Content-Type-Options: nosniff","X-XSS-Protection: 1; mode=block","Content-Security-Policy: default-src 'self'"],"wrapper_type":"http","stream_type":"tcp_socket\/ssl","mode":"rb","unread_bytes":159,"seekable":false,"uri":"https:\/\/learninglocker.moodlemagic.info\/data\/xAPIstatements"}}}}
```

**More info**
I have two Organizations and LRS on the same LL instance, one of the works fine (connected to another Moodle system without a proxy, direct link)

**Expected behaviour**
See Moodle xapi statements in LLv2

**Actual behaviour**
Nothing seen on the LLv2 Dashboard.

**Additional information**
OS: Debian 9
Browser: Version 57.0.2987.133 (64-bit)

**Comment by ht2** [comment]
Looking at the error message in your debug I can see...

```
<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error<\/title>\n<\/head>\n<body>\n<pre>Cannot POST \/data\/xAPIstatements<\/pre>\n<\/body>\n<\/html>
```

After putting this jargon through the (now sentient) Learning Locker AI, and with some CSI level digging of my own, I retreived the error message from the string:

`Cannot POST /data/xAPIstatements`

*Conclusion:*
You need to add a `/` to your xAPI endpoint in Moodle.

**Comment by ht2** [comment]
_In all seriousness, if we could please start work on the sentient Learning Locker AI!_ 😂

**Comment by nadavkav** [comment]
Dear AI, thank you for using your magical powers, but... I sorry. it works without the "/" from other Moodle systems I use. and adding the "/" did not solved it. weird.

This specific Moodle system is using a proxy to get out of the campus and into the LL that is installed on a remote cloud (profitbricks), I hope the proxy is not breaking something. I am trying to monitor the communication with our campus security team, but nothing stands out yet.

I am still exploring this, and if I dig something out I will report.

Can you recommend or direct me to any tools or logs I can use to debug this on the LL server side?

**Comment by ht2** [comment]
Haha, no problem! Did you still see the same error message when you added the `/`? In the original message that will have been the problem, so it might be we're hitting the next issue now.

If you want to test connectivity to your LRS, you can do that using the POSTMAN collections we used to suggest for V1 (still available in the V1 docs via http://v1docs.learninglocker.net/postman/#postman). Using those you can ensure that access to your LRS is working, although simply going to yourlrs.com/data/xAPI/about (you should see JSON with xAPI version information) will be enough to tell you if it is or not.

Out of interest did the URL you use include any ports (e.g. :3000) in the URL. If it did, try it _without_ those - an earlier build of V2 was including the the UI port in the URL we give you for your endpoint (in the clients page.

Let me know how you get on 👍

**Comment by abanghendri** [comment]
I use google cloud platform VM Instance and install with an install script, I can log in to the system but when I post to endpoint I got the same issue, it says error 404
I post using Restlet Client on Google Chrome
This is My Endpoint: http://35.237.140.243/data/xAPI

I use Debian 9 and n1-standard-1 (1 vCPU, memori 3.75 GB)
