### ISSUE TITLE
LL-50 Display free/used disk space for LRS

### ISSUE THREAD

**Issue by nadavkav** [LearningLocker/learninglocker#985]
Add a "used/free disk space" indication on the learning record store UI, for each store.
So an application manager can be aware of this information without the need to consult system IT personal.

**Comment by ht2** [comment]
This is on our roadmap, but is actually quite tricky to achieve. There is no way for Mongo to tell you the size of a subsection of a collection. 

Instead, you can take a sample of the average document size of statements in that organisation ([$sample](https://docs.mongodb.com/manual/reference/operator/aggregation/sample/) is good for this) and then multiply it by how many statements are in that organisation.

Obviously the bigger the sample, the more accurate that will be.

**Comment by nadavkav** [comment]
Happy to read it is on your roadmap :+1: 

I will try to fiddle with the MongoDB functions and see what I can come up with. Thank you for the advice on using the $sample function. I will give it a go, and let you know how accurate it turned out.

**Comment by ht2** [comment]
Something to play with, run raw aggregations at the command line and pipe results into a new collection (using [$out](https://docs.mongodb.com/manual/reference/operator/aggregation/out/)). You can then use [`db.collection.stats()`](https://docs.mongodb.com/v3.2/reference/method/db.collection.stats/) to get some raw data about the size of that collection, including the average object size (avgObjSize). Using that you can start to extrapolate data size.

Also remember that [raw data size does not equate to storage size](https://blog.mlab.com/2014/01/how-big-is-your-mongodb/) and finally that this does not include the size of your indexes.

We are strongly considering moving to a system where each organisation's statements would be stored in different collections. That way we could very easily run a `db.org123_statments.stats()` and get output we can pass to the UI. It also doesn't affect our ability to query across different stores within that organisation, and finally allows us to remove the `organisation` filter from all statments, and therefore all indexes too.

Lots to think about!

**Comment by nadavkav** [comment]
Wow, yes. Lots to think about!
Thank you for all the advices!

**Comment by ht2** [comment]
Going to close this as it is not on the current roadmap. We'd recommend anyone needing to check their space allotment uses DB tools to sample and size the statements per org.

**Comment by nadavkav** [comment]
Eventually, we monitor it with Zabbix, on the system level.
