### ISSUE TITLE
500 error when using a client without an lrs_id attached

### ISSUE THREAD

**Issue by ht2** [LearningLocker/learninglocker#996]
You need to replace the parts of this template where you see {{some text}}.

**Version**
v1.0.9 of xapi-statments

**Steps to reproduce the bug**
1. Create a client without an lrs attached
2. Try to send in a statement

**Expected behaviour**
A 401 error

**Actual behaviour**
A 500 error

```sh
xAPI     | 2017-10-17 10:39:39:999 - error: caae7ebd-d5d1-4022-aea4-1c612a4a8a26 TypeError: Cannot read property 'toString' of undefined
xAPI     |     at Object.<anonymous> (/vagrant/ll/xapi/node_modules/xapi-statements/src/mongoAuthRepo/getClient.ts:30:30)
```

**Comment by ryansmith94** [comment]
Progress
- [X] xapi-statements
- [X] xapi-activities
- [ ] xapi-agents
- [ ] xapi-state
