### ISSUE TITLE
Content type (text/plain;charset=UTF-8) Error Message

### ISSUE THREAD

**Issue by andrewdisney** [LearningLocker/learninglocker#998]
**Version**
2.0.4

**Steps to reproduce the bug**
1. Call Get Statements API From A course
2. Using these headers:

```
:authority:llv2.tld
:method:POST
:path:/data/xAPI/activities/state?method=GET
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.8
cache-control:no-cache
content-length:483
content-type:text/plain;charset=UTF-8
origin:https://media.disneytravelagents.com
pragma:no-cache
referer:https://media.disneytravelagents.com/courses/tincan/20170601-1004_bas_dr_dlr_02themeparks_2017-05-25/story_html5.html?tincan=true&endpoint=https://llv2.tld/data/xAPI/&auth=Basic%20YzQ3OGU3MDk2MTUxNjNjODNkY2YxMGQ2YzUxNDgyZGE4N2EwYjVjOTpkMDIzNGZkNjhmZDA0OTdlZDUzZmM0Njc0YTcxY2VjMmYyY2E5NTI1&activity_id=http://BAS_DR_DLR_02ThemeParks&grouping=http://BAS_DR_DLR_02ThemeParks&actor={%22objectType%22:%22Agent%22,%22name%22:%22Old%20Yeller%22,%22account%22:{%22homePage%22:%22http:\/\/otp.tld%22,%22name%22:%22aaatester%22}}&registration=2395b829-7700-4954-abce-a719351a6a65
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
```
3. Using this payload:
```
Authorization=Basic%20YzQ3OGU3MDk2MTUxNjNjODNkY2YxMGQ2YzUxNDgyZGE4N2EwYjVjOTpkMDIzNGZkNjhmZDA0OTdlZDUzZmM0Njc0YTcxY2VjMmYyY2E5NTI1&Content-Type=application%2Fjson&X-Experience-API-Version=1.0.0&activityId=http%3A%2F%2FBAS_DR_DLR_02ThemeParks&agent=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Old%20Yeller%22%2C%22account%22%3A%7B%22homePage%22%3A%22http%3A%2F%2Fotp.tld%22%2C%22name%22%3A%22aaatester%22%7D%7D&stateId=resume&registration=2395b829-7700-4954-abce-a719351a6a65&
```

**Expected behavior**
This API call works in version 1 of learning locker. We are testing version 2 with all of our courses and came across this issue.

**Actual behaviour**
```
3|xAPI     |   contentType: 'text/plain;charset=UTF-8' }
3|xAPI     | 2017-10-18 09:33:02:009 - error: 072c7e3b-7394-4218-899d-5c4975313606 
3|xAPI     | { message: 'Error',
3|xAPI     |   name: 'default_1',
3|xAPI     |   stack: 'Error: Error\n    at default_1 (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/jscommons/src/errors/BaseError.ts:10:19)\n    at new default_1 (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/src/errors/InvalidContentType.ts:5:5)\n    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/src/expressPresenter/postStatements/index.ts:34:11)\n    at step (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/dist/expressPresenter/postStatements/index.js:32:23)\n    at Object.next (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/dist/expressPresenter/postStatements/index.js:13:53)\n    at /usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/dist/expressPresenter/postStatements/index.js:7:71\n    at __awaiter (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/dist/expressPresenter/postStatements/index.js:3:12)\n    at /usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/src/expressPresenter/postStatements/index.ts:12:64\n    at /usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/xapi-statements/src/expressPresenter/utils/catchErrors.ts:13:5\n    at Layer.handle [as handle_request] (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/learninglocker/releases/ll-20171017-1304a7ac42a06186394e46d54cc4c11d1d1bf4d1_1/xapi/node_modules/express/lib/router/index.js:275:10)',
3|xAPI     |   contentType: 'text/plain;charset=UTF-8' }
```

**Additional information**
OS: CentOS 7
Browser: Chrome
Test course:
https://media.disneytravelagents.com/courses/tincan/20170601-1004_bas_dr_dlr_02themeparks_2017-05-25/story.html?endpoint=https://llv2.tld/data/xAPI/&auth=Basic YzQ3OGU3MDk2MTUxNjNjODNkY2YxMGQ2YzUxNDgyZGE4N2EwYjVjOTpkMDIzNGZkNjhmZDA0OTdlZDUzZmM0Njc0YTcxY2VjMmYyY2E5NTI1&activity_id=http://BAS_DR_DLR_02ThemeParks&grouping=http://BAS_DR_DLR_02ThemeParks&actor={"objectType":"Agent","name":"Old Yeller","account":{"homePage":"http:\/\/otp.tld","name":"aaatester"}}&registration=2395b829-7700-4954-abce-a719351a6a65

**Comment by ryansmith94** [comment]
Hey @andrewdisney, thanks for reporting the issue, we're investigating it now.

**Comment by ryansmith94** [comment]
To be clear, this is making a GET request to the xAPI state.

**Comment by ht2** [comment]
Hi @andrewdisney, 

We've had a look throuhg this and we believe that the LRS is behaving as expected. You are making an "Alternate Request Syntax" GET (which is actually a POST, with a query param of `method=GET`). 

In order for the LRS to receive and process the data, you need to be sending a Content-Type of `application/x-www-form-urlencoded` in the headers, as defined in the specification here: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#user-content-1.3.s3.b9. The application will then take the _actual_ Content-Type from the payload (via this method: https://github.com/LearningLocker/xapi-statements/blob/master/src/expressPresenter/postStatements/index.ts#L30)

Unfortunately this is just one of those areas where V1 was letting something through, as it was never fully conformant (unlike V2, which is tested against the ADL's own conformance test suite: https://adopters.adlnet.gov/products/b8e42cb1-a7f7-41fb-b514-53676ad98cc4/)

**Comment by ryansmith94** [comment]
Relevant code:
- [POST state request handler](https://github.com/LearningLocker/xapi-state/blob/master/src/expressPresenter/postState.ts#L15).
- [Alternate state request handler](https://github.com/LearningLocker/xapi-state/blob/master/src/expressPresenter/utils/alternateStateRequest.ts).
- [Alternate state request GET handler](https://github.com/LearningLocker/xapi-state/blob/master/src/expressPresenter/utils/alternateStateRequest.ts#L43).
- [Alternate state request invalid content type check](https://github.com/LearningLocker/xapi-state/blob/master/src/expressPresenter/utils/alternateStateRequest.ts#L29) - this is where the error is coming from.

**Comment by ht2** [comment]
I'm just reopening this whilst we review how it would handle the utf8 part of that header, we actually think that State may fail (whereas Statements seem to test the content-type nicely). However, we also need to double check the spec to see if it is explicit.

**Comment by ryansmith94** [comment]
Yeah that's interesting, the spec does actually explicitly say `application/x-www-form-urlencoded` without the charset and later in the same section says `All strings MUST be encoded and interpreted as UTF-8` so I guess they consider other parts of the content type (such as the charset to be unnecessary).

**Comment by ryansmith94** [comment]
I guess we could use some regex like `application\/x-www-form-urlencoded(;\s*charset=UTF-8)?` @ht2 since we can only accept UTF-8.

**Comment by ht2** [comment]
Sounds like the best option to me

**Comment by ryansmith94** [comment]
Okay. I'll close this and make a separate issue for that.
